### ISSUE TITLE
Suggestion: Get mail notifications when a container is updated

### ISSUE THREAD

**Issue by Dalko911** [containrrr/watchtower#10]
Hello,

I think it could be a good idea to have notifications of updates.

Or if mail alerts are complicated, maybe a different log file with only the update infos ?

Thanks :-)

**Comment by bthome** [comment]
mail + maybe pushbullet or telegram notifications?  Would be nice to be notified of a change occurring X seconds before the actual pull and restart to give you a chance to delay or stop if needed.

**Comment by ghost** [comment]
Would be good just to know that it has found an update and if it completed successfully. So if we had the option to push some or all of the logs to mail or a webhook to slack or similar service would be great!

**Comment by stffabi** [comment]
There's a PR for slack integration #61. Should be made available with v0.2.0.

**Comment by Angelinsky7** [comment]
+1

**Comment by chasgames** [comment]
this would be useful

**Comment by Natteverf** [comment]
+1

**Comment by cwildfoerster** [comment]
+1

**Comment by rdamazio** [comment]
Sent https://github.com/v2tec/watchtower/pull/106 for this.

**Comment by stffabi** [comment]
EMail notifications have been merged. A new watchtower release will be published soon.
