### ISSUE TITLE
can't run the command

### ISSUE THREAD

**Issue by HFeenstra** [containrrr/watchtower#101]
Below I get when starting the container, so deamon is working. Now what?? 

docker run --rm talmai/rpi-watchtower 6
Executing ./rpi-watchtower_ARM6
time="2017-08-13T13:03:37Z" level=info msg="Executing with command arguments: []"
time="2017-08-13T13:03:37Z" level=fatal msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
pi@Dockerpi:~ $ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: active (running) since Mon 2017-07-17 19:47:59 CEST; 3 weeks 5 days ago
     Docs: https://docs.docker.com
 Main PID: 757 (docker)
   CGroup: /system.slice/docker.service
           ├─ 757 /usr/bin/docker daemon -H fd:// --storage-driver=overlay -D
           ├─ 984 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.2 -container-port 80
           ├─1029 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 53 -container-ip 172.17.0.2 -container-port 53
           ├─1037 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 53 -container-ip 172.17.0.2 -container-port 53
           └─3537 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9000 -container-ip 172.17.0.3 -container-port 9000

**Comment by stffabi** [comment]
talmai/rpi-watchtower, is a fork of the original watchtower. Therefore I don't know what has been changed there. 
Original watchtower has now also arm builds, would be great if you could give them a try 😄 .

Apart from that, It seems like you are missing to mount the docker socket into the watchtower container.  Take a look onto the examples here, https://github.com/v2tec/watchtower#usage

**Comment by stffabi** [comment]
I'll close this issue for now, feel free to reopen it if you have any further questions regarding original watchtower.
