### ISSUE TITLE
Is it possible to configure which image/containers should be updated?

### ISSUE THREAD

**Issue by patakijv** [containrrr/watchtower#102]
If considering implementing watchtower on a server where there are many containers running, we may only want certain containers to be updated based on their image getting updated locally or via a pull, not all of them across the board. Is it possible to have a configuration file or have something on the container/image itself like a label or environment variable that signals to watchtower whether it should be updated? That way we don't have to force all containers to be updated if that is not desired.

**Comment by snow3461** [comment]
read again the README.md (https://github.com/v2tec/watchtower#arguments)

**Comment by patakijv** [comment]
Ah ya, I overlooked the arguments that can be passed at command line. If I plan to use docker-compose to run watchtower, can those arguments be added to the 'command' key?

**Comment by stffabi** [comment]
The possiblity to watch containers with an assigned label has been introduced with #104
