### ISSUE TITLE
Containers get deleted on update

### ISSUE THREAD

**Issue by ElTimablo** [containrrr/watchtower#1043]
**Describe the bug**
Containers updated by Watchtower do not work upon restart for varying reasons.

**To Reproduce**

1. Run Watchtower container in an existing environment with outdated containers
2. Wake up in horror the next day as a significant chunk of your services are now down

**Expected behavior**

All containers will come up correctly when rebuilt.
Containers will be rebuilt rather than deleted.

**Screenshots**

**Environment**

<details>
Many containers that Watchtower attempted to update were instead deleted. Others didn't function when they came back up for some reason, but that may have been due to other containers they depended on being missing.

Some more details on the containers that were damaged or destroyed:
* One linked container, jrcs/docker-letsencrypt-nginx-proxy-companion, failed to rebuild for unknown reasons. Its github repository name changed between the time I built my container and now, and the remote repository is no longer available by the same name. That seems related somehow.
* One standalone container, haugene/transmission-openvon, failed to update for unknown reasons and was simply deleted.
* One standalone container, vectorim/riot-web, was inaccessible over HTTP proxy for unknown reasons. Had to rebuild by hand with the same settings for it to come back up. This may have been due to the letsencrypt companion container being down, however, so this could be a secondary casualty.

I recognize this means I really need to set up ignore rules, as I only really wanted watchtower updating two containers, but in the meantime this has hit a couple of issues that I'd be willing to look into.

Logs are unfortunately gone as I freaked out and deleted Watchtower when I figured out it caused the outage.

</details>

**Additional context**

**Comment by piksel** [comment]
Watchtower probably crashed in the middle of recreating your containers. But as you don't have any logs there isn't much we can do here...

**Comment by ElTimablo** [comment]
I'm sorry. I had a panic attack when I saw my stuff was down.

**Comment by piksel** [comment]
Yeah, I know the feeling 😅

The reason why this happens is that you cannot change the image for a running container. Instead, what watchtower does, is to grab the configuration of the "old" container, stop & remove it, and then start a new container with the same config, but with a new image.
But as you have experienced, if something fatal happens between the removal and startup, you're left without said container(s).

**Comment by ElTimablo** [comment]
Since this happened, I've been trying to think of a way to enable spinning up an updated container before deleting the out of date one, and I've arrived at the conclusion that in order to do so, Watchtower would probably have to reimplement the entirety of Docker's networking stack, so I get why you do it this way. If I come up with something, I'm definitely going to try to contribute it so this isn't an issue anymore.

Alternatively, could there be some way for Watchtower to detect that an update has failed or otherwise stopped before it was complete and resume? That could be a good intermediary method.
