### ISSUE TITLE
Watchtower upgrades Radarr and does not keep variables

### ISSUE THREAD

**Issue by turkeylegs1** [containrrr/watchtower#1044]
Watchtower is updating linuxserver/radarr automatically, but it is not preserving the various configurations, resulting in the image being 'fresh' for Radarr. I have to go and restore from backup every time this happens, and I do not know that it has happened until I try to access Radarr and see that it is all errored out.

**Comment by piksel** [comment]
Do you have /config mounted as a volume? (as per setup instructions at https://hub.docker.com/r/linuxserver/radarr#Usage)

**Comment by turkeylegs1** [comment]
yes.
I have about 10 volumes mounted in various areas.
[image: image.png]

**Comment by piksel** [comment]
Watchtower doesn't do anything special for Radarr. Their documentation should tell you how to preserve configuration when updating (it should be contained in whatever you mounted as `/config` afaikt).

**Comment by turkeylegs1** [comment]
indeed it should - but it constantly wipes everything.
is it a bug, or did I miss something?

the config dir maps directly to the radarr config folder and everything
else.
then again, i have about 10 volume mappings.
I'm just not sure where to start with testing or troubleshooting.

**Comment by piksel** [comment]
Okay, so what does the mapped folder contain? Is it empty, or does it contain your config files? My guess is that you are somehow not using the volume. Could you paste your `docker run` or `docker-compose.yml` for Radarr?

**Comment by turkeylegs1** [comment]
the config folder contains literally everything the radarr config is
looking for - all i do is go and restore from last backup, and it's back to
the way it was - though i miss a few days since i never know when it
crashes and starts over, acting like there is no config folder mapped.
forgive my ignorance, i use docker in synology. i do have ssh access of
course.
how can i get that information for you?


thank you so much for your help!
