### ISSUE TITLE
Crash on startup, on MacOS

### ISSUE THREAD

**Issue by thomasd3** [containrrr/watchtower#1045]
Here is the log:

watchtower_1  | runtime: failed to create new OS thread (have 2 already; errno=22)
watchtower_1  | fatal error: newosproc
watchtower_1  |
watchtower_1  | runtime stack:
watchtower_1  | runtime.throw(0x4f649a, 0x9)
watchtower_1  |         /usr/local/go/src/runtime/panic.go:566 +0x78
watchtower_1  | runtime.newosproc(0x10a22000, 0x10a31fe0)
watchtower_1  |         /usr/local/go/src/runtime/os_linux.go:160 +0x1b0
watchtower_1  | runtime.newm(0x547e68, 0x0)
watchtower_1  |         /usr/local/go/src/runtime/proc.go:1572 +0x12c
watchtower_1  | runtime.main.func1()
watchtower_1  |         /usr/local/go/src/runtime/proc.go:126 +0x24
watchtower_1  | runtime.systemstack(0x706d00)
watchtower_1  |         /usr/local/go/src/runtime/asm_arm.s:247 +0x80
watchtower_1  | runtime.mstart()
watchtower_1  |         /usr/local/go/src/runtime/proc.go:1079
watchtower_1  |
watchtower_1  | goroutine 1 [running]:
watchtower_1  | runtime.systemstack_switch()
watchtower_1  |         /usr/local/go/src/runtime/asm_arm.s:192 +0x4 fp=0x10a1c7ac sp=0x10a1c7a8
watchtower_1  | runtime.main()
watchtower_1  |         /usr/local/go/src/runtime/proc.go:127 +0x5c fp=0x10a1c7d4 sp=0x10a1c7ac
watchtower_1  | runtime.goexit()
watchtower_1  |         /usr/local/go/src/runtime/asm_arm.s:998 +0x4 fp=0x10a1c7d4 sp=0x10a1c7d4

**Comment by piksel** [comment]
Is this consistently happening? That error means that the OS did not allow the executable to create a thread. That is not an error we can do anything about as it's between the go runtime and the host OS (and should never happen under normal circumstances).

**Comment by thomasd3** [comment]
yes, this is consistent. When I search this error with docker / macos, I see many instances but they're all related to an AMD64 image run on a M1 mac, which is not my case (I've an i7).
It seemed there was a similar issue with GoLang in 2017 and a patch was subsequently made.

**Comment by piksel** [comment]
Yeah, this line is suspicious:
`watchtower_1 | /usr/local/go/src/runtime/asm_arm.s:192 +0x4 fp=0x10a1c7ac sp=0x10a1c7a8`

How are you starting watchtower? What image tag do you use?

**Comment by thomasd3** [comment]
yes I think you hit the nail on the head, I thought I used the latest but then I look at the image and my tag is "armhf-latest", so it looks like I somehow got the ARM version.

I got it from there: https://github.com/archetypesc/watchtower-ecr and, besides the tag, nothing really suggested it would be the ARM version, so I totally overlooked that.
Does WatchTower support ECR directly now?

**Comment by piksel** [comment]
I were actually surprised to find out that docker allows running binaries for different architectures (and the only reason it didn't work for you is for the binary loading bug mentioned).

```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:arm64v8-latest --run-once
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
time="2021-08-08T20:08:10Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nChecking all containers (except explicitly disabled with label)\nRunning a one time update."
```

> Does WatchTower support ECR directly now?

It does using a credential helper sidecar: https://containrrr.dev/watchtower/private-registries/#credential_helpers

**Comment by simonaronsson** [comment]
This issue looks solved to me. Closing. 👍🏽
