### ISSUE TITLE
Notifications via shoutrrr (telegram) do not include hostname

### ISSUE THREAD

**Issue by kosli** [containrrr/watchtower#1052]
**Describe the bug**
I am using wachtower on multiple docker hosts and configured the notifications with shoutrrr to a Telegram channel. The notifications do not include any information about which host the notification came from.

**To Reproduce**
Configure to use notifications via shouttr to a telegram channel.

**Expected behavior**
The notifications should include the hostname of the host that they belong to. I assume the problem is that the hostname would be in the "subject" (as it is in emails and gotify), but a message in telegram does not have a subject so that information is lost/not provided. -> I didn't find a way via the WATCHTOWER_NOTIFICATION_TEMPLATE to add the subject myself).

**Screenshots**
Telegram message:
No hostname provide as there is no "subject"
![image](https://user-images.githubusercontent.com/203928/129093313-96cfb020-1c71-421a-b558-49ff6684e360.png)

Gotify message:
DOES contain the hostname in the subject.
![image](https://user-images.githubusercontent.com/203928/129093197-6a644706-ee0e-4977-aa40-80e4ee1c085d.png)

**Comment by piksel** [comment]
There is basically two issues here:

1. there is a generic "title" API in Shoutrrr for all the services that support it in some way, but Telegram currently just ignores it. Shouldn't be too difficult to add it though.

2. the template should have the title as a field (also really easy to add for the new template system).

**Comment by kosli** [comment]
@piksel Thanks
1. okay, that explains why even manually setting the title via the URL didn't work, whereas the documentation implies it differently ;-) (https://containrrr.dev/shoutrrr/v0.4/services/telegram/)
2. i tried using {`{.title}} {{.Title}} {{.Subject}}` in the `WATCHTOWER_NOTIFICATION_TEMPLATE`, e.g. `"{{range .}}{{.Title}}{{println}}TEST{{.Message}}{{println}}{{end}}"` but that field doesn't exist. How can I use the title field?
`Failed to execute Shoutrrrr template: template: :1:13: executing "" at <.Title>: can't evaluate field Title in type *logrus.Entry `

**Comment by piksel** [comment]
> that field doesn't exist

No, there is no such field right now, but it really ought to be there, hence why it's another issue.

**Comment by kosli** [comment]
@piksel ups sorry, I have re-read your message and I see I missed that you mentioned that it IS an issue ;-)
Okay, thanks, so I will wait until it gets implemented.

**Comment by timwsuqld** [comment]
We'd like the title in the template as well for Google Chat notifications

**Comment by piksel** [comment]
Note that the first part of this issue was fixed in containrrr/shoutrrr#196

**Comment by fire1ce** [comment]
+1

**Comment by kosli** [comment]
Thanks @piksel . Looking forward to a new release of watchtower.
