### ISSUE TITLE
Can't send notifications throug email

### ISSUE THREAD

**Issue by desagaia** [containrrr/watchtower#1073]
# Email Notifications
- I'm trying to used but is unstable, some times works and send the notification and sometimes just sat "failed to send using smtp: timed out"

# Configuration
I used a docker compose with the following environment variables
environment:
            - TZ=America/Bogota
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_LABEL_ENABLE=true
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=my-mail@example.com
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=recipient@example.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=my-mail@example.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=app-password
            - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
            - WATCHTOWER_SCHEDULE=@hourly

# Expected Behavior

- Recivied the notification in the recipient@example.com

# Environment 
- Linux
- 64 bits
- Docker version: 19.03.15, build 99e3ed8919

# Output 
watchtower    | Failed to send notification via shoutrrr (url=smtp://my-mail%40example.com:app-password@smtp.gmail.com:587/?auth=Plain&fromaddress=my-mail%40example.com&fromname=Watchtower&subject=Watchtower+updates+on+5343354&toaddresses=recipient%40example.com):  failed to send using smtp: timed out

**Comment by kirbylink** [comment]
Maybe related to #1135 ?

**Comment by piksel** [comment]
@kirbylink As this uses Gmail's SMTP servers, it shouldn't be related to that. Unless this is updating something that brings down the host's network access somehow?

**Comment by PetrusZ** [comment]
I have similar error:

```
time="2021-11-20T22:17:59+08:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: 535 5.7.8 Error: authentication failed: Invalid format." index=0 notify=no service=smtp
```

**Comment by piksel** [comment]
@PetrusZ Error 535 is your mail server responding that it doesn't accept your credentials. They are probably not related.

**Comment by PetrusZ** [comment]
@piksel Thank you, found where the problem is.
