### ISSUE TITLE
Matrix (Shoutrrr) notifications don't parse the address correctly

### ISSUE THREAD

**Issue by k8ieone** [containrrr/watchtower#1075]
**Describe the bug**

Using Matrix notifications doesn't work. It looks like the address isn't being parsed properly. The room name is also cut completely.

**To Reproduce**
1. Set `WATCHTOWER_NOTIFICATION_URL="matrix://uname:password@synapse:8008/?room=#room"`
2. Restart Watchtower
3. See error
```
level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"\\\"matrix://uname:password@synapse:8008/?room=\": first path segment in URL cannot contain colon\n"
```
4. Watchtower stops

**Expected behavior**

Watchtower should launch and notifications should work.

**Environment**
 - Arch Linux - x86_64
 - Docker version 20.10.8, build 3967b7d28e

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

\*the output does not differ\*

</details>

**Additional context**

**Comment by piksel** [comment]
Either leave out the # or escape it, see:
https://containrrr.dev/shoutrrr/v0.5/services/matrix/#room_lookup

Also, note that the latest watchtower release uses Shoutrrr v0.4, which doesn't include Matrix support. You can try it using the unstable `latest-dev` though.

**Comment by k8ieone** [comment]
I moved to `latest-dev` and removed the "#" but it still doesn't work. The room name wasn't stripped this time tho.
```
level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"\\\"matrix://uname:password@synapse:8008/?room=room\\\"\": first path segment in URL cannot contain colon\n"
```

**Comment by piksel** [comment]
```
❯ docker run --rm -it containrrr/shoutrrr verify 'matrix://uname:password@synapse:8008/?rooms=room'
error verifying URL: failed to get login flows: Get https://synapse:8008/_matrix/client/r0/login: dial tcp: lookup synapse on x.x.x.x: read udp y.y.y.y:56821->x.x.x.x:53: i/o timeout
```
(this means that it parses the URL, but cannot connect to `synapse` since it doesn't exit in my local envo)

My guess is that you have some character in the username or password that makes the URL invalid.


You can use `shoutrrr generate matrix` to have it escape it for you:
```
❯ docker run --rm -it containrrr/shoutrrr generate matrix
Generating URL for matrix using basic generator
Enter the configuration values as prompted

DisableTLS[No]:
Host: synapse:8008
Password: p@zzw0:r/d
Rooms: room
User: user@host.com

URL: matrix://user%40host.com:p%40zzw0%3Ar%2Fd@synapse:8008?rooms=room
```

**Comment by k8ieone** [comment]
I used `shoutrrr generate matrix` to generate the URL now and it still won't work. The only thing that changed is the room hashtag was escaped as `%23`.

I tried `verify` and that seems to work.
```
DisableTLS No                                                                                         <Default: No>
Host       synapse                                                                                    <Required>
Password   password                                                                                   <Required>
Rooms      [ #room ]
User       uname
```

My username only contains letters and a dash (-). The password is letters and numbers only.

**Comment by piksel** [comment]
Are you using docker-compose? I think the quotes are being passed into the env variable. Try either
`- WATCHTOWER_NOTIFICATION_URL: "matrix://uname:password@synapse:8008/?room=#room"` (dict syntax)
or
`WATCHTOWER_NOTIFICATION_URL=matrix://uname:password@synapse:8008/?room=#room` (no quotes)

**Comment by k8ieone** [comment]
I can't believe this was it... Well at least I learned something.  
I was using the one with the `=` and I had the quotes as well. Removing the quotes fixed it.

Sorry for the ginormous waste of your time 😞

**Comment by k8ieone** [comment]
One more thing tho. Now that that's working, I ran into this:
```
level=error msg="Failed to send shoutrrr notification" error="title is not a valid config key [disabletls rooms]" index=0 notify=no service=matrix
```

Should I start another issue?

**Comment by piksel** [comment]
You can make one in containrrr/shoutrrr. That is an actual bug. Thanks!

**Comment by k8ieone** [comment]
Great, thank you for all your help and once again, sorry for the time waste.
