### ISSUE TITLE
Add pushover as a notification service

### ISSUE THREAD

**Issue by claym** [containrrr/watchtower#108]
Is there a way to set up notifications when containers are update?

I've gone through the docs and haven't seen a way.

**Comment by waja** [comment]
There is #106

**Comment by stffabi** [comment]
EMail notifications have been merged. A new watchtower release will be published soon. What kind of notifications would you be interested in? Is email fine for you?

**Comment by claym** [comment]
I personally would like email or perhaps Pushover. But I’m good with email.

There are, however, a myriad of different notification services, as I’m sure you are aware :)

Thank you!

**Comment by stffabi** [comment]
Currently slack is in the pipeline. Pushover should be pretty easy to be added. I'm going to change the title of this issue to "Add pushover as a notification service". So we could track this here.

**Comment by ShoGinn** [comment]
logrus has a pushover function, how hard would it be to add this?

**Comment by marcelbrueckner** [comment]
Pushover would be great. For now, one can create e-mail aliasses in the Pushover dashboard for customized Pushover messages (e.g. only selected devices, sounds etc.), see https://updates.pushover.net/post/144473611422/new-e-mail-gateway-features

**Comment by ShoGinn** [comment]
of course you can create a mail alias (which is a good solution) but that still requires a smtp address etc. Mildly defeats the purpose of Pushover. (Considering the fact that pushover has an http api)

**Comment by marcelbrueckner** [comment]
I totally agree with you. Using the e-mail gateway is rather meant as an intermediate solution (as I happened to configure it this way today) until Pushover support is implemented.

**Comment by simonaronsson** [comment]
This issue will be merged with #264, which focuses on notifications in general.
However, as I do not have any experience of using pushover, all help possible would be appreciated.
