### ISSUE TITLE
Missing newlines in Email notifications on Windows mail client

### ISSUE THREAD

**Issue by rose-a** [containrrr/watchtower#1082]
**Is your feature request related to a problem? Please describe.**
When viewing email notifications from Watchtower on a Windows email client (i.e. MS Outlook 2019), they're very hard to read because the linebreaks are missing (I suspect because they are only carriage returns without linefeed). 

In Outlook Web they render fine though.

**Describe the solution you'd like**
Maybe an option to send out notifications with CR LF, like `WATCHTOWER_NOTIFICATION_EMAIL_NEWLINE='windows'` or something

An alternative solution would be an option to to send the emails with a html body.

**Comment by piksel** [comment]
I don't think it's due to CRLF as even Notepad now display single LFs as newlines. 
There is a setting called *Extra line breaks in plain text messages* that seems to cause this issue for others, don't have outlook at hand to check though.

**Comment by rose-a** [comment]
You're right, its just Outlook removing "unnecessary" linebreaks 🤦‍♂️ 

See https://docs.microsoft.com/en-us/outlook/troubleshoot/message-body/line-breaks-are-removed-in-posts-made-in-plain-text for anyone having this "problem", too...

Thanks for responding, anyway!
