### ISSUE TITLE
Watchtower disappears after a while

### ISSUE THREAD

**Issue by vasyugan** [containrrr/watchtower#1087]
**Describe the bug**
I can only report that on my server, every single time when I launched watchtower, it keeps running for some weeks and then disappears without a trace. Even docker container list -a doesn't show a stopped watchtower container, it is just gone. 

I should say that between the last start of watchtower and now there was possibly a reboot of the server, however all other docker containers resumed without any glitch. Only watchtower was gone. I don't know when it actually disappeared, whether this is linked to the reboot or a self update of watchtower or anything else. I just observer, that it is gone, and the same happened again and again before. 

**To Reproduce**
1. Run watchtower with any chosen options
2. Convince yourself that it is running, eg docker container logs watchtower
3. Check back after a few weeks.

**Expected behavior**

Watchtower should still be running, like all other docker containers.

**Screenshots**

**Environment**

Ubuntu 20.04, amd 64
Docker 

 docker-ce      5:20.10.8~3-0~ubuntu-focal amd64   
<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```

```

</details>

**Additional context**

**Comment by agneevX** [comment]
How did you run Watchtower?

**Comment by piksel** [comment]
I'm not sure this is watchtower-specific, if docker just loses a container suddenly. But perhaps it's related to auto-updating somehow?

**Comment by vasyugan** [comment]
> 
> 
> I'm not sure this is watchtower-specific, if docker just loses a container suddenly. But perhaps it's related to auto-updating somehow?

I have to wait and see. This time, Watchtower has been up and running for 2 weeks without disappearing. I'll keep watching it and report back.

**Comment by vasyugan** [comment]
> I'm not sure this is watchtower-specific, if docker just loses a container suddenly. But perhaps it's related to auto-updating somehow?

I don't know. This time, the last log entry was
`
time="2021-10-27T15:25:44Z" level=info msg="Waiting for running update to be finished..." 

`

So, no indication of an error there.

OK, this time I started watchtower with --restart unless-stopped. Hope this helps.

**Comment by piksel** [comment]
You're not starting it using `--rm` by any chance? The `Waiting for running update to be finished...` is usually the last message written by watchtower and indicates that it has been told to stop by Docker.

**Comment by vasyugan** [comment]
> You're not starting it using `--rm` by any chance? The `Waiting for running update to be finished...` is usually the last message written by watchtower and indicates that it has been told to stop by Docker.

No, I have not, I only failed to specify a --restart option. This time I have added --restart unless-stopped and I'll see if that makes any difference, or maybe I should even use --restart always?

**Comment by piksel** [comment]
What is the command line you use to start it?

**Comment by vasyugan** [comment]
> What is the command line you use to start it?

```bash
$ docker run -d \
  --name watchtower \
  --restart unless-stopped \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e WATCHTOWER_NOTIFICATIONS=email \
  -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=***@***.org \
  -e WATCHTOWER_NOTIFICATION_EMAIL_TO=***@***.org \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.***** \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587 \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=***@**** \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=*** \
  -e WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2 \
  containrrr/watchtower
```

**Comment by piksel** [comment]
What is `run_watchtower`?

**Comment by vasyugan** [comment]
> What is `run_watchtower`?

Oh, that' just the name of the script. Not part of the command.

**Comment by simonaronsson** [comment]
There has not been an update to watchtower in quite a few months now, so the watchtower container should not have been updated. Something else is definitely fishy here. If you still experience these problems, please run the watchtower container with `--debug` enabled and dump the logs to a file. Once (if?) it occurs again, please open a new issue including these logs.
