### ISSUE TITLE
Watchtower API Mode always returns 200 OK status code

### ISSUE THREAD

**Issue by dumbasPL** [containrrr/watchtower#1095]
**Describe the bug**
When using watchtower in API mode sending any request to `v1/update` endpoint it will always return status `200 OK`.

**To Reproduce**
1. Setup watchtower in API mode
2. Make a request to `http://ip:port/v1/update` with missing/invalid `Authorization` header
3. Look at response code

**Expected behavior**
The API returns `401 Unauthorized` whenever the `Authorization` header is missing/invalid

**Screenshots**
![image](https://user-images.githubusercontent.com/29180158/137642693-1810038c-d639-40de-b8a4-78a3a023b657.png)

**Environment**
Unrelated

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
"Updates triggered by HTTP API request." only triggered when providing a valid token
```

</details>

**Additional context**
Would be nice to have meaningful status codes instead of just silently failing

**Comment by cdstg** [comment]
Yes i found the same it would be good if this could return like 403 etc.

What would be real nice if it could return the log output as well

Why im running it in http update mode and my calling system could then determine if it failed or not
