### ISSUE TITLE
Update data containers

### ISSUE THREAD

**Issue by jgautheron** [containrrr/watchtower#11]
Since data containers are not running, they are currently not supported.
Any chance they will be supported in the future?

**Comment by vespakoen** [comment]
I also need this for my project, would this be hard to implement? if not I will try to take a stab at it (not much golang knowledge)

**Comment by flw-cn** [comment]
Why not use crontab?

`docker pull path/to/your/image`

**Comment by molten-firescar96** [comment]
was this resolved?

**Comment by simonaronsson** [comment]
As far as I understand your question, this isnt something we plan to support.

The reasoning behind this is that named volumes have become the new standard for persisting data.

If this is something you really need; feel free to elaborate on your sugggestion and, if we can come to a working solution, also provide a pull request.

Thanks!
🙏🏻

**Comment by simonaronsson** [comment]
Closing due to lack of response.
