### ISSUE TITLE
Error response from daemon: client is newer than server (client API version: 1.24, server API version : 1.23)"      

### ISSUE THREAD

**Issue by inject00r** [containrrr/watchtower#110]
Hi v2tec,

QNAP is showing just this error message when starting the container.

Do you have an idea how I could continue? I guess upgrading the docker service within QNAP is not a good idea.

Cheers
Christian

**Comment by stffabi** [comment]
Hi Christian

You are seeing the same issue as in #65 . Currently all testings have been done against docker 1.12 and above, therefore the api version used is 1.24. Even docker 1.12 is quite old and I would prefer it if we don't need to donwgrade that.

Does qnap provide an update? Are you on the latest qnap version?

**Comment by MwC-Trexx** [comment]
The latest docker version available from QNAP via their Container Station application is v1.11.2.

**Comment by MwC-Trexx** [comment]
Any update on feasibility of supporting docker v1.11.2 ?

**Comment by simonaronsson** [comment]
Sorry, but no, that is not something we're gonna do at the moment.

I've just finished upgrading the client api version even further, and it is likely that it will continue down that road. However, older images will continue to exist on dockerhub - so feel free to try them, although they wont get any updates and your mileage may vary.
