### ISSUE TITLE
[Docs] Errors in Quick Start Page 

### ISSUE THREAD

**Issue by mayocream** [containrrr/watchtower#1105]
**Describe the bug**

[Quick Start Page](https://containrrr.dev/watchtower/#quick_start) badger display error and the quick start `docker-compose.yml` example have the wrong format.

**To Reproduce**

[Quick Start Page](https://containrrr.dev/watchtower/#quick_start)

**Screenshots**

![image](https://user-images.githubusercontent.com/35420264/138625438-2b4f80d9-191c-4016-a5c9-b0cb05d5b8ac.png)

**Comment by atombrella** [comment]
@simskij You can close this as well :)
