### ISSUE TITLE
Watchtower adds a /library/ segment to image request URLs to a private docker registry

### ISSUE THREAD

**Issue by nicolaiarocci** [containrrr/watchtower#1113]
Hello, I just added watchtower to my docker stack configuring it to pull updates from a private docker registry (https://hub.docker.com/_/registry/). No updates are being retrieved. By checking on the registry side, I see that watchtower is apparently adding a `/registry/` segment to the requested url, and getting a 404 back. I am also concerned by those HEAD requests failing with a 401.

```
time="2021-10-30T09:01:08Z" level=debug msg="Checking if pull is needed" container=<container> image="<host>/<image>:<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293"
time="2021-10-30T09:01:08Z" level=debug msg="Building challenge URL" URL="<hos>t/v2/"
time="2021-10-30T09:01:08Z" level=debug msg="Got response to challenge request" header="Basic realm=\"Registry realm\"" status="401 Unauthorized"
time="2021-10-30T09:01:08Z" level=debug msg="Parsing image ref" host=<host> image=<image> normalized="<host>/<image>:<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293" tag="<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293"
time="2021-10-30T09:01:08Z" level=debug msg="Doing a HEAD request to fetch a digest" url="<host>/v2/library/<image>/manifests/<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293"
time="2021-10-30T09:01:08Z" level=debug msg="Could not do a head request for \"<host>/<image>:<test>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293\", falling back to regular pull." container=/<container> image="<host>/<image>:<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293"
time="2021-10-30T09:01:08Z" level=debug msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=<container> image="<host>/<image>:<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293"
time="2021-10-30T09:01:08Z" level=debug msg="Pulling image" container=<container> image="<host>/<image>:<tag>@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293"
time="2021-10-30T09:01:08Z" level=debug msg="No new images found for <container>"
time="2021-10-30T09:01:08Z" level=debug msg="Session done: 2 scanned, 0 updated, 0 failed"
time="2021-10-30T09:01:08Z" level=debug msg="Scheduled next run: 2021-10-30 09:02:08 +0000 UTC"
```

On the registry log I get entries similar to this one:

    [30/Oct/2021:09:19:08 +0000] "HEAD /v2/library/<image>/manifests/<tag>@sha256:b7e1743aa4fb67ab2f259841f93e1a733d01c411b7e77844bdb88ecc1fa0d2cd HTTP/1.0" 404 19 "" "Go-http-client/1.1"

I found #715 referring to a similar issue, apparently resolved.

**Comment by thatsk** [comment]
is there any fix on this

**Comment by simonaronsson** [comment]
Head requests failing is OK if you are using private registries as they usually don't support that, hence it being logged on the debug level. It will also not affect the actual pull, so there seems to be no actual error here?

**Comment by piksel** [comment]
The logs show that your image is pinned to a hash though (`@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293`), which means that it will never be updated by watchtower (since there will never be a new image with the same hash).

**Comment by simonaronsson** [comment]
> The logs show that your image is pinned to a hash though (`@sha256:125bf7bd96d04085cf1be574ed5daf55220a92285818690e4f0230608de38293`), which means that it will never be updated by watchtower (since there will never be a new image with the same hash).

Also true, but still, nothing is actually going wrong in the logic of watchtower.
