### ISSUE TITLE
support for rootless docker(Docker API over TCP instead of a UNIX socket)

### ISSUE THREAD

**Issue by FarisZR** [containrrr/watchtower#1118]
**Is your feature request related to a problem? Please describe.**
i would like to see watchtowerr support docker rootless, its very good and very stable.

**Describe the solution you'd like**
support for docker API over TCP, currently you have to mount the UNIX socket which requires rootfull docker

**Comment by piksel** [comment]
That's already supported, you just set the [`--host` or `DOCKER_HOST` to a tcp:// URL](https://containrrr.dev/watchtower/arguments/#docker_host)
