### ISSUE TITLE
Add "Finished" event to log after One-time run or otherwise

### ISSUE THREAD

**Issue by voc0der** [containrrr/watchtower#1122]
**Is your feature request related to a problem? Please describe.**
When using watchtower, you are informed by the log file that is  fed to docker (e.g. docker logs watchtower) that the 
1) Process has started - Docker reports that it is Checking all containers.
2) Container upgrades have been found.
3) Containers have been serviced.

**Describe the solution you'd like**
4) Process has completed - Docker reports it is done Checking all containers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by piksel** [comment]
I actually fixed this in #1123, but forgot to make a PR.
