### ISSUE TITLE
Pass docker config.json content as environment variable

### ISSUE THREAD

**Issue by oceanBT** [containrrr/watchtower#1133]
**Is your feature request related to a problem? Please describe.**
We have a multi OS dev systems, with mac and linux. So there is not always a ~/.docker/config.json.

**Describe the solution you'd like**
So it would be great if I could pass the content of config.json as a environment variable to watchtower:  

 watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_DOCKER_CONFIG_CONTENT='{"auths":{"my.registry.com"{"auth": "MY_SECRET_TOKEN"}}}}'

Should be an easy feature like: echo ${WATCHTOWER_DOCKER_CONFIG_CONTENT} > /config.json  ;) 

Or is there already a feature for something like this? 

Thanks!

**Comment by simonaronsson** [comment]
Hi!

Thank you for opening an issue! Would this solve any issue that is not already solvable using a combination of file mounts and environment variables? I.e.

```yaml
...
    volumes:
      - "${CONFIG_FILE_LOCATION}:/config.json"
...
```

**Comment by oceanBT** [comment]
Hi,

ok, i have to explain a litte bit more: I have my MY_SECRET_TOKEN in my .env-file, so i could use 

`- WATCHTOWER_DOCKER_CONFIG_CONTENT='{"auths":{"my.registry.com"{"auth": "${MY_SECRET_FROM_DOT_ENV_FILE}"}}}}'
`

This is, as far as i know, not possible via volume.

**Comment by piksel** [comment]
> We have a multi OS dev systems, with mac and linux. So there is not always a ~/.docker/config.json.

This is the location for windows and macos versions of Docker Desktop, and for `docker-ce` for linux. Using this file makes sure that it uses the developers own credentials.

This seems like a bit too specialized case to be in the watchtower core... If you really wanted to do it from docker compose .env, then you could add another helper container that just does:
```sh
echo ${WATCHTOWER_DOCKER_CONFIG_CONTENT} > /config/config.json
```
and have `/config` be a shared volume between the helper and watchtower....

**Comment by oceanBT** [comment]
Ok, I thought, regardless of my specific case, it would be a cool feature to be able to define the config system agnostic per environment variable.
