### ISSUE TITLE
[Feature Request] Add functionality to revert if the update fails

### ISSUE THREAD

**Issue by Draxter** [containrrr/watchtower#1134]
**Is your feature request related to a problem? Please describe.**
Sometimes when a container is updated, for whaetever reason it fails.

**Describe the solution you'd like**
It would be useful if Watchtower could monitor the newly updated container to see if it runs after the update, and if not, revert it back to the old version and send a notification describing the failure, if notifications are configured.

**Comment by piksel** [comment]
This has been suggested multiple times, but it's not a straight forward thing to implement (and no PR for this feature has been submitted as of yet).

**Comment by simonaronsson** [comment]
Yeah, I'm not seeing either of us getting around to this anytime soon. If anyone wants this bad enough to create a PR, however, I'd be happy to assist.

**Comment by khalilgharbaoui** [comment]
Kind of related: https://github.com/containrrr/watchtower/issues/1186
