### ISSUE TITLE
OneShot Update

### ISSUE THREAD

**Issue by thelamer** [containrrr/watchtower#114]
Can you do oneshot upgrades on a running container IE:

`docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --rm \
  v2tec/watchtower container_to_watch --oneshot`

Started making a helper container to achieve this  and realized this should be trivial with your app, unless I am missing something.

**Comment by stffabi** [comment]
Currently that's not possible. I like the idea and shouldn't be a big issue to implement that. Probably we should implement this as a breaking change. Normally it's a oneshot if no command line parameter is provided. If it should be run with a schedule, the schedule command line parameter has to be provided.

Any opinions on this?

**Comment by thelamer** [comment]
I actually started digging into the code to make a fork maybe you could point me in the correct direction for what would be the correct place to add the os.exit().  I get adding the variable read and passing it to the upgrade command. 

Also noticed the build process and Dockerfile are all external right now, not a huge deal, but just a comment that it does make it more difficult for an external user to create a pull request they know builds to get a change discussion started. 

As far as this being the default behavior I assume you are asking other collaborators, but IMPO changing the default behavior on a widely deployed Docker container is not a good idea, many companies maintain internal documentation which probably just pulls latest and instructions would not sync even if github/dockerhub README was updated.

**Comment by thelamer** [comment]
Created a pull request to get a discussion started https://github.com/v2tec/watchtower/pull/116

**Comment by simonaronsson** [comment]
merged. closing
