### ISSUE TITLE
Using watchtower with Digital Ocean container registry

### ISSUE THREAD

**Issue by oreaird** [containrrr/watchtower#1150]
Hi all, 

We love watchtower and have employed it across all our projects.  The issue we have had for a while is that we chose digital ocean as our private registry, but that wasn't an issue for a bit as we simply had watch tower alert us of updates and we went in manually to update. 

Digital ocean uses doctl as its login system. (https://docs.digitalocean.com/reference/doctl/how-to/install/) which works in almost all instances apart from this one. 

In watchtower doc's it mentions support for private registries and even credential helpers (which I guess doctl is technically)
https://containrrr.dev/watchtower/private-registries/

however, I cannot work out how to use it. doctl is installed on the server, and I can simply type 
`docker-compose pull`
 and watch the new images arrive, I don't need to the login as I had previously used 
`doctl registry login`

short of writing my own bash script, and we cannot use username/passwords as it's against company policy, can anyone guide me in the right direction to use the credential helper system with digital oceans doctl?

**Comment by piksel** [comment]
It's not apparent exactly how that works. Could you check your `.docker/config.json` for any credhelper-related keys?

**Comment by piksel** [comment]
Actually... I just tried creating a repo on DO and doing `doctl registry login` and it put the credentials in my `config.json`:
```json
{
        "auths": {
                "registry.digitalocean.com": {
                        "auth": "AreallyLongBase64encodedUserPasswordPair"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.8 (linux)"
        }
}
```
So that should work perfectly fine with watchtower, you just mount the config as per the initial instructions in [the docs](https://containrrr.dev/watchtower/private-registries). Doesn't seem to be related to credential helpers...

**Comment by oreaird** [comment]
@piksel Thanks for your input

I just tried that and so close yet so far! lol, I had the following error: 

```
2021-12-02T16:05:36Z [D] Checking challenge header content
                         realm: api.digitalocean.com/v2/registry/auth
                         service: registry.digitalocean.com
2021-12-02T16:05:36Z [D] Setting scope for auth token
                         image: registry.digitalocean.com/xtreme-controls/clix-wordpress-site
                         scope: repository:registry.digitalocean.com/xtreme-controls/clix-wordpress-site:pull
2021-12-02T16:05:36Z [D] Credentials found.
2021-12-02T16:05:36Z [D] Parsing image ref
                         host: registry.digitalocean.com
                         image: xtreme-controls/clix-wordpress-site
                         normalized: registry.digitalocean.com/xtreme-controls/clix-wordpress-site:dev
                         tag: dev
2021-12-02T16:05:36Z [D] Doing a HEAD request to fetch a digest
                         url: registry.digitalocean.com/v2/xtreme-controls/clix-wordpress-site/manifests/dev
2021-12-02T16:05:36Z [D] Could not do a head request for 'registry.digitalocean.com/xtreme-controls/clix-wordpress-site:dev', falling back to regular pull.
                         container: /wordpress
                         image: registry.digitalocean.com/xtreme-controls/clix-wordpress-site:dev
2021-12-02T16:05:36Z [D] Reason: registry responded to head request with '401 Unauthorized', auth: 'Bearer realm=https://api.digitalocean.com/v2/registry/auth,service=registry.digitalocean.com,scope=repository:xtreme-controls/clix-wordpress-site:pull'
                         container: /wordpress
                         image: registry.digitalocean.com/xtreme-controls/clix-wordpress-site:dev

```

I have found that you can download the docker configs from digital ocean and have tried 1 with read, 1 with read/write. I was following this https://docs.digitalocean.com/products/container-registry/how-to/set-up-ci-cd/ however these also do not work.

to confirm:
I can use docker pull image on the same server, and it uses the auth in the .docker config.json successfully and works.
I use an exact copy of the same file and pass it to watchtower using
`- ./config.json:/config.json `
but I receive the above.

**Comment by piksel** [comment]
Do you mean the head request bits? They only mean that the repo doesn't implement the HEAD requests that dockerhub uses for cheap update checking. If that is not available, watchtower proceeds with the regular pull method of checking, hence the `falling back to regular pull` message.

**Comment by oreaird** [comment]
No specifcially the last entry 

> 2021-12-02T16:05:36Z [D] Reason: registry responded to head request with '401 Unauthorized', auth: 'Bearer realm=https://api.digitalocean.com/v2/registry/auth,service=registry.digitalocean.com,scope=repository:xtreme-controls/clix-wordpress-site:pull'
>                          container: /wordpress
>                          image: registry.digitalocean.com/xtreme-controls/clix-wordpress-site:dev

To be fair I haven't updated the image just assumed this was, bad! I will test and let you know.

**Comment by piksel** [comment]
> registry responded to head request with

:D

**Comment by oreaird** [comment]
It worked, Thank Piksel, I appreciate your time on this!
