### ISSUE TITLE
Long argument list results in incorrect checking

### ISSUE THREAD

**Issue by oester** [containrrr/watchtower#1167]
**Describe the bug**
Invoking "docker run --rm containrrr/watchtower" with a long argument list causes some strange behavior.

**To Reproduce**
I was trying to use watchtower to run a quick scan of some remote docker instances using this command:

`docker run --rm containrrr/watchtower --run-once --monitor-only --debug --host "tcp://192.168.15.24:2375" --scope rpi4-2`

    time="2021-12-18T14:16:18Z" level=debug msg=rpi4-2
    time="2021-12-18T14:16:18Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
    time="2021-12-18T14:16:19Z" level=debug msg="Making sure everything is sane before starting"
    time="2021-12-18T14:16:19Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nOnly checking containers in scope \"rpi4-2\"\nRunning a one time update."
    time="2021-12-18T14:16:19Z" level=debug msg="Checking containers for updated images"

This command worked. However, when I added extra arguments to support email notification like this: 

`docker run --rm containrrr/watchtower --run-once --monitor-only --debug --host "tcp://192.168.15.24:2375" --scope rpi4-2 --notifications "email" --notification-email-to "xxxxxx@gmail.com" --notification-email-server 192.168.15.2 --notification-email-delay 2 --notification-email-server-tls-skip-verify "true" --notification-email-subjecttag "rpi4-2" --notification-email-from "xxxxxx@gmail.com"`

Results in checking no containers. Notice the phrase **"Only checking containers with name \"true\","** - which isn't there in the normal case.

    time="2021-12-18T14:15:39Z" level=debug msg=rpi4-2
    time="2021-12-18T14:15:39Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
    time="2021-12-18T14:15:40Z" level=debug msg="Making sure everything is sane before starting"
    time="2021-12-18T14:15:40Z" level=info msg="Watchtower 1.3.0\nUsing notifications: smtp\nOnly checking containers with name \"true\", in scope \"rpi4-2\"\nRunning a one time update."
    time="2021-12-18T14:15:40Z" level=debug msg="Checking containers for updated images"
    time="2021-12-18T14:15:40Z" level=debug msg="Retrieving running containers"
    time="2021-12-18T14:15:40Z" level=debug msg="Session done: 0 scanned, 0 updated, 0 failed"
    Waiting for the notification goroutine to finish

**Expected behavior**
All containers checked.

**Environment**
Docker version 20.10.9, build c2ea9bc, x86

**Comment by piksel** [comment]
You are passing the value `true` on the command line as an argument to a flag. Boolean flags don't take arguments, they are just either passed or not passed. Hence why watchtower interprets the `true` arg as a container name. This was exactly why I added that startup message.

**Comment by oester** [comment]
Ah - I should have caught that. That's what I get for just transferring things from docker to command line args.
