### ISSUE TITLE
Service not found when passing shoutrrr URL

### ISSUE THREAD

**Issue by alfonder** [containrrr/watchtower#1168]
**Describe the bug**

Watchtower [documentation](https://containrrr.dev/watchtower/notifications/) points towards [Shoutrrr documentation](https://containrrr.dev/shoutrrr/v0.5/services/overview/) for service variants.
The one I need is [described](https://containrrr.dev/shoutrrr/v0.5/services/telegram/) as the telegram:// service.
But it doesn't work.

**To Reproduce**

1. Define WATCHTOWER_NOTIFICATION_URL to 'telegram://token@telegram/' type
2. Start watchtower container
3. Observe error in container logs

**Expected behavior**

Receive a message in telegram chat

**Screenshots**

**Environment**

<details>
 <summary><b> Logs from running watchtower container </b></summary>
time="2021-12-19T12:13:35+03:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: unknown service \"\"\n"
</details>

**Additional context**

**Comment by piksel** [comment]
Based on the error message you seem to have a syntax error somewhere. Would you mind posting your command line, or composer file for starting watchtower? 
It looks like you have either an additional quote or a newline at the start of the variable.

**Comment by alfonder** [comment]
> Based on the error message you seem to have a syntax error somewhere. Would you mind posting your command line, or composer file for starting watchtower? It looks like you have either an additional quote or a newline at the start of the variable.

Thank you. You're right. It's an extra quote inside the variable. It began to work. 

The report should be considered as invalid. 
Closing.
