### ISSUE TITLE
Server name in notifications

### ISSUE THREAD

**Issue by modem7** [containrrr/watchtower#1170]
It would be useful to have the server name in the notifications so that it's easier to see which server had an image updated on when running multiple instances on multiple hosts.

E.g. 

```
Server: Proxmox-Docker-Wiki
Found new linuxserver/mariadb:alpine image (080f2fd097da)
Found new linuxserver/mariadb:alpine image (080f2fd097da)
Stopping /GuacDB (d17675fea2fb) with SIGTERM
Stopping /Bookstack-db (19ec461cb1c3) with SIGTERM
Creating /Bookstack-db
Creating /GuacDB
Removing image 9dc8319bb697
```

**Comment by piksel** [comment]
This is actually (almost) implemented in #1125 by using the following template:
```
Server: {{ .Title }}
{{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
```
It would look like this:
```
Server: Watchtower updates on Proxmox-Docker-Wiki
Found new linuxserver/mariadb:alpine image (080f2fd097da)
Found new linuxserver/mariadb:alpine image (080f2fd097da)
Stopping /GuacDB (d17675fea2fb) with SIGTERM
Stopping /Bookstack-db (19ec461cb1c3) with SIGTERM
Creating /Bookstack-db
Creating /GuacDB
Removing image 9dc8319bb697
```

But perhaps #1125 should be extended to include just `.Hostname` as an additional field.

**Comment by modem7** [comment]
Oooh! Custom message field is also real useful! 

Having the additional field(s) would definitely be awesome, would be great for ansible deployments as well!

**Comment by piksel** [comment]
Updated the PR to include it. So
```go-template
Server: {{ .Host }}
{{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
```
should now give you the expected output (if that is merged ofc).

**Comment by modem7** [comment]
> Updated the PR to include it. So
> ```go-template
> Server: {{ .Host }}
> {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
> ```
> should now give you the expected output (if that is merged ofc).

Perfect! Thank you!
