### ISSUE TITLE
Add option to run pre-update script in a container spawned from the new image, not the old one.

### ISSUE THREAD

**Issue by khalilgharbaoui** [containrrr/watchtower#1186]
Using Ruby on Rails I need to run migrations before updating the container, and if these migrations fail I need to abort the deployment and deal with that first.

The problem is these migrations do not exist in the old container yet, and currently the `pre-update` hook only runs on the existing container. Which is kind of useless when doing an update using a recently committed script/codebase.

I need a `pre-update` using newly added script and codebase.

What I'm trying to do is:

1. run a script in the pre-update hook using a container spawned from the new image, 
2. if that fails, I want to give back `exit 127` code and send message. And basically cancel the entire deploy.

Watchtower does not do rollbacks, this is a good way to run migrations for Rails.

**Comment by piksel** [comment]
Hmm, so this is the flow you want:
1. Stop `MyApp` container running MyApp `v1.1`
2. Create new container with the same configuration as `MyApp`, with a new name `MyApp-Update` and version `v1.2` (latest)
3. Run the update-hook inside `MyApp-Update`
4. If the update in step 3 was successful:
    - Rename `MyApp-Update` to `MyApp`
    - Remove `MyApp`  
...or if it failed:
    - Remove `MyApp-Update`
5.  Start `MyApp`

Correct?

**Comment by khalilgharbaoui** [comment]
Yes... almost all except for `Step 1.` this does not need to happen as the first thing. 

1. Leave `MyApp v1.1` container running 
2. Create a new container with the same configuration as `MyApp v1.1`, with a name `MyApp-Update` version `v1.2` (latest)
3. Run the `pre update-hook` inside `MyApp-Update` version `v1.2`
  - If `exit 0` comes back from update in Step 3 (successfull)
     - Stop `MyApp` and rename to `MyApp-OLD` (v1.1)
     - Rename `MyApp-Update` to `MyApp` (v1.2)
     - Start `MyApp` (v1.2)
     - Remove `MyApp-OLD` (v1.1)
 - ...or if it failes with a `non-zero` exit code in Step 3
     - Remove `MyApp-Update`
 
 
 ... 
 
 Inside the Step 3 script, people can do things on their own like:
 
```
# run the migrations command here...

if [ $? -eq 0 ]; then
  # ... code here
  exit 0
else
  # ... run rollback commands here
  exit 1
fi
```
which will allow for all the possibilities needed for a Rails migration run or rollback before even starting the new version.

**Comment by piksel** [comment]
Wouldn't it cause havoc if the update is performed while the app is running? I'm thinking of stuff like db migrations etc.

**Comment by khalilgharbaoui** [comment]
Well, yes and no...
db migrations run in a transaction, either they all go correctly and give `exit 0` or they are rolled back give `exit 1`
_additionally_, things involved within that transaction are **locked** and can not be changed as long as that transaction is running.
Usually this goes ok

But sure if we must have a container stop before/during this process it is also fine...
Max downtime will only last the duration of the migration... which is an acceptable downtime.
As soon as that script is finished, it can go up again with the new version.

Yours is the more generic approach... and is perfectly fine 🤔 
As long as it's possible to run a script within a container spawned from the new image before actual deploy, it's ok.
