### ISSUE TITLE
Suggestion: maintenance window for updates

### ISSUE THREAD

**Issue by mithrandi** [containrrr/watchtower#12]
Some of us without high availability service setups would prefer to keep our restarts / disruptions within scheduled maintenance windows. Being able to specify a time range to do updates in (or equivalently, a time range to _not_ do updates in) would be helpful in this regard.

**Comment by AnotherSymbiote** [comment]
+1 for this!

**Comment by n3r0-ch** [comment]
+1

**Comment by xarem** [comment]
+1

**Comment by TheKas** [comment]
+1

**Comment by EtienneRod** [comment]
Came here to suggest that! A maintenance window is a must for automatic image restart

**Comment by tamara-schmitz** [comment]
+1

**Comment by ATCUSA** [comment]
+1
