### ISSUE TITLE
Exclude Container for Update

### ISSUE THREAD

**Issue by gist901** [containrrr/watchtower#1210]
I would like to request the ability to exclude a container from being processed by Watchtower. I know we can define which containers to be included, but it would be nice to declare which containers to exclude. 

I currently have a container that when it gets updated via Watchtower it breaks several other containers.

**Comment by benridley** [comment]
Isn't this how Watchtower currently works? https://containrrr.dev/watchtower/container-selection/#full_exclude
You can also do the inverse with the --label-enable flag.

**Comment by piksel** [comment]
Yes, as pointed out above. Just put the label `com.centurylinklabs.watchtower.enable="false"` on the container you want watchtower to never update and it will just skip it.
