### ISSUE TITLE
Feat Req: Multiple Hosts Support 

### ISSUE THREAD

**Issue by neo-neo1** [containrrr/watchtower#1218]
Watachtower can be pointed at a remote host, wonderful and useful but stops short to not support multiple. Can the ability to support hosts please be added?

 Trying to avoid running 4 Watchtower containers on each of my Rasp Pi’s. 

Sorry if I missed anything, I read the docs and didn’t see a mention for multiple hosts.

**Comment by piksel** [comment]
This seems like a lot of complexity to add, with very limited usage scope. Especially since it's possible to do using multiple instances.

Why do you need to target multiple hosts on every RPi?

**Comment by neo-neo1** [comment]
> This seems like a lot of complexity to add, with very limited usage scope. Especially since it's possible to do using multiple instances.
> 

Watchtower currently supports remote hosts. I guess multiple remote hosts is not as simple as I assumed to implement.

>
> Why do you need to target multiple hosts on every RPi?

Because I don’t run Kubernetes. Multiple Rasp Pi simply running various containers. Currently to use watchtower I’d be forced to redundantly install it on each Rasp Pi.  

Portainer has the ability to add multiple hosts and works wonderfully. I wouldn’t consider this is a radical use case.

Thanks anyway. Will seek elsewhere.

**Comment by piksel** [comment]
I mean, you run all the watchtower instances on the same "controller" machine, each connecting to a different host.

> Trying to avoid running 4 Watchtower containers on each of my Rasp Pi’s.

This made it seem like you have X amount of RPis that connect to 4 hosts *each*, totaling X * 4 hosts.

**Comment by simonaronsson** [comment]
Yeah, this is not a use case I see us add to the core.

I would also say that running something expecting it to be redundant using vanilla docker only most likely is a bad idea. I would advise you to consider either Swarm or Kubernetes if redundancy is something you actually want and need.

**Comment by PostWarTacos** [comment]
Not sure why anyone sh**ting on the idea. I recently added 3 more pis to my setup and about 30 more containers. Literally, what I have been researching for the last 10 mins is how to do multiple remote hosts. If I need to run multiple instances, I might as well just write the script and cron myself. A single host, including local host, is literally the dumbest idea in any form of self-hosting or automation. *removes watchtower from compose file, firefox bookmark, and docker hub account*

**Comment by piksel** [comment]
@PostWarTacos, you are free to do whatever you want, but the point is that "that is not how watchtower currently works". This is a community project and if you want someone to spend time on implementing this, the usage should be clear. I still have no idea what the original poster was trying to do, or why the current solutions would not suffice.

**Comment by neo-neo1** [comment]
> @PostWarTacos, I still have no idea what the original poster was trying to do, or why the current solutions would not suffice.

Not sure how I could've been more clearer

**Comment by piksel** [comment]
@neo-neo1 Okay. Let me try to elaborate.

> Trying to avoid running 4 Watchtower containers on each of my Rasp Pi’s.

Why would you need to be doing that? Are you running docker in docker, or VMs on your Pis?

And if you really mean that you are doing that, then why would not a watchtower instance per docker host be sufficient? Are you concerned about memory usage? CPU? network IO?
Why would it not be simpler to just run the same stack on each host (including watchtower)?

**Comment by PostWarTacos** [comment]
> you are free to do whatever you want

thank you so much for your unsolicited permission. I truly appreciate it!



> the usage should be clear

it is...half ass automation is the message here.

> I still have no idea what the original poster was trying to do, or why the current solutions would not suffice.

would you like assistance? maybe some lessons in critical thinking? Coincidentally, I'm actually a cybersecurity instructor and I usually spend several days talking about docker every class.

**Comment by PostWarTacos** [comment]
> Why would you need to be doing that? Are you running doc

@piksel Either broken English or misspoke. I'm starting to think it's the lessons in critical thinking that would help most. 

> Why would it not be simpler to just run the same stack on each host (including watchtower)?

I'm assuming each host is running different containers. I have different containers running on 3 (soon to be 5) different hosts. I wrote a bash script to update each container and host via a cronjob. The logs from the updates are sent to a website and i'm considering webhooking the sites feed to my private discord or signal.

automation should NEVER about doing it half ass. Full and complete solutions or don't do it at all. maybe one day I'll decide to fork watchtower and make my own. today is not that day.

**Comment by piksel** [comment]
@PostWarTacos, listen. If you want me to spend my free time, providing you additional features in an open source project, then I am telling you how to proceed. This is not an argument that you can "win" or whatever. If I don't think I have the information I need to help you, it's not like you can just convince me that I am wrong about that. 

I guess I also have to point out that insults will rarely get you anywhere.

**Comment by PostWarTacos** [comment]
Lmfao who's insulting you? I'm just responding and offering you help... I already stated I have my solution.

**Comment by piksel** [comment]
> > the usage should be clear

> it is...half ass automation is the message here.

It's only "half assed" for your particular setup, and that's because it's not the common case. That's why I am trying to understand your setup. Talking about how it's obvious to you doesn't help (or how you have deleted bookmarks and wrote your own script).

> Full and complete solutions or don't do it at all.

Then I think you should try to avoid community driven projects. We try to create software we find useful together, incrementally improving on what others have done before.

**Comment by PostWarTacos** [comment]
It's useful only if you have just one host... are you saying that encompasses the majority of the community? Lol watchtower is narrowly scoped. You wanna use it? Cool, good for you. But don't paint a picture showing that it's something it isn't. For example, it isn't the answer if you have more than one host. 
Wanna know how to script it? Should I explain how to write a cron job, too?
A 2 second google search, and I found your answer. Did all the legwork for you.
https://gist.github.com/vermotr/f9ba7dc5cd7834b9c9730e4e1a5e9cab
Ok, this conversation is certainly going places, so, I'll just end it there. Have a wonderful day.

**Comment by PostWarTacos** [comment]
As stated earlier...3, soon to be 5 hosts, and over 30 (soon to be closer to 50) containers. I'm well versed in community projects....
