### ISSUE TITLE
v2tec/watchtower on DockerHub out of date? Option "label-enable" not working

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#122]
I am trying to get Watchtower running by integrating it in my compose file. I am using the example from the Readme with a small difference:

```
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --label-enable
```

I am using `--lable-enable` as it is listed in the [commands](https://github.com/v2tec/watchtower#options). Docker successfully pulls "v2tec/watchtower" and creates a container, but the container log just contains:

```
Incorrect Usage. flag provided but not defined: -label-enable

NAME:
   watchtower - Automatically update running Docker containers

USAGE:
   watchtower [global options] command [command options] [arguments...]

VERSION:

1


:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --host value, -H value      daemon socket to connect to (default: "unix:///var/run/docker.sock") [$DOCKER_HOST]
   --interval value, -i value  poll interval (in seconds) (default: 300) [$WATCHTOWER_POLL_INTERVAL]
   --schedule value, -s value  the cron expression which defines when to update [$WATCHTOWER_SCHEDULE]
   --no-pull                   do not pull new images [$WATCHTOWER_NO_PULL]
   --no-restart                do not restart containers [$WATCHTOWER_NO_RESTART]
   --cleanup                   remove old images after updating [$WATCHTOWER_CLEANUP]
   --tlsverify                 use TLS and verify the remote [$DOCKER_TLS_VERIFY]
   --debug                     enable debug mode with verbose logging
   --help, -h                  show help
   --version, -v               print the version
```

It seems that the watchtower version on DockerHub does not know the command "label-enable" command. The page for [hub.docker.com/r/v2tec/watchtower](https://hub.docker.com/r/v2tec/watchtower/) does not include "label-enable" either.

When I used `command: --version` to get the exact version that is hosted on DockerHub I got "watchtower version v0.1.1" as a result.

**Comment by stffabi** [comment]
Unfortunately [v0.2.0](https://github.com/v2tec/watchtower/milestone/3), which contains this new feature, has not yet been released.

**Comment by ghost** [comment]
Can you please give a rough estimate when this new feature will be available via docker?

**Comment by oschrenk** [comment]
Hah. I just experienced the same issue, debugged for twenty minutes and now found this issue that was opened two hours ago. Small planet.

**Comment by stffabi** [comment]
I hope to find some spare time for releasing it until the end of the weekend.

**Comment by Aidi2016** [comment]
Can you please give a rough estimate when this new feature will be available and  released latest docker image ?

**Comment by stffabi** [comment]
Watchtower `v0.2.0` has been released and docker hub has been updated.
