### ISSUE TITLE
[DOCS] Messed up formatting of the docker-compose example

### ISSUE THREAD

**Issue by SIMULATAN** [containrrr/watchtower#1226]
**Describe the bug**
The formatting of the docker-compose example on the main page in the docs is for some reason messed up, it looks fine in the source.

**Screenshots**
![Docs Page](https://user-images.githubusercontent.com/63104422/154044186-b6f56866-e2e4-48ca-8d19-1acf0f3db049.png)
![Code in the Source](https://user-images.githubusercontent.com/63104422/154044250-0d518f38-7f63-44d3-b565-05765aa931f0.png)

<details>
<summary>Notes</summary>
I hope this belongs here! Also, I found no other issue regarding this, hopefully I didn't overlook something...
</details>

**Comment by piksel** [comment]
The docs where not automatically published upon release. Not sure why that CI job didn't run, but that's why it seemed fixed in the source (it was).
