### ISSUE TITLE
Option "--label-enable" behaviour

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#123]
There is something about `--label-enable` that is not completely clear in the documentation. The [options](https://github.com/v2tec/watchtower#options) in the Readme say:

> --label-enable: Watch containers where the com.centurylinklabs.watchtower.enable label is set to true.

Does that mean watchtower *also* watches containers with that label, or does it mean that watchtower *exclusively* watches containers with that label? If I use both option the filter by container names and `--label-enable` which of the two will take preference?

I want to achieve the following configuration: Watchtower should be deployed as a container along with some other services, and it should *only* watch those containers that are labeled with `com.centurylinklabs.watchtower.enable`, and ignore all other containers.

**Comment by stffabi** [comment]
Currently all filters are combined with `AND`. Therefore if you use `--label-enable` only containers with `com.centurylinklabs.watchtower.enable=true` are considered for the remaining filters. If you additionally specify container names, at the end only containers with both conditions are considered for an update.

**Comment by stffabi** [comment]
For your use case you can just use `--label-enable` without listing any container names and flag your containers with the label `com.centurylinklabs.watchtower.enable=true`.

**Comment by stffabi** [comment]
I hope my explanations clarified the situation. If you are still having questions, feel free to open another issue, or reopen this one.

**Comment by ghost** [comment]
Yes, thanks for the clarification
