### ISSUE TITLE
HTTP API: Endpoint other than /v1 ?

### ISSUE THREAD

**Issue by wfleurant** [containrrr/watchtower#1236]
**feature request: allow changing http api endpoint from /v1 to other**

I put in haproxy.cfg something like
```
backend watchtower_svc
	mode http
	server watchtower-api 127.0.0.1:8080 check maxconn 200
        timeout connect 2s
        timeout server 30s

frontend docker.box
	mode http
	bind 0.0.0.0 443 ssl crt /path/cert.oil alpn http/1.1
	default_backend other_svc

	acl watchtower path_beg /v1
	use_backend watchtower_svc if watchtower
```

If the omitted default "other_svc" backend is expecting `/v1` endpoint then the config would clobber the services.  
If i try to use `acl watchtower path_beg /watchtower` then watchtower will return 404.  

The HTTP API is sweet, so thanks for adding this. 

**Describe the solution you'd like**
Why not something we can namespace `--http-api-endpoint /v2` or `--http-api-endpoing /watchtower`

**Describe alternatives you've considered**
In the case `/v1` is used twice.... one _could_ bind on a 2nd IP/Hostname but... meh, you know.

**Comment by wfleurant** [comment]
https://github.com/containrrr/watchtower/blob/f79e4b5435baf8cdf6f69281ae11a7215e17f320/pkg/api/update/update.go#L26

**Comment by piksel** [comment]
I don't really understand your problem, it seems like it should just be possible to do in haproxy. I have never seen a web service where you would customize it's API to suit the proxy. It seems really backwards.

**Comment by wfleurant** [comment]
if haproxy matches /watchtower and pipes to watchtower:8080, watchtower sees /watchtower/v1/update.  
right... as a proxy, i dont think rewrites even exist.

perhaps its only common if a docker-compose has 3 containers with live, rc, and dev environment.  
here is a flask example where a /v1 container could be a default, but overwritten by environment variable.

```python

app = Flask(__name__, **flask_opts)
app.config.from_object(__name__)
app.wsgi_app = PrefixMiddleware(app.wsgi_app, prefix=environ['API_PREFIX'])

class PrefixMiddleware(object):

    def __init__(self, app, prefix='/v1'):
        self.app = app
        self.prefix = prefix

    def __call__(self, environ, start_response):

        if environ['PATH_INFO'].startswith(self.prefix):
            environ['PATH_INFO'] = environ['PATH_INFO'][len(self.prefix):]
            environ['SCRIPT_NAME'] = self.prefix
            return self.app(environ, start_response)
        else:
            start_response('404', [('Content-Type', 'text/plain')])
            return ["This url does not belong to the app.".encode()]

app.run()
```

**Comment by piksel** [comment]
I looked at the HAProxy docs, and it doesn't support any rewriting as you said. It's probably because it's main purpose as a load balancing proxy. If you wanted to map several services to a single HTTP host, it would be more suitable to use something like `traefik` or `nginx`.
