### ISSUE TITLE
[Feature request] Run a script as notification

### ISSUE THREAD

**Issue by ln-12** [containrrr/watchtower#1237]
**Is your feature request related to a problem? Please describe.**
watchtower and shoutrrr provide a lot of integrations for notifications, but currently I see no option to add a custom notification service. In my opinion, the most versatile solution would be to run a pre-defined script when a notification occurs.  

**Describe the solution you'd like**
Define a path (and call arguments) to run a user defined (shell) script.

**Describe alternatives you've considered**
As [shoutrrr](https://github.com/containrrr/shoutrrr) is responsible for handling a lot of use cases, this feature request might also fit there.

**Comment by ln-12** [comment]
I don't think that this can be closed.

**Comment by piksel** [comment]
The watchtower container contains neither a shell, nor any other binaries except `watchtower` itself, so running a shell script is not really feasible.

**Comment by ln-12** [comment]
How about passing a binary using volumes which can be called with arguments?

**Comment by simonaronsson** [comment]
This is outside the scope of the watchtower project.
