### ISSUE TITLE
Add arm64 support

### ISSUE THREAD

**Issue by RyanRamchandar** [containrrr/watchtower#124]
Also called `arm64v8` or `aarch64`

**Comment by stffabi** [comment]
Thanks, that would be a nice idea, but unfortunately I'm not really familiar with the `arm64v8` architecture. 

Is that the normal `arm64` [GOARCH](https://golang.org/doc/install/source#environment) architecture?

**Comment by RyanRamchandar** [comment]
@stffabi yes.

As a side note, I ran the latest `v2tec/watchtower:armhf-0.1.1` docker image on our `arm64` device and it worked just fine. It didn't update any containers yet but it seems to be polling for updated images normally. Perhaps a `arm64` variant is unnecessary. Still investigating.

**Comment by stffabi** [comment]
Glad to hear the armhf builds works for you. I'll close the issue for now, feel free to reopen it if you need `arm64' builds.
