### ISSUE TITLE
Option "--label-enable" doesn't exist !!!

### ISSUE THREAD

**Issue by ystreibel** [containrrr/watchtower#125]
Hi,

I need to use this cool feature but :

$> docker run --rm v2tec/watchtower --help
NAME:
   watchtower - Automatically update running Docker containers

USAGE:
   watchtower [global options] command [command options] [arguments...]

VERSION:
   v0.1.1

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --host value, -H value      daemon socket to connect to (default: "unix:///var/run/docker.sock") [$DOCKER_HOST]
   --interval value, -i value  poll interval (in seconds) (default: 300) [$WATCHTOWER_POLL_INTERVAL]
   --schedule value, -s value  the cron expression which defines when to update [$WATCHTOWER_SCHEDULE]
   --no-pull                   do not pull new images [$WATCHTOWER_NO_PULL]
   --no-restart                do not restart containers [$WATCHTOWER_NO_RESTART]
   --cleanup                   remove old images after updating [$WATCHTOWER_CLEANUP]
   --tlsverify                 use TLS and verify the remote [$DOCKER_TLS_VERIFY]
   --debug                     enable debug mode with verbose logging
   --help, -h                  show help
   --version, -v               print the version

**Comment by stffabi** [comment]
That new feature will be introduced with `v0.2.0`, which unfortunately has not been released yet. Please see #122 for more information.

I'm going to close this issue, as it duplicates #122

**Comment by stffabi** [comment]
I hope to get the release out by the end of the weekend. So stay tuned 😄

**Comment by stffabi** [comment]
I reopened the issue, so you get informed, when the release is out. Thanks for using watchtower.

**Comment by stffabi** [comment]
This new feature has been just released with watchtower `v0.2.0` and docker hub has been updated. 

Everything should work as soon you are pulling the latest version. Feel free to open a new issue if you are seeing any new problems.

**Comment by jacobalberty** [comment]
I see the 'latest' tag was updated 20 minutes ago but when I check the version I get...
```
docker pull v2tec/watchtower
Using default tag: latest
latest: Pulling from v2tec/watchtower
Digest: sha256:c1b50574d4d12c16906f4498b9e2a75b7816779534e2e084c2aa300d446de24b
Status: Image is up to date for v2tec/watchtower:latest
docker run -t -i --rm v2tec/watchtower -v
watchtower version v0.1.1
```

Is latest supposed to stay on 0.1.1 and I need to use tag 0.2.0 or was there a mistake in the latest tag?

**Comment by ransur0t** [comment]
Pull with the 0.2.0 tag to get "latest". Worked for me ;)

**Comment by stffabi** [comment]
Thanks, there was a mistake with the latest tag. Has been fixed.
