### ISSUE TITLE
Do not reuse hostname for new container

### ISSUE THREAD

**Issue by giggio** [containrrr/watchtower#1251]
**Is your feature request related to a problem? Please describe.**
I am running Azure DevOps build agents as containers, and they identify themselves to the server with their hostnames. When the container is recreated the hostname from the container that was replaced is being kept in the new container and it cannot connect back to the server, as there is already a build agent with that name.

**Describe the solution you'd like**
A label that would inform watchtower to do not keep the hostname, but rather generate a new one with the default value (based on the container id).

**Describe alternatives you've considered**
I can't see an alternative, if the hostname can't be recreated I won't be able to use watchtower to update the build agent containers.

**Comment by piksel** [comment]
I link this to https://github.com/containrrr/watchtower/issues/1231 since it's a very niche use that would be better supported by user scripting.
