### ISSUE TITLE
Proposal: Specify no-pull per service/container via label

### ISSUE THREAD

**Issue by neurolabs** [containrrr/watchtower#1256]
I am watching multiple containers with watchtower. One of them only gets local image updates (built via cron). It would be nice if watchtower could restart/update that container. But currently, I get this error message:

`Unable to update container "/name_name_1": Error response from daemon: pull access denied for custom/name, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next.`

It would be nice to be able to specify the no-pull option just for this container via a label.

**Comment by simonaronsson** [comment]
Sounds like a good idea! Feel free to open a PR and I'll make sure to review it!

**Comment by neurolabs** [comment]
@simskij I would love to, but I am quite busy at the moment. Don't expect anything soon. Maybe we can wait a bit until others show interest for this particular functionality.

**Comment by neurolabs** [comment]
So lovely to see this implemented. Thanks to everyone involved @gilbsgilbs @nedzadalibegovic @piksel
