### ISSUE TITLE
Shoutrrr Notification to Pushover doesn't respect Priority

### ISSUE THREAD

**Issue by Snuffy2** [containrrr/watchtower#1258]
Running Watchtower setup to send notifications to Pushover via Shoutrrr. It is working but the Priority doesn't seem to be respected. I'm trying to send it as a priority of -2 as I like to get it as an FYI but don't want an actual notification. 

When I use Shoutrrr to call Pushover directly, then the Priority works as expected. Cross-posted as a Shoutrrr issue (https://github.com/containrrr/shoutrrr/issues/230) as well. Happy to close one if desired.

From my docker-compose for Watchtower:
```
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - "WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:<mytoken>@<myuser>/?priority=-2"
      - "WATCHTOWER_NOTIFICATION_TEMPLATE=({{.Level}}): {{.Message}}{{println}}{{end}}"
```

**Comment by piksel** [comment]
Watchtower currently uses v0.5.2 of shoutrrr which was released before this fix was incorporated. We should release a new version with the fix included.

**Comment by OliverHi** [comment]
Any plans when this will be updated? I see that PR is already merged and would love to have properly working notification priorities. Please let me know if there is anything I can do to help make that happen
