### ISSUE TITLE
Container [container] could not be removed

### ISSUE THREAD

**Issue by Manuel5cc** [containrrr/watchtower#1268]
From some time ago, certain containers don't update correctly and there is no info on what the error was. It just shows an error on the logs saying "container could not be removed", but it is actually removed, so I end with no update and no container either.
is there a way to prevent this removal when something fails?

```
time="2022-04-09T04:40:11+02:00" level=debug msg="No pre-update command supplied. Skipping" container=/sonarr
time="2022-04-09T04:40:11+02:00" level=info msg="Stopping /sonarr (5dc4dc12618d) with SIGTERM"
time="2022-04-09T04:40:12+02:00" level=debug msg="Removing container 5dc4dc12618d"
time="2022-04-09T04:40:14+02:00" level=error msg="container /sonarr (5dc4dc12618d) could not be removed"
```

[_watchtowerr_logs (1).txt](https://github.com/containrrr/watchtower/files/8456589/_watchtowerr_logs.1.txt)

**Comment by piksel** [comment]
This means that `sonarr` was still running after watchtower had told docker to stop it. Not sure how that happened, but you could try increasing the timeout using `--stop-timeout 30s` or `WATCHTOWER_TIMEOUT=30s`

**Comment by Manuel5cc** [comment]
> This means that `sonarr` was still running after watchtower had told docker to stop it. Not sure how that happened, but you could try increasing the timeout using `--stop-timeout 30s` or `WATCHTOWER_TIMEOUT=30s`
My timeout was actually set on 120 and also Sonarr is an easy container to stop, does not require many preparation. Should I try shortening this timeout or maybe use any other signal to terminate it?

**Comment by Manuel5cc** [comment]
> This means that `sonarr` was still running after watchtower had told docker to stop it. Not sure how that happened, but you could try increasing the timeout using `--stop-timeout 30s` or `WATCHTOWER_TIMEOUT=30s`

My timeout was actually set on 120 and also Sonarr is an easy container to stop, does not require many preparation. Should I try shortening or expanding this timeout or maybe use any other signal to terminate it?

**Comment by piksel** [comment]
Maybe. I have no experience with that image myself, I only know that watchtower first tells the container to stop, then asks docker to remove the container, and then asks docker if the container is still present. If it is, then the above message is presented.

One possibility is that, since you increased the timeout and maybe have `restart: always` on the container, it gives it enough time to restart again? I have never experienced this problem earlier.

**Comment by Manuel5cc** [comment]
> One possibility is that, since you increased the timeout and maybe have `restart: always` on the container, it gives it enough time to restart again? I have never experienced this problem earlier.

This container is set to `restart: Unless stopped `so that should't be the issue. Do the timeout env need to have the "s" after the number? Maybe the issue is that it's not applying the configuration because I set it only with the numeric value.

**Comment by piksel** [comment]
Haha, yeah, I think that is interpreted as `120ms`.

**Comment by Manuel5cc** [comment]
Yeah checking the logs again it was definitely not waiting 120s. I'll review the result in the next schedule.

**Comment by piksel** [comment]
It's actually a bit worse. Due to the way the viper/cobra are set up, it actually reverts to `0` when a value that cannot be parsed is encountered.
