### ISSUE TITLE
Watchtower is unable to update itself

### ISSUE THREAD

**Issue by Dids** [containrrr/watchtower#127]
I'm successfully using Watchtower with a private registry, and it's correctly detecting changes in the private images.

However, when it comes to updating Watchtower itself, I'm assuming it's trying to use the same (private repository) credentials for the public repository, which naturally will fail:

```
time="2017-12-20T07:21:15Z" level=debug msg="Pulling v2tec/watchtower:latest for /tyomaarainrealm_watchtower_1" 
time="2017-12-20T07:21:15Z" level=debug msg="Loaded auth credentials {user password     } for v2tec/watchtower:latest" 
time="2017-12-20T07:21:16Z" level=debug msg="Error pulling image v2tec/watchtower:latest, Error response from daemon: Get https://registry-1.docker.io/v2/v2tec/watchtower/manifests/latest: unauthorized: incorrect username or password" 
time="2017-12-20T07:21:16Z" level=info msg="Unable to update container /tyomaarainrealm_watchtower_1. Proceeding to next."
```

**Comment by stffabi** [comment]
Thanks for your report. May I ask you what version of docker you are using?

**Comment by simonaronsson** [comment]
Closing due to lack of replies.

**Comment by thomas-udalrik** [comment]
@simskij This seems to be the problem on my instance as well.

I enabled the slack notification and every 30 seconds I'm receiving the message "Unable to update container /watchtower. Proceeding to next."

Update of containers from the private registry work.

Watchtower version is 0.3.4

My configuration:
```
sudo docker run -d \
  --name watchtower \
  -e REPO_USER=private-registry-user \
  -e REPO_PASS=private-registry-pass \
  -e WATCHTOWER_NOTIFICATIONS_LEVEL=info \
  -e WATCHTOWER_NOTIFICATIONS=slack \
  -e WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL="hook-url" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower -i 30
```

**Comment by simonaronsson** [comment]
@kirladu Oh, when using private registrys you'll have to provide the watchtower instance the full path to the image, I.e. index.docker.io/containrrr/watchtower:latest. if the problem remains after trying that, feel free to open a new issue and i'll try to help you to the best of my abilities 🙏

**Comment by thomas-udalrik** [comment]
@simskij Thanks for the hint! I switched to the full image address. Still the error message I receive every 30 seconds in Slack hasn't changed.

My adapted configuration:

```
sudo docker run -d \
  --name watchtower \
  -e REPO_USER=private-registry-user \
  -e REPO_PASS=private-registry-pass \
  -e WATCHTOWER_NOTIFICATIONS_LEVEL=info \
  -e WATCHTOWER_NOTIFICATIONS=slack \
  -e WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL="hook-url" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  registry.hub.docker.com/containrrr/watchtower:latest -i 30
```

I'm going to have a look at the source code. Maybe Watchtower is trying to login to Docker Hub with the credentials for the private registry?

**Comment by thomas-udalrik** [comment]
@simskij Turned on debug mode and got the following message in Slack:

```
Error response from daemon: Get https://registry.hub.docker.com/v2/containrrr/watchtower/manifests/latest: unauthorized: incorrect username or password
```

So Watchtower is in deed trying to login to Docker Hub with the credentials for the private registry.

Am I missing something in the configuration concept or should we improve Watchtower for that situation?

**Comment by thomas-udalrik** [comment]
My current workaround is to maintain Watchtower in my private registry.

**Comment by vergissberlin** [comment]
Hi! A workaround is no solution right? When I use a private registry, _watchtower_ is not able to download images from other registries like docker hub. Is there another ticket about this topic?

Cheers, André

**Comment by aktur** [comment]
My workaround is to use the same credentials for my public and private repo.

**Comment by simonaronsson** [comment]
@aktur and @vergissberlin, could you please open a new issue and also provide your config.json and docker-compose.yml and/or launch commands? Locking this issue to prevent further discussion as it's closed. Thanks.
