### ISSUE TITLE
not respecting WATCHTOWER_NOTIFICATION_TITLE_TAG

### ISSUE THREAD

**Issue by eddgeywing** [containrrr/watchtower#1272]
I was kindly informed that my previous report of WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG not working had already been addressed. However, the change in [#1219](https://github.com/containrrr/watchtower/pull/1219) does not work either. I continue to receive the container ID in the subject line. The new variable is now --notification-title-tag <TAG> but I cannot get it to work with my email notifications. Would it also be WATCHTOWER_NOTIFICATION_TITLE_TAG=ComputerName? That does not work either. I do receive the emails and there is nothing of note in the debug logs. I am using this on 3 different machine with same result. All running current 1.4.0 container.

Thanks for any assistance or guidance.

**Comment by piksel** [comment]
These changes have not been released yet.

**Comment by timrettop** [comment]
@eddgeywing why not use WATCHTOWER_NOTIFICATIONS_HOSTNAME ?
