### ISSUE TITLE
notifiy via sendmail

### ISSUE THREAD

**Issue by asaage** [containrrr/watchtower#1276]
Would you add the option to notifiy via the sendmail command?
I realy dont want to put any email-credentials or create a dedicated mailbox for watchtower to send notification-mails.

**Comment by piksel** [comment]
Are you using watchtower outside a container? Otherwise there is no `sendmail` command inside the container, and it would still need configuration mounted.

**Comment by asaage** [comment]
It's inside a container.
Well i guess i have to go with the available smtp-options then.
