### ISSUE TITLE
Updating container with wrong different arch

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [containrrr/watchtower#1287]
**Describe the bug**
 i have latest watchtower app, when i run first time it downloaded and restarted all my container's image which were pending for update but after that i found that some of my containers are not starting and after inspection i found that watchtower downloaded wrong arch for those container images , i am on arch64 and i have 27 or more containers running watchtower downloaded correct arch for many containers but 4-5 container got problem, i think problem is those container's app developer stopped to support arch64 in newer version and so there is no new images on registry for arm64 only amd64 is available. and watchtower is trying with only latest tag and downloading amd64 image despite of my arch which is arm64

**To Reproduce**

**Expected behavior**
 it should download and start exact same container ,
I.e if i am running container of arm64 then it should download arm64 images not amd64

**Screenshots**

**Environment**

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```

```

</details>

**Additional context**

**Comment by piksel** [comment]
Watchtower does not process the target/arch in any way, it only tells docker to pull the image with the given tag, so selecting the appropriate architecture should be done by the docker daemon. If they changed from a multi-arch tag to one that only explicitly points to an `amd64` image, that might cause the above issue...? But that seems like such a strange thing to do, and especially that multiple authors have done that simultaneously... Could you provide logs and/or a list of what images this concerns?

**Comment by Morakhiyasaiyam** [comment]
> Watchtower does not process the target/arch in any way, it only tells docker to pull the image with the given tag, so selecting the appropriate architecture should be done by the docker daemon. If they changed from a multi-arch tag to one that only explicitly points to an `amd64` image, that might cause the above issue...? But that seems like such a strange thing to do, and especially that multiple authors have done that simultaneously... Could you provide logs and/or a list of what images this concerns?

Yes it make sense! 
https://hub.docker.com/r/frappe/erpnext-worker/tags
Look inam talking about this image and every image of erpnext ecosystem ! They stopped to build arm64 after  building some version and now if i start watchtower it updates with amd64 image

**Comment by piksel** [comment]
Yeaah. That actually seems to be the case.

What watchtower does is the equivalent of:
```
$ docker pull frappe/erpnext-worker:latest
$ docker run frappe/erpnext-worker:latest
```
And that will cause docker to grudgingly use the image tagged with `latest`, even if the current arch is not supported.
If your vendor has stopped supporting your target, you should just disable watchtower updates on it (since there won't be any new images anyway), or ask the vendor to add a separate tag for `:latest-aarch64`. Or perhaps dropping the arch was done by accident?

In either case, this is not something that watchtower currently tries to handle. Arguably, it might actually be what most user wants, since they explicitly instructed that the container should be updated to `latest` and docker desktop has [multi-arch support](https://docs.docker.com/desktop/multi-arch/#multi-arch-support-on-docker-desktop) with emulation.

**Comment by Morakhiyasaiyam** [comment]
> Yeaah. That actually seems to be the case.
> 
> What watchtower does is the equivalent of:
> ```
> $ docker pull frappe/erpnext-worker:latest
> $ docker run frappe/erpnext-worker:latest
> ```
> And that will cause docker to grudgingly use the image tagged with `latest`, even if the current arch is not supported.
> If your vendor has stopped supporting your target, you should just disable watchtower updates on it (since there won't be any new images anyway), or ask the vendor to add a separate tag for `:latest-aarch64`. Or perhaps dropping the arch was done by accident?
> 
> In either case, this is not something that watchtower currently tries to handle. Arguably, it might actually be what most user wants, since they explicitly instructed that the container should be updated to `latest` and docker desktop has [multi-arch support](https://docs.docker.com/desktop/multi-arch/#multi-arch-support-on-docker-desktop) with emulation.

No it is not done by accidentally! They are building images for all arch on amd and for Building arm image they have to use qemu and according to them some pandas and other python packages taking so much time on building wheels so they dropped support for arm
So maybe can i open issue on moby repository to check request of pull image by first which arch is requesting and then process latest tag with same arch if available? Maybe today i got in this situation but it can solve same for other in future?

**Comment by piksel** [comment]
You could, but I don't think it would lead to anything. I still think the current behaviour is favorable for most users.
What exactly were the problem you had with it switching arch? Performance?

**Comment by TrueXakeP** [comment]
I faced this issue too. One of our service relies on 32-bit Apache httpd. But Watchtower always pulls out the amd64 image.
Why Watchtower can't check the image platform on which the container is based to run the equivalent of `docker pull http:2.4 --platform linux/i386`? Of course `docker pull httpd:2.4` doesn't know that I'm going to build a 32-bit container on it with `--platform`. (I use compose with `platform:` set)

**Comment by piksel** [comment]
@TrueXakeP it's related, but not exactly the same issue. The reason for closing this was the scenario where a `platform` stopped being supported by a vendor. In that case, you could either stop updating it with watchtower, or use it to get the latest version (using qemu).

In your scenario, it's a multi-arch tag that both contains your host platform and the one you want to actually use. Even though it seems like a very specialized use case, the current behaviour doesn't seem correct.
If the container was started with an explicit platform set, an updated container should use the same platform.

**Comment by TrueXakeP** [comment]
I have used docker compose to create containers.

So should I open a new issue?

Okay, I'll file a new issue when I collect debug logs on the next image update.
