### ISSUE TITLE
Can you please add this to the post-update

### ISSUE THREAD

**Issue by THillebrand** [containrrr/watchtower#1290]
The (still undocumented) feature is great for our purpose, but can you add the same functionality to the post-update hook (in the same manner, of course)?

I have added a script to the post-update to check the database-version. If they not match, the script returns exit 1. It would be great if the post-update hook could log a error- or warning-message, so the slack-notification gets a message (level warn) and we are alarmed that something went wrong.

https://github.com/containrrr/watchtower/blob/9e7dfe7be442d1259b6ed5223558f2201f1fd43b/internal/actions/update.go#L76-L80

**Comment by THillebrand** [comment]
The original issue: https://github.com/containrrr/watchtower/issues/499

**Comment by piksel** [comment]
So basically changing this to log an error if the error code is not 0?:
https://github.com/containrrr/watchtower/blob/9e7dfe7be442d1259b6ed5223558f2201f1fd43b/internal/actions/update.go#L124

**Comment by THillebrand** [comment]
Yes, this is correct. Seems not to be a big deal.

**Comment by simonaronsson** [comment]
I agree that this change makes sense.

**Comment by 11-aryan** [comment]
Hi can I take up this issue?

**Comment by piksel** [comment]
Hello! Sure, @11-aryan. I'd be happy to review it!

**Comment by gaurangkudale** [comment]
Hi @piksel 
I have created on PR to solve this issue please let me know if you have any suggestions for this change #1791

**Comment by piksel** [comment]
Actually, I think this is already implemented? 
Looking at the code:

https://github.com/containrrr/watchtower/blob/284066a39d083fe4865ae43119a41b42d450b178/pkg/lifecycle/lifecycle.go#L101-L105

It already adds an error log message (which will be sent in notifications) if the post update hook returns something other than a 0.

**Comment by gaurangkudale** [comment]
Hi @piksel 
Thanks for the update
Can you please give me more context on this? or Do we need to add a testcase for this?

**Comment by simonaronsson** [comment]
As this has already been fixed, I'm closing this issue.
