### ISSUE TITLE
Extend "cleanup" functionality to leave N last versions of the container.

### ISSUE THREAD

**Issue by masteranza** [containrrr/watchtower#1291]
**Is your feature request related to a problem? Please describe.**
When a new image is pulled and new container created the logs from the previous container are gone forever.

**Describe the solution you'd like**
Add an option to keep a number of old containers (even though 1 would be enough, generalizing this to N would have benefits for some people)

**Describe alternatives you've considered**
Not cleaning up old containers at all, but this requires additional manual checks of available space on the device. 

**Additional context**

**Comment by piksel** [comment]
I think this could be doable by renaming the old container to `containername-old` (and of course removing any `containername-old` already present), as long as it's startup type is not `always` (which is guaranteed to interfere with the new container).

**Comment by masteranza** [comment]
@piksel  Yes, but could it be handled this way by watchtower? I'm not using startup type `always`, but btw. should I use startup time `on-failure` or does watchtower restart the containers on spontaneous failures automatically? I've noticed that it restarts them upon system restart, so I guess it does right?

**Comment by piksel** [comment]
Docker handles the restarts, not watchtower. The reason I mention it, is that if you were to create a new copy of a container, while having told the old one to stop, Docker would restart the container again and you would have two instances competing over the same resources. But only for `restart: always`.

**Comment by simonaronsson** [comment]
I do not think this is something that warrants any changes in Watchtower, as it's already completely possible to solve natively in Docker by [switching to the journald logging driver](https://docs.docker.com/config/containers/logging/journald/).

**Comment by piksel** [comment]
@simskij yeah, for the logging that is a much better option. keeping the previous container could still be useful, but someone still needs to write that code, and I don't see that happening anytime soon.
