### ISSUE TITLE
Use hostname of docker host instead of hostname of watchtower container in notifications

### ISSUE THREAD

**Issue by sgofferj** [containrrr/watchtower#1343]
At the moment, email notifications have a subject like `Watchtower updates on 22fc394ef353`. WT uses the hostname of its own container. If you have WT programmatically deployed on a larger number of hosts, e.g. through Portainer Edge Stacks, that is not overly helpful. It would IMHO be better if WT would use the hostname of the docker host its running on for this.

**Comment by piksel** [comment]
> It would IMHO be better if WT would use the hostname of the docker host its running on for this

There doesn't seem to be a way to query the hostname of the docker daemon in the API. But you can either use host networking for watchtower (which is what the `Watchtower updates on HOSTNAME` was designed for), set the hostname on the watchtower docker container, or specify `--notifications-hostname`/`WATCHTOWER_NOTIFICATIONS_HOSTNAME`.

**Comment by sgofferj** [comment]
Host networking it would have to be then. I looked into getting it done through environment variables in the Portainer Edge Stacks before opening the issue but Portainer doesn't seem to offer a way to find out the hostname of a host where it deploys an Edge Stack. Maybe I suggest it to them.

**Comment by sgofferj** [comment]
https://github.com/portainer/portainer/issues/7469

**Comment by sgofferj** [comment]
Using host networking works.
