### ISSUE TITLE
WATCHTOWER_NOTIFICATION_EMAIL_SERVER hard coded port

### ISSUE THREAD

**Issue by nightah** [containrrr/watchtower#135]
I've recently setup watchtower with email notifications and I've noticed a small issue which likely won't be affecting a lot of people. I can't receive emails on 25 as my ISP has it blocked so I have an alternative port opened for mail.

Having said that, in https://github.com/v2tec/watchtower/blob/master/notifications/email.go#L75 the port is hard coded to 25,

Can we possible get a feature that if a colon exists within the WATCHTOWER_NOTIFICATION_EMAIL_SERVER option ie:
WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.example.com:465 that it doesn't add the :25 suffix?

**Comment by stffabi** [comment]
Thanks for your report. The easiest would be to add another cli flag/environment variable which allows to set the port. The default for this would be 25, so we don't break anything.

**Comment by nightah** [comment]
Great, thanks for the prompt response.
Look forward to the new release, keep up the great work!

**Comment by Xaelias** [comment]
Ah was going to post the same :-)

**Comment by stffabi** [comment]
`v0.2.1` has just been released with the new config option.

**Comment by Xaelias** [comment]
Thanks!
