### ISSUE TITLE
[Question] Is there an option to monitoring only

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#138]
Hi,

Can I use watchtower only for notification when new image was pushed without updating the container?
I want get notification when new image was pushed but without pulling them or updating and restaring container. Notification via email, pushover or pushbullet will be good.

**Comment by kevincaradant** [comment]
Hi @Haxy89 , I'm agree with you and If I can add a support for notification => It's Discord. 
Today, a lot of people incuding me, use Discord, and the one of the last applications that I want use with Discord is WatchTower :)

**Comment by ghost** [comment]
@kevincaradant 
Sure Kevin, but I asked about monitoring mode only. Sending notification when new version without updating container.
@v2tec-admin  Is it supported in current version of watchtower?

**Comment by stffabi** [comment]
hi @Haxy89, unfortunately this is currently not possible, but should be pretty easy to enhance watchtower. Would you be interested adding this functionality?

**Comment by stffabi** [comment]
@kevincaradant I've added #143 to track adding discord as a notification service.

**Comment by ghost** [comment]
@stffabi Can you add pushbullet as a notification service too (api: https://docs.pushbullet.com/)? 
Its free in contrast to pushover :)
I will try to create pull request with notification mode only when I set up GO language develope env. ;)

**Comment by kevincaradant** [comment]
@stffabi, Thank you to take the initiative to create an issue for that ;)

@Haxy89, 
> Sure Kevin, but I asked about monitoring mode only

Yes as I said, I wish the same feature :)=> "Hi @Haxy89 , I'm agree with you" in my previous message



> I will try to create pull request with notification mode only

Thank you to take the time to do it ;)

**Comment by khandelwalpiyush** [comment]
Hope this is in development.. Would love this feature.. Just want to be notified prior to updating.. :)

**Comment by boexler** [comment]
I'm using a commercial docker container. The licence inside needs to be deactivated before updating the container. (Licence is bound to the container ID). 
So this feature would be awesome if I get an notification for a specific container that theres a new version available, without updating it by watchtower! 😃

**Comment by simonaronsson** [comment]
This has been implemented as a flag, `--monitor-only`, which will notify about new images, but not download and update containers.
