### ISSUE TITLE
Email notifications suppress on no update

### ISSUE THREAD

**Issue by nightah** [containrrr/watchtower#139]
If you have a shorter update interval set (even the default 5 minutes) and email notifications setup, it's likely you can be spammed with emails with an empty message body.

It appears that when an update is performed, after the docker pull is completed if no new images are found you will be sent an email irrespective (which has an empt message body).
Could it be possible to add another config variable to suppress notifications when no updates found/performed?

**Comment by stffabi** [comment]
Thanks for the report. Yes it shouldn't send any empty emails. Will be fixed with version `v0.2.1`

**Comment by Mazo** [comment]
+1. It's rather annoying getting a blank email every 15 minutes. Have to disable watchtower or email notifications until it's fixed.

**Comment by ransur0t** [comment]
+1 Thanks for addressing this issue. I did some testing at analysis and determined that I would need to set a larger internal or a cron schedule to avoid/mitigate this behavior. Looking forward to 0.2.1 update. 👍

**Comment by stffabi** [comment]
Thanks for your patience, `v0.2.1` has just been released with the fix.
