### ISSUE TITLE
Updates : Issue Templates 🛠

### ISSUE THREAD

**Issue by tamalCodes** [containrrr/watchtower#1402]
## What i am suggesting to update ? 

**I am suggesting to update the Issue templates , almost all of them were updated long ago. Currently we are using `.md` files instead of the brand new issue forms with `.yml` files which provides a much more premium experience.**

## Why to update it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to write a test or maybe fix something in the website
 - The issue template forms makes writing details more efficient
 - Here's a general idea : 
 
![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

![image](https://user-images.githubusercontent.com/72851613/193424759-6ff15f6b-c43a-4de2-bcab-931bc9e06ec3.png)

## Can i work on it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by piksel** [comment]
Yeah, since the current issue templates already have explicit "fields" to fill out, this would be a nice improvement! A PR would be welcomed!
