### ISSUE TITLE
Raspberry Pi 4 | ExitCode 255

### ISSUE THREAD

**Issue by tobschndr** [containrrr/watchtower#1428]
### Describe the bug

Everytime I start the container, it is stopped with ExitCode 255.

```
1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4
AppArmorProfile
Args [ --cleanup, --include-restarting, --rolling-restart, --include-stopped, --interval, 86400 ]
Config { AttachStderr: false, AttachStdin: false, AttachStdout: false, Cmd: --cleanup,--include-restarting,--rolling-restart,--include-stopped,--interval,86400, Domainname: , Entrypoint: /watchtower, Env: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, ExposedPorts: [object Object], Hostname: 1464ef6bc94f, Image: containrrr/watchtower, Labels: [object Object], OnBuild: null, OpenStdin: false, StdinOnce: false, Tty: false, User: , Volumes: null, WorkingDir: / }
Created 2022-10-15T12:21:10.727536481Z
Driver overlay2
ExecIDs
GraphDriver { Data: [object Object], Name: overlay2 }
HostConfig { AutoRemove: false, Binds: /var/run/docker.sock:/var/run/docker.sock, BlkioDeviceReadBps: null, BlkioDeviceReadIOps: null, BlkioDeviceWriteBps: null, BlkioDeviceWriteIOps: null, BlkioWeight: 0, BlkioWeightDevice: , CapAdd: null, CapDrop: null, Cgroup: , CgroupParent: , CgroupnsMode: private, ConsoleSize: 0,0, ContainerIDFile: , CpuCount: 0, CpuPercent: 0, CpuPeriod: 0, CpuQuota: 0, CpuRealtimePeriod: 0, CpuRealtimeRuntime: 0, CpuShares: 0, CpusetCpus: , CpusetMems: , DeviceCgroupRules: null, DeviceRequests: null, Devices: , Dns: , DnsOptions: , DnsSearch: , ExtraHosts: null, GroupAdd: null, IOMaximumBandwidth: 0, IOMaximumIOps: 0, IpcMode: private, Isolation: , KernelMemory: 0, KernelMemoryTCP: 0, Links: null, LogConfig: [object Object], MaskedPaths: null, Memory: 0, MemoryReservation: 0, MemorySwap: 0, MemorySwappiness: null, NanoCpus: 0, NetworkMode: default, OomKillDisable: null, OomScoreAdj: 0, PidMode: , PidsLimit: null, PortBindings: [object Object], Privileged: true, PublishAllPorts: false, ReadonlyPaths: null, ReadonlyRootfs: false, RestartPolicy: [object Object], Runtime: runc, SecurityOpt: label=disable, ShmSize: 67108864, UTSMode: , Ulimits: null, UsernsMode: , VolumeDriver: , VolumesFrom: null }
HostnamePath /var/lib/docker/containers/1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4/hostname
HostsPath /var/lib/docker/containers/1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4/hosts
Id 1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4
Image sha256:ac708a0cd96706c6ba4bc0bed52e9113b21dd789322ea69561c85e3d9838abc7
LogPath /var/lib/docker/containers/1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4/1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4-json.log
MountLabel
Mounts [ [object Object] ]
Name /watchtower
NetworkSettings { Bridge: , EndpointID: 4ad74798163a6292c025cb44c57553e23eeee125a60f412c36baa37f98ed3254, Gateway: 172.17.0.1, GlobalIPv6Address: , GlobalIPv6PrefixLen: 0, HairpinMode: false, IPAddress: 172.17.0.3, IPPrefixLen: 16, IPv6Gateway: , LinkLocalIPv6Address: , LinkLocalIPv6PrefixLen: 0, MacAddress: 02:42:ac:11:00:03, Networks: [object Object], Ports: [object Object], SandboxID: c9ccf4de874f8b1dc78f92d106ccc7f30144b6ee6665ebcc7b2e82866441a171, SandboxKey: /var/run/docker/netns/c9ccf4de874f, SecondaryIPAddresses: null, SecondaryIPv6Addresses: null }
Path /watchtower
Platform linux
ProcessLabel
ResolvConfPath /var/lib/docker/containers/1464ef6bc94fb25ae2067b5d3b47415ec257f263ce3db12e599b8c652df841b4/resolv.conf
RestartCount 0
State
Dead false
Error
ExitCode 255
FinishedAt 2022-10-15T14:38:00.796800866+02:00
OOMKilled false
Paused false
Pid 0
Restarting false
Running false
StartedAt 2022-10-15T12:21:11.720321411Z
Status exited
```

### Steps to reproduce

```
docker run --privileged -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup \
    --include-restarting \
    --rolling-restart \
    --include-stopped \
    --interval 86400
```

### Expected behavior

Container is running smooth with respect to the provided arguments.

### Environment

Raspberry Pi 4 Model B Rev 1.5
Docker version 20.10.5+dfsg1, build 55c4c88

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Your logs

```text
time="2022-10-15T12:21:13Z" level=info msg="Watchtower 1.4.0"
time="2022-10-15T12:21:13Z" level=info msg="Using no notifications"
time="2022-10-15T12:21:13Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2022-10-15T12:21:13Z" level=info msg="Scheduling first run: 2022-10-16 12:21:13 +0000 UTC"
time="2022-10-15T12:21:13Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
```

**Comment by piksel** [comment]
It says that it exited at `2022-10-15T14:38:00.796800866+02:00` which means it ran for 17 minutes before exiting. Are you saying that it always exits after 17 minutes?

**Comment by tobschndr** [comment]
@piksel : Thanks for your quick reply to my inquiry. Today, I started 20 min ago another try and it's still in status "running".
I think it's around two hours the container is running, or?

FinishedAt 2022-10-15T14:38:00.796800866+02:00
StartedAt 2022-10-15T12:21:11.720321411Z

**Comment by simonaronsson** [comment]
Rolling restarts, but also including stopped and restarting containers, would be something that I'd be interested in removing from the equation (although including restarting is the least likely one).

Same goes for cleanup. If you remove all of them and run it, does it work? If it does, would you mind adding them back one by one to see when it starts to fail?

```
docker run --privileged -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    # --cleanup \
    # --include-restarting \
    # --rolling-restart \
    # --include-stopped \
    --interval 86400
```

I'm also wondering, is there really no stack trace or **anything** additional in the logs when the container exits? Seems odd to me that it just exits silently.

**Comment by tobschndr** [comment]
Thanks for your inputs. The container (started yesterday evening) was still running. I stopped the container and restarted with your proposed start command:

docker run --privileged -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --interval 86400

I will monitor the container and will let you know if this might be the solution for my issue :)

Unfortunately I was looking for log files as well but there is kind of nothing documented. That was the reason why I reported the issue here.

**Comment by tobschndr** [comment]
Your recommendation seems to have solved the issue. The container is still running. Thanks for your help 😊

**Comment by simonaronsson** [comment]
> Your recommendation seems to have solved the issue. The container is still running. Thanks for your help

@Ashcora Well, I would still very much like to know where and how it breaks. Would you mind adding your flags back one by one and see when it breaks so we can raise a bug ticket about it? 😅

**Comment by tobschndr** [comment]
@simskij: For sure I can run the different setups to provide proper information when the container keeps exiting. Shall I run each config for e.g. 24 hours and provide feedback for each about the container status? Shall I try specific combinations in addition?

**Comment by simonaronsson** [comment]
> @simskij: For sure I can run the different setups to provide proper information when the container keeps exiting. Shall I run each config for e.g. 24 hours and provide feedback for each about the container status? Shall I try specific combinations in addition?

Sounds good. Thanks! Just add them one by one until you're back to where you were at when it was broken. 👍🏼

**Comment by tobschndr** [comment]
I have now tested each Docker run with respect to the different setups.

docker run --privileged -d \
    --name watchtower_no_cleanup \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    # --cleanup \
    --include-restarting \
    --rolling-restart \
    --include-stopped \
    --interval 86400

**Result: Working without exit.**


docker run --privileged -d \
    --name watchtower_no_include-restarting \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup \
    # --include-restarting \
    --rolling-restart \
    --include-stopped \
    --interval 86400

**Result: Working without exit.**


docker run --privileged -d \
    --name watchtower_no_rolling-restart \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup \
    --include-restarting \
    # --rolling-restart \
    --include-stopped \
    --interval 86400

**Result: Working without exit.**


docker run --privileged -d \
    --name watchtower_no_include-stopped \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup \
    --include-restarting \
    --rolling-restart \
    # --include-stopped \
    --interval 86400

**Result: Working without exit.**


_To summarize: it seems to be a combination that triggers the bug._


Fun fact:
To reestablish the working run before the trying out section with the following command

docker run --privileged -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --interval 86400

the following error was thrown this morning:
<html>
<body>


Status | Stopped for 4 hours with exit code 255
-- | --
Created | 2022-10-19 23:04:20
Finished | 2022-10-20 10:19:52


</body>
</html>

It is maybe also interesting that if the container exits with code 255, that all other container are also affected around the same time but these containers have the auto restart enabled.

01e6b1bdd53b | containrrr/watchtower |   "/watchtower --inter…" |  4 hours ago  |  Up 4 hours*
763008e70081 |  openhab/openhab:latest |  "/entrypoint gosu op…" |  22 hours ago |  Up 7 hours (healthy)
5cfb92e18b46 |  portainer/portainer-ce |  "/portainer"      |       2 weeks ago  |  Up 6 hours

(* restarted/started manually)
