### ISSUE TITLE
Env variable to define hostname

### ISSUE THREAD

**Issue by Skaronator** [containrrr/watchtower#145]
Would be cool if its possible to define a environment variable to set the hostname used in the email header.

https://github.com/v2tec/watchtower/blob/4c63746feb688fb963e3c3d4b9acfe41e1fc3c67/notifications/email.go#L44-L46

Currently it is **70114e0b01fd** on my machine.

**Comment by stffabi** [comment]
Thanks for your report and using watchtower.

Have you tried setting your custom hostname by adding the `-h` flag to the docker run command, like [mentioned here](https://serverfault.com/a/640466)? This should also change the hostname used in the subject.
I haven't tried it, but I think it should work 😄.

**Comment by Skaronator** [comment]
Yup this works!

Is there any way to set the timezone? I've some containers that use the TZ env variable to set the timezone inside the container.

https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

I tried to mount "/etc/timezone:/etc/timezone:ro" and "/etc/localtime:/etc/localtime:ro" but that didn't worked.

**Comment by stffabi** [comment]
Glad that worked.

What was your exact run command? I think setting `TZ` and mounting `/etc/timezone` should be enough.

**Comment by stffabi** [comment]
If that doesn't work could you please try setting TZ and mounting  `/usr/share/zoneinfo`?

**Comment by Skaronator** [comment]
TZ and mounting `/usr/share/zoneinfo` worked! Thanks again.

**Comment by stffabi** [comment]
You're welcome.
