### ISSUE TITLE
Problem with "glide install" when setting up development enviroment

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#147]
When I run `glide install` from my root workspace I get:

![image](https://user-images.githubusercontent.com/32634129/34499597-0f0b190a-f007-11e7-8464-55d041dfb428.png)

Can't build the project. I have the newest glide.exe and I put it in root workspace.

**Comment by stffabi** [comment]
There were some glide versions that had this problem. Which version of glide did you install?

On the build container currently glide 0.12.3 is used. At least that version should work. For the future I would like to switch over to [deb](https://github.com/golang/dep), which is most like going to be the official golang tool for vendoring dependencies.

**Comment by stffabi** [comment]
This is a glide issue and should be fixed on the glide side. Feel free to reopen the issue if you have any further questions.
