### ISSUE TITLE
Watchtower not taking all arguments

### ISSUE THREAD

**Issue by tobschndr** [containrrr/watchtower#1479]
### Describe the bug

When using Docker run to start Watchtower, not all arguments are taken over. The log files do not show any indication.

### Steps to reproduce

docker run --privileged -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /etc/localtime:/etc/localtime:ro \
    containrrr/watchtower \
    --schedule "0 0 23 * * *" \
    --include-restarting

### Expected behavior

After restarting of the system, the container of Watchtower should be started as well. The policy in e.g. Portainer shows a different as set with the docker run command: "none" instead of "restart" (see checkmark and the blue marked what should have been set)

### Screenshots

![Screenshot_Watchtower_in_Portainer](https://user-images.githubusercontent.com/58374721/202820732-620455fc-230d-4745-9394-e7f9a16a3b2d.png)

### Environment

Raspberry Pi 4 Model B Rev 1.5
Docker version 20.10.5+dfsg1, build 55c4c88

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Your logs

```text
time="2022-11-19T00:39:39+01:00" level=info msg="Watchtower 1.5.1"
time="2022-11-19T00:39:39+01:00" level=info msg="Using no notifications"
time="2022-11-19T00:39:39+01:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2022-11-19T00:39:39+01:00" level=info msg="Scheduling first run: 2022-11-19 23:00:00 +0100 CET"
time="2022-11-19T00:39:39+01:00" level=info msg="Note that the first check will be performed in 22 hours, 20 minutes, 20 seconds"
```

**Comment by piksel** [comment]
Sorry, I don't understand what the issue is. You don't have a `--restart` argument in your command. If you are referring to `--include-restarting` it has a very different function.

**Comment by tobschndr** [comment]
...sometimes you can't see the forest for the trees - or the argument function for the arguments.
Thank you for your good eye.

I tried with the additional line
`--restart=always`

...and the issue is not really an issue anymore.
