### ISSUE TITLE
Failed to send notification email

### ISSUE THREAD

**Issue by nightah** [containrrr/watchtower#148]
As per the subject I'm now getting the following error:

`Failed to send notification email:  535 5.7.8 Error: authentication failed:`

This appears to have randomly started occurring, I can see it making a connection with the mail server however it doesn't get past the initial negotiation. This same container with the same account details has managed to connect and send mail previously.

I've tried turning on --debug, though it appears there isn't more verbose logging.

**Comment by stffabi** [comment]
Hmm, if this occurs only randomly I would suspect there's some temporary problem with the mail server. 

Are you still seeing this issue?

**Comment by nightah** [comment]
Sorry when I said randomly, I didn't mean it's intermittent, it's occurring every single time.
The random nature of it I guess is associated with the fact that it worked at some point, but no longer does now.

To answer your question yes this issue is still occurring, with the same error, the mailserver hasn't had any changes since and is accepting/sending mail from other sources and destinations without any problems.

**Comment by nightah** [comment]
Looks like the problem was related to the password, specifically if it includes a '$'.
When creating the container via docker run or docker create with the appropriate escaping this worked.
When creating the container via a docker-compose you need to escape the $ with another $,while everything appeared to be passing through appropriately and looking at the password in the docker inspect was correct, it continued to fail SASL authentication on the mail server.

Not sure if it's worth debugging, but if you want specifics I can post some up here.

**Comment by stffabi** [comment]
Thanks for providing your information. I'll close the issue for now as it seems to be a docker-compose escaping problem.
