### ISSUE TITLE
Feature request: support multiple notification urls

### ISSUE THREAD

**Issue by ksurl** [containrrr/watchtower#1482]
### Is your feature request related to a problem? Please describe.

can't specify more than one notification type (gotify, webhook, discord, pushover, email etc) for shoutrrr.

### Describe the solution you'd like

support sending to more than url if specified

### Describe alternatives you've considered

run 2 copies of watchtower with scoped labels but then you won't get notified on the same containers on both channels

### Additional context

useful for backup notifications if one service is down

**Comment by piksel** [comment]
It's not stated in the docs, but you can supply `--notification-url` multiple times to add multiple notification targets.
If you are using environment variables, just separate them with spaces, like this:
```
$ docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  --env WATCHTOWER_NOTIFICATION_URL="logger: logger:" \
  containrrr/watchtower --notification-log-stdout --run-once
INFO[0001] Watchtower 1.5.1
INFO[0001] Using notifications: logger, logger
INFO[0001] Checking all containers (except explicitly disabled with label)
INFO[0001] Running a one time update.
Watchtower 1.5.1
Using notifications: logger, logger
Checking all containers (except explicitly disabled with label)
Running a one time update.
Watchtower 1.5.1
Using notifications: logger, logger
Checking all containers (except explicitly disabled with label)
Running a one time update.
```
Using the `logger:` notification service here as an example to show that it outputs every message twice (once per specified `logger:` URL).

**Comment by ksurl** [comment]
thanks.
