### ISSUE TITLE
ntfy integration

### ISSUE THREAD

**Issue by rubenixnagios** [containrrr/watchtower#1487]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

would be nice to integrate https://ntfy.sh/ notifications to this project

### Describe alternatives you've considered

slack works fine, but find ntfy more secure and also selfhosted, any chance?

**Comment by piksel** [comment]
Duplicate/tracked in https://github.com/containrrr/shoutrrr/issues/261
