### ISSUE TITLE
possible issue with metrics endpoint

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#1488]
### Describe the bug

I'm trying to access the metrics from the ghcr.io/benphelps/homepage container which recently added support for watchtower metrics.

I guess my question is, what output should I expect from /v1/metrics, is it JSON? Homepage certainly seems to expect JSON but my output is more of a plain-text output with shell-style comments. It starts like this:

```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 8.559e-05
go_gc_duration_seconds{quantile="0.25"} 0.000152664
go_gc_duration_seconds{quantile="0.5"} 0.000157905
go_gc_duration_seconds{quantile="0.75"} 0.00016346
go_gc_duration_seconds{quantile="1"} 0.000571509
go_gc_duration_seconds_sum 0.041510663
go_gc_duration_seconds_count 257
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 14
```

The end of that output does contain values that relate to watchtower:

```
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP watchtower_containers_failed Number of containers where update failed during the last scan
# TYPE watchtower_containers_failed gauge
watchtower_containers_failed 0
# HELP watchtower_containers_scanned Number of containers scanned for changes by watchtower during the last scan
# TYPE watchtower_containers_scanned gauge
watchtower_containers_scanned 0
# HELP watchtower_containers_updated Number of containers updated by watchtower during the last scan
# TYPE watchtower_containers_updated gauge
watchtower_containers_updated 0
# HELP watchtower_scans_skipped Number of skipped scans since watchtower started
# TYPE watchtower_scans_skipped counter
watchtower_scans_skipped 0
# HELP watchtower_scans_total Number of scans since the watchtower started
# TYPE watchtower_scans_total counter
watchtower_scans_total 0
```

This output was fetched via curl: `curl -H "Authorization: Bearer MYTOKEN" http://containerhost:8080/v1/metrics > watchtower_metrics.txt`

This might very well be an issue inside the homepage docker image, since their support for watchtower metrics is days old

### Steps to reproduce

1. set up watchtower with API metrics enabled
2. set up homepage docker container and configure watchtower widget
3. I have configured the watchtower widget as follows:
```
    - testwatchtower:
        name: test tower
        description: api tests
        container: watchtower
        widget:
          type: watchtower
          url: WATCHTOWER_IP:8080
          key: MYTOKEN

```

### Expected behavior

metrics are shown as intended

### Screenshots

![grafik](https://user-images.githubusercontent.com/7829392/205319683-b4190b56-6d19-42f5-ad67-01dc73cdfc0a.png)

### Environment

- ARM64, Debian 11
- Architecture
- Docker Version 20.10.21

### Your logs

```text
-
```

**Comment by piksel** [comment]
> Homepage certainly seems to expect JSON

That is odd. This has never been JSON, it's in Prometheus' [text exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/).

It looks like their proxy acts as a paser/converter to JSON:
https://github.com/benphelps/homepage/blob/826fe15e15179cb8c4aa0e3f910ca0c84ba26270/src/widgets/watchtower/proxy.js#L39-L45

**Comment by ghost** [comment]
Right, so it looks like my metrics output is formatted the way it should be. I'll take this to the homepage developers to see what's up on their end. Thanks!
