### ISSUE TITLE
Certificate problem sending email notifications

### ISSUE THREAD

**Issue by mabanos** [containrrr/watchtower#149]
Since last pushed image, console shows the following error:

`Failed to send notification email:  x509: certificate signed by unknown authority`

The same error is present in Windows 10 and Ubuntu, and using 2 different smtp servers.

It's something related to the certificates used to send emails by Watchtower?

Thanks in advance
 
**EDIT: Seems to be a local problem with my Docker version. I close this issue.**

**Comment by davidsarkany** [comment]
I have the same problem.
How did you solve it?

**Comment by stffabi** [comment]
You can now use the `--notification-email-server-tls-skip-verify` flag to disable tls checking. Please be aware about the consequences.
