### ISSUE TITLE
Can't send notifications through default port

### ISSUE THREAD

**Issue by mabanos** [containrrr/watchtower#150]
I'm working in a host that only has ports 22, 80, 443 opened. This could be the problem behind this log message:

`Failed to send notification email:  dial tcp 74.125.206.109:25: getsockopt: connection timed out`

Do i need to open port 25 to send notifications with Watchtower?

Thanks in advance

**Comment by stffabi** [comment]
Hi thanks for using watchtower. The message means that watchtower was unable to connect to the mail server on port 25.

> I'm working in a host that only has ports 22, 80, 443 opened.

Do you mean that only these ports are opened for outbound connections? If this is the case you would need to open the firewall that your host is allowed to connect to other machines to the port 25.

**Comment by mabanos** [comment]
> Do you mean that only these ports are opened for outbound connections?

Yes. Port connections (in/out) are restricted actually to ports 22, 80, 443. So, I was thinking the problem was that, but I wanted to be sure.

I will ask to open port 25, because email notifications works perfectly fine in any other hosts (without this limitation) I tried.

Thanks you for your attention,
You are doing a great job with Watchtower!

**Comment by stffabi** [comment]
Glad I could help you with the information.

I'll close the issue, feel free to open a new one if you have any other questions.
