### ISSUE TITLE
How can I watch image update without run this image?

### ISSUE THREAD

**Issue by qwIvan** [containrrr/watchtower#151]
I want to watch a image update in docker hub, then pull it automatically.
But I don't need to run this image for a long time, I just run it when i need.

**Comment by ghost** [comment]
Hi, this is why I create this pull request https://github.com/v2tec/watchtower/pull/144
but still no merged :(

**Comment by simonaronsson** [comment]
You can run it with the flag `--run-once`, which will be made available in v0.4.0. Until then you can build watchtower from source, beware though that your mileage may vary as we're still in the middle of development here. 🙏
