### ISSUE TITLE
Cannot do a head request for private registry

### ISSUE THREAD

**Issue by Pwuts** [containrrr/watchtower#1525]
### Describe the bug

I am having the exact same issue as described and discussed in https://github.com/containrrr/watchtower/issues/715, with the latest version of the image and the latest `registry:2` image.

My registry is located at `docker-registry.sub.domain.nl`, image names are single part, so `docker-registry.sub.domain.nl/imagename:latest`.

Watchtower tries `HEAD /v2/library/imagename/manifests/latest`. This fails, after which it "falls back to regular pull" and requests `HEAD /v2/imagename/manifests/latest`, which succeeds.

### Steps to reproduce

Have watchtower try to pull an image from a private registry.

### Expected behavior

`HEAD /v2/imagename/manifests/latest` -> no unnecessary pulls

### Environment

* Docker 20.10.11
* `containrrr/watchtower:latest` (latest version)
* `registry:2` (latest version)

### Your logs

```text
msg="Trying to load authentication credentials." container=/container image="docker-registry.sub.domain.nl/imagename:latest"
msg="Loaded auth credentials for user deploy, on registry docker-registry.sub.domain.nl/imagename:latest, from file /config.json"
msg="Got image name: docker-registry.sub.domain.nl/imagename:latest"
msg="Credentials loaded"
msg="Checking if pull is needed" container=/container image="docker-registry.sub.domain.nl/imagename:latest"
msg="Building challenge URL" URL="https://docker-registry.sub.domain.nl/v2/"
msg="Got response to challenge request" header="Basic realm=\"Registry Realm\"" status="401 Unauthorized"
msg="Parsing image ref" host=docker-registry.sub.domain.nl image=imagename normalized="docker-registry.sub.domain.nl/imagename:latest" tag=latest
msg="Doing a HEAD request to fetch a digest" url="https://docker-registry.sub.domain.nl/v2/library/login/manifests/latest"
msg="Could not do a head request for \"docker-registry.sub.domain.nl/imagename:latest\", falling back to regular pull." container=/container image="docker-registry.sub.domain.nl/imagename:latest"
msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/container image="docker-registry.sub.domain.nl/imagename:latest"
msg="Pulling image" container=/container image="docker-registry.sub.domain.nl/imagename:latest"
msg="No new images found for /container"
```

**Comment by Pwuts** [comment]
As far as I can tell, the problem is that watchtower currently does not exactly follow the reference implementation of the docker registry, causing issues where they deviate.

I have started an attempt at fixing here: https://github.com/Pwuts/watchtower/tree/fix%2Fref-processing

Disclaimer: this is my first time touching Golang, so please bear with me.

**Comment by piksel** [comment]
There is code to prevent the `library/` prefix to be added when not using docker hub, but perhaps there is something that still adds it to the HEAD request URL for some reason?

**Comment by Pwuts** [comment]
This piece of code will add `library/` to any image name with a single-part path: https://github.com/containrrr/watchtower/blob/main/pkg/registry/manifest/manifest.go#L37

Digging further, I discovered more deviations from the (reference) implementation that docker itself uses, partly because Watchtower has its own implementations to manipulate image refs instead of using those available in the `docker/distribution/reference` package. I'm preparing a PR to (hopefully) fix all of this and will elaborate when I'm ready. :)

**Comment by Pwuts** [comment]
While I'm working on this, I wonder whether Watchtower tries to accommodate situations that should never occur. For example, `pkg/registry/auth_test.go` contains the following tests:
```Go
It("should not add \"library/\" for one segment image names if they're not on dockerhub", func() {
	Expect(auth.GetScopeFromImageName("ghcr.io/watchtower", "ghcr.io")).To(Equal("watchtower"))
	Expect(auth.GetScopeFromImageName("watchtower", "ghcr.io")).To(Equal("watchtower"))
})
```
The latter requires that `GetScopeFromImageName` can handle image names without a domain, but as I understand it the `Image` field in [`ContainerJSON`](https://pkg.go.dev/github.com/docker/docker@v20.10.22+incompatible/api/types#ContainerJSON) *always* contains the registry domain in case it is anything other than `docker.io`.

If that is the case, that specific test can be removed and the code of `GetScopeFromImageName` greatly simplified.

**Comment by piksel** [comment]
While aligning with the docker behaviour is a good goal, it seems like this could grow a lot and be hard to CR.  
Just fixing `BuildManifestURL` should be the quickest way to fix the original issue.  

I do appreciate the work though, it's just a bit of a caution.

**Comment by Pwuts** [comment]
I understand, thanks for the heads up! I'd like to give it a try though, as I think fixing this properly now can benefit future maintenance as well.

Right now, my changes are limited to 4 files (+ small changes to the 4 corresponding test files and to 2 documentation files).
