### ISSUE TITLE
Unable to send email using "docker.for.mac.localhost" - x509 cert error

### ISSUE THREAD

**Issue by jamieshaw** [containrrr/watchtower#153]
I'm running a mail server on the same machine as my docker instance; in most scenarios I can connect to this using the "docker.for.mac.localhost" hostname but this is failing using watchtower. The domain name is not matching that of the letsencrypt cert that I'm using.

Is there any way to disable SSL for SMTP messaging? As it's localhost, it's not really required here.

**Comment by stffabi** [comment]
Thanks for your report. It would be possible to add another flag to skip the TLS verify. Unfortunately currently this is not possible.

**Comment by stffabi** [comment]
You can now use the flag `--notification-email-server-tls-skip-verify` introduced with `v0.2.2`

**Comment by jamieshaw** [comment]
Still having issues using 'docker.for.mac.localhost'.  Logs are now showing the following error:
`Helo command rejected: need fully-qualified hostname`.

Any ideas?

**Comment by stffabi** [comment]
That's a message from your mail server, you need to disable that check on your mail server or change the mail server address used by watchtower to something that your mail sever accepts.

**Comment by jamieshaw** [comment]
Fair enough. Thanks for the help.
I'll dig around through the Postfix stuff, see if I can find an option somewhere.
