### ISSUE TITLE
Allow Ignore of Specific Scope(s)

### ISSUE THREAD

**Issue by owine** [containrrr/watchtower#1541]
### Is your feature request related to a problem? Please describe.

When running multiple instances, it would be nice to tell an instance to ignore specific scopes to allow it to coexist with other instances monitoring those scopes.

Example:
Global instance monitoring all containers except the "critical" scope
Critical instance monitoring just "critical" scoped containers

Currently, the global instance must be carefully managed to avoid conflicts.

### Describe the solution you'd like

Allow defining an ignored scope in order to use scopes for exclusions rather than inclusions.

### Describe alternatives you've considered

Manually building a scope for the instance intended to monitor "everything except critical"

**Comment by piksel** [comment]
Yes, the "default" scope should be treated as it's own scope and not apply to other scoped containers. This has been suggested before, but no one has implemented yet.
