### ISSUE TITLE
SMTP Notifications rejected

### ISSUE THREAD

**Issue by TheQue42** [containrrr/watchtower#1545]
### Describe the bug

The latest release, and the updates to shoutrr, seems to have changed to smtp notification logic.

The SMTP client will now try to send mail with an SMTP HELO/EHLO containing just a ".", instead of the nodes name.

This is rejected by my mailserver (postfix), so all notifications from watchtower fail.

"501 Syntax: EHLO hostname." or "501 Syntax: HELO hostname."

### Steps to reproduce

Just start the container with something like:

'--run-once' '--log-level' 'debug' '--cleanup' '--notifications' 'email' '--notifications-level' 'info' '--notification-email-server' 'IP' '--notification-email-to' '<mailaddress>' '--notification-email-from' '<mailaddress>' '--notification-email-server-tls-skip-verify'

### Expected behavior

A valid SMTP negotiation, with a successful email sent.

### Environment

 Operating System: Raspbian GNU/Linux 10 (buster)
 Architecture: aarch64
 Server Version: 20.10.23

### Your logs

```text
time="2023-01-29T20:09:44Z" level=error msg="Failed to send shoutrrr notification" error="server did not accept the handshake: 501 Syntax: HELO hostname" index=0 notify=no service=smtp
```

**Comment by TheQue42** [comment]
Also tried recreating the container (in portainer) with a "better" fqdn, but it seems to be ignored by shoutrr

**Comment by vipergts450** [comment]
Just noticed the same issue upon upgrading to 1.5.2 this morning. All SMTP notifications are rejected by the sever. Interestingly, my logs catch a different response which could be related to my Postfix install, but 1.5.1 was working great.

`time="2023-01-29T15:19:06-05:00" level=error msg="Failed to send shoutrrr notification" error="server did not accept the handshake: 501 5.5.4 Invalid argument" index=0 notify=no service=smtp`

**Comment by piksel** [comment]
It should default to using "localhost", but you can set `clienHost` to `auto` to set it to the container hostname. See https://containrrr.dev/shoutrrr/v0.7/services/email/

You cannot do that through the legacy notification options though, you would need to convert your options to a shoutrrr URL. You can start watchtower with --trace to see what Shoutrrr URL is currently being generated from your options.

**Comment by vipergts450** [comment]
The watchtower trace logs do not seem to give me any more detail about which argument the mail server thought was invalid and caused shoutrrr to fail, unfortunately.

**Comment by Shirkan79** [comment]
Same issue here, with 1.5.1 notifications are working fine, with 1.5.2 error:
`time="2023-01-29T21:14:24Z" level=error msg="Failed to send shoutrrr notification" error="server did not accept the handshake: 501 Syntax: HELO hostname" index=0 notify=no service=smtp`

**Comment by piksel** [comment]
I pushed a hotfix that should fix this.

**Comment by vipergts450** [comment]
1.5.3 working fine!

**Comment by Surgical71** [comment]
Can Also confirm that it is working again.

Added question (Then I don't need to create my own issue):
How do I set watch tower to only send the result information in the log via email?

Results I want to send via email:
level=info msg="Session done" Failed=0 Scanned=34 Updated=6 notify=no

Thanx

**Comment by piksel** [comment]
@Surgical71 please ask questions in discussions instead. You probably want to use `--notification-report`
