### ISSUE TITLE
last update breaks my telegram notifications

### ISSUE THREAD

**Issue by sochartgit** [containrrr/watchtower#1559]
### Describe the bug

This error is log
time="2023-02-13T10:26:43-05:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"telegram://XXXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYY/?chats=ZZZZZZZZZZZ\": invalid port \":YYYYYYYYYYYYYYYYYYYY\" after host\n"

### Expected behavior

Send a telegram notification without this error

### Environment

- Platform:  photonOS 4
- Architecture  x64
- Docker Version   latest

### Your logs

```text
copied in the desc.
```

**Comment by piksel** [comment]
Not sure why it would've worked before, but you need to have a server name in the URL. Use `telegram` for the default telegram server:
```
telegram://XXXXXXXXXXX:YYYYYYYYYYYYYYYYYYYYYYYYY@telegram/?chats=ZZZZZZZZZZZ
```

**Comment by sochartgit** [comment]
Thanks, works like a charm.

De : nils måsén ***@***.***>
Envoyé : 14 février 2023 02:27
À : containrrr/watchtower ***@***.***>
Cc : sochartgit ***@***.***>; Author ***@***.***>
Objet : Re: [containrrr/watchtower] last update breaks my telegram notifications (Issue #1559)


Not sure why it would've worked before, but you need to have a server name in the URL. Use telegram for the default telegram server:

***@***.***/?chats=ZZZZZZZZZZZ
