### ISSUE TITLE
--label-enable not working

### ISSUE THREAD

**Issue by NathanTheGr8** [containrrr/watchtower#157]
Watchtower is not auto updating my containers when I specify the --label-enable flag. I believe I am specifying the label on my other containers correctly, but they are not updating when new containers are release. I included command I use to run [glances ](https://hub.docker.com/r/nicolargo/glances/tags/) below.

Running watch tower 0.2.2
```
docker run -d \
  --name watchtower \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower --cleanup --tlsverify --label-enable
```

Glances container 
```
docker run -d --restart="always" --name="glances" --label=com.centurylinklabs.watchtower.enable=true -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances
```

**Comment by stffabi** [comment]
Thanks for your report. The labeling looks fine on your run command. Could you please provide us the watchtower log? You might also want to run watchtower with the `--debug` flag to see if the container gets selected and investigated for an update. That output should also help us to track down your problem.

**Comment by NathanTheGr8** [comment]
Thank you for your quick reply! I had relaunched my watchtower with the debug command and started looking at the age of my containers and it seems the ones that were out of date have relaunched. I am not sure what I changed or had goofed up, but it is working as expected now. Sorry for the trouble.

**Comment by stffabi** [comment]
Glad to hear that it's working for you now. Feel free to open another issue if you have any problems.
