### ISSUE TITLE
cant get env WATCHTOWER_SCHEDULE to work like I expect it to

### ISSUE THREAD

**Issue by jetski28** [containrrr/watchtower#1573]
### Describe the bug

Unable to configure a cron schedule for every 4th Saturday of the month.

### Steps to reproduce

1. Configure an environment variable for WATCHTOWER_SCHEDULE with 0 0 22-28 * SAT or 0 0 ? * SAT#4
2. Run the watchtower docker container
3. View the console logs
4. Either get error "End of range (28) above maximum (23): 22-28" or "Failed to parse int from SAT#4: strconv.Atoi: parsing \"SAT#4\": invalid syntax" depending on which cron syntax I use.

### Expected behavior

Since the Cron Syntax is valid (checked with various Cron Generators) I would expect it to load without error.

### Environment

- Debian Linux
- x64
- Docker 20.10.5+dfsg1 (API: 1.41)

### Your logs

```text
Cron Syntax 1: 0 0 22-28 * SAT
End of range (28) above maximum (23): 22-28

Cron Syntax 2: 0 0 ? * SAT#4
Failed to parse int from SAT#4: strconv.Atoi: parsing \"SAT#4\": invalid syntax
```

### Additional context

Any ideas? or is this a limitation with using robfig/cron

**Comment by piksel** [comment]
The [schedule argument](https://containrrr.dev/watchtower/arguments/#scheduling) uses a different syntax than posix cron. Unfortunate, but changing it is a breaking change which we don't want to do.
