### ISSUE TITLE
New version release date?

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#158]
@v2tec-admin 
There are minor pull requests in queue.
Do you consider release new version soon?

**Comment by stffabi** [comment]
Unfortunately I'm currently very busy and have limited spare time. I'm aware of the pull requests and try to do my best to review them soon. 

Thanks for your understanding.

**Comment by Nightbr** [comment]
Hey, any ETA on future release 0.3.0 for example? 
Do you need any help to review some PR, we really need slack notifications to notify when containers are updated.

Thanks in advance.

**Comment by stffabi** [comment]
New versions will be released during the next week. First some patch releases and then the new minor `0.3.0`.

**Comment by stffabi** [comment]
@Nightbr, `v0.3.0` with slack notifications has been released.

Other PR's all still open with some requested changes, new versions will be released accordingly.
