### ISSUE TITLE
Random update off-schedule, no logs

### ISSUE THREAD

**Issue by HerbCSO** [containrrr/watchtower#1589]
### Describe the bug

I have watchtower set up to send notifications to me via Telegram when an update occurs. I got a notification at 14:07 UTC today that one of my containers was updated to the latest tag (rustdesk/rustdesk-server:latest image (24f56bdbd4e2) - which is correct, that is the latest image at this point).

What makes me suspicious about this is that a) my schedule for updates is set to ` "0 0 8/12 * * *"` and I do NOT have the HTTP API enabled (only `--http-api-metrics` with a `WATCHTOWER_HTTP_API_TOKEN` set to a 29 character string, since updated to a new 64-byte value) and b) there was nothing showing up in `docker logs` about this update happening.

Last reboot of this server was 16 days ago and the watchtower docker image had been running for 14 days at this point.

I've since realized that I had the metrics API exposed externally, I've now changed the port to be exposed only on 127.0.0.1.

### Steps to reproduce

No idea?

### Expected behavior

Updates should have happened only at 8am/pm UTC per my schedule setup, or there should at least be an entry in the log if the update was triggered by something else.

### Environment

- Platform: Debian GNU/Linux 11 (bullseye)
- Architecture: x86_64
- Docker Version: 23.0.1

### Your logs

```text
N/A - one-time occurrence and I didn't have `--debug` enabled at the time.
```

### Additional context

I'm concerned that this might have been somebody accessing my server, but I cannot find any evidence of logins or fail2ban entries that might be relevant (not to say there aren't any, I'm not a security expert, but I did look).

**Comment by piksel** [comment]
You can add the logs without debug as well. They should both show how the schedule was interpreted and why the session was started (schedule or http-api call).

If there were nothing in the logs between 08:00 and 20:00, it probably didn't come from that watchtower instance. There is no way for it to run a session without logging anything. Perhaps it's from a different server? Have you checked when the container you think was updated was started?

**Comment by HerbCSO** [comment]
Well, that's just the thing - there really was no log, which is what prompted this issue. And it definitely came from this instance - the hostname is in the message and I specifically set it to be able to easily distinguish it from other watchtower instances. I'm also not running the docker images that got updated anywhere else.

I did check the container start time, and it was restarted at that time.

It's all very odd. But if there is nothing else I can check on at this time, we can close this as a weird one-off.

**Comment by HerbCSO** [comment]
FWIW my docker logs show this at startup:

```
$ docker logs watchtower-watchtower-1                                                                                                                                                                                              time="2023-03-12T15:14:32Z" level=info msg="Watchtower 1.5.3"
time="2023-03-12T15:14:32Z" level=info msg="Using notifications: telegram"
time="2023-03-12T15:14:32Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2023-03-12T15:14:32Z" level=info msg="Scheduling first run: 2023-03-12 20:00:00 +0000 UTC"
time="2023-03-12T15:14:32Z" level=info msg="Note that the first check will be performed in 4 hours, 45 minutes, 27 seconds"
time="2023-03-12T20:00:00Z" level=info msg="Session done" Failed=0 Scanned=5 Updated=0 notify=no
time="2023-03-13T08:00:01Z" level=info msg="Session done" Failed=0 Scanned=5 Updated=0 notify=no
```

**Comment by HerbCSO** [comment]
I'm going to close this as I don't see how to get more information about what happened at this time.
