### ISSUE TITLE
Restarting acme-companion failed

### ISSUE THREAD

**Issue by RefurioAnachro** [containrrr/watchtower#1591]
### Describe the bug

Updating acme-companion https://github.com/nginx-proxy/acme-companion caused it to fail with broken mounts. See "additional context" for its error message. Maybe watchthrower cannot handle --volumes-from properly?

### Steps to reproduce

use watchtower on nginx-proxy and acme-companion.

### Expected behavior

acme-companion comes up again.

### Environment

- Debian Bullseye
- x86_64
- Docker version 20.10.22, build 3a2c30b

### Your logs

```text
time="2023-03-13T03:31:05Z" level=info msg="Found new nginxproxy/nginx-proxy:alpine image (ed19382349ac)"
time="2023-03-13T03:31:08Z" level=info msg="Found new nginxproxy/acme-companion:latest image (50906ba2df2b)"
time="2023-03-13T03:31:13Z" level=info msg="Stopping /acme-companion (10f6c5a3b871) with SIGTERM"
time="2023-03-13T03:31:14Z" level=info msg="Creating /acme-companion"
time="2023-03-13T03:31:14Z" level=info msg="Stopping /nginx-proxy (28616462d3ad) with SIGTERM"
time="2023-03-13T03:31:15Z" level=info msg="Creating /nginx-proxy"
```

### Additional context

Info: running acme-companion version v2.2.6
2023/03/13 22:54:12, Error: can't get my container ID !
Error: can't get nginx-proxy container ID !
Check that you are doing one of the following :
        - Use the --volumes-from option to mount volumes from the nginx-proxy container.
        - Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
        - Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.

**Comment by piksel** [comment]
I think you need to add a `com.centurylinklabs.watchtower.depends-on=/nginx-proxy` label to get the containers to be started in the correct order.

**Comment by RefurioAnachro** [comment]
Good idea!, I could have tried that earlier. Thanks!

**Comment by RefurioAnachro** [comment]
After watching things for some time I can say that this seems to work. Using dependendcies like this is incompatible with --rolling-restart which helped to make gotify notifications happen in some cases. Thanks again, I'll close the issue.
