### ISSUE TITLE
Plan for dockerhub's new policy?

### ISSUE THREAD

**Issue by hydrargyrum** [containrrr/watchtower#1594]
### Describe the bug

Watchtower's docker image is currently hosted on dockerhub, which has released a [new policy](https://blog.alexellis.io/docker-is-deleting-open-source-images/) that might endanger your hosting there. Do you have any plans for migrating hosting elsewhere?

### Steps to reproduce

1. Host opensource image on dockerhub
2. Wait
3. Dockerhub will delete your image

### Expected behavior

Image is still hosted somewhere.

### Environment

Irrelevant

### Your logs

```text
Irrelevant
```

**Comment by simonaronsson** [comment]
Hi there! Thanks for asking!

Containrrr, and subsequently Watchtower, is part of DockerHub's sponsored OSS program. This means that the changes to their free tier won't impact any watchtower users.

![image](https://user-images.githubusercontent.com/1596025/225614008-52e725b2-9df1-49e6-9630-aa59254aa93f.png)
