### ISSUE TITLE
Be able to login to dockerhub registry more easily

### ISSUE THREAD

**Issue by kerphi** [containrrr/watchtower#1599]
### Is your feature request related to a problem? Please describe.

I would have to login to dockerhub because of my currents docker pull "rate limit" problem (using anonymous pull).

I have an opensource dockerhub plan (equivalent of paid plan) so that I would like to do authenticated docker pull with watchtower to pull my opensources images so that I could make use of higher rate limitation provided by dockerhub.

### Describe the solution you'd like

I saw it's possible to use a config.json to give the login/mdp to watchtower: 
https://containrrr.dev/watchtower/private-registries/

But this way is not the easiest because it needs to create a new file and to share it thanks to a shared docker volume.
My idea would be to add env parameters to watchtower in order to easily use dockerhub login/mdp, for example: 
```
WATCHTOWER_DOCKERHUB_LOGIN
WATCHTOWER_DOCKERHUB_PASSWORD
```

### Describe alternatives you've considered

Of cours it could be possible to use a config.json to enable [this feature](https://containrrr.dev/watchtower/private-registries/) but it's just less easy.

**Comment by piksel** [comment]
You can set the `REPO_USER` and `REPO_PASS` environment variables (note the lack of `WATCHTOWER_` prefix) to accomplish the same thing.

**Comment by kerphi** [comment]
Thank you, even if it's not prefixed by `WATCHTOWER_` that's perfect for the easy side!

**Comment by kerphi** [comment]
The REPO_USER and REPO_PASS arguments are not listed in the documentation here:
https://containrrr.dev/watchtower/arguments/

Could be a good idea to add it or theses arguments are not ready to be public?

**Comment by piksel** [comment]
They are listed on the general usage, but not on arguments. I think they are generally not recommended since they may lead to users sending their credentials to the wrong repository.
