### ISSUE TITLE
Use local time for --schedule?

### ISSUE THREAD

**Issue by steve28** [containrrr/watchtower#160]
If I try to have watchtower do its thing at 4am every day by using the:
`--schedule "0 0 4 * * *"`
It seems to be interpreting this as 0400 UTC.  Per the log, I get:
`time="2018-01-27T22:26:55Z" level=info msg="First run: 2018-01-28 04:00:00 +0000 UTC" `

Is there any way to have watchtower use local time for the schedule?

**Comment by solipsist01** [comment]
`docker run --name=watchtower -d -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone -v /var/run/docker.sock:/var/run/docker.sock v2tec/watchtower --cleanup --schedule '0 0 4 * * *' `

**Comment by stffabi** [comment]
Setting TZ and mounting `/usr/share/zoneinfo` as mentioned in #145, should work as expected.

If you have any further questions about this, feel free to reopen the issue.

**Comment by stffabi** [comment]
Since version `0.3.0` you could just set the `TZ` environment variable and you don't need to mount anything else.
