### ISSUE TITLE
Additional "host" option for email notifications

### ISSUE THREAD

**Issue by nightah** [containrrr/watchtower#168]
Would it be possible to add another option/environment variable which will allow us to specify the "host" that watchtower is monitoring?
Perhaps even adding something like the following to the body of the email:
```
This message was generated by the Watchtower daemon running on:

host name:  $HOST

2018-02-24 22:05:41 (info): Found new jenkins/jenkins:alpine image (sha256:d93a4d3ed23dbd37a98aa481ec4c37218d25ad7e4ca4cc5d7dbb67b208211a43)
2018-02-24 22:05:53 (info): Stopping /jenkins (6a024baf4c9f139a682be6d0c634db32c57c846a62e2ba96836e5e0ed31cce94) with SIGTERM
2018-02-24 22:05:57 (info): Creating /jenkins
```
For now the only way for me to differentiate which host the email notifications are coming from are either the containers in which are being updated, or by changing the FROM/TO email addresses which some may prefer not to do. I want to easily be able to tell all watchtower related notifications for filing so they're all coming from the same email, being able to identify the host in the body of the email would be amazing.

**Comment by stffabi** [comment]
Thanks for your report.

The subject contains the hostname where watchtower is running on. You can easily change the hostname that docker uses for the container as mentioned in #145, by using the `-h` flag.

**Comment by nightah** [comment]
Ah that makes total sense, thanks.
