### ISSUE TITLE
How to disable watchtower on a single container?

### ISSUE THREAD

**Issue by Skaronator** [containrrr/watchtower#169]
The Readme doesn't answer this question directly. I assume setting `com.centurylinklabs.watchtower.enable` to `false` will disable updates for a single container? Do I need to change something on my start parameter?

**Comment by stffabi** [comment]
Thanks for your report. In order to use the label you have to pass `--label-enable` after having passed this flag, only containers with the label `com.centurylinklabs.watchtower.enable` set to true will be updated.

**Comment by Skaronator** [comment]
Is there a way to make the exact opposite? I'd like to auto-update all containers except a single one.

**Comment by redge76** [comment]
Exactly what I need for my comment #167 . Unfortunately, it seems there is no safe way to do this.

**Comment by stffabi** [comment]
It would be possible to change the behaviour, that containers which have the label `com.centurylinklabs.watchtower.enable` set to false are always excluded from the updates. Those would be also excluded if the `--label-enable` wasn't specified.

@redge76 would that be a possible trade-off for you? You would then need to always create your containers with the label set to false.

**Comment by redge76** [comment]
That's better than nothing. 
And it's true that the option "--label-enable" has no added value.
If there is a label, then watchtower honors it. If not, default behaviour.
It's now 100% safe because you can always forget to set this label for a new container, but it's a lot better.

**Comment by stffabi** [comment]
Yeah, I know it's not the best solution. But it would be a trade-off where we don't break anything for the people out there but at least give some safer behaviour.

**Comment by Skaronator** [comment]
Thanks!

**Comment by stffabi** [comment]
@Skaronator you're welcome. Please note a new release is scheduled for in about one to two weeks.

**Comment by redge76** [comment]
Hi,
Still no release ?

**Comment by Keridos** [comment]
please release this. My logs are full of spam because of some containers that watchtower wants to update, but fails to do so.
