### ISSUE TITLE
Add option to search for updates at startup

### ISSUE THREAD

**Issue by FilipLaurentiu** [containrrr/watchtower#1696]
### Is your feature request related to a problem? Please describe.

I have a few docker containers that I run once I start my PC and I want to use watchtower to monitor them for updates each day. If I use the default update interval, 24 hours, watchtower will never check for updates because each time I restart the container it also reset this interval. 

### Describe the solution you'd like

The solution I see is to check for update immediately after it starts

### Describe alternatives you've considered

My current solution is to set a lower updater interval, a few hours, but this is not ideal.

**Comment by piksel** [comment]
There is `--run-once` that does a check on startup, but it cannot be combined with a schedule. If you restart your computer once per day it would effectively be the same as having a 24h schedule. 
Allowing both has been proposed and drafted before, but no concrete implementation has been done so far.

**Comment by FilipLaurentiu** [comment]
> There is `--run-once` that does a check on startup, but it cannot be combined with a schedule. If you restart your computer once per day it would effectively be the same as having a 24h schedule. Allowing both has been proposed and drafted before, but no concrete implementation has been done so far.

Hmm.. I try it this way. I have a `docker-compose` file and add `--run-once` to the watchtower container but doesn't seems to work good.
I can't have a restart policy anymore. The container will start, check for updates, and exit. Next time I open my pc the container will be stopped. 
And if I set a restart policy, docker will restart the container in an infinite loop.

**Comment by simonaronsson** [comment]
> > There is `--run-once` that does a check on startup, but it cannot be combined with a schedule. If you restart your computer once per day it would effectively be the same as having a 24h schedule. Allowing both has been proposed and drafted before, but no concrete implementation has been done so far.
> 
> Hmm.. I try it this way. I have a `docker-compose` file and add `--run-once` to the watchtower container but doesn't seems to work good. I can't have a restart policy anymore. The container will start, check for updates, and exit. Next time I open my pc the container will be stopped. And if I set a restart policy, docker will restart the container in an infinite loop.

Unfortunately, you won't be able to both have the cake and it at the same time. 😅 To me, it sounds like having it execute with `--run-once` would be the preferable option. Optionally, you could execute it whenever your computer starts using the appropriate docker-compose command and a line in your `.bashrc` or equivalent to call it.
