### ISSUE TITLE
Watch tower not updating the containers

### ISSUE THREAD

**Issue by akib1689** [containrrr/watchtower#1736]
I Have down graded one of docker container version specifically to test this my current Dockerfile is like this:

```dockerfile
FROM containrrr/watchtower

# Set environment variables
ENV PUID=1000
ENV PGID=100
ENV WATCHTOWER_CLEANUP=true
ENV WATCHTOWER_LABEL_ENABLE=true
ENV WATCHTOWER_INCLUDE_RESTARTING=true
ENV WATCHTOWER_HTTP_API_TOKEN=mySecretToken

# Set the command to run Watchtower
CMD ["--interval", "86400", "--http-api-update", "--http-api-periodic-polls"]

# Expose port
EXPOSE 8080

# Mount the host's localtime file as read-only
VOLUME ["/etc/localtime:/etc/localtime:ro"]
```

and my run command looks like this:

```console
docker run -d     --name watchtower-container     -p 8080:8080     -v /var/run/docker.sock:/var/run/docker.sock     my-watchtower-image
```
and I have tagged my container perfectly. But this is the log of the watch tower when I manually trigger from the end point of watchtower

```console
time="2023-08-17T23:19:37Z" level=info msg="Watchtower 1.5.3"
time="2023-08-17T23:19:37Z" level=info msg="Using no notifications"
time="2023-08-17T23:19:37Z" level=info msg="Only checking containers using enable label"
time="2023-08-17T23:19:37Z" level=info msg="Scheduling first run: 2023-08-18 23:19:37 +0000 UTC"
time="2023-08-17T23:19:37Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
time="2023-08-17T23:19:37Z" level=info msg="The HTTP API is enabled at :8080."
time="2023-08-17T23:20:59Z" level=info msg="Updates triggered by HTTP API request."
time="2023-08-17T23:21:01Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
time="2023-08-17T23:28:17Z" level=info msg="Updates triggered by HTTP API request."
time="2023-08-17T23:28:20Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
```
May be I'm doing something wrong. My current Image version is 1.4.0 and the latest is 1.5.1
![image](https://github.com/containrrr/watchtower/assets/54747148/52681d2e-443a-4e86-a90c-6aa8a3a76eb8)
![image](https://github.com/containrrr/watchtower/assets/54747148/6f6382e4-a2f6-4a19-8039-646735792db1)

_Originally posted by @akib-89 in https://github.com/containrrr/watchtower/discussions/1735_

**Comment by piksel** [comment]
> I Have down graded one of docker container version

How did you do this? Watchtower reports that it checked one container for an updated image, but found no newer version. 

If you use the version tags in the screenshot above it won't work, since watchtower only checks images with the same tag. If you want "latest minor' updates, you need to tag your images with both `v1` **and** `v1.5.1` (and if you want "latest patch", you would also need `v1.5`).

Then you would start your container with `akib-89/view-service:v1` or `:v1.5` etc.

**Comment by piksel** [comment]
See discussion #1735.
