### ISSUE TITLE
Update only specific containers

### ISSUE THREAD

**Issue by jebabin** [containrrr/watchtower#1745]
### Is your feature request related to a problem? Please describe.

I'd like to be able to globally disable containers update but enable update for a specific container.

Currently, it's possible to disable globally containers update with WATCHTOWER_MONITOR_ONLY
But, unless i missed something, when WATCHTOWER_MONITOR_ONLY is set to true, there is no way to enable update for a specific container

The only way would be to set com.centurylinklabs.watchtower.monitor-only to true on all containers except the one that need to be update.  

### Describe the solution you'd like

Instead of having update enable by default then disable update on some containers, I'd like to have update disable by default then enable update on some contrainers

### Describe alternatives you've considered

set com.centurylinklabs.watchtower.monitor-only to true on all containers except the one that need to be update.  

### Additional context

May be in case WATCHTOWER_MONITOR_ONLY=true && com.centurylinklabs.watchtower.monitor-only=false the update could be performed ?
It would imply to default com.centurylinklabs.watchtower.monitor-only to true when WATCHTOWER_MONITOR_ONLY=true

May be the following changes would do this
in update.go (line 37), changing
`shouldUpdate := stale && !params.NoRestart && !params.MonitorOnly && !targetContainer.IsMonitorOnly()`
to something like 
`shouldUpdate := stale && !params.NoRestart && !targetContainer.IsMonitorOnly()`
in update.go (line 75), removing
`if !params.MonitorOnly {`

in container.go (line 134), changing
```
func (c Container) IsMonitorOnly() bool {
	rawBool, ok := c.getLabelValue(monitorOnlyLabel)
	if !ok {
		return false
	}

	parsedBool, err := strconv.ParseBool(rawBool)
	if err != nil {
		return false
	}

	return parsedBool
}

```
to
```

func (c Container) IsMonitorOnly() bool {
	rawBool, ok := c.getLabelValue(monitorOnlyLabel)
	if !ok {
		if params.MonitorOnly {
			return true
		} else {
			return false
		}
	}

	parsedBool, err := strconv.ParseBool(rawBool)
	if err != nil {
		if params.MonitorOnly {
			return true
		} else {
			return false
		}
	}

	return parsedBool
}
```
but params is not defined in containers.go

**Comment by jebabin** [comment]
I figured out that what I'm looking for is available with WATCHTOWER_LABEL_ENABLE=true then com.centurylinklabs.watchtower.enable=true on the containers.
But where I'm lost is that it means that WATCHTOWER_MONITOR_ONLY=true is equal to WATCHTOWER_LABEL_ENABLE=true but the last one allow to still enable update for some containers with com.centurylinklabs.watchtower.enable=true while WATCHTOWER_MONITOR_ONLY doesn't
So I'm not understanding why WATCHTOWER_MONITOR_ONLY exist. I must miss something.
If someone could explain the difference I'd be happy to submit a PR to improve the documentation

**Comment by piksel** [comment]
There is a case to be had that the container label should always override the global value for `monitor-only`. It's a breaking change though, and as such we haven't made the change (due to watchtowers nature, all updates are "mandatory" as watchtower updates itself and may in this case break peoples setups).

There is a way to implement this "safely" though, by adding an opt-in flag for the label override, something like `label-precedence`...

**Comment by piksel** [comment]
> I figured out that what I'm looking for is available with WATCHTOWER_LABEL_ENABLE ...

The `label-enable` and `monitor-only` does a bit different things:
- `monitor` is "Check for newer images, but don't recreate (update) the container"
- `enable` is whether the container will be included in the check at all.

If you only want to include some containers (and not bother with checking the one you don't want updated) you can also use a regular expression as the first argument to watchtower to only include containers which name matches the expression.

Another alternative is to use scopes (one with `monitor-only` and one without):
https://containrrr.dev/watchtower/running-multiple-instances/

**Comment by jebabin** [comment]
Thanks for pointing to scope but it doesn't solve my problem as i'd like monitoring by default on all containers (without having to add a specific label, including the scope one) but update on some specific containers
To ensure all containers are monitored (even if someone forget a label), watchtower need to be started without scope and running an instance without scope in parallel to an instance with scope is not possible.

So i submited #1754 to implement your idea of a label-precedence argument. 

I've made a table of the behavior depending of the combinaison of the enable/monitor only options.
I don't know if this could be useful in the documentation, but at least it will be there.

Default WatchTower behavior

| | WATCHTOWER_LABEL_ENABLE=false<br>WATCHTOWER_MONITOR_ONLY=false<br>(default env values) | WATCHTOWER_LABEL_ENABLE=true<br>WATCHTOWER_MONITOR_ONLY=false | WATCHTOWER_LABEL_ENABLE=false<br>WATCHTOWER_MONITOR_ONLY=true | WATCHTOWER_LABEL_ENABLE=true<br>WATCHTOWER_MONITOR_ONLY=true |
| --- | --- | --- | --- | --- |
| **No labels**  | Monitor and update container   | Do nothing (no monitoring, no update) | Monitor containers but don't update | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.monitor-only=true** | Monitor containers but don't update| Do nothing (no monitoring, no update) | Monitor containers but don't update | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.monitor-only=false**  | Monitor and update container   | Do nothing (no monitoring, no update) |  Monitor containers but don't update<br>(**The environment variable take precedence on the label**) | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.enable=true** | Monitor and update container   | Monitor and update container  | Monitor containers but don't update | Monitor containers but don't update |
| **com.centurylinklabs.watchtower.enable=true**<br>**com.centurylinklabs.watchtower.monitor-only=false**  | Monitor and update container   | Monitor and update container  | Monitor containers but don't update<br>(**The environment variable take precedence on the label**) | Monitor containers but don't update<br>(**The environment variable take precedence on the label**) |
| **com.centurylinklabs.watchtower.enable=true**<br>**com.centurylinklabs.watchtower.monitor-only=true** | Monitor containers but don't update| Monitor containers but don't update   | Monitor containers but don't update | Monitor containers but don't update |
| **com.centurylinklabs.watchtower.enable=false**| Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update)  | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.enable=false**<br>**com.centurylinklabs.watchtower.monitor-only=false** | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update)  | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.enable=false**<br>**com.centurylinklabs.watchtower.monitor-only=true**  | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update)  | Do nothing (no monitoring, no update)  |

Behavior with WATCHTOWER_LABEL_TAKE_PRECEDENCE=true

| | WATCHTOWER_LABEL_ENABLE=false<br>WATCHTOWER_MONITOR_ONLY=false<br>(default env values) | WATCHTOWER_LABEL_ENABLE=true<br>WATCHTOWER_MONITOR_ONLY=false | WATCHTOWER_LABEL_ENABLE=false<br>WATCHTOWER_MONITOR_ONLY=true | WATCHTOWER_LABEL_ENABLE=true<br>WATCHTOWER_MONITOR_ONLY=true |
| --- | --- | --- | --- | --- |
| **No labels**  | Monitor and update container   | Do nothing (no monitoring, no update) | Monitor containers but don't update | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.monitor-only=true** | Monitor containers but don't update| Do nothing (no monitoring, no update) | Monitor containers but don't update | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.monitor-only=false**  | Monitor and update container   | Do nothing (no monitoring, no update) | Monitor and update container<br>(**Label take precedence over environment variable**) | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.enable=true** | Monitor and update container   | Monitor and update container  | Monitor containers but don't update | Monitor containers but don't update |
| **com.centurylinklabs.watchtower.enable=true**<br>**com.centurylinklabs.watchtower.monitor-only=false**  | Monitor and update container   | Monitor and update container  | Monitor and update container<br>(**Label take precedence over environment variable**) | Monitor and update container<br>(**Label take precedence over environment variable**) |
| **com.centurylinklabs.watchtower.enable=true**<br>**com.centurylinklabs.watchtower.monitor-only=true** | Monitor containers but don't update| Monitor containers but don't update   | Monitor containers but don't update | Monitor containers but don't update |
| **com.centurylinklabs.watchtower.enable=false**| Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update)  | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.enable=false**<br>**com.centurylinklabs.watchtower.monitor-only=false** | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update)  | Do nothing (no monitoring, no update)  |
| **com.centurylinklabs.watchtower.enable=false**<br>**com.centurylinklabs.watchtower.monitor-only=true**  | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update) | Do nothing (no monitoring, no update)  | Do nothing (no monitoring, no update)  |

**Comment by jebabin** [comment]
With tables as image, default behavior:
![image](https://github.com/containrrr/watchtower/assets/11474713/89384a4f-5f5a-41c1-9090-99a6155e02fc)

with WATCHTOWER_LABEL_TAKE_PRECEDENCE=true
![image](https://github.com/containrrr/watchtower/assets/11474713/a3b27897-604d-44aa-bd9f-d76075ada7be)
