### ISSUE TITLE
Support delaying notification

### ISSUE THREAD

**Issue by ArthurGarnier** [containrrr/watchtower#1746]
### Is your feature request related to a problem? Please describe.

I'm using selfhosted notifications but when watchtower update the image of the notification system involved (Gotify or HomeAssistant webhooks), the notification is sent before the application is ready, so I don't receive it.

### Describe the solution you'd like

Add a variable to delay the notification of X seconds

### Describe alternatives you've considered

No application workaround found

**Comment by piksel** [comment]
I think you are looking for `--notification-delay`:
https://containrrr.dev/watchtower/notifications/

**Comment by ArthurGarnier** [comment]
Exactly, don't know I missed that. 
Thank you !
