### ISSUE TITLE
Add flag to disable "First run" notifications

### ISSUE THREAD

**Issue by Ezwen** [containrrr/watchtower#175]
I have enabled watchtower with email notifications, and it works great.

However, I am running a server which voluntarily reboots once a day, which means each morning I get a "First run" email from watchtower.

In case I am not the only one interested in such a feature: could we imagine a way to disable such notification on watchtower startup? Either through a simple flag, or a more sophisticated mechanism to customize which messages should be part of notifications?

and thanks for watchtower!

**Comment by stffabi** [comment]
Thanks for your report. The easiest would be to set the loglevel to debug, which should be enough for this message. This would also exclude it from getting send by notifications as these use `info` as default level.

**Comment by mandreko** [comment]
From my understanding, wouldn't setting the log level to 'debug' be even more verbose, and also include all 'info' messages, such as the first-run email?

**Comment by simonaronsson** [comment]
Yes, you are absolutely correct. I think you’re talking about different things though.

First run should likely be a debug message rather than info, which I think is what was suggested here.

**Comment by simonaronsson** [comment]
Switched log level for "First run" to debug. Closing issue.

**Comment by kimpenhaus** [comment]
Hi,

might be nitpicking so please don't get me wrong - but I think this feature was deployed with v0.3.4 already and not with the upcoming v0.4.0. I just moved from v2tec to your docker container and was waiting for the startup email... none came. 🤣 

I checked the logs which stated:

`time="2019-04-21T15:27:22Z" level=debug msg="Starting Watchtower and scheduling first run: 2019-04-21 16:27:22 +0000 UTC m=+3600.598949237"`

So I searched the code and issues... found this issue and a commit that changed from info to debug:  https://github.com/containrrr/watchtower/commit/a2158c2bdc2ac06b6afcd41736a921673f30b4a3

Thanks for maintaining watchtower 👍

**Comment by simonaronsson** [comment]
Yeah, im doing running releases each sunday (if there is anything to deploy). It was in the 0.4.0 milestone but got finished early. 😅

**Comment by svengo** [comment]
Did you use v0.3.3, @kimpenhaus? The version broke e-mail notifications (see #281).
