### ISSUE TITLE
Support DOCKER_CONTENT_TRUST

### ISSUE THREAD

**Issue by fortuna** [containrrr/watchtower#176]
There doesn't seem a way for watchtower to validate the signatures of the images it pulls.
I need that to ensure the images were not tampered with.

**Comment by stffabi** [comment]
Thanks for your report.

Did you try setting the environment variable `DOCKER_CONTENT_TRUST` when running the watchtower container? AFAIK this should be directly handled from the internally used docker client.

**Comment by simonaronsson** [comment]
Closing due to lack of response.
