### ISSUE TITLE
function \"n\" not defined

### ISSUE THREAD

**Issue by cholzer79** [containrrr/watchtower#1764]
### Describe the bug

The notification template for docker to "always send a notification" throws an error when Watchtower is started.

`level=error msg="Could not use configured notification template: template: :19: function \"n\" not defined. Using default template"`

This is the template taken from here https://containrrr.dev/watchtower/notifications/

```sh
docker run -d \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e WATCHTOWER_NOTIFICATION_REPORT="true"
  -e WATCHTOWER_NOTIFICATION_URL="discord://token@channel slack://watchtower@token-a/token-b/token-c" \
  -e WATCHTOWER_NOTIFICATION_TEMPLATE="
  {{- if .Report -}}
    {{- with .Report -}}
  {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
        {{- range .Updated}}
  - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
        {{- end -}}
        {{- range .Fresh}}
  - {{.Name}} ({{.ImageName}}): {{.State}}
      {{- end -}}
      {{- range .Skipped}}
  - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
      {{- end -}}
      {{- range .Failed}}
  - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
      {{- end -}}
    {{- end -}}
  {{- else -}}
    {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
  {{- end -}}
  " \
  containrrr/watchtower
```

### Steps to reproduce

1. use the template from the documentation
2. start watchtower
3. see the error in the logs

### Expected behavior

not get an error, have the notification work

### Environment

Ubuntu 22.04
Virtual Machine on Proxmox
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:55 2023
 OS/Arch:           linux/amd64
 Context:           default

### Your logs

```text
level=error msg="Could not use configured notification template: template: :19: function \"n\" not defined. Using default template"
```

**Comment by piksel** [comment]
Hello! Yeah, I think the author (probably me) forgot about go templates not allowing newline escapes. Sorry for not catching this earlier!

**Comment by piksel** [comment]
Actually, this works correctly when supplying the string directly to the go template. This is due to your shell quoting. You need to either escape the `"` using `\"`, or use `'` quotes.

The example in the docs have been updated to actually escape them, but the change has not been published yet.

**Comment by cholzer79** [comment]
> Actually, this works correctly when supplying the string directly to the go template. This is due to your shell quoting. You need to either escape the `"` using `\"`, or use `'` quotes.
> 
> ...in fact, the example in the docs already _does_ escape them?
> 
> > ```
> > {{range .Entries -}}{{.Message}}{{\"\n\"}}{{- end -}}
> > ```

I simply did a copy/paste of the example in the documentation.
You can see my config in the first post - what exactly did I do wrong?

**Comment by piksel** [comment]
Sorry, I were looking at the docs in `main`, not the released ones. There are missing escapes in the currently published docs.

So, the 4th row from the bottom should instead be:
```
    {{range .Entries -}}{{.Message}}{{\"\n\"}}{{- end -}}
```

**Comment by piksel** [comment]
New docs have been deployed and now correctly escape the quotes.
