### ISSUE TITLE
Allow update "on demand" from another container

### ISSUE THREAD

**Issue by PierrickPuimeanChieze** [containrrr/watchtower#18]
I have a continuous integration server running in a container on my host.

The continuous integration process produce docker images and publish them on Docker hub

Bases on these images, I have multiple container running on the same host, each one corresponding to a different state of my application (say, dev, test and prod, for the sake of the discussion). Given this, I can't use Watchtower on each of theses container (don't want to see my dev version pushed in prod).

What I would like is a way to ask Watchtower to update a given container from inside my CI container, if I link the watchtower container to my CI container.

**Comment by simonaronsson** [comment]
As this is very closely related to what is being asked for in #262, this ticket will now be closed. Discussions may be continued in the related issue.
