### ISSUE TITLE
[notifications] msteams

### ISSUE THREAD

**Issue by YoShiiro** [containrrr/watchtower#180]
I got error when i try to use msteams notifications webhook 

_docker run -it --name watchtower   -v /var/run/docker.sock:/var/run/docker.sock   -e WATCHTOWER_NOTIFICATIONS=msteams   -e WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL="https://outlook.office.com/webhook/YYYYYYYYYYYYYYYYYYYYYYYYYY/IncomingWebhook/XXXXXXXXXXXXXXXXXXXXXXXXXXX"   -e WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA=true  v2tec/watchtower_

_FATA[0000] Unknown notification type "msteams"_

**Comment by dan-hughes** [comment]
I have this error too. It looks like the docker image has not been updated since msteams integration was added. @stffabi @napstr can the updated docker images be pushed to docker hub please?

**Comment by stffabi** [comment]
Thanks for your report. 

As @dan-hughes already mentioned, a new release hasn't been published with msteams support. A new release will be created this week. So stay tuned...

**Comment by YoShiiro** [comment]
thanks for the answer ;).

**Comment by YoShiiro** [comment]
Hi @stffabi Any eta regarding the docker image update for the msteams integration ?

**Comment by cbirkenbeul** [comment]
Hi,
the message still there. Do you know when u release the new version?
Cheers

**Comment by ThomasRunting** [comment]
it still has not been released yet? @stffabi @napstr @dan-hughes

**Comment by pvaillant** [comment]
Any update on this? I'm also interested in msteams integration.

**Comment by freebo** [comment]
any update on teams please -I also have this issue

**Comment by simonaronsson** [comment]
This issue will be merged with #264, which focuses on notifications in general.
However, as I do not have any experience of using pushover, all help possible would be appreciated.
