### ISSUE TITLE
Option to keep in memory env vars

### ISSUE THREAD

**Issue by JohannesFleischer** [containrrr/watchtower#1803]
### Is your feature request related to a problem? Please describe.

Docker secrets that are not stored on disk (e.g., in a `docker-compose.yml` file) and solely in memory are cleared when the container gets updated and the container stops to work as expected.

### Describe the solution you'd like

Therefore, it would be great to have an option to create the new container with an identical env as the old one when it was stopped.

### Describe alternatives you've considered

Another option would be to pull these secrets again, but in some setups this is not possible:

E.g., when using `envconsul` to pull the secrets out of a `hashicorp vault`, because `envconsul` sets the in memory env variables for the docker process. Also, the token to pull the secrets out of the `vault` could be stored externally or expired so that rerunning the `envconsul` command to run the container is not possible.

**Comment by piksel** [comment]
This is the default behaviour of watchtower. All environment variables are compared with the default ones in the image, and if they match they will be removed (to not override defaults in the new image). All other variables will be transferred to the new container. Of not, then it's either a bug, or I don't understand your setup completely...

Perhaps you are talking about the runtime environment? But then, surely those would be cleared if the container was just restarted?

**Comment by JohannesFleischer** [comment]
@piksel you're absolutely right. I did an oopsie on my side, so thanks for your reply, without it, I probably would not have looked at it again.
