### ISSUE TITLE
Add telegram as a notification service

### ISSUE THREAD

**Issue by ag0r4n** [containrrr/watchtower#181]
Possibility to notify through a Telegram bot https://core.telegram.org/bots/api

**Comment by aaomidi** [comment]
Is the team alright with me working on this?

**Comment by jake-walker** [comment]
I've just started using Watchtower today and I'd love to be able to use Telegram to notify me.
👍

**Comment by MAGICCC** [comment]
@aaomidi Any updates on this?

**Comment by aaomidi** [comment]
Ah I didn't start. I'll get to it on Monday!

**Comment by simonaronsson** [comment]
This issue will be merged with #264, which focuses on notifications in general.
However, as I do not have any experience of using pushover, all help possible would be appreciated.
