### ISSUE TITLE
Executing commands before stopping containers and after restarting them

### ISSUE THREAD

**Issue by alexandremenif** [containrrr/watchtower#183]
Hello,

I would like to use Watchtower to automatically update some database containers. However, these containers (running the official postgres image) cannot be simply updated by stopping them, pulling the new image, and restarting the containers. Indeed if the update happened between major versions, the data needs to be migrated. One way to do this is to dump the data from the old container, and import the dump with the updated containers.

I do not think that there is now a simple way to do this using Watchtower. However I was thinking that a mechanism could be added to watchtower in order to execute this kind of actions. It could take the form of a pair of pre/post command lines that should be executed before stopping the container, and after restarting it. A different pair could be specified for each container using labels, for instance.

I would like to investigate the feasibility of this features, and implement it. But I would like to know first if such a feature would be welcomed, or if there is some issues with the idea itself.

Best regards,

Alexandre Menif

**Comment by simskij** [comment]
It would! Feel free to have a stab at it and I'll make sure to help you review it and guide you towards something fitting.

**Comment by mikeboiko** [comment]
@alexandremenif, thanks for implementing this feature. It's exactly what I was looking for!
Have you posted your postgres update scripts anywhere? Would love to use them as a reference.

**Comment by alexandremenif** [comment]
Hello @mikeboiko. This was some time ago and unfortunately I no longer have the scripts that i was using at the time.

**Comment by mikeboiko** [comment]
No worries :)
