### ISSUE TITLE
Watchtower stuck in a loop trying to update container that has no label enabled. 

### ISSUE THREAD

**Issue by maxze** [containrrr/watchtower#184]
I have three containers running:

Two that should not be touched and one that will change in the future. Watchtower keeps trying to update all three of them even though only one of them was started with the label true. 

Here's the command to start the container. It starts up fine so far.

`sudo docker run --restart=always \
-d --label=com.centurylinklabs.watchtower.enable=true \
-p 8088:8088 --name api localapi`

I then use this command to start watchtower: 

`sudo docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock \
-e WATCHTOWER_NOTIFICATIONS=slack \
-e WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL="hook_url" \
-e WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=docker_updates \
-e REPO_USER="user" -e REPO_PASS="pass" v2tec/watchtower -i 180`

I then get the message that watchtower is unable to update the container (the one without the flag) and that it'll be "Proceeding to next". It then goes back to the container it's unable to update and is stuck in a loop. 

Is there anything I'm doing wrong or do I have to restart every other container using the label false? 

Thank you in advance.

**Comment by simonaronsson** [comment]
Thanks for creating an issue!

Passing `--label=com.centurylinklabs.watchtower.enable=true` only makes a difference if you run watchtower with the flag `--label-enable`. Your other option is to omit the `--label-enable` flag and instead set `--label=com.centurylinklabs.watchtower.enable=false` on the ones you dont want to update.

🙏
