### ISSUE TITLE
Notify arbitrary URL with a WebHook

### ISSUE THREAD

**Issue by nogweii** [containrrr/watchtower#185]
I love the notification support but I don't use Slack or MS Teams. It'd be nice if watchtower supported sending a JSON payload to an arbitrary URL. In the mean time, I could use the slack notification and point it to somewhere else.

**Comment by frankfarrell** [comment]
It would be really nice if this could work off a url specified in a label. That way automated builds could have a specific webhook that would be called when the image updated

**Comment by jeremiahkjones** [comment]
+1
Would love to be able to notify jenkins that an update was completed

**Comment by simonaronsson** [comment]
This issue will be merged with #264, which focuses on notifications in general.
However, as I do not have any experience of using pushover, all help possible would be appreciated.
