### ISSUE TITLE
Mattermost integration

### ISSUE THREAD

**Issue by afteroot** [containrrr/watchtower#1856]
### Is your feature request related to a problem? Please describe.

....

### Describe the solution you'd like

Recieve message into [Mattermost](https://mattermost.com/)

### Describe alternatives you've considered

For now funtional is close to send Slack message,
but the error in url check
Slack url https://hooks.slack.com/services/xxx/yyyyyyyyyyyyyyy"
MM url https://mattermost.com/hooks/xxxxxxxxxxxxxxxx \

So if Mattermost send message will be implemented will be appreciated

**Comment by piksel** [comment]
Mattermost is fully supported using shoutrrr:

https://containrrr.dev/watchtower/notifications/#shoutrrr_notifications

https://containrrr.dev/shoutrrr/v0.8/services/mattermost/

```
WATCHTOWER_NOTIFICATION_URL: mattermost://[username@]mattermost-host/token[/channel]
```

**Comment by afteroot** [comment]
@piksel Thanks a lot for your answer, will try!
