### ISSUE TITLE
Reload nginx proxy config on image update

### ISSUE THREAD

**Issue by norpan** [containrrr/watchtower#186]
Hi,
I'm trying to use watchtower to update my applications when I push a new image. My problem is that they are behind an nginx reverse proxy, and when the containers restart they sometimes get a new IP address. They are referred to by name in the nginx config, but it doesn't do a new lookup on each request, so I have to send it a SIGHUP.

I'm wondering if there is a way to configure watchtower send SIGHUP to my nginx container whenever it updates an image.

**Comment by qqilihq** [comment]
We're just having very similar issues, and I think if the `link` would work as expected (see #126), this problem would also be resolved.

**Comment by norpan** [comment]
I think I solved it by specifying in nginx.conf server section resolver and valid=1s

**Comment by qqilihq** [comment]
Interesting, that hadn't even come to my mind. Although I solved it differently for now, this is very valuable input. Thanks!

**Comment by redge76** [comment]
Some cool project https://traefik.io/
Great reverse proxy tailored for Docker.

**Comment by yspreen** [comment]
@norpan I'm facing the same issue. Could you maybe elaborate on:
`specifying in nginx.conf server section resolver and valid=1s`
?

**Comment by norpan** [comment]
So, it's finally solved.
The two things that you need to do is to specify a resolver (which is 127.0.0.11 in docker) in your server config, and use variables in the proxy_pass to make the resolver actually resolve each time. When using variables in proxy_pass you need to create the whole new access url.

So, here is what my server section looks like:
```
http {
  server {
    resolver 127.0.0.11 valid=1s;
    set $my_service my_service_name;
    # Admin client
    location / {
      proxy_pass http://$my_service$request_uri;
    }
```

**Comment by simonaronsson** [comment]
> So, it's finally solved.
> The two things that you need to do is to specify a resolver (which is 127.0.0.11 in docker) in your server config, and use variables in the proxy_pass to make the resolver actually resolve each time. When using variables in proxy_pass you need to create the whole new access url.
> 
> So, here is what my server section looks like:
> 
> ```
> http {
>   server {
>     resolver 127.0.0.11 valid=1s;
>     set $my_service my_service_name;
>     # Admin client
>     location / {
>       proxy_pass http://$my_service$request_uri;
>     }
> ```

Thanks for the solution, @norpan ! Would you mind creating a PR updating the readme with your solution? 🙏

**Comment by SebastianRzk** [comment]
@norpan @simskij 

Nginx just open sourced a new feature for dynamic DNS resolving in upstream blocks:

https://blog.nginx.org/blog/dynamic-dns-resolution-open-sourced-in-nginx

You still need to define the docker resolver, but you can skip the workaround with the variable. I think this would be a much nicer solution.
