### ISSUE TITLE
Set a fixed time instead of a timer

### ISSUE THREAD

**Issue by XHyperDEVX** [containrrr/watchtower#1882]
### Is your feature request related to a problem? Please describe.

It's for clarity for me, so not a physical problem, but something that would be nice to have.

### Describe the solution you'd like

It would be great if, instead of specifying a time that expires and thus always depends on when the container is started, you could have the option of specifying a fixed time.

So that you don't say "From now on every 24 hours", but "Every day at 6 pm".

### Describe alternatives you've considered

From the host system with cron, is cumbersome and not reliable.

**Comment by piksel** [comment]
Perhaps something like [scheduling](https://containrrr.dev/watchtower/arguments/#scheduling)? 😁

**Comment by XHyperDEVX** [comment]
@piksel 
Thank you. That's exactly what I was looking for xD
I would always have my containers up to date. Are there any disadvantages to having watchtower check for updates every 5 minutes, for example?

**Comment by piksel** [comment]
Yes, you might hit the free usage limit for docker hub. Watchtower tries to avoid pulling to not reach that limit, but depending on your setup it might still happen.

See https://docs.docker.com/docker-hub/download-rate-limit/ for more details.

**Comment by XHyperDEVX** [comment]
@piksel These pulls only count for downloading, not for watchtower's check if new ones are available, don't they?

**Comment by piksel** [comment]
You cannot check for changes without downloading, but there is a hash that can be compared to see whether *something* has changed with the image. Watchtower uses that hash to avoid pulling (downloading) when possible.
