### ISSUE TITLE
Doesn't update image of multiple containers when docker-compose scale is used

### ISSUE THREAD

**Issue by c-m-hunt** [containrrr/watchtower#19]
I have scaled up one of the containers to two instances using docker-compose. When the image updates, only the first instance of the container is updating its image fine. The other doesn't update

Before:
![image](https://cloud.githubusercontent.com/assets/17702197/15958834/bb52be96-2eef-11e6-8952-6c9173a8caf5.png)

Then, updating image.

Can see that it's getting detected in the Watchtower logs
![image](https://cloud.githubusercontent.com/assets/17702197/15959088/ddff6146-2ef0-11e6-9616-9869d980860d.png)

Situation now....
![image](https://cloud.githubusercontent.com/assets/17702197/15959105/f75a91ba-2ef0-11e6-86fa-5a8126b89494.png)

The second container just shows the ID of the old image.

**Comment by MartijnHols** [comment]
I just tested this, this doesn't look to be the case (anymore?) and both containers get updated;
![image](https://user-images.githubusercontent.com/4565223/48490202-3119ab80-e825-11e8-895c-191641b73b24.png)

**Comment by c-m-hunt** [comment]
Ah nice. I'll try and revisit at some point. Thanks
