### ISSUE TITLE
Update volumes

### ISSUE THREAD

**Issue by aleogr** [containrrr/watchtower#190]
My stack is composed by two services: app, which has my application's content and nginx, the webserver.

The nginx service has access to my app's content through a shared volume. The thing is, when watchtower sees a new version for my app, it creates a new container using the new image, as expected. The problem is that the shared volume remains with the old version of my application's content.

Is there a way to configure watchtower to recreate both container and its volume?

**Comment by tomscholz** [comment]
Bump

**Comment by hazcod** [comment]
I am having the same issue for a bind mount.

**Comment by simonaronsson** [comment]
We could probably add a flag to allow for volume removal as well. 
Feel free to create a PR. This is likely solved by flipping client.go:107

**Comment by tomscholz** [comment]
Bump

**Comment by zoispag** [comment]
Bump

**Comment by euberdeveloper** [comment]
I have experiencing exactly the same issue. The problem is that if I use this option, all the volumes are deleted. I want only one specific volume to be deleted, the Frontend one, because the other volumes save important files
