### ISSUE TITLE
Using localhost as email server

### ISSUE THREAD

**Issue by a10kiloham** [containrrr/watchtower#193]
I'd like to use localhost or 127.0.0.1 as my email server with postfix but getting invalid domain name (configured so postfix does not use username or password)
`Failed to send notification email:  dial tcp: lookup 127.0.0.1 \: invalid domain name`
Any way to fix this or a workaround?

**Comment by a10kiloham** [comment]
Actually, when testing with dummy info this fails the same even with smtp.gmail.com the same way using test login/password. Confused!

I've the following setup as my .env file (loading via command --env-file=filename)
`WATCHTOWER_NOTIFICATIONS=email
WATCHTOWER_NOTIFICATION_EMAIL_FROM=me@mysite.com \
WATCHTOWER_NOTIFICATION_EMAIL_TO=me@mysite.com \
WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com \
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=test@test.com
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=test
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY`

**Comment by a10kiloham** [comment]
Argh, ignore, I think my env file had added \ in it.

**Comment by ovizii** [comment]
Would you mind sharing how I can quickly test if my notifications work? I mean how to trigger one.

**Comment by a10kiloham** [comment]
it sends a message on first-run
