### ISSUE TITLE
Documentation to build a docker container from the source

### ISSUE THREAD

**Issue by martinkoehler** [containrrr/watchtower#196]
This is probably due to the fact, that I#m no go expert, but I had some difficulties to build a working docker container from the sources.
I was able to build a docker container using `billyteves/alpine-golang-glide:1.2.0` as a base image after adding `apk add --update alpine-sdk` to compile and build the `watchtower` executable:

To reproduce clone this repo into your current directory ($PWD) then: 
`docker run -it --rm -v $PWD:/go/src/github.com/v2tec/watchtower -w /go/src/github.com/v2tec/watchtower billyteves/alpine-golang-glide:1.2.0 /bin/bash`
then  `apk add --update alpine-sdk` to add e.g. `gcc` and headerfiles.
Thereafter `glide install` and finally
`go build` to build a watchtower executable that runs under alpine.

The final docker image is than based on `alpine:latest` with `COPY watchtower /`   and `ENTRYPOINT ["/watchtower"]` as the docker build commands.

I'm sure there is an easier and better way to build such a container and suggest to include the corresponding recipe into this project. Thanks

**Comment by ralsu091** [comment]
Have you looked in here? https://github.com/v2tec/watchtower/tree/master/dockerfile

Thanks,

**Comment by martinkoehler** [comment]
Thanks. Yes, I did this and observered that the dockerfiles (in my case amd64) assume an executable watchtower in the build directory. To build this executable on the host system produced an executable watchtower, that I was unable to run in the alpine image. Hence I thought the executable must be build from within an alpine environment. 
However using the above mentioned alpine-golang-glide image, I was able to build an executable watchtower, which works under alpine (but not on ubuntu at my hostsystem. The latter is fine, btw)
Using the dockerfile from tree/master/dockerfile did _not_ work. When I remove "FROM scratch", than it works. (And that's in fact what I did).
I presume that there must be a different way, but I seem not to be able to see it.

**Comment by ChessSpider** [comment]
Thanks for the suggestions, Martin. 
In the end I created this:

```
FROM golang:alpine as builder
RUN apk update && apk add  alpine-sdk ca-certificates tzdata
RUN curl https://glide.sh/get | sh

RUN go get github.com/v2tec/watchtower; exit 0

WORKDIR /go/src/github.com/v2tec/watchtower

RUN glide install

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM scratch

LABEL "com.centurylinklabs.watchtower"="true"

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /go/src/github.com/v2tec/watchtower/watchtower /watchtower

ENTRYPOINT ["/watchtower"] 
```

**Comment by martinkoehler** [comment]
Thanks!
