### ISSUE TITLE
client version too new

### ISSUE THREAD

**Issue by setchy** [containrrr/watchtower#2012]
### Describe the bug

```Error response from daemon: client version 1.45 is too new. Maximum supported API version is 1.43```

### Steps to reproduce

Use [containrrr/watchtower:latest@sha256:e7dd50d07b86c380dd53caeb7778da052d1a8fc2c606644a419afa35e9f5691e](http://192.168.20.222:9000/#!/2/docker/images/sha256%3Ae7dd50d07b86c380dd53caeb7778da052d1a8fc2c606644a419afa35e9f5691e) with Docker Engine - Community v26.1.0

### Expected behavior

Watchtower supports latest Docker Engine and API Version

### Environment

- Platform: debian
- Architecture: x86
- Docker Version: 26.1.0

### Your logs

```text
DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized. 

DEBU[0001] Making sure everything is sane before starting 

DEBU[0001] Retrieving running and restarting containers 

ERRO[0001] Error response from daemon: client version 1.45 is too new. Maximum supported API version is 1.43 

INFO[0001] Waiting for the notification goroutine to finish  notify=no

```
```


### Additional context

_No response_

**Comment by gfacek** [comment]
I'm having the same error. Did you find a working solution?

**Comment by setchy** [comment]
I'm not too sure what changed on my server, but this issue has resolved itself
