### ISSUE TITLE
unauthorized when pulling from private gitlab AND public dockerhub

### ISSUE THREAD

**Issue by PhE** [containrrr/watchtower#202]
watchtower is working fine for pulling images from my private gitlab registry but fails to pull public images from dockerhub :
```
watchtower_1 | time="2018-06-27T05:56:02Z" level=info msg="Unable to update container /xxx_watchtower_1, err='Error response from daemon: Get https://registry-1.docker.io/v2/v2tec/watchtower/manifests/latest: unauthorized: incorrect username or password'. Proceeding to next." 
```
watchtower uses gitlab credentials provided by REPO_USER/REPO_PASS env variables to connect to dockerhub.
How can we mix 2 images registries with different credentials ?

**Comment by DaEkstrim** [comment]
You can use a `config.json` to specify authentication per registry. Structure should be as follows, however documentation about this file structure is sketchy on the internet. Look at `docker login` command to automatically generate a `config.json`

```
{
  "auths": {
      "https://registry.url/": {
          "auth": "XXXXX"
      }
  }
}
```

**Comment by simonaronsson** [comment]
> You can use a `config.json` to specify authentication per registry. 

This. Closing issue. 🙏
