### ISSUE TITLE
watchtower DNS resolution is broken, cannot use hostnames on DOCKER_HOST var

### ISSUE THREAD

**Issue by ssbarnea** [containrrr/watchtower#203]
I discovered that the DNS resolution is broken on the container as it fails to resolve hostnames even if DNS resolution works well on the docker host itself.

I had to such problems with any other (>20) containers running on the same docker host.

I suspect it may have some hardcoded DNS servers configured inside which prevent it from using local DNS server, so using an address like "mydocker.local" would fail to resolve.

**Comment by simonaronsson** [comment]
Unable to reproduce. Closing due to issue age. If this is still a problem that needs to be fixed, feel free to open a new ticket. 🙏
