### ISSUE TITLE
Respect depends_on Docker option

### ISSUE THREAD

**Issue by nightah** [containrrr/watchtower#204]
Currently watchtower checks to see if a container has any link(s) defined to determine dependency and stop/start containers in a specific order when updating.

Docker have specified that --links flag is a legacy feature that could be dropped [here](https://docs.docker.com/network/links/):

```
Warning: The --link flag is a legacy feature of Docker.
It may eventually be removed.
Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link.
One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers.
However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.
```

Could we update the code to respect both links and depends_on to satisfy both cases until --links is removed?

**Comment by randellhodges** [comment]
I would like to see this too. If I'm not mistaken, isn't depends_on a docker-compose feature and not a core docker feature? If that is the case, watchtower would need to need to be able to read and use a docker-compose file.

Right now, it looks like it uses docker inspect on the running container and looks at the links. There isn't any depends_on information in the returned docker inspect information.

**Comment by jfl209** [comment]
Is it possible to use watchtower without docker-compose?

**Comment by simonaronsson** [comment]
> Is it possible to use watchtower without docker-compose?

Sure, just launch it using `docker run` as described in the readme. 👍

**Comment by simonaronsson** [comment]
At this point I don't really see parsing docker-compose files to check for depends_on to be part of the roadmap for watchtower. If someone would like to have a stab at this using some other method, feel free to create a PR and I'll make sure to review it.

Until then, this issue is closed. Thanks for your contributions 🙏

**Comment by danchal** [comment]
A possible solution would be to add some new labels to simulate docker-compose depends_on functionality.
[As an example, this has been implemented by Ouroboros.](https://github.com/pyouroboros/ouroboros/wiki/Usage#labels)

**Comment by simonaronsson** [comment]
Sounds great! If you’d like to have a stab at it I’d be more than happy to review it.
