### ISSUE TITLE
Skipped another update already running

### ISSUE THREAD

**Issue by phantomakc** [containrrr/watchtower#205]
Hi, We use this service to check the new docker images for our service. We see sometimes errors:
`time="2018-07-04T19:29:55Z" level=debug msg="Scheduled next run: 2018-07-04 19:30:05 +0000 UTC"
time="2018-07-04T19:30:05Z" level=debug msg="Checking containers for updated images"
time="2018-07-04T19:30:05Z" level=debug msg="Retrieving running containers"
time="2018-07-04T19:30:15Z" level=debug msg="Skipped another update already running."
time="2018-07-04T19:30:15Z" level=debug msg="Scheduled next run: 2018-07-04 19:30:25 +0000 UTC"
time="2018-07-04T19:30:25Z" level=debug msg="Skipped another update already running."
time="2018-07-04T19:30:25Z" level=debug msg="Scheduled next run: 2018-07-04 19:30:35 +000`
Tell me please, how can we understand what is causing this error? Docker image uploaded successfully on quay.io.
Watchtower version
`v2tec/watchtower       latest              3069a9fb302a        4 months ago        9.49MB`
`docker run --name watchtower \
    --detach \
    --restart=always \
    --log-driver=awslogs \
    --log-opt awslogs-group=watchtower-${service_name}-${application_env} \
    --log-opt awslogs-stream=watchtower-${service_name}-${application_env} \
    --log-opt awslogs-region=us-east-1 \
    --log-opt awslogs-create-group=true \
    --volume /root/.docker/config.json:/config.json \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    v2tec/watchtower:latest \
    --interval 10 \
    --debug`

**Comment by simonaronsson** [comment]
This happens when watchtower tries to start another round of updates before the current one finished. One way of avoiding this is to use a longer interval than 10s. However, it wont do any harm other than polluting your logs 😅 

🙏

**Comment by paolini** [comment]
I think this could be a problem: if an image has been modified in the meanwhile, the corresponding container is not updated. This happens frequently if you use two different images of the same service (development and production) and they are updated in sequence.

I think that if the update is triggered while another update is running, it should wait and then execute again.
