### ISSUE TITLE
 Failed to send notification email - Unrecognized authentication type

### ISSUE THREAD

**Issue by mnl1121** [containrrr/watchtower#209]
Upon first run I'm getting the following error. I searched and found other email failure errors, but not this one. 

`Failed to send notification email:  504 5.7.4 Unrecognized authentication type [DF4PR8401CA0017.NAMPRD84.PROD.OUTLOOK.COM]`

Here are my container settings. I'm using my email in each of the email fields and the password is an app password. Not sure what's wrong. 

```
docker run -d \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e WATCHTOWER_NOTIFICATIONS=email \
  -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxxxx \
  -e WATCHTOWER_NOTIFICATION_EMAIL_TO=xxxx \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.office365.com \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587 \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxxxxx \
  -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xxxxxxx \
  v2tec/watchtower -i 43200
```

**Comment by Darkheir** [comment]
I'm having the same issue with `smtp.office365.com` too.

**Comment by mnl1121** [comment]
This issue still isn't resolved. Any ideas?

**Comment by Darkheir** [comment]
Maybe the porject should use an external email library instead of  implementing a `sendemail` method on top of the SMTP lib.

This would allow to handle more email functionalities.

**Comment by danielwbn** [comment]
I have the same problem with WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.live.com

**Comment by mnl1121** [comment]
Notification emails work with Gmail, but not Outlook. Please add outlook support!

**Comment by simonaronsson** [comment]
Unsure whether this is still an issue. Could someone please confirm? Thanks! 🙏

**Comment by simonaronsson** [comment]
Closing due to lack of response.

**Comment by Hazy87** [comment]
Yes this is still an issue,

**Comment by mnl1121** [comment]
Can confirm. Still an issue.
________________________________

**Comment by simonaronsson** [comment]
Email handling will be reimplemented as part of the notification overhaul (#264).
I'm not gonna put any effort into solving this bug until that work is completed.

**Comment by zyystudio** [comment]
any update on this?

**Comment by mnl1121** [comment]
> any update on this?
I've been using Gmail ever since and haven't tried outlook. Looks like the notification overhaul has been completed so Outlook may be working now? Have you given it a try?

**Comment by piksel** [comment]
None of the implemented authentication methods in the go stdlib email client are supported by outlook/office365. Tracked upstream in [shoutrrr#334](https://github.com/containrrr/shoutrrr/issues/334).

**Comment by zyystudio** [comment]
> 

Thanks for the update! Any plan to implement?
