### ISSUE TITLE
Will the container be automatically updated in this case?

### ISSUE THREAD

**Issue by wanghai1988** [containrrr/watchtower#211]
For example, when using watchtower to monitor localhost:5000/example:1.0, when I add a example:2.0 to a private repository in localhost:5000, will the container be automatically updated at this time?Or tag must be “latest”？thank you！

**Comment by simonaronsson** [comment]
Thanks for creating an issue!

It will only update the container if the tag you've started the container with changes. For example, if 2.0 were to change, you'd be getting an updated container running the *new* 2.0. If you want it to always use the latest image however, you'd most likely want to set it up against :latest. 

🙏
