### ISSUE TITLE
Restrict update times 

### ISSUE THREAD

**Issue by Southclaws** [containrrr/watchtower#212]
It would be great to configure (via labels) certain containers to only accept updates during certain times of the day. If a new image is downloaded but it's in a container's "active hours" the restart will be deferred until later.

Reason being: I'm planning to use Watchtower to host a small multiplayer game. Now players are usually online in the evening but rarely in the early hours of the morning so this would be a good time to defer updates to.

I did consider setting up a basic API for this but using time seems like a simpler approach for now.

**Comment by dmwyatt** [comment]
I wonder if you could use a cronjob to just start the watchtower container during the acceptable hours for updating.

Not that that solves all the use cases, but maybe a workable interim solution?

**Comment by Jleagle** [comment]
What's wrong with using --schedule to run watchtower in the early hours of the morning?

**Comment by Southclaws** [comment]
Oh I didn't see that when reading the docs.

**Comment by Southclaws** [comment]
I've got another use-case for this, per-container schedule using labels.

Mainly because I have a couple of services that I want updates to propagate to instantly and others that I want to push updates to only in early hours.

**Comment by simonaronsson** [comment]
Duplicate of #97. Closing in favor of that issue.
