### ISSUE TITLE
Customizable Verbosity for Slack Notifications

### ISSUE THREAD

**Issue by iMerica** [containrrr/watchtower#214]
It would be great to do a less noisy version of the Slack notifications.

Instead of this:
```
for container in containers:
   print [stopping|creating]  container ....
```

It would be great to  to summarize this to:

`All containers redeployed with latest image`

**Comment by dbrgn** [comment]
Alternatively, simply bundle the "found new image - stopping - creating - removing" messages into a single message. That would already reduce the "spam" quite significantly, especially when using Mattermost which does not seem to bundle the messages automatially:

![screenshot](https://tmp.dbrgn.ch/screenshots/20180917160143-d5wpfh6z.png)

**Comment by zoispag** [comment]
Ideally allow us to provide a template file (using go template syntax, similar to Alert Manager for Prometheus), to be able to define our own format. That would be extremely useful!

```go
{{ if gt (len .Notifications.Updated) 0 }}
  {{ range .Notifications.Updated }}
    Container {{ .Annotations.container }} was updated with ({{ .Annotations.imageName }}) {{ .Annotations.imageHash }}.
    {{ .Annotations.deletedHash }} has been deleted.
  {{ end }}
{{ end }}
{{ if gt (len .Notifications.Failed) 0 }}
  {{ range .Notifications.Failed }}
    There was a failure: {{ .Annotations.Error }}
  {{ end }}
{{ end }}
```

And I would totally try to implement it and start a new PR, but my golang knowledge is not sufficient.

**Comment by zoispag** [comment]
Bump up!?
Not a low priority for some of us! 😄 

Not bugging though :)

**Comment by simonaronsson** [comment]
I feel you, but I only have so many hours to put into open source each month.

It’s up for grabs though so if anyone want to take a stab at it; feel absolutely free. For now, however, I believe my time is better used elsewhere on the project. 

🙏🏻

**Comment by zoispag** [comment]
Up

**Comment by simonaronsson** [comment]
Closing this issue in favor of #255 which is aimed towards a more generic (ie. not only for slack) solution.
