### ISSUE TITLE
Only check top image layer?

### ISSUE THREAD

**Issue by Jleagle** [containrrr/watchtower#218]
Is it possible to only check the highest image layer? So if i push a new image watchtower will update it but if alpine (which mine extends) updates, it won't.

This means my service will only go down when i change something, not when all the other layers get updated.

Thanks.

**Comment by simonaronsson** [comment]
Thanks for your question.

That's actually already the case. What watchtower is checking is whether the image on dockerhub with the tag you've specified (or latest; if you havent opted for something in particular) has a hash that differs from yours. If not; nothing will happen.
