### ISSUE TITLE
RaspberryPi Support for watchtower ?

### ISSUE THREAD

**Issue by fdattein** [containrrr/watchtower#22]
Any chance to make it compatible with the RPI (arm)?
Thanks,
Franklin

**Comment by SeijiSuenaga** [comment]
There's an ARM port available here: https://hub.docker.com/r/armhfbuild/watchtower/

Note that it's not built from the current code in this repo, so it isn't based on the Ubuntu 14.04 image like the current Dockerfile here is.  (That's a good thing, in my opinion.)

**Comment by stffabi** [comment]
Duplicate with #46

**Comment by stffabi** [comment]
New official armhf builds are now available on [docker hub](https://hub.docker.com/r/v2tec/watchtower/tags/).
