### ISSUE TITLE
Auto update of container doesn't preserve Propagation/IPC mode of /storage

### ISSUE THREAD

**Issue by crypticc1** [containrrr/watchtower#221]
This watchtower has really gotten me out of a bind with keeping my containers up-to-date. However, I have noted that while watchtower was successfully able to update my container for jlesage/crashplan-pro:latest some start property details, Propagation and IpcMode were not identical between old and new containers

Watchtower was started as follows:
`docker run -d   --name watchtower   -v /var/run/docker.sock:/var/run/docker.sock   v2tec/watchtower -i 21600  --no-pull --cleanup`

Export previous config:
`docker container inspect $oldcontainerID > oldconfig`

New container pulled using :
`docker pull jlesage/crashplan-pro `

Export config of the newly updated container:
`docker container inspect $newcontainerID > newconfig`

_Expected result_ :  recreated container using same start config.
_Actual result_ : diff in exported container explainable except for Propagation setting on /share/CASHDEV1_DATA which is the root to allow backups.

See ** highlighted below

**Original**
```
        "HostConfig": {
            "Binds": [
                "/share/CACHEDEV1_DATA:/storage:ro",
                "/share/CACHEDEV1_DATA/Container/crashplan-pro:/config:rw"
            ],
 ...
            **_"IpcMode": "",_**
...

```

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
               **_ "Propagation": "_rprivate"_**
            },
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA/Container/crashplan-pro",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]
```

**New**
```
        "HostConfig": {
            "Binds": [
                "/share/CACHEDEV1_DATA:/storage:ro",
                "/share/CACHEDEV1_DATA/Container/crashplan-pro:/config:rw"
            ],
 ...
            **_"IpcMode": "shareable",_**
...

```

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
                **_ "Propagation": "rslave" _**
            },
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA/Container/crashplan-pro",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]
```

I do not know if this is relevant but I had initially started the container with /share/CACHEDEV1_DATA as read-only to protect the NAS until/unless I need to restore.

`
/storage | /share/CACHEDEV1_DATA | Read

/config | /share/CACHEDEV1_DATA/Container/crashplan-pro | Read/Write
`

Thanks very much.

**Comment by crypticc1** [comment]
I'd love to help but Linux and c isn't my strong point.  Happy to donate

**Comment by Sveeeeeen** [comment]
Issue still exists
