### ISSUE TITLE
[Question] Exclude container

### ISSUE THREAD

**Issue by darox** [containrrr/watchtower#222]
I run a container with the following command, to exclude it from watchtower:

```
sudo docker run \
  --restart=always \
  --net prod-network --ip 172.18.0.109 \
  --name=prod-mqtt-http-api \
  --label=com.centurylinklabs.watchtower.enable=false \
  mqtt-api
```
Is it the right syntax? Because Watchtower still tries to update this image.

**Comment by srinivasrk** [comment]
I would say just ignore the label altogether.

**Comment by mnl1121** [comment]
I'm running into this same problem. Watchtower ignores the label and updates my container. I would also like to know what is wrong.

**Comment by razor109** [comment]
Same problem here. Passing the False lable nut still keeps getting updates.

Any suggestions?

**Comment by mpatton125** [comment]
You have to make sure you set "--label-enable" on the watchtower command line, or label functionality won't work.

**Comment by simonaronsson** [comment]
What @mpatton125 said.
Closing this issue as solved.
