### ISSUE TITLE
Discord option

### ISSUE THREAD

**Issue by MakerTim** [containrrr/watchtower#226]
Hey, my team of opensourcers is using discord instead of slack, would there be an option to have discord integration as addition next to slack?

**Comment by JoyDistelbrink** [comment]
Hi,
Using watchtower slack option with discord webhook and adding "/slack" at the end of the discord webhook should work.
But maybe, you want more customizations.

**Comment by MakerTim** [comment]
could you give an example that works?

**Comment by JoyDistelbrink** [comment]
I'm using docker compose. 
add this in evironment vars
`environment:`
`WATCHTOWER_NOTIFICATIONS: slack`
` WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://discordapp.com/api/webhooks/{{your_discord_hook}}/slack"`

Or with docker look at the [documentation](https://github.com/v2tec/watchtower#notifications-through-slack-webhook) 
just use your discord web hook and add "/slack" at the end of the url

**Comment by Tuumke** [comment]
this is my bash file i use to create watchtower:

```bash
#!/usr/bin/env bash
dockername=watchtower
dockerimage="v2tec/watchtower"
dockernetwork=br_0

docker stop $dockername
docker rm $dockername
docker rmi $dockerimage
docker create \
  --name $dockername \
  --hostname=$dockername \
  --net=$dockernetwork \
  --ip=172.20.0.254 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e WATCHTOWER_NOTIFICATIONS=slack \
  -e WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL="https://discordapp.com/api/webhooks/xxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/slack" \
  v2tec/watchtower \
  --cleanup --notifications-level=info
docker update --restart=always $dockername
docker start $dockername
```
The only thing i really mis, is an option to identify my different watchtowers in discord

**Comment by JoyDistelbrink** [comment]
You can have different webhooks with different pictures to identify the watchtower that is sending notifications. 

It seems that the name will always be 'watchtower',  but the picture is based on your discord weebhook configuration.

**Comment by simonaronsson** [comment]
I believe this issue has been resolved for now. Closing. Feel free to get in touch if the suggested solution doesn’t solve your problem.
