### ISSUE TITLE
Reload certain containers after their config files change?

### ISSUE THREAD

**Issue by adrianocr** [containrrr/watchtower#227]
I run several containers that have config files mapped from the host into the container via a volume. 

I often make changes to those config files on the host and then manually reload the container via `docker restart [container-name]`. I was wondering if this is something that watchtower can do for me automatically? But I am not interested in pulling a new image, just restarting the container. 

Thanks

**Comment by simonaronsson** [comment]
I dont think this is within the scope of what watchtower is trying to solve.
If this is something you'd really need however, feel free to drop a PR and I'll have a look.

Thanks 🙏
