### ISSUE TITLE
Simplify multi-arch Dockerfile with multiarch project

### ISSUE THREAD

**Issue by paulfantom** [containrrr/watchtower#230]
Would you guys be interested in unifying your Dockerfiles into one and still providing multi-arch support? I have recently done that in netdata project and can do the same for you by using https://github.com/multiarch.

Here is netdata Dockerfile and build/release script: https://github.com/netdata/netdata/tree/master/docker. It is a bit complicated, but that's not due to project requirements not due to multi-arch support.

Let me know if you want me to start working on this.

**Comment by simonaronsson** [comment]
Our dockerfiles are all the same at the moment, so it's not really an issue. However, we should probably slim it down into one single file sometime soon. Feel free to have a stab on it and send in a PR. Thanks!
