### ISSUE TITLE
Pulling & updating containers doesn't work

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#232]
Watchtower cannot pull an image when it's updated:
```
time="2018-09-27T14:05:24+03:00" level=debug msg="Error pulling image XXX:test@sha256:47f6cc76f727b36cb888568c06103e343e37e844bac32f1b0d8b81bc16c0cf2d, Error response from daemon: manifest for XXX@sha256:47f6cc76f727b36cb888568c06103e343e37e844bac32f1b0d8b81bc16c0cf2d not found" 
time="2018-09-27T14:05:24+03:00" level=info msg="Unable to update container XXX/test_app.1.lu4rygd1y01pqvw5zjeh4fxsa, err='Error response from daemon: manifest for XXX@sha256:47f6cc76f727b36cb888568c06103e343e37e844bac32f1b0d8b81bc16c0cf2d not found'. Proceeding to next." 
```

The shasum in the log message doesn't even exist.

**Comment by simonaronsson** [comment]
Hi!

Thanks for creating an issue!

We need more information to be able to help you.

- What command are you using to launch  the container you want watchtower to update?
- What command are you using to launch watchtower itself?
- Are you using docker-compose? If so, please paste relevant parts of your config in a code block.

**Comment by simonaronsson** [comment]
Closing due to lack of response.
