### ISSUE TITLE
32-bit armv7l incompatible image

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#234]
I am getting the following error code while running the following docker command.
I think this problem comes from an incompatibility issue within watchtower.
Please give me an update about how we, as a community can fix this problem.
```
#!/bin/sh
docker run -d \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower:armhf
```
**standard_init_linux.go:190: exec user process caused "exec format error"**

```
root@orange:# uname -a
Linux orange 4.14.70-sunxi #265 SMP Wed Sep 19 10:01:19 CEST 2018 armv7l armv7l armv7l
GNU/Linux
```
```
root@orange:# arch
armv7l
```
```
root@orange:# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:34:27 2018
 OS/Arch:           linux/arm
 Experimental:      false
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:30:10 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

**Comment by grewhit25** [comment]
Try using tag: armhf-latest

I.e v2tec/watchtower:armhf-latest

**Comment by ghost** [comment]
Thanks for the quick reply @grewhit25 
Got it working now. Can you tell me where I can find these tags?

**Comment by grewhit25** [comment]
You find it under docker hub [v2tec/watchtower](https://hub.docker.com/r/v2tec/watchtower/tags/) registry tags
