### ISSUE TITLE
Synology Task Scheduler - Why not just "on Boot"

### ISSUE THREAD

**Issue by restalfep** [containrrr/watchtower#238]
For the wiki I see it says to create the task for sudo ln -s /var/run/docker.sock /volume1/docker/docker.sock and run it every 1 hour. Couldn't we just run it on Boot instead by selecting "Triggered Task" then "on boot" and then put sudo ln -s /var/run/docker.sock /volume1/docker/docker.sock in there?

**Comment by diamondsw** [comment]
Agreed that running on boot should be all that is required (I have similar links created at boot). To add to this, the task should run as root and omit the sudo, as sudo will request a password.

**Comment by niXta1** [comment]
Some other (qnap?) NAS can't/have a problem with start on boot. Synology does not have that problem, and there is no need to run it at an interval.
It is more of a general NAS solution.

**Comment by simonaronsson** [comment]
This seem more like a question regarding the Synology NAS than watchtower. Closing this issue as I'm afraid I can't help much here. Maybe https://stackoverflow.com would be a better arena for this question?

**Comment by restalfep** [comment]
I asked here since it was in your wiki https://github.com/containrrr/watchtower/wiki/Synology-DSM-Installation-Guide.

Step IV

I changed it to on boot though and been working well. Thanks for the great program.
