### ISSUE TITLE
Extra notification info

### ISSUE THREAD

**Issue by Jacobh2** [containrrr/watchtower#239]
Hey!

I'm right now using msteams to get notifications from my watchtower instances using `WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA=true`, working really nicely!

But I realised a limitation: I'm not able to know from which host the notification is coming from, so for some messages it tells me for example that it has problems reaching the image repository, but from the notifications alone I'm not able to pinpoint which device it is that is having this issue.

Would it be possible to customise what info is being sent? For example to add the hostname would solve it for my use-case!

**Comment by darknode** [comment]
Hi!
As for me it's relevant feature, but keep in mind that watchtower used to work inside docker container, so in this case docker argument `--hostname` should be added: `docker .... --hostname watchtower1 ....` to set some useful value. Also I would add and enable this feature with flag like  `WATCHTOWER_NOTIFICATIONS_USE_HOSTNAME`. If it's ok, I'll try to implement it.

**Comment by Jacobh2** [comment]
The ability to set hostname and for watchtower to also send that would completely solve my use case! Either that we can set the hostname using the flag you name, or that it uses the hostname of the docker container (which can be customized with `--hostname`) 

Today I'm using the "use log" flag, which is still nice, just not verbose enough since it lacks the hostname. If these flags could be used together that would be great!

**Comment by Jacobh2** [comment]
Another version of this is if there should be a flag to also include the hostname in all the logs as a prefix. That way it will also show in the logs where it's from! And since the logs are already being sent to msteams, all the nessecary information will be there!

**Comment by simonaronsson** [comment]
This issue will be merged with #264
