### ISSUE TITLE
add DOCKER_HOST can not run   

### ISSUE THREAD

**Issue by SuperXFan** [containrrr/watchtower#243]
mine run:
```docker run -d --name watchtower --rm -v /var/run/docker.sock:/var/run/docker.sock --env DOCKER_HOST="tcp://192.168.3.13:5000"  --env REPO_USER="pi" --env REPO_PASS="123456" v2tec/watchtower:armhf-latest --interval 30```

docker ps  &&  docker ps -a     can not  show  watchtower. i have to remove --env DOCKER_HOST="tcp://192.168.3.13:5000"?

**Comment by simonaronsson** [comment]
Thanks for creating an issue!

You shouldn't have to specify both docker.sock and a docker host. Could you please try the command below? The watchtower container will still be created on the docker host you're currently running the command on, however it will connect and perform updates on the host you've specified in as your `--host` argument.

```
docker run -d \
  --name watchtower \
  --rm \
  --env REPO_USER="pi" \
  --env REPO_PASS="123456" \
  containrr/watchtower:armhf-latest \
  --interval 30 \
  --host tcp://192.168.3.13:5000
```

🙏

**Comment by simonaronsson** [comment]
Closing due to lack of response.
