### ISSUE TITLE
Repo Status?

### ISSUE THREAD

**Issue by nightah** [containrrr/watchtower#246]
@stffabi just wondering on an official word regarding status of this repository.

Firstly I would like to say that I appreciate all you've done for us so far, so please don't take this the wrong way. 

I haven't seen any commits since March and not much involvement around merging PRs. I understand that things can get very busy in real life and sometimes we don't get as much chance as we would like to, for working on FOSS.

Having said that, do any of the contributors have access to perform activities in your stead? If not, are you willing to give anybody access to maintain the repo?

I hope all is well and that you are okay. Thanks again for this fantastic piece of software!

**Comment by niXta1** [comment]
The last sign of movement: https://github.com/v2tec/watchtower/issues/169

This container is way too good and useful to die :(

**Comment by circa10a** [comment]
Not bashing watchtower at all. It's great, but for anybody looking for another solution, I've recreated most of watchtower's functionality, but in python. https://github.com/circa10a/ouroboros

**Comment by nightah** [comment]
It's likely at this rate that we might need to start looking for alternatives, I hope @stffabi is okay.

Thanks @circa10a for the alternative, some nice additional features in Ouroboros, will track to try out once you're at feature parity.

**Comment by niXta1** [comment]
Ouroboros seems great except for email/notifications.
Another alternative is this fork with all good commits included: https://hub.docker.com/r/svengo/watchtower/

**Comment by circa10a** [comment]
@niXta1 Webhook/Slack notifications were recently added

**Comment by KopfKrieg** [comment]
> Another alternative is this fork with all good commits included: https://hub.docker.com/r/svengo/watchtower/

Oh, that's nice.

Since nothing happened here for 10 months now, maybe we should fork the project (and include multiple maintainers)?

**Comment by circa10a** [comment]
@nightah
We've reached full feature parity with watchtower and then some!

**Comment by KopfKrieg** [comment]
Just wanted to let you know I've forked the project and I'm currently trying to apply some of the pull requests. If anyone wants to join, feel free to create pull requests. Also, if anyone has more experience than me with docker hub, I'd be glad if someone could help me (even though autobuilds are now working).

Also, a co-maintainer would be nice, you know why.

Links:
 - https://github.com/kopfkrieg/watchtower
-  https://hub.docker.com/r/kopfkrieg/watchtower

**Comment by simonaronsson** [comment]
The project is now actively maintained again. All help is appreciated. I hope @KopfKrieg would like to join us here as well. I'm not bashing at the progress of @circa10a and Ouroboros or anything, but this project wont be archived just yet 👍 😃

**Comment by simonaronsson** [comment]
I'm currently in the process of going through all active issues and pull requests.
