### ISSUE TITLE
Error response from daemon trying to update or reinstall

### ISSUE THREAD

**Issue by wikkixwikki** [containrrr/watchtower#249]
getting error when trying to reinstall. While it was installed i was getting the same error when it would try to run and update other containers. 

sudo docker run -d \
>   --name watchtower \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   v2tec/watchtower
Unable to find image 'v2tec/watchtower:latest' locally
latest: Pulling from v2tec/watchtower
a5415f98d52c: Pull complete
c3f7208ad77c: Pull complete
169c1e589d74: Pull complete
docker: error pulling image configuration: Get https://registry-1.docker.io/v2/v2tec/watchtower/blobs/sha256:3069a9fb302acfc664970a4cdb962b9915f15aeb089b6216f17edcd29d5dfc80: net/http: TLS handshake timeout.
See 'docker run --help'.
devin@efcinema:/docker/varken$ sudo docker run -d   --name watchtower   -v /var/run/docker.sock:/var/run/docker.sock   v2tec/watchtower
Unable to find image 'v2tec/watchtower:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/v2tec/watchtower/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Av2tec%2Fwatchtower%3Apull&service=registry.docker.io: net/http: TLS handshake timeout.
See 'docker run --help'.

**Comment by gnumoksha** [comment]
The same error here. This is happening since I've installed Watchtower.

**Comment by simonaronsson** [comment]
Cannot reproduce. Try again with containrrr/watchtower and let me know if the problem remains. My first thought is that this might be related to date/time sync issues on the docker host.

🙏
