### ISSUE TITLE
Watchtower not compatible with raspberry pi 3 B+

### ISSUE THREAD

**Issue by jmbegley** [containrrr/watchtower#251]
Hi,

Would it be possible to add aarch64 support to watchtower? I have a raspberry pi 3B+ (running fedora), and unfortunately watchtower isnt compatible with this hardware :(

Many thanks,
James

**Comment by JasonSwindle** [comment]
Try `v2tec/watchtower:armhf-latest`

**Comment by apveening** [comment]
I have talmai/rpi-watchtower running on a Pi 3B+ (running Armbian, it started as a NAS project). As an alternative, I can recommend pyouroboros/ouroboros. 

Small caveat: Neither product retains the IP address of the container in the upgrade, something of a hazzle as two of the containers are Pi-Hole and and Unbound recursive DNS server, which both need to be available at specifice IP addresses.

EDIT:
Just tested (CLI with Putty) and the following works fine:
docker run -d \
    --name watchtower \
    --restart always \
    --network host \
    -v /var/run/docker.sock:/var/run/docker.sock \
    v2tec/watchtower:armhf-latest -i 43200

**Comment by SuperSandro2000** [comment]
@jmbegley build this on the pi https://github.com/v2tec/watchtower/blob/master/dockerfile/arm64v8/Dockerfile

**Comment by grewhit25** [comment]
@jmbegley that Dockerfile won't work on the pi because it just copy in watchtower source for a different platform.

Try the Dockerfile below, build the image on your Pi 3B+ or any platform you wish to run the image on.

```Dockerfile
FROM golang:alpine as builder
RUN apk update && apk add  alpine-sdk ca-certificates tzdata
RUN curl https://glide.sh/get | sh
RUN go get -v github.com/v2tec/watchtower
WORKDIR /go/src/github.com/v2tec/watchtower
RUN glide install
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM scratch
LABEL "com.centurylinklabs.watchtower"="true"
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /go/src/github.com/v2tec/watchtower/watchtower /watchtower

ENTRYPOINT ["/watchtower"]
```

**Comment by SuperSandro2000** [comment]
@grewhit25 I am going to save that for when I get my ubuntu arm64 to build.

**Comment by grewhit25** [comment]
@SuperSandro2000 OK, it appears that Watchtower is being actively maintained so you might be interested in this [python-based alternative to watchtower](https://hub.docker.com/r/pyouroboros/ouroboros) which has multi-arch support for arm32 and arm64 platforms.

**Comment by apveening** [comment]
@grewhit25 Please see my post of six days ago, I (still) recommend ouroboros and the self-updating ability is very nice.

**Comment by grewhit25** [comment]
@apveening thanks I’ve noted your post. I have actually already made the switch to that product.

**Comment by simonaronsson** [comment]
This project is now actively maintained again. Closing this question however as you seem to have gotten the answers you needed. In case you need anything else, feel free to open a new issue.
