### ISSUE TITLE
Everything down !

### ISSUE THREAD

**Issue by lowrisk75** [containrrr/watchtower#254]
So I installed watchover:

```
  docker run -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    centurylink/watchtower \
    --interval 82800 \
    --cleanup
```

my other docker was removed, then back and start again, but nothing would work anymore.

PiHole is down, sonar/radar/jacket is down, Iperf is down.

**Comment by simonaronsson** [comment]
What do the logs say? Please attached the log of the watchtower container, preferably using the —debug switch.

**Comment by simonaronsson** [comment]
In case this is still an issue for you and you'd like to collaborate on a solution, feel free to get in touch again. Otherwise, this issue will now be closed.
