### ISSUE TITLE
Google Hangouts Chat notifications support

### ISSUE THREAD

**Issue by erseco** [containrrr/watchtower#261]
Would be nice add support to Google Hangouts Chat room notification, can be really similar to Slack webhooks, here there is some documentation about: 
https://developers.google.com/hangouts/chat/how-tos/webhooks

**Comment by simonaronsson** [comment]
This issue will be merged with #264, which focuses on notifications in general.
However, as I do not have any experience of using pushover, all help possible would be appreciated.
