### ISSUE TITLE
Manually triggering Watchtower to check for updates outside of normal interval?

### ISSUE THREAD

**Issue by deten** [containrrr/watchtower#262]
Hi Guys,

I am trying to figure out if there is a way to trigger watchtower outside of the normal interval I set up.  One of my containers was updated but its actually a flawed update and it isnt working right now.  The image was updated again but it waits about 10 days to recheck.  In the mean time I wanted to see if I could send a command to watchtower to check now instead of waiting another 9 days.

Thanks

**Comment by simonaronsson** [comment]
The easiest solution would likely be to just restart the watchtower container.

**Comment by simonaronsson** [comment]
I've now merged the commit adding the ability to --run-once. See the readme for a suggested solution.
