### ISSUE TITLE
[Fork available] This project have been abandoned for quite a while now.

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#263]
I've managed to get a hold of Brian DeHamer, who was one of the original developers. Unfortunately, he doesn't have any access to the repository. As I've been unable to get hold of anyone with write access to the repo I've continued per Brians suggestion and forked the repo.

So, until development is continued in this repo or I've been able to get access to the repo; a fork will be available on https://github.com/containerized/watchtower where development will (hopefully) be continued. All submissions, suggestions and help is welcome to keep the forked project up and running.

Thanks,
Simon

**Comment by simonaronsson** [comment]
Much love to the original developers for their great effort with creating such a great product.

**Comment by stffabi** [comment]
My deepest apologize to the community for not being able to keep the project maintained and alive. I currently have very little spare time for keeping the project maintained.

I really like people are still very interested in the project. So if you @simskij are interested in keeping the development continued and the project alive, I could transfer the repo over to  https://github.com/containerized/ so you have all the PRs and issues there...

**Comment by simonaronsson** [comment]
Thanks! That would be great. I'll go ahead and kill off my repo so you'll be able to transfer it.

And thanks again for the awesome job you've done!

**Comment by simonaronsson** [comment]
Could you please make sure I get any needed dockerhub and circleci credentials as well? You can reach me at simme<at>0x12b.com

**Comment by stffabi** [comment]
Great thanks for keeping the project alive, that's really awesome. I'll transfer during about the next hour.

Regarding credentials, there aren't any npm credentials needed. For CircleCI is the easiest whe you are going to link your `containerized` organization to it as soon as the repo is transferred. Then you could also publish it to your docker hub account. Then in CircleCI you could add the following env variables: `DOCKER_USER`, `DOCKER_PASS` and a github token in `GITHUB_TOKEN` for go releaser to publish the releases to github.

**Comment by stffabi** [comment]
We can discuss the details via mail for setting up the build-process.
