### ISSUE TITLE
Additional notification options

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#264]
Moving this discussion to a [issue in shoutrrr](https://github.com/containrrr/shoutrrr/issues/2).

Thanks for understanding! 🙏

**Comment by Codelica** [comment]
I like it, just wish Pushover were higher.  😇 I can help test that and Webhooks when the time comes.

Also for Webhooks please consider header support if possible, for Bearer authentication.

**Comment by simonaronsson** [comment]
Lets move it up a bit then :)

**Comment by simonaronsson** [comment]
These will be solved by replacing the current notification implementation with another project I'm working on; [containrrr/shoutrrrr](https://github.com/containrrr/shoutrrr). Whether or not this will be in 0.4.0 or in a later release is not yet written in stone and depends a lot on whether im doing it by myself or with help. 😄

**Comment by simonaronsson** [comment]
Discord, telegram, slack and pushover are all implemented in shoutrrr as of [5314ee954ba8dbc1c6eb6cbde310af695c8ae1da](https://github.com/containrrr/shoutrrr/commit/5314ee954ba8dbc1c6eb6cbde310af695c8ae1da). Will implement a couple more before i'll even attempt integrating it.

**Comment by Codelica** [comment]
FWIW... I'm no Go expert, but I did made a little test run using a Pushover URL in Shoutrrr and it worked fine.  :)

**Comment by somq** [comment]
Just to say, HTTP webhook is a killer feature imo.

**Comment by MAGICCC** [comment]
Neat, so we should wait until the shoutrrr code is in watchtower to use Telegram notifications?

**Comment by simonaronsson** [comment]
Yeah. Feel free to help out though if you want it to happen sooner rather than later! :-)

**Comment by alexanderadam** [comment]
Just to be sure: would it be possible to integrate more than one service with [shoutrrr](https://github.com/containrrr/shoutrrr#as-a-package)?
So i.e. to have notifications via email, XMPP and Sentry **at the same time**?

**Comment by simonaronsson** [comment]
> Just to be sure: would it be possible to integrate more than one service with [shoutrrr](https://github.com/containrrr/shoutrrr#as-a-package)?
> So i.e. to have notifications via email, XMPP and Sentry **at the same time**?

yeah, that's our thought exactly! 👍 we've not really decided on how to do this in the case of watchtower, but yes - that will be possible in a general.

**Comment by noplanman** [comment]
Just voicing my interest in the Telegram notifications. From the comments above it seems the wait is due to shoutrrr not being used in watchtower just yet.

What's the progress on that?

**Comment by simonaronsson** [comment]
#405 should be taken into consideration when migrating to shoutrrr.

**Comment by deadmerc** [comment]
Hey guys, maybe like for temporary solution `identifier` will be append to message?
`server-name-1: Starting Watchtower and scheduling first run:...`

**Comment by davtur19** [comment]
Are there updates for notifications on Telegram?

**Comment by simonaronsson** [comment]
Unfortunately not. I've not had any time to work on switching the current notification module to shoutrrr.

**Comment by tcurdt** [comment]
@simskij how much work to you suspect this will be? I haven't looked at the code at all, but are also craving for telegram and webhook support.

**Comment by davtur19** [comment]
[Telegram's Bot API](https://core.telegram.org/bots/api) are very simple to use, but I don't know how to implement it since I don't know Go

For example to send a message (It also works with POST):
`https://api.telegram.org/botTOKEN/sendMessage?chat_id=ID&text=TEXT`

**Comment by mbrandau** [comment]
> [Telegram's Bot API](https://core.telegram.org/bots/api) are very simple to use, but I don't know how to implement it since I don't know Go
> 
> For example to send a message (It also works with POST):
> `https://api.telegram.org/botTOKEN/sendMessage?chat_id=ID&text=TEXT`

@davtur19 Telegram seems to be implemented already. https://github.com/containrrr/shoutrrr/issues/2

**Comment by davtur19** [comment]
@mbrandau yes, but has not yet been implemented/documented in
watchtower

**Comment by tcurdt** [comment]
@davtur19 the problem is that watchtower needs to move to use shoutrrr and that's not been done yet.

**Comment by mbrandau** [comment]
I will try to add shoutrrr as another notification type. WIP PR coming in soon. I have no experience in Go though 🙃

**Comment by simonaronsson** [comment]
No better time to learn a new programming language than during quarantine! 😅

**Comment by mbrandau** [comment]
One feature I’m missing while testing the new notifications on latest-dev is to disable the timestamps. Since I think most of the services show timestamps anyway, I think there should be an option to disable and/or format them in watchtower.

**Comment by arnested** [comment]
Agree, @mbrandau.

The combination of timestamp, level and message doesn't really help on readability.

Maybe an environment variable with a template string to use?

**Comment by simonaronsson** [comment]
Shoutrrr support will be included in the next release. It's already been merged to master, so I will go ahead and close this issue now. 🎉  Thank you so much everyone for your contributions!
