### ISSUE TITLE
cant update container jellyfin

### ISSUE THREAD

**Issue by icf20** [containrrr/watchtower#269]
for some odd reason watchtower cant update  https://github.com/jellyfin/jellyfin container 

i dont know if is your issue or theirs :face_with_head_bandage:

**Comment by simonaronsson** [comment]
Hi!

Thanks for creating an issue!
Could you please provide some more details?

Please paste how you are currently launching both jellyfin and watchtower.
Additionally, please start watchtower with the --debug flag and paste any output in the issue in a code block.

Thanks,
Simon

**Comment by icf20** [comment]
> Please paste how you are currently launching both jellyfin and watchtower.

is the default way 

i cant send you any debug for this issue now because last update for watchtower results into dead state

**Comment by simonaronsson** [comment]
this problem relates to issue #269

**Comment by icf20** [comment]
my bad please ignore

```
level=debug msg="Pulling jellyfin/jellyfin:latest for /jellyfin"
time="2019-04-06T12:02:02+02:00" level=debug msg="No credentials for jellyfin in /config.json"
time="2019-04-06T12:02:02+02:00" level=debug msg="No authentication credentials found for jellyfin/jellyfin:latest"
time="2019-04-06T12:02:03+02:00" level=debug msg="No new images found for /jellyfin"
```

**Comment by simonaronsson** [comment]
No worries, thanks for letting us now!
