### ISSUE TITLE
Multi Arch Builds

### ISSUE THREAD

**Issue by thelamer** [containrrr/watchtower#274]
I have the logic layed out in travis-ci for building and pushing armhf,arm64, and x86_64 builds of watchtower with a manifest so users can just use the :latest tag across different hardware. 

https://github.com/Taisun-Docker/updater/blob/master/.travis.yml
https://github.com/Taisun-Docker/updater/blob/master/Dockerfile.amd64
https://github.com/Taisun-Docker/updater/blob/master/Dockerfile.armhf
https://github.com/Taisun-Docker/updater/blob/master/Dockerfile.aarch64

This was all out of necessity to provide Taisun and Linuxserver.io users an easy to use command to upgrade their containers without having a watch concept. 

I do not know circle well, but it does not look like you are currently using them for your CD pipeline just CI. 

At a minimum if armhf,arm64, and amd64 manifested dockerhub endpoints are available we can swap to recommending our users run the `taisun/updater` method as it is a static fork and start using watchtower with the --run-once flag. 

Given the ease of cross compilation it might also be prudent to add other arches to this manifest list (powerpc etc).

**Comment by simonaronsson** [comment]
Hey!

Thanks for opening a ticket. Im not sure I understand what you are asking here, so feel free to elaborate in case I got it wrong. :D

Right now, we’re building arm64v8, armhf, amd64 and i386 images. This is done both for CI and CD. However, only pushed to dockerhub during CD.

Looking at our current available images I see the arm alternatives as well, though not taggad with a -latest suffix. Is that the part you’re missing? Pulling for exempel containrrr/watchtower:0.3.2 should in other words already work.

🙌🏻

**Comment by thelamer** [comment]
Ahh this new endpoint does not even show up in searches yet. I was basing off the v2tech that has not been updated in a year.

**Comment by thelamer** [comment]
@simskij Re-opening this issue as it boils down to leveraging Docker Manifests, you have tags available for armhf and arm64v8 but when you pull latest or 0.3.1 you get the x86 variant. 

Check out the difference of these commands: 

```
docker manifest inspect taisun/updater:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 948,
         "digest": "sha256:006c11a486ba0829498bb1ef7cb00547ad16c6034a3fa93b3015da37b999668c",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 948,
         "digest": "sha256:e38d3396e48c73ec54df8f64768bbd2e27453a8cde766f1107f85a1892f8208a",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 948,
         "digest": "sha256:d775f179f6e1ee6177ac4fe79289f52dc2343fd5384da68ca3b642999ccd3c08",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```
```
docker manifest inspect containrrr/watchtower:latest
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 2396,
		"digest": "sha256:a5a429658e9e194351f45c4d102442a125c1544366b1f9af8dc8d0cf45525e09"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 132019,
			"digest": "sha256:bbbdad0af5a49063709c89ed4058bb260aab4088ac24743ad724434c80859fe0"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 329258,
			"digest": "sha256:3e76a767ab3a92ab43b6da3ff3ff11c81eb2efc7a69fdef73d4431172231808f"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 4316910,
			"digest": "sha256:1ec9119220cd90a2835dee9f65bdc095d6dc1eb5295614a0e29bb9ff9feaa326"
		}
	]
}
```
As I say the logic for pushing a manifested endpoint is here: 

https://github.com/Taisun-Docker/updater/blob/master/.travis.yml

I am not entirely sure how to apply this type of logic to circle as it does use beta features of the docker client. (for pushing the pulling has been baked in for years now)

**Comment by simonaronsson** [comment]
Thanks! I see what you mean now. I've looked through your travis files and you should be able to do the same annotation shennanigans, ie:
```
        # Generate local manifests for latest and at commit
        - docker manifest create ${DOCKERHUB_LIVE}:latest ${DOCKERHUB_LIVE}:amd64-latest ${DOCKERHUB_LIVE}:arm32v6-latest ${DOCKERHUB_LIVE}:arm64v8-latest
        - docker manifest annotate ${DOCKERHUB_LIVE}:latest ${DOCKERHUB_LIVE}:arm32v6-latest --os linux --arch arm
        - docker manifest annotate ${DOCKERHUB_LIVE}:latest ${DOCKERHUB_LIVE}:arm64v8-latest --os linux --arch arm64 --variant v8
        - docker manifest create ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT} ${DOCKERHUB_LIVE}:amd64-${TRAVIS_COMMIT} ${DOCKERHUB_LIVE}:arm32v6-${TRAVIS_COMMIT} ${DOCKERHUB_LIVE}:arm64v8-${TRAVIS_COMMIT}
        - docker manifest annotate ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT} ${DOCKERHUB_LIVE}:arm32v6-${TRAVIS_COMMIT} --os linux --arch arm
        - docker manifest annotate ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT} ${DOCKERHUB_LIVE}:arm64v8-${TRAVIS_COMMIT} --os linux --arch arm64 --variant v8
        # Push the manifests to these meta tags
        - docker manifest push ${DOCKERHUB_LIVE}:latest
        - docker manifest push ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT}
```
with circleci as subsequent run commands [here](https://github.com/containrrr/watchtower/blob/1f9099770b25b26b66bef355f4d66dda492db06f/.circleci/config.yml#L96). Feel free to give it a try. I'd be happy to review your changes and help you in getting it to work. 👍 

Thanks again,
Simon

🙏
