### ISSUE TITLE
Watchtower config file?

### ISSUE THREAD

**Issue by ookla-ariel-ride** [containrrr/watchtower#276]
Could a feature be added to Watchtower to allow it load runtime arguments from a config file?  I'd like this to be something we can put on the host filesystem so that it would be very easy to change runtime arguments (especially for new features being added, like additional notification agents, turning on debug, etc.) and simply restart the container to load the new config.

**Comment by simonaronsson** [comment]
It could! If you want, feel free to create a pull request and I'll have a look at it and provide you with feedback. 👍

**Comment by simonaronsson** [comment]
Closing due to lack of response
