### ISSUE TITLE
--tlsverify not working

### ISSUE THREAD

**Issue by wzv5** [containrrr/watchtower#277]
```
$ docker run -it --rm \
  -v /c/Users/<username>/.docker/machine/machines/default:/etc/ssl/docker \
  containrrr/watchtower \
  --host tcp://<ip>:2376 \
  --tlsverify \
  --debug

DEBU[0000] Retrieving running containers
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
FATA[0000] Get http://<ip>:2376/v1.24/containers/json?limit=0: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
```

**Environment**
 - Platform: Windows 10, VirtualBox driver
 - Architecture: x64
 - Docker version: 18.09.3

**Additional context**
When I using `-e DOCKER_CERT_PATH=/etc/ssl/docker`, it is working well.
```
$ docker run -it --rm \
  -v /c/Users/<username>/.docker/machine/machines/default:/etc/ssl/docker \
  -e DOCKER_CERT_PATH=/etc/ssl/docker
  containrrr/watchtower \
  --host tcp://<ip>:2376 \
  --tlsverify \
  --debug

DEBU[0000] Retrieving running containers
DEBU[0000] Checking if /compassionate_swartz is a watchtower instance.
...
```

**Comment by simonaronsson** [comment]
Thanks for your report!

Seeing as the instruction in the readme specifically says to do as you've done in your "Additional context" example, I fail to see how this is a bug. Am I missing something? 😄

From the readme:
> The directory containing the certificates for the remote host needs to be mounted into the watchtower container at /etc/ssl/docker. With the certificates mounted into the watchtower container you need to specify the --tlsverify flag to enable verification of the certificate:
```
docker run -d \
  --name watchtower \
  -e DOCKER_HOST=$DOCKER_HOST \
  -v $DOCKER_CERT_PATH:/etc/ssl/docker \
  containrrr/watchtower --tlsverify
```

🙏

**Comment by wzv5** [comment]
First, in Windows, `$DOCKER_CERT_PATH` is `C:\Users\...\.docker\machine\machines\default`, it must be converted to `/c/Users/.../.docker/machine/machines/default`.

And as you said:
```
$ docker run -it --rm \
  -e DOCKER_HOST=%DOCKER_HOST% \
  -v /c/Users/.../.docker/machine/machines/default:/etc/ssl/docker \
  containrrr/watchtower --tlsverify

FATA[0000] Get http://192.168.99.106:2376/v1.24/containers/json?limit=0: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
```
The problem remains.

So it's necessary to pass `-e DOCKER_CERT_PATH=/etc/ssl/docker`, and it is not included in the readme.

**Comment by simonaronsson** [comment]
I've been digging through the moby repo trying to find out what you might have encountered, as we only forward this param to the docker engine-api.

 [This part of client/options.go](https://github.com/moby/moby/blob/ad9362bb1567da92096ed3d74968bf3feb643fce/client/options.go#L27) as well as [this part of request.go](https://github.com/moby/moby/blob/5635c2a49870332b8d8a7ee912558fd64cece1a6/client/request.go#L135) caught my attention.

Judging from those parts, you'll have to specify the path yourself; just as you said.
I'll go ahead and add that to the readme.

Thanks for your report!
