### ISSUE TITLE
Allow logging output to use JSON formatter

### ISSUE THREAD

**Issue by warmfusion** [containrrr/watchtower#28]
We use FluentD to collate logs from our containers automatically.

It'd be useful if the watchtower logging could use the logrus JSON formatter built into its library;

```
log.SetFormatter(&log.JSONFormatter{})
```

**Comment by simonaronsson** [comment]
If this is still something you'd like to have added, feel free to get back with a pull request and i'll make sure to review it as soon as possible. Until then, closing the issue due to lack of activity.
