### ISSUE TITLE
Execute command inside container after update

### ISSUE THREAD

**Issue by Redsandro** [containrrr/watchtower#286]
**Is your feature request related to a problem? Please describe.**

The GitLab CE docker container [does not include sendmail](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2630#note_117675596). You can manually install it, but when watchtower updates `gitlab/gitlab-ce:latest`, it is gone again.

**Describe the solution you'd like**

It would be convenient if a configurable command or script could be run on a specific container that has watchtower enabled. In this specific case, I need to execute the following after every update:

```
docker exec -t gitlab_gitlab_1 apt update
docker exec -t gitlab_gitlab_1 apt install -y sendmail
docker exec -t gitlab_gitlab_1 service sendmail start
```

**Describe alternatives you've considered**

I'm running a cron-job that checks every now and then if the sendmail package is installed, and if not, install it. However there is a delay between the watchtower run and the cron task. Also, this is external and needs to be memorized by the sysadmin. If you move `docker-compose.yml` to a different directory, the container name changes after reboot. The cron job will not find the container.

**Additional context**

This is partially similar to #183. However, this issue does not require a script to run externally, e.g. access external/local volumes, nor require pre-update steps. We would just need a facility to execute some simple commands _on the container_.

**Comment by KopfKrieg** [comment]
I'm against this. The usual method is to build a container that already contains sendmail. Running apt within a container is, in general, a bad idea.

IMHO the same applies to issue #183. Updating databases is not what watchtower should do. We've got tags to make sure we pull only compatible images, everything else can be manually (and should! Someone should test it before rolling out major changes).

**Comment by Redsandro** [comment]
> The usual method is to build a container that already contains sendmail.

Be that as it may, `gitlab-ce` builds containers _without_ `sendmail`. I'm not sure personal container building etiquette is relevant here.

**Comment by simonaronsson** [comment]
@Redsandro it might be, if personal container building etiquette isn't aligned with the common practices of the community - as this project is meant to be useful for the majority of the user pool. i think what kopfkrieg is saying, is that you should wrap the gitlab-ce container with your own Dockerfile, adding sendmail using a `RUN` command. 

@KopfKrieg I don't have that strong feelings in either direction. Alot of solid work seems to have gone into #197. feel free to decide on this one. However, if this isn't something we're looking to add to watchtower, this should close both #286 and #183, as well as PR #197.

**Comment by Redsandro** [comment]
@simskij said:

> you should wrap the gitlab-ce container with your own Dockerfile, adding sendmail using a RUN command.

Doesn't this defeat the purpose of watchtower? `gitlab-ce` has daily updates. Or are you saying watchtower can build a specified Dockerfile when an upstream update was detected?

**Comment by KopfKrieg** [comment]
@simskij Thanks, that's what I was trying to say. Building a custom container with sendmail is what I'd do, even if it's just adding a single argument to the Docker build file.

@Redsandro As far as I understand the philosophy behind Docker, containers shouldn't be used like virtual machines. We don't install packages in a container, we build containers that already include those packages (which can easily be automated). Running a package manager within a container defeats (from my point of view) the whole use case of a container.

On the other hand … I don't feel comfortable with closing #197. I don't think it's a valid use case (neither the problem here nor the problem described in #197), but if someone provides a PR, sure, why not? If someone really has to execute a command after a container upgrade (or before, and I'm sure somewhere there's a valid use case where this functionality is absolutely necessary), then why shouldn't watchtower include that?

I'd leave this issue open until PR #197 gets merged (or, as alternative, mark this as duplicate of #183).

**Comment by simonaronsson** [comment]
@KopfKrieg thanks for weighing in. in that case, i'll continue going through that PR. 👍

**Comment by Redsandro** [comment]
Thank you for clarifying. 

I understand your position. I think though that it is a bit too strict.

> Running a package manager within a container defeats (..) the whole use case of a container.

It is _"not ideal"_ at worst. The end result is the same, but the (minimal) layer is generated directly on the server while the updated image is already running/serving, in stead of having a polling infra watching upstream building a custom image to the cloud and downloading it to the server. I understand the concept of containers, and they are great for packaging complex services. However, forcing the design pattern where a simple one-liner suffices contrives complexity that needs to be maintained.

I'll take a look at the proposed implementation of #183, and see if it would work in this case.

**Comment by KopfKrieg** [comment]
Yeah, it might be a bit strict.

> but the (minimal) layer is generated directly on the server while the updated image is already running/serving

Sure, but you have to do this on every single instance. That's what bothers me.

> in stead of having a polling infra watching upstream building a custom image to the cloud and downloading it to the server.

That depends on your update strategy. I only update once a day, some services only get updated once a week. So I'd have to build new images only a few minutes before the update on the server happens.

**Comment by unstephenk** [comment]
So are we able to run custom exec commands when the new container has been retrieved?
