### ISSUE TITLE
Logger not working through multiprocessing Process

### ISSUE THREAD

**Issue by victorjabur** [containrrr/watchtower#29]
Hello,

I started another Process using multiprocessing module, but the watchtower was unable to logging on Aws Cloud Watch. See this example:

import logging
import watchtower
import multiprocessing as mp

logging.basicConfig(level=logging.NOTSET, format="%(message)s")
logger = logging.getLogger(__name__)
logger.addHandler(watchtower.CloudWatchLogHandler(log_group="my_log_group",
                                                  stream_name="my_stream_name"),
                  )

def another_process():
    logger.info("message info inside another process")
    logger.error("messege error inside another process")

if __name__ == "__main__":
    
    logger.info("message info main")
    logger.error("message error main")

    p = mp.Process(target=another_process)
    p.start()
    p.join()

    logger.info("Finish :-)")

See this image with what happened:

![image](https://cloud.githubusercontent.com/assets/1077464/20174296/4f5d3808-a724-11e6-93ec-c2e0428e809d.png)

Just messages inside main function worked.

How can I do to log the messages inside Process ?
This is a bug ?
There is a configuration to enable this feature ?

Thank you.
Victor Jabur

**Comment by jslu9** [comment]
I have ran into this issue as well. Were you able to figure out a workaround?
