### ISSUE TITLE
Notifications for several different log levels

### ISSUE THREAD

**Issue by ianrossi** [containrrr/watchtower#291]
Is there a way to have WT send notifications for multiple log level events, like `error`, `fatal` and `panic`? It would be helpful to have a notification when any of these things occur. I could not find any indication of how to do this after looking through this repo or also at the Logrus repo. It looks as though the README only shows how to notify for a single log level. Thanks!

**Comment by simonaronsson** [comment]
Thank you for creating an issue and thank you for using watchtower!

The notification level selected with `--notifications-level` is a threshold, not an exclusive selector. Basically, setting it to debug, will send notifications for the `debug` level and above. Setting it to `fatal` will only notify you on `fatal` or `panic` and so on.

I hope this answers your question. 🙏
