### ISSUE TITLE
Update info on dockerhub and site with envrironment variable

### ISSUE THREAD

**Issue by Ansem93** [containrrr/watchtower#292]
Hi,
I just wanted to ask if it would be possible to update the usage info adding the environment variable too.
I found them looking in the code, but it's not exactly something easy to do :/

**Comment by simonaronsson** [comment]
Thank you for the report 🙏 

Would you mind elaborating on which variable's missing?

**Comment by Ansem93** [comment]
For example: it's not written in the usage and option section the  that the environment variable of cleanup is WATCHTOWER_CLEANUP.
Also i can't find the environment variable of "debug"

**Comment by simonaronsson** [comment]
Would be awesome if you'd update the readme with your findings then! I'd be happy to review your pull request. Thanks. 🙏

**Comment by Ansem93** [comment]
Sure :) give me a while and I'll update it with all the information that I can take from app.go file :)

**Comment by simonaronsson** [comment]
Awesome! Thanks!

**Comment by Ansem93** [comment]
Edited the file with new descriptions :) If you like it I'll update it with missing options.
A request since I can edit the app.go file: Can you add the line:
EnvVar: "WATCHTOWER_DEBUG", 

please?

**Comment by simonaronsson** [comment]
That would be great! Just submit a PR when you’re done and I’ll add the debug env var as well. :)

**Comment by simonaronsson** [comment]
Thanks for your contribution! Merged after some layout changes.
