### ISSUE TITLE
Github Package Registry Support

### ISSUE THREAD

**Issue by seupedro** [containrrr/watchtower#293]
is it going to be supported?

**Comment by simonaronsson** [comment]
I havent even received a beta invite yet, so i'm not really sure about the details yet.

From what I've understood, however, it's supposed to be equivalent to any other private (or non-dockerhub) registry, and should therefor be supported out of the box.

Have anyone received an invite yet and would be open to confirming whether this is correct?

**Comment by seupedro** [comment]
Yeah, you're right. Only waitlist until the moment. But you can [subscribe to waitlist here.](https://github.com/features/package-registry/signup)

![Captura de Tela 2019-05-13 às 19 35 18](https://user-images.githubusercontent.com/33115289/57658834-9ec94900-75b6-11e9-8bd0-ff35be7867d0.png)

**Comment by cipi1965** [comment]
@simskij i confirm it is equivalent to any private registry

**Comment by simonaronsson** [comment]
@cipi1965 awesome! I’ll go ahead and close this issue then. :)
