### ISSUE TITLE
failing to send mail to gmail over port25 where to specify port?

### ISSUE THREAD

**Issue by ward0** [containrrr/watchtower#294]
Failed to send notification email:  dial tcp 108.177.126.109:25: getsockopt: no route to host

docker run -d --name watchtower --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -e WATCHTOWER_NOTIFICATIONS=email -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=***@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_TO=***@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=****@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=*****
v2tec/watchtower:armhf-latest

I should specify port587 and not port25 by default.. but where to specify?

**Comment by simonaronsson** [comment]
Thanks for your report!
`WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587` would likely solve your problem 😄 🙏
