### ISSUE TITLE
Add prometheus metrics

### ISSUE THREAD

**Issue by michaelarnauts** [containrrr/watchtower#295]
**Is your feature request related to a problem? Please describe.**
I'm monitoring my containers trough cAdvisor with prometheus. This gives me nice metrics per container to see how they behave. 

I'm also looking for a way to check if some containers are using an outdated image. I want to avoid running old software that might have security issues. **Important is that I can't have my containers updated randomly during the day. This needs to be in an maintenance window.**

I can already use `--monitor-only`, so this seems like a good idea. The only issue is that I now need a way to get this updatable information into prometheus.

**Describe the solution you'd like**
Provide metrics that prometheus can use to follow up when images are outdated. Usefull metrics might be:
* watchtower_last_checked{container="whatever"} timestamp
* watchtower_updatable{container="whatever"} 1/0
* watchtower_updated{container="whatever"} timestamp

**Comment by simonaronsson** [comment]
Yeah, prometheus support seems like a really reasonable feature request for watchtower.
Feel free to create a pull request with the needed changes and I'll make sure to review it 🙏

**Comment by paulfantom** [comment]
I would propose a minor modification to @michaelarnauts request to implement metrics as follows:
```
Counter watchtower_updates_total{container="foo"} int
Gauge   watchtower_stale{container="foo"} 0/1
Gauge   watchtower_last_update{container="foo"} timestamp
```

As for `last_checked` I would say it isn't very important. Watchtower checks everything every X seconds, so this metric would be max X seconds behind last scrape, which doesn't give much new information.

Also I started implementing it :)

**Comment by simonaronsson** [comment]
Awesome!

**Comment by michaelarnauts** [comment]
@paulfantom do you have a merge request somewhere?

**Comment by simonaronsson** [comment]
@paulfantom, may I assist you in any way in getting this feature ready for integration with master?

**Comment by simonaronsson** [comment]
Reopening this as I believe this is something we really should have.

**Comment by simonaronsson** [comment]
I've started implementing some kind of embryo for this in #450
