### ISSUE TITLE
Failed to send notification email i/o timeout

### ISSUE THREAD

**Issue by khandelwalpiyush** [containrrr/watchtower#296]
Hi

Trying the following setting on docker on my Synology NAS

`docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock -e WATCHTOWER_NOTIFICATIONS=email -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXXXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_TO=XXXXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXXXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXXXX -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587 containrrr/watchtower --monitor-only --debug --run-once`

Get the error

> Failed to send notification email:  dial tcp: lookup smtp.gmail.com on 192.168.X.X:53: read udp 172.X.X.X:53732->192.168.X.X:53: i/o timeout

What am I doing wrong?

**Comment by khandelwalpiyush** [comment]
Sorry.. Network config issue

**Comment by olskar** [comment]
@khandelwalpiyush  care to explain how you fixed it? I have the same problem

**Comment by piyush-khandelwal-sp** [comment]
@olskar This is the command which worked for me

`docker run -d --restart unless-stopped --network host --name watchtower -v /var/run/docker.sock:/var/run/docker.sock -e WATCHTOWER_NOTIFICATIONS=email -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_TO=XXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXXX -e TZ=XXX/XXX containrrr/watchtower --cleanup --include-stopped --schedule "0 0 20 * * *"`

**Comment by khandelwalpiyush** [comment]
@olskar This is the command which worked for me

`docker run -d --restart unless-stopped --network host --name watchtower -v /var/run/docker.sock:/var/run/docker.sock -e WATCHTOWER_NOTIFICATIONS=email -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=XXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_TO=XXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=XXX@gmail.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=XXXX -e TZ=XXX/XXX containrrr/watchtower --cleanup --include-stopped --schedule "0 0 20 * * *"`
