### ISSUE TITLE
Ignore some containers - flag provided but not defined: -label

### ISSUE THREAD

**Issue by khandelwalpiyush** [containrrr/watchtower#297]
Hi

I am trying to ignore a container watch pihole-1

I am running the following

`docker run --rm --network host --restart=unless-stopped --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --label="com.centurylinklabs.watchtower.enable=false" pihole-1 --monitor-only --debug
`
I get the error

> time="XXXXX" level=fatal msg="flag provided but not defined: -label"

What is missing here?

**Comment by simonaronsson** [comment]
Thank you for your report 🙏🏻

Move the label parameter to the left of the image name and you should be good to go!

**Comment by khandelwalpiyush** [comment]
Thanks @simskij 

Did you mean

`docker run --rm --network host --name watchtower -v /var/run/docker.sock:/var/run/docker.sock  --label="com.centurylinklabs.watchtower.enable=false" pihole-1 containrrr/watchtower --monitor-only --debug`

Get the message

> Unable to find image 'pihole-1:latest' locally
> docker: Error response from daemon: repository pihole-1 not found: does not exist or no pull access.

Then I realised that maybe it should be the image name (pihole/pihole) and not container name (pihole-1) ? 

Get the same error on putting 

`docker run --rm --network host --name watchtower -v /var/run/docker.sock:/var/run/docker.sock  --label="com.centurylinklabs.watchtower.enable=false" pihole containrrr/watchtower --monitor-only --debug`

> Unable to find image 'pihole:latest' locally
> docker: Error response from daemon: repository pihole not found: does not exist or no pull access.

I am obviously doing something stupid here... :(

**Comment by simonaronsson** [comment]
My bad! Didn’t really read carefully enough I’m afraid. Labels are a docker feature used to annotate containers or images. In your case it looks like you are trying to exclude pihole from auto updates. If that is correct, then you’d want to start your pihole with that flag rather than setting it on your watchtower container.

It’s also important that a docker run command is written as `docker run [docker args] some/image-name [image args]` or the command won’t be interpreted as you intended. 

Hope that helps.

**Comment by simonaronsson** [comment]
I.e

```shell
docker run --rm \
  --network host \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower \
  --monitor-only \
  --debug
```

Then add the label to your pihole instance while launching it to exclude it from watchtower checks.

**Comment by khandelwalpiyush** [comment]
Thanks @simskij 

Will get back to you. Since I created the pihole container via the Synology Docker GUI, I will either need to figure out how to add label to my existing container. Or delete it and either run a docker CLI command or create a docker composer file.. If you have experience with the Synology GUI and label do let me know

**Comment by khandelwalpiyush** [comment]
Thanks @simskij 

I believe this issue is resolved.  I put the label on pihole container. Started watchtower and didn't see any reference to pihole in the debug log.

Thanks for your help
