### ISSUE TITLE
how does watchtower handle tagged images

### ISSUE THREAD

**Issue by remiyazigi** [containrrr/watchtower#298]
hello,
i was wondering how watchtower handles tagged images for example 
ubuntu:xenial-20190515 and ubuntu:xenial-20190414 
are those considered the same image and watchtower will pull from the newer tag or 2 different images ?
PS: not using the "latest"  option

**Comment by simonaronsson** [comment]
Thanks for creating a report! 🙏🏻

Watchtower monitors a certain label for differences and updates the container if it finds any changes. 

As a lot of repos contain multiple “living” image versions I don’t really see how we’d be able to solve this in a reasonable way.

With that said however, if you have any cool suggestions on how to solve this; feel free to submit a pull request implementing it and I’ll make sure to review it! 😅

**Comment by remiyazigi** [comment]
thank you for the reply, that is what i also thought, anyway if i manage to find a solution i will definitely submit a pull request.
until then keep up the awesome work
and you may close the issue, if you want to .

Regards,
Remi
