### ISSUE TITLE
Synology Docker GUI Restart Fatal Crash Issue

### ISSUE THREAD

**Issue by khandelwalpiyush** [containrrr/watchtower#299]
Not sure if directly related to https://github.com/containrrr/watchtower/issues/252

I created the watchtower docker via CLI (as root)

> docker run -d --restart unless-stopped --network host --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --include-stopped --schedule "0 0 20 * * *"

Works fine. But when I stop it via Synology GUI and restart it via GUI - it keeps crashing with the following message

> level=fatal msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

Something to do with root or privileges I believe? But no other container crashes as such. I think the /var/run/docker.sock is not read or detected by the GUI and maybe the GUI is running as the admin user?

srw-rw---- 1 root root 0 May 21 14:39 /var/run/docker.sock

Any thoughts on how we can fix this? Only way I fix atm is to delete the container by the GUI and then run the above command again.

**Comment by simonaronsson** [comment]
I suggest you turn to a synology user forum for this. Maybe someone at https://serverfault.com might be able to help you? I'm afraid I neither have any synology devices or any knowledge of how they've implemented their docker support.

**Comment by MichelZ** [comment]
@khandelwalpiyush If you have found a solution to this, please add it here. I'm having the same issue. Thanks

**Comment by khandelwalpiyush** [comment]
@MichelZ No unfortunately didn't get time to investigate as I am travelling

**Comment by fufar** [comment]
same issue for me
