### ISSUE TITLE
not able to download/update from my private docker registry.

### ISSUE THREAD

**Issue by weslleycamilo** [containrrr/watchtower#30]
Hello,

I am using the gitlab docker registry and i get a error like below:
weslley@pc:~/ahpi$ docker run -it   -e REPO_USER="weslley" -e REPO_PASS="password!" -e REPO_EMAIL="myemail@email.com" -v /var/run/docker.sock:/var/run/docker.sock centurylink/watchtower 

INFO[0000] Checking containers for updated images       
Get https://registry.private.com.br/v2/git/pw2/manifests/pwnginx: denied: access forbidden

Or 
the error below that is trying to use the docker registry.. how can i specify my gitlab docker registry?

docker run -it   -e REPO_USER="weslley" -e REPO_PASS="password" -e REPO_EMAIL="myemail@email.com" 
 -v /var/run/docker.sock:/var/run/docker.sock 
  drud/watchtower --interval 30 

INFO[0000] Checking containers for updated images       
Get https://registry-1.docker.io/v2/drud/watchtower/manifests/latest: unauthorized: incorrect username or password

Thank you.

**Comment by stffabi** [comment]
Should be fixed with the latest changes from #26
