### ISSUE TITLE
Ability to notify about updates for false labeled containers

### ISSUE THREAD

**Issue by khandelwalpiyush** [containrrr/watchtower#300]
**Is your feature request related to a problem? Please describe.**
Have some containers which I have labeled so that they are not updated. But would like to still know there is an update available.

**Describe the solution you'd like**
Another type of flag or value which can monitor some containers but not update. While still keeping ability to auto update others (not exactly --monitor-only flag)

**Describe alternatives you've considered**
Only possible ways I see are

1) --monitor-only : Monitors all containers but no update
2) --label-enable: Updates only those containers where label is enabled
3) com.centurylinklabs.watchtower.enable="false": This allows to not update particular container but update others

Looking for a combination of 1 + 3 scenario

**Comment by simonaronsson** [comment]
I like the idea. This could be implemented by looking for a tag, ie. `com.centurylinklabs.watchtower.monitor="true"` which basically choses the same path as `--monitor-only` for that specific container.

Feel free to have a stab at it. If anyone else is interested in implemented this, you're welcome as well. I'll make sure to review it and provide feedback. Thanks 🙏

**Comment by khandelwalpiyush** [comment]
Thanks.. don't have the capability.. hopefully someone more learned can do it :)
