### ISSUE TITLE
Stop working after Error: image not found

### ISSUE THREAD

**Issue by renatoriccio** [containrrr/watchtower#31]
After watchtower tries to pull an image that is not able to find (for example an image locally builded) it is not able to go on scanning the following images in the list.

So in the log I have

time="2016-12-04T22:34:24Z" level=info msg="Checking containers for updated images" 
time="2016-12-04T22:34:24Z" level=debug msg="Retrieving running containers" 
time="2016-12-04T22:33:41Z" level=debug msg="Pulling localimage:latest for /test-container" 
Error: image library/localimage:latest not found
time="2016-12-04T23:24:24Z" level=info msg="Checking containers for updated images"

**Comment by stffabi** [comment]
Fixed with c4efc838757aff437b22c07c85be29761974eb72
