### ISSUE TITLE
Testing notification function

### ISSUE THREAD

**Issue by kevindd992002** [containrrr/watchtower#331]
I have watchtower configured through docker compose and I want to test its core functionality and email notification feature. How do I force it to send an email to check if my email settings are correct? Will it only send a notification when there is a container image update? If so, then would I just need for a container to have an update for me to test my setup? Here's what I have basically:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM="Watchtower" <{my Yahoo email address}>
      - WATCHTOWER_NOTIFICATION_EMAIL_TO={my Yahoo email address}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.mail.yahoo.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER={my Yahoo account username}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD={my Yahoo account password}

Anything I missed with the yml file? 

When do I need to mount the docker config? I don't see a .docker folder in my root folder. I'm running Debian Stretch, btw.

**Comment by simonaronsson** [comment]
Looks OK to me.

You could always try pulling whatever image you like, for example:
`docker pull dockercloud/hello-world:staging`

Then tag it as latest using:
`docker tag dockercloud/hello-world:staging dockercloud/hello-world:latest`

Run it with `docker run -d dockercloud/hello-world:latest` and then wait for watchtower to notice that the image hashes differ.

Hope this helps 🙏

**Comment by kevindd992002** [comment]
I just did that, sorry I'm a Linux/Docker noob just trying to get by building a NAS Media Server :)

It looks like the update worked because the container ID changed but the email notification didn't. Let me try using port 465 instead.

**Comment by kevindd992002** [comment]
By default though, does it connect to the SMTP server securely (TLS/SSL) or not? Port 465 doesn't work too. For my other email notification services, 587 works without secure SMTP and 465 work with secure SMTP. So I'm not sure what's going on here.

**Comment by kevindd992002** [comment]
Found out what the problem is. It doesn't want this as the FROM address: 

"Watchtower" <{my Yahoo email address}>

So I thought it was just a matter of a character escape (because of the space. So I tried:

"Watchtower"\ <{my Yahoo email address}>

And it still doesn't work. Is "<" also a special character that I need to escape?

**Comment by simonaronsson** [comment]
Yeah, both < and > will likely need to be escaped. Good catch!

**Comment by kevindd992002** [comment]
I actually realized that before you even replied but it still didn't work :( Specifying the email address alone is the workaround but I'd really like to make the original value to work.

**Comment by kevindd992002** [comment]
The correct syntax is:

\"Watchtower\"\ \<email@yahoo.com\>

But it still won't work. Any more ideas?

Also, when I try doing `docker logs watchtower`, there isn't really any output. Why is this?

**Comment by simonaronsson** [comment]
What you're trying to do is currently not supported. This is because both [the header](https://github.com/containrrr/watchtower/blob/985a9220993d09f0bb0232a558447773ac6006dd/notifications/email.go#L65) and [the actual smtp command](https://github.com/containrrr/watchtower/blob/985a9220993d09f0bb0232a558447773ac6006dd/notifications/email.go#L95) use the same environment variable for population.

We will try to solve this in [shoutrrr](https://github.com/containrrr/shoutrrr), but until then, im afraid you'll have to make do with just an email address.

**Comment by asaage** [comment]
> How do I force it to send an email to check if my email settings are correct?

set ```WATCHTOWER_NO_STARTUP_MESSAGE``` to false will (try to) send a notification on container-startup.
