### ISSUE TITLE
When using docker-compose scale

### ISSUE THREAD

**Issue by amarCosmospace** [containrrr/watchtower#333]
Hi, i got a litle question, does watchtower do a (http) request to the registry for each container image in the scaled service or it's grouped when having the same image ? 

Like : 
service 1 -> image A -> scaled 15 
15 containers of service 1
So watch tower makes 15 http request of image A
or just 1 http request of image A

I'm asking that cause i'm having some quota issue with gcr. And i got 5 services scalled each on 15 containers and i got some errors from the google api saying that i've reached the max quota. So i'm asking that. 

Thanks for your anwser

**Comment by simonaronsson** [comment]
Thank you for the report! 🙏 

Yes, that's currently how we do it I'm afraid.

We've still got some thinking to do on exactly how (or if) we'd change that.
Suggestions about aggregating the same type of images have been suggested, but that might have other implications that we haven't thought off.

**Comment by simonaronsson** [comment]
Until (or if) something changes, a workaround would be to run watchtower with `--no-pull`.
Then schedule another instance that runs with the `--run-once` option at a fixed interval targeting only one instance of each container type.
