### ISSUE TITLE
Replace watchtower with this new one?

### ISSUE THREAD

**Issue by enoch85** [containrrr/watchtower#334]
Hi,

First of all, thanks for a great tool, it's really amazing!

We use this in the [Nextcloud VM](https://github.com/nextcloud/vm) and it's integrated for everyone using any docker containers such as Collabora, OnlyOffice and so on.

The questions is; how do you replace `v2tec/watchtower` with `containrrr/watchtower` and keep the current settings (send an email when an update happens and so on)?

Would [this](https://github.com/nextcloud/vm/pull/844/files) delete all the settings or is there a better way to do it?

Thanks again.

**Comment by KopfKrieg** [comment]
> v2tec/watchtower with containrrr/watchtower

Usually you just replace v2tec with containrrr in your docker-compose file. If you're not using docker-compose I recommend to take a look at it.

**Comment by enoch85** [comment]
@KopfKrieg No, I don't use that here, so question remains (with a bit of rephrasing); *how do I update to the new repo without loosing any settings when not using `docker-compose`?*

**Comment by simonaronsson** [comment]
Hey and thanks for the report! 🙏 

Yeah, that script would definitely wipe all your settings.
You could probably use the following command to extract all environment variables however:

```sh
docker inspect -f \
   '{{range $index, $value := .Config.Env}}export {{$value}}{{println}}{{end}}' \
  watchtower
```

These could then be used when creating the new instance.

**Comment by enoch85** [comment]
@simskij Thanks for the extract command, but how would I then import the settings again? Sorry for my ignorance.

**Comment by simonaronsson** [comment]
> how would I then import the settings again?

Just add them to the run command using `-e`. You could even reformat the output of the extract command to print it that way by replacing export with `-e`. :)

See https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by enoch85** [comment]
Aah got it, thanks! Will try later today. :)

**Comment by enoch85** [comment]
@simskij Sorry to disturb you again. 

A very hacky soulution that is not yet working, but it's close:

```
# Get Env values
docker inspect -f \
   '{{range $index, $value := .Config.Env}}-e {{$value}}{{println}}{{end}}' \
  watchtower > env.list

sed -i '/^[[:space:]]*$/d' env.list

# Get Cmd values
CmdDocker=$(docker inspect --format='{{.Config.Cmd}}' watchtower | cut -d "]" -f 1 | cut -d "[" -f 2;)

# Check if env.list is empty and run the docker accordingly
if [ -s env.list ]
then
docker run -d \
  --restart always \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --env-file ./env.list \
  containrrr/watchtower $CmdDocker
else
docker run -d \
  --restart always \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  containrrr/watchtower $CmdDocker
fi
```

What do you think?

**Comment by enoch85** [comment]
It seems like newlines are not supported: https://github.com/moby/moby/issues/12997

**Comment by enoch85** [comment]
In my test environment it complains about: `docker: poorly formatted environment: variable '-e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD' has white spaces.`

**Comment by enoch85** [comment]
Sorry for the noise, the issue is now solved. Thanks for the pointers!

**Comment by simonaronsson** [comment]
> Sorry for the noise, the issue is now solved. Thanks for the pointers!

Awesome! Happy you solved it!
