### ISSUE TITLE
Execution hooks

### ISSUE THREAD

**Issue by carroarmato0** [containrrr/watchtower#335]
I'd like to be able to have scripts/actions be executed depending on which phase watchtower is in.

- Upon detection of an update
- After the old container is stopped
- After the new container is started

Ideally, some metadata could be exposed to the hook (name or id of the container)

**Additional context**
I run a backup script which iterates over all the volumes in use by containers right before updating the versions of the containers.
People might have other uses cases.

**Comment by simonaronsson** [comment]
Thank you for your report 🙏 

This is available in https://github.com/containrrr/watchtower/pull/197. However, I've not yet had time to go through that and merge it into master.

**Comment by carroarmato0** [comment]
> Thank you for your report 
> 
> This is available in #197. However, I've not yet had time to go through that and merge it into master.

Oh I missed that existing issue. In that case will close this one.
