### ISSUE TITLE
Failed to send notification email:  dial tcp xxx:0: connect: connection refused

### ISSUE THREAD

**Issue by brightdroid** [containrrr/watchtower#341]
**Describe the bug**

I try to send notification mails via an external / host postfix.

**To Reproduce**
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e WATCHTOWER_NOTIFICATIONS=email -e WATCHTOWER_NOTIFICATION_EMAIL_FROM=me@example.com -e WATCHTOWER_NOTIFICATION_EMAIL_TO=me@example.com -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER=x.x.x.x -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25 containrrr/watchtower --run-once --monitor-only`

**Expected behavior**
notification mail sent via x.x.x.x:25

**Environment**
 - Platform: Ubuntu 19.04
 - Architecture: x64
 - Docker version: 18.09.6

**Logs from running watchtower with the `--debug` option**

time="2019-07-02T08:23:23Z" level=info msg="Running a one time update."
time="2019-07-02T08:23:23Z" level=debug msg="Checking containers for updated images"
time="2019-07-02T08:23:23Z" level=debug msg="Retrieving running containers"
Failed to send notification email:  dial tcp x.x.x.x:0: connect: connection refused

**Additional context**

As you can see, the port is ignored and watchtower tries to connect to port 0, whis also happpen if I omit  WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT

**Comment by simonaronsson** [comment]
Solved with release v0.3.7 which is available as of now.
