### ISSUE TITLE
WATCHTOWER_SCHEDULE is ignored

### ISSUE THREAD

**Issue by brightdroid** [containrrr/watchtower#343]
**Describe the bug**
The env var WATCHTOWER_SCHEDULE is ignored and the default interval of 300 sec. is used instead.

**To Reproduce**
Run:
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -e WATCHTOWER_SCHEDULE="$(date --date='now + 2 minute' +'0 %M %H * * *')" containrrr/watchtower --debug`

**Expected behavior**
Run in now + 2 minutes every day

**Environment**
 - Platform: Ubuntu 19.04
 - Architecture x66_64
 - Docker version: 18.09.6

**Logs from running watchtower with the `--debug` option**

```
time="2019-07-02T14:45:59+02:00" level=debug msg="Sleeping for a seconds to ensure the docker api client has been properly initialized."
time="2019-07-02T14:46:00+02:00" level=debug msg="Retrieving running containers"
time="2019-07-02T14:46:00+02:00" level=debug msg="There are no additional watchtower containers"
time="2019-07-02T14:46:00+02:00" level=debug msg="Starting Watchtower and scheduling first run: 2019-07-02 14:51:00 +0200 CEST m=+301.146423442"
```

**Additional context**

With the param "-s" everything works as expected:
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro containrrr/watchtower --debug -s "$(date --date='now + 2 minute' +'0 %M %H * * *')"`

**Comment by simonaronsson** [comment]
Thank you for your report!

This is solved in v0.3.8, which is available on dockerhub.
