### ISSUE TITLE
watchtower run-once returning 1 in shell

### ISSUE THREAD

**Issue by gpaterno** [containrrr/watchtower#347]
**Describe the bug**
When asked to run once, rc 1 is sent back to shell and CI/CD pipeline fails.

**To Reproduce**
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once --no-pull container1 container2
time="2019-07-10T09:16:33Z" level=info msg="Running a one time update."
echo $?

**Expected behavior**
Return 0 if no error.

**Environment**
Ubuntu 18.04 LTS
Docker version 18.09.7, build 2d0083d

**Comment by simonaronsson** [comment]
Thank you for the report! 🙏 

I agree that this is a bug. Would you mind providing a pull request changing this?
