### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by claudiu-edi** [containrrr/watchtower#352]
Hello! While using watchtower I get this:

`time="2019-07-27T06:58:09Z" level=debug msg="Error pulling image linuxserver/letsencrypt:latest, Error response from daemon: Get https://registry-1.docker.io/v2/linuxserver/letsencrypt/manifests/latest: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution"`
`time="2019-07-27T06:58:09Z" level=info msg="Unable to update container /letsencrypt. Proceeding to next."`
`time="2019-07-27T06:58:09Z" level=debug msg="Error response from daemon: Get https://registry-1.docker.io/v2/linuxserver/letsencrypt/manifests/latest: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution"`

Also I get e-mail notifications for failed updates on my running containers. I can't really figure out what's the issue so any help is appreciated. Thanks!

**Comment by simonaronsson** [comment]
Thanks for your report! 🙏 

Could you please provide some more context? docker-compose files, run commands for both  watchtower and the other containers would be super helpful.

**Comment by claudiu-edi** [comment]
Hi! Sorry I didn't come back with an answer but it seems that a simple host restart solved the issue. Watchtower container seems to be working normally for now. Thank you!

**Comment by simonaronsson** [comment]
Awesome! I'll go ahead and close the issue then. Feel free to come back if you experience any other issues! 👍

**Comment by JSchoreels** [comment]
Same problem here, however restarting the daemon is not a solution we are excited to see in production. We run docker in Server Version: 19.03.8. We have multiple stacks running across multiple nodes. One of those nodes wasn't reachable by the other with the error in the title. We had to manually restart the daemon docker to make the resolution working again.
