### ISSUE TITLE
Defer or disable notifications when registry is down

### ISSUE THREAD

**Issue by qqilihq** [containrrr/watchtower#360]
**Is your feature request related to a problem? Please describe.**

We’re running our own Docker registry which is on scheduled maintenance during the night. During this time, when Watchtower cannot access the registry, our Slack channels will be flooded with messages:

![Bildschirmfoto 2019-08-04 um 11 17 54](https://user-images.githubusercontent.com/2172260/62421971-06210180-b6ab-11e9-8f07-0f3180273b36.png)

**Describe the solution you'd like**

An ideal solution, though obviously quite narrow to our use case, would be, that errors about an unreachable registry are only propagated after x failed attempts, or y minutes.

**Describe alternatives you've considered**

Alternatively, completely turning off notifications about unreachable registries might work for us as well -- while retaining other info and error notifications. (doesn’t seem to be possible with the current log levels, as the mentioned message is [logged](https://github.com/containrrr/watchtower/blob/bfae38dbf8b8aaa3108a61e7c2570d97faa28c7c/internal/actions/update.go#L24) with `info`)

**Additional context**

I understand that this is probably a quite “special” case, so I’m not expecting a feature like this. However, I’d like to hear how/if others are dealing with this situation.

**Comment by simonaronsson** [comment]
We already have a suggestion in place for implementing per container maintenance windows. Seems like that would solve your use case as well. Closing this issue in favor of #97

**Comment by qqilihq** [comment]
Thx.
