### ISSUE TITLE
want to delete --no-pull command while container keeps running

### ISSUE THREAD

**Issue by SchenbergZY** [containrrr/watchtower#363]
Here I want to change no-pull to pull or vice versa when keeping the watchtower running. Is there any options?

**Comment by simonaronsson** [comment]
Hey there @SchenbergZY! Thank you for the report.
This is not possible at the moment. My suggestion is that you just restart watchtower.

**Comment by SchenbergZY** [comment]
how about change env?

**Comment by simonaronsson** [comment]
I'm afraid that wont help as the environment vars are read during launch.
