### ISSUE TITLE
Updater not working with AutoRemove policy

### ISSUE THREAD

**Issue by DrJume** [containrrr/watchtower#366]
**Describe the bug**
When creating a watchtower container through the Docker API with 
```
HostConfig: { AutoRemove: true }
```
and --run-once parameter, watchtower crashes:
```
Running a one time update.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**To Reproduce**
1. Run a watchtower container through the API (dockerode) with following settings:
```
HostConfig: { AutoRemove: true }
```
and --run-once parameter.

**Expected behavior**
It should behave exactly the same as by running watchtower through the CLI with --run-once and --rm flags set.
The watchtower container should be removed after the containers' process ends.

**Environment**
 - MacOS Mojave 10.14.6
 - x64
 - Docker version 19.03.1, build 74b1e89 

**Logs from running watchtower with the `--debug` option**
```
DEBU[0000] Checking containers for updated images       
DEBU[0000] Retrieving running containers                
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
INFO[0000] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by simonaronsson** [comment]
Thank you for the report!

When creating using the API, are you actually supplying a bind mount for docker.sock?
A more exhausting snippet from the http request would be very helpful.

**Comment by simonaronsson** [comment]
Closing this due to lack of response.
