### ISSUE TITLE
missing ENV after update on Synology

### ISSUE THREAD

**Issue by r2ixuz** [containrrr/watchtower#377]
**Describe the bug**
Since the latest Synology Docker update from 17.05.0 to 18.09.6 after every container rebuild through containerrr/watchtower the containers missing their manually set ENV variables.

**To Reproduce**
1. Have latest stale DSM release (6.2.2-24922 Update 3)
2. Have latest Synology Docker package (18.09.0-0505)
3. Create Container with ENV variables set
4. Use containrrr/watchtower to automatically update your containers.
5. After watchtower did update a container, it will be started without your needed ENV variables.

**Expected behavior**
Every container launch parameter including ENVs should be used to rebuild a container after updating it through watchtower.

**Comment by r2ixuz** [comment]
Maybe it is because I used Portainer to recreate the watchtower container with these automatically created capabilities:

`       "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],`

**Comment by yongbi85** [comment]
I used portainer and docker synology, same issue.
I am on synology DSM 6.1 but with the latest docker package too. I had to delete watchtower for now..;
So it is not a DSM issue but an issue wih synology docker 18.09.0-0505 and watchtower (tried other watchtower image to be franck, like v2tec, but exactly the same issue)

**Comment by r2ixuz** [comment]
Ok it seems that there is a problem in this new Synology Docker release:

https://community.synology.com/enu/forum/15/post/128146

I don't know if watchtower is using docker-compose to set ENV but Synology support stated that they will fix in the next version that ENV cannot be set via docker-compose, only via Synology UI.

**Comment by simonaronsson** [comment]
Thanks for the report!

Watchtower is using the docker api directly, not through docker-compose. However, I suspect that docker-compose is using the same go client as we do to create containers. Synology seem to have their own fork (or addon) on the docker package, which causes issues in their latest release.

With that said, I dont see that much for us to do here until they've released their fix.
Let us know if your issues remain even after the fix has been rolled out.

Thanks,
Simon

**Comment by bxlouis** [comment]
Had the same issue. I confirm that rolling back Docker from v18.09.0-505 to v17.05.0-0401 as explained by John McCabe on the Synology forum fixed the issue. (cf. https://community.synology.com/enu/forum/15/post/128146)
Also, it looks like the v18.09.0-505 has been rolled back as the newest available version is now v17.05.0-0401 (cf. screenshot).

![Screenshot 2019-09-02 at 20 21 09](https://user-images.githubusercontent.com/4128333/64129942-92fccf00-cdbf-11e9-8089-a10c335e2993.png)

**Comment by LeeThompson** [comment]
Seeing this too, it's very annoying.  I hope Synology fixes this soon.

**Comment by r2ixuz** [comment]
With the latest Synology Docker package 18.09.0-0506 the issue has been resolved.

[Synology Docker Release Notes](https://www.synology.com/en-global/releaseNote/Docker)
