### ISSUE TITLE
Add flag to disable TLS check for all notification provider, or better allow certificate providing

### ISSUE THREAD

**Issue by h1dden-da3m0n** [containrrr/watchtower#382]
### Is your feature request related to a problem? Please describe.
The current release of Watchtower only features the disable TLS flag for the E-Mail notification provider, yet any other notification provider, where the host can be on-premise, may be locked behind a self-signed cert (Gotify in this case) and therefore would need the same treatment.

### Describe the solution you'd like
I would like the addition of the disable TLS flag for all notification providers globally, or at least for those that can be hosted on-premise.
Additionally, the ability to provide the self-signed certificate for the notification provider would be extra awesome! (so we don't have to disable TLS verification 😃 )

### Describe alternatives you've considered
The current workaround is to bind-mount an altered `ca-certificates.crt` that includes the self-signed certificate.
Alternatively, if the notification service runs in a docker container behind a reverse proxy, then the service could be reached via the docker network without TLS. (untested but should work theoretically)

### Additional context
My motivation for this request is only my home-lab, yet I know that quite a few companies use self-signed certificates internally (including the one I work at), which could benefit from this functionality.

---

some very basic research that I have done on how this might be done in GO (not a GO dev ☹️):
* [Set Insecure](https://stackoverflow.com/a/12122718)
* [Make Client Trust Server](https://ericchiang.github.io/post/go-tls/#getting-the-client-to-trust-the-server)
* [Golang https examples](https://github.com/jcbsmpsn/golang-https-example)

*not sure why I include this, yet maybe this comes in handy, I don't know* 😕 

---

Anyway, hope I am not asking for too much 😟.
Besides that, thank you all for this great project and keep up the great work!

**Comment by h1dden-da3m0n** [comment]
sorry for bumping this but I would like this to not get closed without getting noticed

**Comment by h1dden-da3m0n** [comment]
final bump

**Comment by h1dden-da3m0n** [comment]
thy @simskij for that tag add 😄

**Comment by tammert** [comment]
@h1dden-da3m0n I took a stab at it, but 'only' the skipping of TLS verification (I agree the option of adding specific certs to trust is pretty cool, but that's a much larger effort). As far as I could see this was the only other self-hosted option apart from smtp, so now these are more on-par as functionality goes.

**Comment by h1dden-da3m0n** [comment]
@tammert thank you very much :grin:
