### ISSUE TITLE
--remove-volumes doesn't work as expected with named volumes

### ISSUE THREAD

**Issue by leninalive** [containrrr/watchtower#383]
When using named volumes with docker-compose and watchtower, it won't remove named volumes with --remove-volumes argument (will only deassociate them from container) though volume contents won't be updated.

Is it possible to change this behavior and perform something like `docker volume prune` after container has been stopped and removed?

**Comment by simonaronsson** [comment]
Hey there!

You should be able to do this already using [lifecycle hooks](https://containrrr.github.io/watchtower/lifecycle-hooks/). For instance, you could add a script running `docker volume prune` on `post-update`. Another solution, which I tend to utilize myself, is to add a cronjob running the prune command every night.
