### ISSUE TITLE
What is the recommended way to make an unscheduled update?

### ISSUE THREAD

**Issue by alexanderadam** [containrrr/watchtower#385]
Imaging having a watchtower instance running with an update schedule.
What would be the recommended way of making an unscheduled update?

Running a second instance and removing this afterwards?

**Comment by simonaronsson** [comment]
Hey there @alexanderadam! Thank you for the report 🙏 

The recommended way to do unscheduled updates is to use the --run-once argument to run a second instance. See [the documentation](https://containrrr.github.io/watchtower/arguments/) for more details.
