### ISSUE TITLE
Failed to send notification email

### ISSUE THREAD

**Issue by devopsadmin-james** [containrrr/watchtower#386]
Failed to send notification email:  535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials q124sm727416oia.5 - gsmtp

gmail consider watchtower accessing its/my email ID with my credentials as less secure for watchtower since 2 October 2019 and doesn't send emails from specified users to specified users.

Please look into it.

I am using containrrr/watchtower image.

**Comment by kevdogg** [comment]
Hi -- new to this forum but not new to github projects :)

Installed watchtower last night and enabled it to send me email.  
Specifically with gmail:
You need to apply an app specific password (May need to search internet how to do this -- but you use this as the email password)
Also run on port 587.  (For those wondering I tried on port 465 and it didn't work!!)

Hopefully that helps.

**Comment by simonaronsson** [comment]
Thank you for the report! 🙏

As @kevdogg mentioned, you'll need to use an app specific password. Google have published a guide for this [here](https://support.google.com/accounts/answer/185833?hl=en). I'll go ahead and close this issue.
