### ISSUE TITLE
Add mail customized mail notification subject tag

### ISSUE THREAD

**Issue by 8ear** [containrrr/watchtower#388]
Hi all,

Your Watchtower container is very nice and the mail function works as excepted. Really great and a huge thanks to you!

I have more than one Docker server with different purposes and on every server I have a watchtower container running in monitoring mode. But the mails I got have all the following subject: `Watchtower updates on <container id>` 
For example: `Watchtower updates on 1a25cbf5f088`.

So my Question is, is it possible to add an environment variable to add an tag in the subject line at the beginning which can be customized?

The result can be:
`[TAG] Watchtower updates on <container id>` for example: `[server 13] Watchtower updates on 1a25cbf5f088`.
ENV: WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=[server 13]

Kind regards

**Comment by simonaronsson** [comment]
Thank you for taking care of this. I'll go ahead and switch the status of this ticket to `In Progress` meanwhile.

**Comment by 8ear** [comment]
Thanks.

**Comment by simonaronsson** [comment]
This is already merged. Closing.
