### ISSUE TITLE
What is the right Syntax for sending email to multiple email ids

### ISSUE THREAD

**Issue by devopsenggineer** [containrrr/watchtower#395]
What is the right Syntax for sending email to multiple email ids?

I have tried these three-ways but it didn't work out.

1.  -e WATCHTOWER_NOTIFICATION_EMAIL_TO=abc@gmail.com,test@gmail.com

2.  -e WATCHTOWER_NOTIFICATION_EMAIL_TO=abc@gmail.com 
    -e  WATCHTOWER_NOTIFICATION_EMAIL_TO=test@gmail.com

3. -e WATCHTOWER_NOTIFICATION_EMAIL_TO=[abc@gmail.com,test@gmail.com]

Watchtower didn't fire an email with 2 & 3 options while with the first option only first email-id (abc@gmail.com) got an email, not the second email-id(test@gmail.com)

So what's the right syntax for sending email to multiple email addresses.

A quicker response will be appreciated.

Thanks

**Comment by simonaronsson** [comment]
It should be option 1 according to http://www.faqs.org/rfcs/rfc2822.html
Does it change anything if you wrap your whole env var in quotes? Like this:
```sh
-e "WATCHTOWER_NOTIFICATION_EMAIL_TO=abc@gmail.com,test@gmail.com"
```

**Comment by devopsenggineer** [comment]
I tried this -e "WATCHTOWER_NOTIFICATION_EMAIL_TO=abc@gmail.com,test@gmail.com" option, it returns with the following error.

Failed to send notification email:  553 5.1.2 The recipient address <abc@gmail.com,test@gmail.com> is
5.1.2 not a valid RFC-5321 address. j2sm576793qki.15 - gsmtp
