### ISSUE TITLE
Suggestion: Choose containers to restart based on container label

### ISSUE THREAD

**Issue by sirlatrom** [containrrr/watchtower#4]
Currently, if I don't want all containers to be restarted when newer image versions are available, I have to specify a static list of container names when I run `watchtower`.

If additionally I could set a label on a container that I would like to be upgraded by `watchtower`, I would not have to manage restarting watchtower itself with new arguments each time I create a new container that I want auto-upgraded.

**Comment by bdehamer** [comment]
:+1: love this idea

**Comment by davidgardner11** [comment]
Hi @sirlatrom, @bdehamer is no longer at CenturyLink, but we welcome and encourage community contributions. Would you be interested in submitting a PR with this enhancement?

**Comment by sirlatrom** [comment]
I would love to but don't have the faintest clue where to start...

**Comment by JulianKingman** [comment]
Great idea, to me this would greatly enhance its usability. I don't understand go, but if anyone wants to have at it, you can see how [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) handles container environment variables, which is pretty much the same thing as this.

In most cases I only really want to update the app container, I don't particularly care about updating secondary images (and in fact don't want to in an automated fashion, lest dependencies break).

**Comment by stffabi** [comment]
The possiblity to watch containers with an assigned label has been introduced with #104
