### ISSUE TITLE
Update base docker alpine image to 3.10 minimum to address CVEs in alpine:3.9

### ISSUE THREAD

**Issue by keatontaylor** [containrrr/watchtower#400]
**Describe the bug**
The current base image for  watchtower is alpine 3.9 which contains the following security CVEs

![image](https://user-images.githubusercontent.com/657559/67969931-28f28180-fbd8-11e9-98b3-a3d6ea92f074.png)

alpine:3.10 updates these packages to versions that are not currently known to be vulnerable. Suggestion would be to move the base docker image to 3.9. 

**To Reproduce**
1. Install Trivy from https://github.com/aquasecurity/trivy
2. Run against alpine:3.9 base image 
4. See CVEs

**Expected behavior**
Base images should be updated on a regular interval and scanned periodically to ensure that security vulnerabilities in base packages are resolved.

**Screenshots**
N/A

**Environment**
Ran on the latest docker image on docker hub.

**Comment by simonaronsson** [comment]
Hey there!

Thank you a lot for your report. 🙏🏼

This will be prioritized for an upcoming release.  While we run the watchtower binary in a scratch image, and only use alpine as a build stage, we still need to address this issue.

Best regards,
Simon
