### ISSUE TITLE
Slack Identifier doesn't do anything

### ISSUE THREAD

**Issue by unstephenk** [containrrr/watchtower#405]
**Describe the bug**
I added a slack Identifier to the an env file and am sucking in the env file to set up slack. I setup a web hook in slack. Notifications are working but I have watchtower setup in mulitple places. As of right now the identifier does not seem to be doing anything.
```
WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=server-1
```

**To Reproduce**

**Expected behavior**
There should be someway to distinguish which identifier the notifications are coming from in the slack channel.

**Screenshots**

**Environment**

**Logs from running watchtower with the `--debug` option**

**Additional context**

**Comment by crossworth** [comment]
This is a bug indeed.
Slack webhook dont support setting the username anymore, is possible set the username using a token but the library used for [slack](https://github.com/johntdyer/slack-go) is old and dont support oauth tokens.

Eventually the notification system will be replaced by [shoutrrr
](https://github.com/containrrr/watchtower/issues/264), which seens to support oauth token.

**Comment by simonaronsson** [comment]
Closing this in favor of #264
