### ISSUE TITLE
Volumes aren't kept after update

### ISSUE THREAD

**Issue by ghost** [containrrr/watchtower#410]
The container is successfully updated with the new image I pushed in registry, but the volumes aren't kept, they are replaced by new empty volumes instead. The original volumes aren't erased, they are just detached and replaced by new empty volumes.

I do not know what I am doing wrong, I looked at the documentation, and I have neither `--remove-volumes` nor `WATCHTOWER_REMOVE_VOLUMES`, and the default is false.

So, I do not understand what is happening.

**Comment by simonaronsson** [comment]
Hey there,

Thank you for your report! 🙏🏼

To my knowledge this is by design. We don't want any state to leak to a new container. If you have volumes that you'd like to keep attached after an upgrade, I'd suggest you use an external/named  volume.

Thanks,
Simon

**Comment by ghost** [comment]
Is there a way to disable this feature?

Am I required to use external/named volume ?

**Comment by ghost** [comment]
If I contribute such feature, would you merge it ?

**Comment by simonaronsson** [comment]
Hey! Sorry for the delay in response. No, I don't see that this suggestion should make it into watchtower as it would go against the intended container philosophy. Rather, I'd suggest that you go for the external/named volumes option. See https://success.docker.com/article/different-types-of-volumes
