### ISSUE TITLE
Fatal Error when specifying multiple notification types

### ISSUE THREAD

**Issue by mikey32230** [containrrr/watchtower#412]
When specifying multiple notification types via environment variable in comma separated format, the watchtower container will not start and has the following fatal error, for example:

`level=fatal msg="Unknown notification type \"email,slack\""`

This is currently still functional in the original v2tec/watchower image.
This is supposed to be a supported method as described in the documentation:

> The types of notifications to send are passed via the comma-separated option --notifications (or corresponding environment variable WATCHTOWER_NOTIFICATIONS), which has the following valid values:
> 
> email to send notifications via e-mail
> slack to send notifications through a Slack webhook
> msteams to send notifications via MSTeams webhook
> gotify to send notifications via Gotify

**To Reproduce**
1. For example, specify the following line in a docker-compose file, environment section (or equivalent):
`- WATCHTOWER_NOTIFICATIONS=email,slack`
2. Run the docker container
3. View docker logs to see error and view status to see container continuously restarting

**Expected behavior**
Watchtower container should be able to run with multiple notification types specified.

**Environment**
 - Linux
 - amd64
 - Docker Version: 19.03.5

**Logs from running watchtower with the `--debug` option**
`level=fatal` msg="Unknown notification type \"email,slack\""`

**Additional context**
The command line options still appear to work as expected, for example:
`--notifications email,slack`

**Comment by rguenther-dz** [comment]
i can fully confirm this issue

**Comment by simonaronsson** [comment]
Hi,

There is an open issue for this in the viper repository (https://github.com/spf13/viper/issues/380). The current workaround, which from what I can tell works for watchtower as well, is to replace any comma-separator with spaces:

```sh
$ WATCHTOWER_NOTIFICATIONS=slack,msteams go run . --debug
FATA[0000] Unknown notification type "slack,msteams"
exit status 1
```

```sh
$ WATCHTOWER_NOTIFICATIONS="slack slack" go run . --debug
DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized.
DEBU[0001] Retrieving running containers
...
```

**Comment by mikey32230** [comment]
> Hi,
> 
> There is an open issue for this in the viper repository ([spf13/viper#380](https://github.com/spf13/viper/issues/380)). The current workaround, which from what I can tell works for watchtower as well, is to replace any comma-separator with spaces:
> 
> ```shell
> $ WATCHTOWER_NOTIFICATIONS=slack,msteams go run . --debug
> FATA[0000] Unknown notification type "slack,msteams"
> exit status 1
> ```
> 
> ```shell
> $ WATCHTOWER_NOTIFICATIONS="slack slack" go run . --debug
> DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized.
> DEBU[0001] Retrieving running containers
> ...
> ```

If we use this workaround will it then break again when the actual issue is corrected? Or will it retain space delimitation support?

**Comment by simonaronsson** [comment]
> > Hi,
> > There is an open issue for this in the viper repository ([spf13/viper#380](https://github.com/spf13/viper/issues/380)). The current workaround, which from what I can tell works for watchtower as well, is to replace any comma-separator with spaces:
> > ```shell
> > $ WATCHTOWER_NOTIFICATIONS=slack,msteams go run . --debug
> > FATA[0000] Unknown notification type "slack,msteams"
> > exit status 1
> > ```
> > 
> > 
> > ```shell
> > $ WATCHTOWER_NOTIFICATIONS="slack slack" go run . --debug
> > DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized.
> > DEBU[0001] Retrieving running containers
> > ...
> > ```
> 
> If we use this workaround will it then break again when the actual issue is corrected? Or will it retain space delimitation support?

hard to say. from what i can tell, the space variant was available even before the issue, so it should be safe to use, but as i'm not a maintainer of viper, i cant really make any promises.
