### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by jscottelblein** [containrrr/watchtower#415]
So I have WT running all the time, and it seems to be working great, using this command:

```shell
$ docker run -d \
    --restart always \
    --name watchtower \
    --net=my-bridge \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup
```

Now, once in awhile I also want to manually run an update on a specific container in the list. i.e. I just want to run a WT check/update on the container named 'nginx'.

How would I go about that (w/out it shutting down the main WT container that I leave always running)?

TIA

P.S. Also, just being able to manually trigger an update against the entire list would be fine as well, my main thing Is I want to make sure the container that I leave running all the time doesn't quit when it's done..

**Comment by simonaronsson** [comment]
Hey there! 👋🏼

Thank you for the question! This is possible using the `--run-once` argument in combination with specifying the image to update, ie.

```sh
$ docker run -d 
    --net=my-bridge \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup \
    --run-once \
    nginx
```
