### ISSUE TITLE
[Question] Can watchtower detect images changes in local repo?

### ISSUE THREAD

**Issue by bluefangs** [containrrr/watchtower#416]
Hello,

I was looking for ways to streamline docker images updates and came accross watchtower. After reading a bit of the documentation, I've come to know that it is possible for watchtower to pull images from local docker repositories. 

My question is, is it mandatory to first push an update to the local repository (or dockerhub for that  matter) in order for watchtower to detect the update and pull? If I were run a `docker pull` or `docker load` and download a new repo manually, will it be enough for watchtower to restart the exising containers with the new image?

Scenario:

1. I have custom_img:1.0 in my local machine.
2. There is a container running off of the above image. (tag: custom_img_container)
3. I manually push a new image (custom_img:2.0) in my local machine
Question: Will watchtower detect that there is now a new image and restart `custom_img_container` based off custom_img:2.0 ?

Thanks.

**Comment by agtokty** [comment]
Hi,

I just try to test your scenario, but it didn't worked as expected for local images without pushing them to hub. 
I build another image with different tag version (also change image content to create image with different image id) but, local image is not used...

Regards

**Comment by simonaronsson** [comment]
Hey there! 👋🏼

Thank you for the question! Currently, watchtower requires images to be published on some kind of registry, however you might run the registry locally in a docker container if you want to keep your images local.

If you feel up for it, feel free to have a go at implementing updates based on local hash differences as well. I\d be happy to review it.

Closing this issue for now.

Best regards,
Simon

**Comment by 9bany** [comment]
Hi there!  @bluefangs @simskij 
- i has been added this feature in this commit: [326256d](https://github.com/9bany/watchtower/commit/326256d9db7e203e6fb69fb32ac982bcd058c67e)
That can be detect the images changes in the local machine.
- Check this example: https://github.com/9bany/watchtower/blob/main/examples/main.go

Requirements:
- You need to add a label `com.centurylinklabs.watchtower.local-image=true` when run your container.
- The new image have the same name with the image used in your container.

Thanks guys

**Comment by jebabin** [comment]
Thanks for your patch @9bany, but have you done a pull request of your patch ?

**Comment by 9bany** [comment]
Thank for your reminder @jebabin, i was push a pull request for this feature from here https://github.com/containrrr/watchtower/pull/1753
@simskij  please check it out, many thanks

**Comment by jebabin** [comment]
Many thanks @9bany , I was also wondering if instead of using the local-image label, we could assume that an image name without a "/" in it is local ? 
i’m not sure my assumption is valid

**Comment by 9bany** [comment]
I ain't test that case in this feature.
Anyway, i think it's fine cause watchtower already handle the `/` in the image named

You can see here @jebabin 

https://github.com/containrrr/watchtower/blob/36391b0ae791ef9a451fd63b34b117689f6248eb/pkg/container/client.go#L323-L340

**Comment by 9bany** [comment]
@jebabin please check this commentary, i think, it's a best answer 
https://github.com/containrrr/watchtower/pull/1753#issuecomment-1709976911
