### ISSUE TITLE
credHelpers field in docker config.json does not work for ECR

### ISSUE THREAD

**Issue by jtyler258** [containrrr/watchtower#419]
Following the document here https://github.com/containrrr/watchtower/blob/master/docs/credential-helpers.md

My docker config.json should be set up properly

```json
{
        "auths": {
                "https://index.docker.io/v1/": {},
                "xxxxxxx.dkr.ecr.xxxxx.amazonaws.com": {},
                "https://xxxxxxxx.dkr.ecr.xxxxxxx.amazonaws.com": {}
        },
        "credsStore": "secretservice",
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.5 (linux)"
        },
        "credHelpers": {
                "xxxxxxxx.dkr.ecr.xxxxx.amazonaws.com": "ecr-login"
        }
}
```

However with this setup I get an error `docker.errors.DockerException: Credentials store error: StoreError('docker-credential-ecr-login not installed or not available in PATH',)`

If I change my config to use ecr-login in the credsStore field instead of credHelpers it works fine
```json
{
        "auths": {
                "https://index.docker.io/v1/": {},
                "xxxxxxx.dkr.ecr.xxxxx.amazonaws.com": {},
                "https://xxxxxxxx.dkr.ecr.xxxxxxx.amazonaws.com": {}
        },
        "credsStore": "ecr-login",
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.5 (linux)"
        }
}
```

However this isn't ideal because now I can't pull public images from other container registries.

Am I missing something? Has anyone else been able to get the credHelpers field working with private registries?

**Comment by jtyler258** [comment]
Wanted to put this issue up in case anyone else runs across the same thing. I've spent probably 3+ hours on this already.

using credHelpers with docker-compose is currently not supported, credsStore must be used instead

[issue referenced here](https://github.com/danielcompton/amazon-ecr-credential-helper/commit/bf06378a3caddd59bab622c627e6f1e4136b8695)

**Comment by simonaronsson** [comment]
Hey!

Thanks for the report. @rymdo and I collaborated on this one and to the best of my memory we got it working.  I'll go ahead and reopen this as I want to dig deeper into this.

**Comment by simonaronsson** [comment]
Just as a follow up:

Did you follow the full instruction documented [here](https://containrrr.dev/watchtower/private-registries/#example)? It's vital that you actually build the ecr-helper in a separate container and launch that container as well or there won't be any binary for available for watchtower to use.

Also, the issue referenced is more than three years old, and the up-to-date readme does not mention any need for this workaround anymore.

In case you'd like us to look deeper into this, I'd suggest that you'd open a new issue with full configuration examples.

Thanks 🙏🏼
