### ISSUE TITLE
Delayed updates

### ISSUE THREAD

**Issue by wsw70** [containrrr/watchtower#426]
**Is your feature request related to a problem? Please describe.**

It happens that an image is released, then recalled / pulled back because of an issue. Currently such an image would be updated by watchtower (as designed) 

**Describe the solution you'd like**

The ability to delay the update, such as in *update the image, but only if it is 3 days old*

Ideally on a per image basis, but a global setting is ok as well. 

**Describe alternatives you've considered**

There are none I can think of, except a very long time between checks but this will not solve the issue of a faulty image is released right before the check (it will be even worse, as a possible recovery/corrected one will not be pulled quickly)

**Comment by simonaronsson** [comment]
Thank you for the report! 🙏🏼Unfortunately, this feature is not something that I'll prioritize right now. However, if you feel up for it - have a stab at it and put up a PR. I'd be happy to assist you in getting it merged 👍

**Comment by cdloh** [comment]
@simskij sorry to ping a closed issue but this is a feature that I'd quite like in watchtower. Is this still something you'd be willing to accept a PR for?

**Comment by simonaronsson** [comment]
> @simskij sorry to ping a closed issue but this is a feature that I'd quite like in watchtower. Is this still something you'd be willing to accept a PR for?

Definitely!

**Comment by pannal** [comment]
Bump! Any news on this?

**Comment by NebelNidas** [comment]
Bump

**Comment by minscof** [comment]
Bump
