### ISSUE TITLE
Watchtower update fallback

### ISSUE THREAD

**Issue by dinuta** [containrrr/watchtower#427]
Hi guys,

This tool it is a great help in infrastructures where docker is used, or in organizations where the adoption of Kubernetes  is conditioned by first testing the cloud deployments in docker.

I read your documentation and i did not see any fallback mechanism in case the docker image is "broken".

This is a critical feature that needs to be implemented, as per production environments.

Here i just imagine somekind of restApi mechanism or ENV VARS where you instruct watchtower to spawn the latest working image.

Or there is another case of a wrapper implemented by the user to treat such cases.

What do you think and is there a step towards?

Thanks,
Catalin

**Comment by iamareebjamal** [comment]
Not stale

**Comment by simonaronsson** [comment]
Hi,

There currently is no such functionality, and to be totally fair I lack the time to do it as this point. If you'd be up to providing a PR I would be more than happy to review and guide you in the right direction, though.

Thanks
