### ISSUE TITLE
Issues with updates of docker container images from private Gitlab/Dockerhub container registry.

### ISSUE THREAD

**Issue by avinashkurup** [containrrr/watchtower#428]
I'm using watchtower to test an automated container image update/download/run mechanism. The docker instance (which runs watchtower) is running on linux 5.0.19 built with yocto 2.7 in a qemuarm64 emulator. Docker has been tested and works correctly in pushing, pulling and running images in the QEMU ARM emulator. I face an issue with the following use case. I am uploading container images to gitlab container registry, I have also tested with docker hub and face this same issue. I am running these tests from behind a proxy.

This is the command I'm running to run watchtower.

docker run -d \
  --name watchtower \
  -v /home/root/.docker/config.json:/config.json \
  -v /var/run/docker.sock:/var/run/docker.sock \
registry.xxxx.io/avinashkurup/testcontainerregistry:mudball-arm64v8 --debug

$ docker logs watchtower
time="2020-01-07T05:27:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:27:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:27:18Z" level=debug msg="Scheduled next run: 2020-01-07 05:32:18 +0000 UTC"
time="2020-01-07T05:32:18Z" level=debug msg="Checking containers for updated images"
time="2020-01-07T05:32:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:32:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:32:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:32:18Z" level=debug msg="Scheduled next run: 2020-01-07 05:37:18 +0000 UTC"
time="2020-01-07T05:37:18Z" level=debug msg="Checking containers for updated images"
time="2020-01-07T05:37:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:37:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:37:18Z" level=debug msg="Retrieving running containers"
time="2020-01-07T05:37:18Z" level=debug msg="Scheduled next run: 2020-01-07 05:42:18 +0000 UTC"

I don't see any authentication taking place or any messages of downloading updated container images in the above logs? Is this normal?

docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
8a4a8b19ca28        containrrr/watchtower   "/watchtower registr…"   About an hour ago   Up About an hour                        watchtower

docker images
REPOSITORY                                                   TAG                 IMAGE ID            CREATED             SIZE
registry.xxxx.io/avinashkurup/testcontainerregistry   mudball-arm64v8     eb6acdf50e46        About an hour ago   9.14kB
containrrr/watchtower                                        latest              2ad95879d2ee        10 days ago         13.7MB

I cannot see the container image updated with the version on the registry when the time interval of 5 minutes elapses. I see that the downloaded container image is supposed to be automatically run. also is docker-compose needed for using watchtower? I am new to docker and watchtower, am I missing something here?

Regards,
Avinash. B.

**Comment by zoispag** [comment]
```
docker ps  CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES  8a4a8b19ca28        containrrr/watchtower   "/watchtower registr…"   About an hour ago   Up About an hour                        watchtower

```
Watchtower updates only running containers. It will not pull new images, for images found by ‘docker images’ command if a container is not running.
