### ISSUE TITLE
Watchtower HTTP API proposal

### ISSUE THREAD

**Issue by victorcmoura** [containrrr/watchtower#429]
Since Watchtower basically watches for docker registries and actively pulls images in order to check for outdated containers, it keeps continuously incrementing the registries' pull counter, making them useless. The counts can no longer be considered as user downloads/pulls.

This issue has been impacting some of my co-workers' personal projects and I have managed to use it as a working case in my bachelor's thesis. My proposal is to implement an HTTP API to enable DockerHub's Webook service to trigger Watchtower instances and make them check for updates only when a new image is pulled. Another use case would be a request made by a CI platform in order to trigger the update process.

I have already started some prototypes and I hope to be implementing a working version soon.

**Comment by dinuta** [comment]
Hi @victorcmoura 

Can you also consider update fallback in the api implementation? 

https://github.com/containrrr/watchtower/issues/427

**Comment by victorcmoura** [comment]
Hi, @dinuta. As I mentioned in the PR, I believe it is safer not to overwhelm, with more complex features, the first implementation and keep them for future contributions. But it is certainly something that I see as necessary to make Watchtower usage more feasible in production environments (at least small production environments).

**Comment by victorcmoura** [comment]
Closed in https://github.com/containrrr/watchtower/pull/432
