### ISSUE TITLE
docker swarm service update

### ISSUE THREAD

**Issue by edouardkleinhans** [containrrr/watchtower#43]
Is it possible to trigger an update to a docker swarm service ?

**Comment by stffabi** [comment]
At the moment watchtower can only update local running containers. I've briefly taken a look into the api, I think it should be possible to enhance watchtower with this functionality.

**Comment by ragemac** [comment]
That would be of great help for us as well. I hope we see this functionality soon. Thank you for your hard work

**Comment by dcrystalj** [comment]
this feature is must for future. Im looking forward to see this one day

**Comment by pjutard** [comment]
🙏

**Comment by oguya** [comment]
:+1:

**Comment by oguya** [comment]
Would deploying watchtower service to all manager & worker nodes in a swarm cluster achieve the same functionality as is in non-swarmed nodes??

**Comment by djmaze** [comment]
@oguya No, it does not work, because swarm manages the running containers itself.

As it turns out, automatically updating containers in a swarm-mode cluster is a lot simpler, since swarm itself queries the registry and updates the running containers [every time you call `swarm update --image`](https://docs.docker.com/engine/swarm/services/#update-a-services-image-after-creation). That means you just need to trigger a service update.

That is what I have just done with [shepherd](https://github.com/djmaze/shepherd).

**Comment by danieljuhl** [comment]
@djmaze looks interesting.. I assume shepherd needs to be constrained to the manager ?

**Comment by djmaze** [comment]
@danieljuhl You are right, of course. Also there needs to be exactly one replica running. 
 
I updated the README accordingly. Thanks!

**Comment by lnshi** [comment]
+1

**Comment by Dunky13** [comment]
Is there any update on this issue?

Seems like Shepherd does the job: https://github.com/djmaze/shepherd But I'd rather have one program updating my containers

**Comment by dhruvit01** [comment]
+1 https://github.com/djmaze/shepherd seem to be working fine. Just a concern that I see that logs talks about updating service all the time, regardless if the base image is changed or not...

**Comment by Dunky13** [comment]
@dhruvit01 exactly, That's an issue I'm experiencing with shepherd... And would like watchtower to pick up where they slack off.

**Comment by dhruvit01** [comment]
@Dunky13 : Agree. At this point I am using both but would like to have watch tower to support swarm. Any news/timeline on if/when this should be coming in?

**Comment by simonaronsson** [comment]
With that said; what are the actual functional requirements? Would someone even like to have a stab at implementing it? If so, feel free to - I'll make sure to review the PR. Thanks 🙏

**Comment by Dunky13** [comment]
Don't think this should be closed or stale imho. It's an issue that can/should be addressed in the future. Closing it will put in too much in the background.

**Comment by sixcorners** [comment]
If I use local containers and swarm containers will this try to update the swarm containers?
Does this at least support swarm insofar as it will skip them?

**Comment by simonaronsson** [comment]
@sixcorners I don't know to be totally honest as I don't use swarms myself. Feel free to try and report back! 😅

**Comment by bd8392** [comment]
+1

**Comment by simonaronsson** [comment]
Closing this issue. As @stffabi stated previously, the swarm support is currently extremely limited (if any). If you have any more specific errors, or would like to have a stab at implementing more thoroughly covering swarm support, please open a new issue and/or PR respectively.

Thank you.
