### ISSUE TITLE
Email Notification to multiple Adresses

### ISSUE THREAD

**Issue by S2ciOnur** [containrrr/watchtower#435]
Hello, I would like to use the email notification function and send it to several email addresses.
i.e. I would like to assign the environment variable 
WATCHTOWER_NOTIFICATION_EMAIL_TO
Assign more than one address
e.g. separated with a comma

like
WATCHTOWER_NOTIFICATION_EMAIL_TO=User1@mail.com, User2@mail.com

**Comment by simonaronsson** [comment]
Thank you for reporting this issue! This is solved in the referenced issue, which will be part of release v0.3.11.

**Comment by nhgiang196** [comment]
this is a **note** to someone who still had problem:
**there is no space between thoose commas**. If  you put a space to them. You will receive ERROR message: 
`Failed to send notification email:  553 5.1.3 The recipient address .... `
