### ISSUE TITLE
Support for Rocket.Chat notifications

### ISSUE THREAD

**Issue by jaylenw** [containrrr/watchtower#439]
**Is your feature request related to a problem? Please describe.**

I have been using Rocket.Chat for many of my dev-ops notifications instead of Slack. I recently implemented Watchtower for one of my projects and wondered if I could use the Slack notification feature to actually send notifications to a channel in [Rocket.Chat](https://rocket.chat). I did the following in my `docker-compose.yml` file:

```
environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
```

Where `WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL` was the incoming webhook I created for one of my channels. The value looked something like this `https://rocketchat.somedomain.com/hooks/fXXXXXXXX/yyyyyyyyyyyyyyy`. In all, the screenshot attached below shows it works (or at least I think it does :) ).

![rocket-chat-with-watchtower](https://user-images.githubusercontent.com/6505395/72318925-7d8f8f80-3652-11ea-8ef2-59c45196d7f4.png)

**Describe the solution you'd like**

The following are things I would like to see:

- Are there any missing information / features in my example screenshot of using Rocket.Chat that I would be experiencing if I were using Slack? If so, may we implement the missing features to have robust support of Rocket.Chat?

- If the team decides to support Rocket.Chat, may there be similar documentation on using it as there is for Slack?

**Describe alternatives you've considered**

I thought of using Slack, but with all of my dev-ops projects configured to use Rocket.Chat, I did not want to move over to a new platform, therefore, I gave it a shot to see if it would work with Rocket.Chat.

**Additional context**

I believe this issue would be related to #264 . Thank you to the Watchtower team and collaborators for your awesome work!

**Comment by simonaronsson** [comment]
Looks equivalent to what I get in slack 👍🏻

We're still in the process of migrating the notification support to using [shoutrrr](https://github.com/containrrr/shoutrrr). I've gone ahead and added Rocket.Chat to the list of services we should add at one point or another, but for now I'd say you're good to go with what you've got. 😅

Thanks 🙏🏼

**Comment by jaylenw** [comment]
Thank you @simskij for your reply. Sounds good! I look forward for the migration to [shoutrrr](https://github.com/containrrr/shoutrrr).
