### ISSUE TITLE
latest release on hub.docker.com

### ISSUE THREAD

**Issue by wasgehthierab** [containrrr/watchtower#44]
Hi,

on dockerhub the centurylink/watchtower is linking to this repository but it is last pushed: a year ago.
How do I get the latest version?
If I try to run another version (e.g. dockhippie/watchtower) I get an error, that my docker client (1.26) is newer then my docker server (1.24). How is this possible, when I run the container with `-v /var/run/docker.sock:/var/run/docker.sock \`?

**Comment by stffabi** [comment]
I've just taken over the maintenance of watchtower and I'm currently in the process of building up a new build infrastructure. As soon as this is setup, new builds will be published onto dockerhub. I'll also introduce version tags on dockerhub.

Regarding your versioning question. Newer builds from the master need to specify the API version which should be used. Please see https://github.com/v2tec/watchtower/pull/26#issuecomment-259382544

This may get changed in the future, I'm still thinking about some ideas to improve this behaviour.

**Comment by wasgehthierab** [comment]
So is it your repo i should use on dockerhub instead to get the latest version?
Thank you for the --apiversion tip, I will test it as soon as possible!

**Comment by stffabi** [comment]
The v2tec repo where the new images will be published is not yet public. As soon as everything is setup, you will find the latest images at https://hub.docker.com/r/v2tec/watchtower

**Comment by stffabi** [comment]
In the meantime you may also use my main development fork, https://hub.docker.com/r/stffabi/watchtower
Please be aware that these are development versions and there's no garantee that these versions will always be upgradable or functional.

**Comment by wasgehthierab** [comment]
I try to run the docker image via systemd
```
ExecStart=/usr/bin/docker run \
    --name watchtower \
    -e cleanup \
    -v /var/run/docker.sock:/var/run/docker.sock \
    stffabi/watchtower
    --apiversion=1.24
```
but the error is still there:
`level=fatal msg="Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)"`

**Comment by stffabi** [comment]
Aren't you missing a backslash after the imagename?

**Comment by wasgehthierab** [comment]
you are right. In the example you were posting there wasn't a backslash so I did not use it.

thank you!

**Comment by stffabi** [comment]
Oh sorry, didn't see that the example was wrong. My fault...
