### ISSUE TITLE
Container image updates from local filesystem.

### ISSUE THREAD

**Issue by avinashkurup** [containrrr/watchtower#441]
Hi,

I have been using Watchtower & it has some pretty cool features that I'm interested in. I would like to know
1. Is it possible for Watchtower to update running containers using images that are stored on a local filesystems (for eg. USB storage). I would like to do this employing lifecycle hooks the same way it works for online container registries?
2. Has there been any current effort/plans to implement anything similar to this?
3. Can this be done using any existing features? Please let me know.

Thanks,
Avinash.

**Comment by kylemiller3** [comment]
I would like to know this too. I do not use docker hub as I just ssh my container into a load command.

**Comment by simonaronsson** [comment]
Hi, and thank you for the report! 🙏🏼

This is possible, you could just use the --no-pull option as described [here](https://containrrr.github.io/watchtower/arguments/#without_pulling_new_images).

> When this flag is specified, watchtower will not attempt to pull new images from the registry. Instead it will only monitor the local image cache for changes. Use this option if you are building new images directly on the Docker host without pushing them to a registry.

This however, requires you to utilise `docker save` and `docker load` to move the images into the registry of the local docker host.

Hopes this helps!
