### ISSUE TITLE
Multiple Notifications Level

### ISSUE THREAD

**Issue by S2ciOnur** [containrrr/watchtower#442]
Is there a way, to configure multiple Notification level in Watchtower?

like

- WATCHTOWER_NOTIFICATIONS_LEVEL=info,panic,fatal,error,warning

i'm not sure, if this is possible because i didn't found anything in the documentation about multiple levrels.

If this is not Possible, could you please create a Feature Request out of this?

Thank you for your amazing work <3

**Comment by RDYW81** [comment]
I would like to know about this issue too ...

Or it may be that the terms are arranged hierarchically. If so, I could not find the exact arrangement in the documentation. 

I would be glad about an information - thank you very much in advance.

**Comment by simonaronsson** [comment]
It is actually hierarchical, in the following order:

* Debug
* Info
* Warning
* Error
* Panic
* Fatal

The level you select will include all levels below that one in the list.

Thanks you for asking! 🙏🏼
