### ISSUE TITLE
Rollback to previous container in case of error or exit

### ISSUE THREAD

**Issue by DaniyalCuboid19** [containrrr/watchtower#444]
Is it possible to rollback to previous version if new uploaded container is stop or exit due to error ?

**Comment by DaniyalCuboid19** [comment]
#90  mentioned earlier as well

**Comment by simonaronsson** [comment]
Unfortunately, it is not. Anyone up for the task is welcome to have a go at implementing it though.

**Comment by dankozlowski** [comment]
This seems pretty essential to me.  Is there any support for such functionality?

**Comment by piksel** [comment]
No, no one has tried to implement this afaik.
