### ISSUE TITLE
Does watchower ignore containers outside compose

### ISSUE THREAD

**Issue by rparree** [containrrr/watchtower#445]
Hi,

I have a watchtower setup inside a docker compose. It nicely monitors all containers inside the compose, but not those outside of it. I searched the documentation to see if this is expected behaviour, but was not able to find this.

I would like to also include monitoring of containers outside the compose file. 

I'm not using labels, all the config is:

```
WATCHTOWER_CLEANUP: "true"
WATCHTOWER_NO_PULL: "true"
WATCHTOWER_POLL_INTERVAL: "150"
```

Should watchtower include containers outside the compose file and if not, how can i enable this?

tx.,

**Comment by simonaronsson** [comment]
Hi there, and thank you for posting!

Watchtower should monitor all containers available through the mounted socket.
I know I've heard at some point that someone had to specify the default network in their compose-file, but I've never had to do that myself.

Would you mind running watchtower with the `--debug` flag and paste any output here?

Thanks 🙏🏼

**Comment by bnounours** [comment]
Hello,
I have the same behavior.
Here is my docker ps:
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                 PORTS                                                                                   NAMES
bb6dc1135ae3        bubuntux/riot-web           "nginx -g 'daemon of…"   3 days ago          Up 3 days              80/tcp                                                                                  riotim_riot_1
24bfd487dfe1        95f80ead9d6b                "/start.py"              4 days ago          Up 3 days              8008-8009/tcp, 8448/tcp                                                                 matrix_synapse_1
5745910594ff        97f1045583bf                "docker-entrypoint.s…"   4 days ago          Up 4 days              5432/tcp                                                                                matrix_db_1
56f5a7de4809        grafana/grafana             "/run.sh"                4 days ago          Up 4 days              0.0.0.0:3000->3000/tcp                                                                  grafana
```
docker-compose.yml file :
```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_RUN_ONCE=true 
    command: --interval 30 \
      --run-once \
      --monitor-only \
      --debug
```

Launch the docker: 
```
docker-compose up
Recreating watchtower_watchtower_1 ... done
Attaching to watchtower_watchtower_1
watchtower_1  | time="2020-03-27T00:42:24+01:00" level=info msg="Running a one time update."
watchtower_1  | time="2020-03-27T00:42:24+01:00" level=debug msg="Checking containers for updated images"
watchtower_1  | time="2020-03-27T00:42:24+01:00" level=debug msg="Retrieving running containers"
watchtower_watchtower_1 exited with code 0
```
=> No containers found

**Comment by mbrandau** [comment]
@bnounours beware you set the `WATCHTOWER_LABEL_ENABLE` flag to `true`. Only containers with the label `com.centurylinklabs.watchtower.enable=true` will be checked.

https://containrrr.github.io/watchtower/container-selection/

**Comment by simonaronsson** [comment]
Correct! The docs would definitely benefit from linking to https://containrrr.github.io/watchtower/arguments/#filter_by_enable_label from the page you linked though. I'll make an edit.

**Comment by rparree** [comment]
In my case the problem was that out system launched some containers using the image id and not the tag. So i believe this issues can be closed.
