### ISSUE TITLE
Documentation need more details about the --schedule Argument

### ISSUE THREAD

**Issue by sebkrueger** [containrrr/watchtower#446]
The document sad that watchtower has a cron like --schedule parameter, but there was not much information how to use it.

- Why there are 6 Parameters, what is the sixed about (seconds i guess!?), and is it at the beginning or the end?
- The example is nearly useless, without saying what time/date/intervall it will trigger the update
- Some more info what crontab syntax are supported e.g. slash, comma, hyphen "*/5" , "9-6" , "9,3"

**Comment by eapetitfils** [comment]
Had the same question today, more details are available in #87 
It looks like the go documentation [linked ](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format) by the watchtower documentation has been updated to remove the seconds entry, hence 5 fields only.

**Comment by simonaronsson** [comment]
Thanks for pointing that out! 🙏🏼

It would be super-helpful with a pull request updating the documentation to reflect what @eapetitfils linked from #87

**Comment by hepto** [comment]
I'm confused by these two issues (#446 and #87) - has watchtower now been updated to use the v3 of https://github.com/robfig/cron and therefore expect 5 fields?  On their docs it says to support 6 fields you need to explicitly construct the Cron object with `cron.WithSeconds()`, but my cursory glance at the watchtower source suggest that is not happening, so if using v3 it will expect 5 fields and then the fields are shifted by 1?

**Comment by hepto** [comment]
May have instantly answer my own question - I've not used go, but if modules are defined in the `go.mod` file, then it is currently set to `github.com/robfig/cron v0.0.0-20180505203441-b41be1df6967` which is an old/original version of `robfig/cron` that uses 6 fields by default.  Carry on!

**Comment by simonaronsson** [comment]
Docs have been updated to reflect this.
