### ISSUE TITLE
Confirmation/Approval Before Updating Container

### ISSUE THREAD

**Issue by heywoodlh** [containrrr/watchtower#447]
First off, thanks for all the awesome work on Watchtower. :)

<br>
<br>

**Is your feature request related to a problem? Please describe.**
I use Docker for running desktop applications on my Linux laptops (i.e. Firefox, Tor Browser, etc.). If I have Watchtower running in the background while using one of these applications in a Docker container it will often kill the container without warning so that it can run a new container with the new image.

The delay is brief as the updates are usually relatively quick, but still annoying when I'm in the middle of some sort of session with the container and it just dies and re-opens. For example, if I'm using Firefox in a Docker container and I'm browsing Watchtower can just kill my Firefox session after pulling an updated image for the image I am using for the container.

<br>
<br>

**Describe the solution you'd like**
It would be awesome if Watchtower supported a way to notify a user that an image update is pending and then for the user to confirm the update before Watchtower attempts to kill the container after pulling the image.

Preferably for my use-case, it would be great to have desktop notifications and confirmation prompts. However, I understand if that's out of scope since containers are typically not geared toward desktop use. 

A potential workflow could be something like this (using Slack as an example):

1. User sets up a Slack app for Watchtower.
2. Allow Watchtower to send **_and receive_** messages using that app.
3. When Watchtower has pulled a new image for a running container, send the user a message via Slack prompting with yes/no for an update.
4. When user approves the update, kill the running container and replace it with a container using the newer image. If the user doesn't approve the update, wait for a time before prompting again (perhaps with a timeout configuration setting).

If there were some way at all to approve container updates that would be great. I looked at the documentation and saw no feature/argument there for something like this. I think this would be beneficial not just for my use case, but I think it'd probably be a cool feature for Watchtower to implement in general.

<br>
<br>

**Describe alternatives you've considered**
Looking at the Watchtower documentation I don't know if there is a possible alternative aside from just not using Watchtower and pulling images manually or writing some alternative program/shell script for this specific use-case (which I will probably attempt in the meantime).

**Comment by simonaronsson** [comment]
Thank you for the report! 🙏🏼

Unfortunately, this is not something we're looking to implement at this time. However, If you'd like to have a stab at implementing it, I'd be happy to assist in reviewing the code.
