### ISSUE TITLE
Image not found, private repository

### ISSUE THREAD

**Issue by EAnushan** [containrrr/watchtower#45]
I'm getting the below issue when trying to update my images from a private repository. I've provided the `config.json` to authenticate against my repository. I'm running https://hub.docker.com/_/registry/ as my registry. Any idea why this might be happening?

```
user@server:~$ docker run -d --name watchtower -v /home/user/.docker/config.json:/config.json -v /var/run/docker.sock:/var/run/docker.sock centurylink/watchtower --debug
3c0c984b54da2e3d02743a473f8bae7ca21196f4c8efef5c1d6189b33da4e872
user@server:~$ docker logs watchtower 
time="2017-01-17T19:40:05Z" level=debug msg="Retrieving running containers" 
time="2017-01-17T19:40:05Z" level=info msg="Checking containers for updated images" 
time="2017-01-17T19:40:05Z" level=debug msg="Retrieving running containers" 
time="2017-01-17T19:40:05Z" level=debug msg="Pulling centurylink/watchtower:latest for /watchtower" 
time="2017-01-17T19:40:06Z" level=debug msg="Pulling privateregistry:443/my-image for /project_web_1" 
Error: image my-image not found
```

Docker pull works on my local machine using the same credentials. My registry uses a self signed certificate, so I had to add a `ca.crt` to `/etc/ssl/certs.d/privateregistry:443/ca.crt`. Do I need to mount this in the watchtower container as well?

**Comment by stffabi** [comment]
Can you try using the latest development version?
```
docker run -d --name watchtower -v /home/user/.docker/config.json:/config.json -v /var/run/docker.sock:/var/run/docker.sock stffabi/watchtower --debug --apiversion 1.24
```

Lately there has been a PR #26 which should fix problems with private registries. Please keep in mind `stffabi/watchtower` is a development fork and its implementation may change at anytime with backwards incompatible changes. New official images will be published soon, after some build environment refactoring has been completed.

Normally you don't need to to add the certificates, as communication is going through the unix socket and therefore communication goes out from the docker.

**Comment by EAnushan** [comment]
Ah, thank you. That seems to have resolved the issue. I'll use the `stffabi/watchtower` version for now until an official image is published.
