### ISSUE TITLE
Feature Request: Restart Other Container when Updated

### ISSUE THREAD

**Issue by ryester19** [containrrr/watchtower#453]
**Is your feature request related to a problem? Please describe.**
Thanks to fde6e730770521919fec63d04bbe0b93dff846f4, updating containers that shares a network stack with a "parent" container has been fixed. However, if the "parent" container is the one that's being updated, every other container attached to it loses connectivity until those containers are also restarted.

**Describe the solution you'd like**
Either:
1) Automatically find out what containers are using the updated container's network stack, and restart them also
2) (probably the more easier solution) Let people set a label on the "parent" container that tells watchtower what other containers to restart when the "parent" container is updated

**Comment by simonaronsson** [comment]
Hi, and thank you for you report! 🙏🏼

This idea sounds very useful, and while it's possible to accomplish something similar using [lifecycle hooks](https://containrrr.github.io/watchtower/lifecycle-hooks/), I'd much prefer for a cleaner, more robust solution.

Sadly, I don't really have any time at this point, so if someone is open to having a stabat it; feel free! I'll try to aid you as much as possible, through gitter, reviews and such.

**Comment by geraintwhite** [comment]
@ryester27 did you come up with a solution for this? I'm trying to do a similar thing with a flyway container (see https://github.com/containrrr/watchtower/discussions/678) where I need to start the flyway container when the other container gets updated by watchtower.
