### ISSUE TITLE
Watchtower should additionally set the maximum memory per container

### ISSUE THREAD

**Issue by touramakan** [containrrr/watchtower#456]
**The maximum memory usage per container should be limitable if this feature is toggle on.**
If the corresponding flag is active watchtower should additionally set the configured limit of maximum memory each container can consume.

**Possible solution**

- Introduce one flag to toggle the feature on/off
- Introduce a second flag to set the desired maxMemory
- Depending on the first flag set the max memory for each container, which does not have a memory less than the second flag

**Alternativ solution**
Start a new project on basis of watchtower (scan containers, stop/start with dependencies consideration) but without the functionality image update 

**Additional context**
As platform provider we face the challenge that end-user deploys their containers (apps), which sometime consume the whole available memory. Since we are already using the watchtower, we would like to extended with this feature.

**Comment by simonaronsson** [comment]
Unfortunately, I don't really think it fits within the scope of the project. I'd recommend that you set up a separate small go binary to do those checks for you, or maintain that feature in a fork.

To me, the use case of watchtower is quite clear, and I'd prefer not to alter that at this point but focus on providing the best experience possible for that.

Thank you for understanding, and hope you find a reasonable way forward. 🙏
