### ISSUE TITLE
Docker image for arm architecture (Raspberry Pi)

### ISSUE THREAD

**Issue by alexhaller** [containrrr/watchtower#46]
Hi,
can you please provide a docker image for the arm architecture to use it with my raspberry pi?

Thank you a lot in anticipation!
Alex

**Comment by stffabi** [comment]
It's on the roadmap. Hopefully I can put out a first version by the end of next week.

**Comment by stffabi** [comment]
@alexhaller in my main development fork you will find a first arm build, please see https://github.com/stffabi/watchtower/releases/tag/v0.1.3.

Would it be possible for you to test it? Please keep in mind it's a prerelease version and the API may change on the official versions. Furthermore It's not yet packaged in a docker container.

**Comment by stffabi** [comment]
New official armhf builds are now available on [docker hub](https://hub.docker.com/r/v2tec/watchtower/tags/).
