### ISSUE TITLE
Option to select which tags should be pulled

### ISSUE THREAD

**Issue by kiprasmel** [containrrr/watchtower#460]
**Is your feature request related to a problem?**

Yes. I'd like to be able to specify some sort of a pattern that would filter out only the matching tags, so that only they're pulled & updated by watchtower.

**Describe the solution you'd like**

Something like:

```sh
watchtower --allow-tags='v*'
``` 

or

```sh
watchtower --disallow-tags='dev-*'
```

Given tags `v1.2.0`, `dev-d8f7983`, `latest`,

the first option would allow the first tag (`v1.2.0`),
and the second option would disallow the second tag, allowing others.

**Additional context**

I'd like build (& thus auto-deploy) docker images not only for the `master` branch, but for other branches / PRs too, without automatically deploying them to production - that's all - thanks.

**Comment by zoispag** [comment]
I don’t get that. Watchtower will pull new version of the same tag. It will never jump from one tag to another afaik. Instead you can add the label to only allow updates for the containers that are running the images you actually want to be updated.

**Comment by simonaronsson** [comment]
The way I currently solve this for my own projects is that I push to two different tags depending on where the image should be deployed; `:latest` and `:latest-dev`. But as @zoispag points out, watchtower never jumps between tags but rather looks for hash changes of the same tag.

**Comment by kiprasmel** [comment]
Wait, so if I normally push to, say, `name:latest`, and then I push to `name:8439e4`, watchtower won't pull it?
If so - we can close, as this is exactly the behaviour I need!

**Comment by zoispag** [comment]
Exactly. If `name:latest` is running and watchtower is monitoring, only new builds with tag `:latest` will be picked up and update the running container.
