### ISSUE TITLE
Portainer agent and watchtower remote

### ISSUE THREAD

**Issue by SAOPP** [containrrr/watchtower#462]
Hi!

Guys I have an question 'bout pissibility to use for remote host running portainer agent container at remote docker host - it's possible to connect with remote key to remote host at tcp://ip:9001?

'Coz I'm just trying to do this, and I have an the next logs:

```
time="2020-03-12T14:16:09Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized.",
time="2020-03-12T14:16:10Z" level=fatal msg="Error response from daemon: Client sent an HTTP request to an HTTPS server.",
time="2020-03-12T14:16:10Z" level=debug msg="Retrieving running containers",
time="2020-03-12T14:16:14Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized.",
time="2020-03-12T14:16:15Z" level=debug msg="Retrieving running containers",
time="2020-03-12T14:16:15Z" level=fatal msg="Error response from daemon: Client sent an HTTP request to an HTTPS server.",
```

I'm not sure, but my portainer is working with this instance via this remote agent container at port 9001 now, maybe I need to running another container with different port on my remote host only for this watchtower?

I would be glad to any comments on this matter, I would like to keep the watchtower remotely. Thanks in advance!

**Comment by simonaronsson** [comment]
Hi and thank you for the report! 🙏🏼

Im a little bit unsure if I get what you're doing here, so please let me know if I misunderstand your question.

As the error says, you try to access an https resource using http, which won't work due to the encryption. See [this gist](https://gist.github.com/styblope/dc55e0ad2a9848f2cc3307d4819d819f) for info on how to set up your docker daemon for remote connections.

It should be noted though that this, in general, is a really dangerous practice and could leave you open for attacks. So in case you decide to do this, make sure you take proper precautions as to allow access from your known host only.

**Comment by SAOPP** [comment]
Thanks for answer. Okay, yes, I'm understand the risk, but at current moment I spoke about local connection to the remote instance.

I have an remote machine with portainer agent container - with this container I can connect from my main portainer instance to this remote machine. And I thinked I will connect watchtower to this machine via this agent. But nope.

So againt what I have:
1. machine with portainer agent (https://github.com/portainer/agent) e.g. 192.168.20.1
1.1 this machine have an container with agent at 9001 port
2. machine with watchtower linked to this the 1 machine e.g. 192.168.20.2
2.2 from this instance I want to connected to the 1 machine (tcp://192.168.20.1:9001) and I'm faced with log what u saw above.

Not sure about why watchtower detected my remote host as https, I don't have it there.

**Comment by simonaronsson** [comment]
Yes, you are correct. Watchtower does not work with the portainer agent. That one is for portainer only as far as I know.

**Comment by SAOPP** [comment]
Okay understood, I read that agent have an api, and I think... it's can be implemented at 3r party software... okay, thanks for the reply homie. Have a nice day time.
