### ISSUE TITLE
Multiple running watchtower instances

### ISSUE THREAD

**Issue by zamberjo** [containrrr/watchtower#468]
**Describe the bug**

I am implementing watchtower and I would like to know how I can do my 
case of use.

I have 2 types of containers: `[image]:test` and `[image]:prod`.

I would like the containers with tag `test` to be updated every 5 minutes. And the containers with tag `prod` through a schedule at 5am.

After studying it, I have decided to implement 2 watchtower:
 - The first with name `watchtower-test` with args:
	```--cleanup --tlsverify --interval 300 --label-enable```
 - The second with name `watchtower-prod` with args:
	```--cleanup --tlsverify --schedule "0 0 5 * * *"```

And add to `[image]:test` containers the label:
```com.centurylinklabs.watchtower.enable = true```

But I just realized that there cannot be 2 active watchtower containers.
[see code](https://github.com/containrrr/watchtower/blob/3fb299794b54175e5f06a6e12694651b596d5a4e/internal/actions/check.go#L36)

Could this deletion be parameterized?
Is there another possible solution? What do you think?

**To Reproduce**
```bash
$ docker run -d --name watchtower-prod --label com.centurylinklabs.watchtower.enable=false -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:0.3.10
[some_id1]

$ docker run -d --name watchtower-test --label com.centurylinklabs.watchtower.enable=false -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:0.3.10
[some_id2]

$ docker ps --all --quiet --filter name='watchtower$'|wc -l
1
```

Regards,

**Comment by simonaronsson** [comment]
I just reasoned around something very similar to what you're trying to achieve (although that user had a completely different goal) in #440. By adding a `WATCHTOWER_SCOPE_UID` env var, we could allow for multiple watchtower instances, as each would only kill other instances with the same scope uid.

Unfortunately, I don't  really have time to implement this change at this point, so if you'd like to have a go at it, it would be awesome. I would of course aid as much as possible with reviews, cheers and cookies! 😅

**Comment by victorcmoura** [comment]
I can try to implement the WATCHTOWER_SCOPE_UID approach

**Comment by zamberjo** [comment]
Hi @victorcmoura that would be great. The truth is that I have never programmed in GO, so it would be very helpful.

**Comment by ghost** [comment]
To avoid important communication to get lost in a closed issues no one monitors, I'll go ahead and lock this issue. If you want to continue the discussion, please open a new issue. Thank you! 🙏🏼
