### ISSUE TITLE
Docker image could maybe not be the absolute bare minimum?

### ISSUE THREAD

**Issue by DoTheEvo** [containrrr/watchtower#475]
I know its popular to be minimalistic but its not like watchtower is suppose to run in many instances. 

We could have nice things when its not trying to be under 5MB 
we could exec in to shell
we could have localtimezone from TZ variable
...

anyway, maybe its just mine issue where I cant exec in to it, but I am playing with various docker stuff and I am increasingly annoyed by these tiny alpine based stuff that makes stuff complicated and benefit being more or less just MB of disk space

**Comment by zoispag** [comment]
Just a fact: It very common for go apps to be distributed in scratch images.

**Comment by simonaronsson** [comment]
Thank you for submitting a report!

While I do understand where you're coming from, this is very much by choice as shell access into the container is something that, during normal usage, should not be needed.

Switching from the scratch image we currently use (which makes alpine look like a full-fledged desktop OS) to alpine would double the image size. This is a trade-off I've been unwilling to make, given that I think shell access should not be needed in the first place. It would also have the downside of *possibly* making our container less secure. 

With that said; If this is something you really think is needed, feel free to submit a PR with an alternative Dockerfile for making it easier to build your own, non-minimalistic version. I'd be more than happy to assist with PR's and getting your change merged. However, this is unlikely to ever become the default image available on DockerHub.

Thanks for understanding. 🙏🏼
