### ISSUE TITLE
obtain official dockerhub badge for watchtower docker image

### ISSUE THREAD

**Issue by ssbarnea** [containrrr/watchtower#48]
I think it would be really useful to get the official docker image badge, so people would know which is the official watchtower docker image.

At this moment there is no official watchtower image listed https://hub.docker.com/search/?isAutomated=0&isOfficial=1&page=1&pullCount=0&q=watchtower&starCount=0

**Comment by simonaronsson** [comment]
Official images are images published by docker. As far as I can tell, there is no possibility for us to apply or get enrolled without docker approaching us. If I'm wrong, feel free to let me know what's what though! 😅 

Closing this due to age. 

🙏

**Comment by ssbarnea** [comment]
Based on the documentation, official images do start with a PR.... see https://docs.docker.com/docker-hub/official_images/
