### ISSUE TITLE
WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER is not working

### ISSUE THREAD

**Issue by MrCaringi** [containrrr/watchtower#487]
**Describe the bug**
In Slack channel, the WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER value is not displayed

**To Reproduce**
1. Go to Slack Channel
2. see the log message, there is no Identifier for the host of the watchtower host

**Expected behavior**
It is expected to indentify the host running the watchtower container

**Screenshots**
screenshot attached

**Environment**
 - Linux Ubuntu Server (Virtualized)
 - amd64
 - Docker version 19.03.8

![2020-03-28_144707](https://user-images.githubusercontent.com/47096567/77833451-08850f80-7103-11ea-9455-e2fd5019f2ce.jpg)

**Comment by simonaronsson** [comment]
Thank you for your report! 🙏 

The existing slack notification won’t be maintained anymore as we’re currently moving to shoutrrr for notifications. The new notification system is currently in test and will be released once found stable enough.

**Comment by MrCaringi** [comment]
thanks for the notice,
keep pushing!

---JF Caringi@MrCaringi 

    On Sunday, April 12, 2020, 8:19:06 AM CDT, Simon Aronsson <notifications@github.com> wrote:  
 
 


Thank you for your report! 🙏
 
The existing slack notification won’t be maintained anymore as we’re currently moving to shoutrrr for notifications. The new notification system is currently in test and will be released once found stable enough.
