### ISSUE TITLE
cant get env WATCHTOWER_SCHEDULE to work like I expect it to

### ISSUE THREAD

**Issue by DoTheEvo** [containrrr/watchtower#488]
**Describe the bug**
when I use env variable to pass cron format (6) schedule it does not actually work like cron format. both `0 * * * * *` and `0 0 * * * *` are executed every minute instead of every hour at xx:00 or every day at 00:00

**To Reproduce**
1. use [this](https://pastebin.com/CkL75Hj5) compose file with `WATCHTOWER_SCHEDULE=0 * * * * *`
2. run it  - `docker-compose up -d`
3. see debug log - `docker logs watchtower`
4. See scheduled date - one minute in to the future from when its run

**Expected behavior**
the date should be the next whole hour

I tried from documentation example `0 0 4 * * *` and it sets to 4am next day instead of midnight of 4th of the next month.

**Environment**
 - arch linux host
 - x64
 - Docker version 19.03.8-ce

**Logs from running watchtower with the `--debug` option**

<details><summary>logs</summary>
<p>
    time="2020-03-29T23:13:07+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
    time="2020-03-29T23:13:08+02:00" level=debug msg="Retrieving running containers"
    time="2020-03-29T23:13:08+02:00" level=debug msg="There are no additional watchtower containers"
    time="2020-03-29T23:13:08+02:00" level=info msg="Starting Watchtower and scheduling first run: 2020-03-29 23:14:00 +0200 CEST"
    time="2020-03-29T23:14:00+02:00" level=debug msg="Checking containers for updated images"
    time="2020-03-29T23:14:00+02:00" level=debug msg="Retrieving running containers"
    time="2020-03-29T23:14:00+02:00" level=debug msg="Pulling containrrr/watchtower:latest for /watchtower"
    time="2020-03-29T23:14:00+02:00" level=debug msg="No credentials for containrrr in /config.json"
    time="2020-03-29T23:14:00+02:00" level=debug msg="Got image name: containrrr/watchtower:latest"
    time="2020-03-29T23:14:00+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:02+02:00" level=debug msg="No new images found for /watchtower"
    time="2020-03-29T23:14:02+02:00" level=debug msg="Pulling linuxserver/bookstack:latest for /bookstack"
    time="2020-03-29T23:14:02+02:00" level=debug msg="No credentials for linuxserver in /config.json"
    time="2020-03-29T23:14:02+02:00" level=debug msg="Got image name: linuxserver/bookstack:latest"
    time="2020-03-29T23:14:02+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:04+02:00" level=debug msg="No new images found for /bookstack"
    time="2020-03-29T23:14:04+02:00" level=debug msg="Pulling linuxserver/mariadb:latest for /bookstack_db"
    time="2020-03-29T23:14:04+02:00" level=debug msg="No credentials for linuxserver in /config.json"
    time="2020-03-29T23:14:04+02:00" level=debug msg="Got image name: linuxserver/mariadb:latest"
    time="2020-03-29T23:14:04+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:07+02:00" level=debug msg="No new images found for /bookstack_db"
    time="2020-03-29T23:14:07+02:00" level=debug msg="Pulling b4bz/homer:latest for /homer"
    time="2020-03-29T23:14:07+02:00" level=debug msg="No credentials for b4bz in /config.json"
    time="2020-03-29T23:14:07+02:00" level=debug msg="Got image name: b4bz/homer:latest"
    time="2020-03-29T23:14:07+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:09+02:00" level=debug msg="No new images found for /homer"
    time="2020-03-29T23:14:09+02:00" level=debug msg="Pulling redis:alpine for /nextcloud-redis"
    time="2020-03-29T23:14:09+02:00" level=debug msg="No credentials for redis:alpine in /config.json"
    time="2020-03-29T23:14:09+02:00" level=debug msg="Got image name: redis:alpine"
    time="2020-03-29T23:14:09+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:11+02:00" level=debug msg="No new images found for /nextcloud-redis"
    time="2020-03-29T23:14:11+02:00" level=debug msg="Pulling mariadb:latest for /nextcloud-db"
    time="2020-03-29T23:14:11+02:00" level=debug msg="No credentials for mariadb:latest in /config.json"
    time="2020-03-29T23:14:11+02:00" level=debug msg="Got image name: mariadb:latest"
    time="2020-03-29T23:14:11+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:14+02:00" level=debug msg="No new images found for /nextcloud-db"
    time="2020-03-29T23:14:14+02:00" level=debug msg="Pulling nextcloud:apache for /nextcloud-cron"
    time="2020-03-29T23:14:14+02:00" level=debug msg="No credentials for nextcloud:apache in /config.json"
    time="2020-03-29T23:14:14+02:00" level=debug msg="Got image name: nextcloud:apache"
    time="2020-03-29T23:14:14+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:16+02:00" level=debug msg="No new images found for /nextcloud-cron"
    time="2020-03-29T23:14:16+02:00" level=debug msg="Pulling caddy/caddy:latest for /caddy"
    time="2020-03-29T23:14:16+02:00" level=debug msg="No credentials for caddy in /config.json"
    time="2020-03-29T23:14:16+02:00" level=debug msg="Got image name: caddy/caddy:latest"
    time="2020-03-29T23:14:16+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:18+02:00" level=debug msg="No new images found for /caddy"
    time="2020-03-29T23:14:18+02:00" level=debug msg="Pulling bitwardenrs/server:alpine for /bitwarden"
    time="2020-03-29T23:14:18+02:00" level=debug msg="No credentials for bitwardenrs in /config.json"
    time="2020-03-29T23:14:18+02:00" level=debug msg="Got image name: bitwardenrs/server:alpine"
    time="2020-03-29T23:14:18+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:20+02:00" level=debug msg="No new images found for /bitwarden"
    time="2020-03-29T23:14:20+02:00" level=debug msg="Pulling portainer/portainer:latest for /portainer"
    time="2020-03-29T23:14:20+02:00" level=debug msg="No credentials for portainer in /config.json"
    time="2020-03-29T23:14:20+02:00" level=debug msg="Got image name: portainer/portainer:latest"
    time="2020-03-29T23:14:20+02:00" level=debug msg="Got auth value: "
    time="2020-03-29T23:14:22+02:00" level=debug msg="No new images found for /portainer"
    time="2020-03-29T23:14:22+02:00" level=debug msg="This is the watchtower container /watchtower"
    time="2020-03-29T23:14:22+02:00" level=debug msg="Scheduled next run: 2020-03-29 23:15:00 +0200 CEST"
</p>
</details>

**Additional context**
For some reason it thinks it should run every minute, I dunno if I can somehow exec the value of WATCHTOWER_SCHEDULE to check if its correctly set.
If I use interval for example 900 I see that it works and the first run is scheduled 15minutes in to the future..

**Comment by simonaronsson** [comment]
Hi!

Thank you for the thorough report!
I think the reason this is happening is because the string gets terminated after the first 0, thus resulting in the env var being `WATCHTOWER_SCHEDULE=0`.

Any difference if you use `WATCHTOWER_SCHEDULE="0 0 4 * * *"`?

**Comment by DoTheEvo** [comment]
log complains about failure to parse with both types of quotation 

- WATCHTOWER_SCHEDULE="0 * * * * *"
`level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"`

- WATCHTOWER_SCHEDULE='0 * * * * *'
`level=error msg="Failed to parse int from '0: strconv.Atoi: parsing \"'0\": invalid syntax"`

I tried to do it using command in docker compose instead of env variable but seems the behavior is the same 

<details><summary>docker-compose.yml</summary>
<p>

    version: '3'
    services:
      watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        hostname: watchtower
        restart: unless-stopped
        command: --schedule "0 0 * * * *"
        environment:
          - TZ=Europe/Prague
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_TIMEOUT=30s
          - WATCHTOWER_DEBUG=true
          - WATCHTOWER_INCLUDE_STOPPED=false
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

</p>
</details>

btw, I always do `docker-compose down` not just restart.

From my observation it seems the first symbol is ignored, if its 0 or * or whatever number, cant be a letter though. But if I ignore that character then rest of them behave like normal cron without a year

**Comment by piksel** [comment]
I think this is because of the optional "seconds" field. 
Older version of robfig/cron used the [Quartz](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html) format, with the first field being "seconds".

**Comment by DoTheEvo** [comment]
yeap, can confirm, tested and dunno where my eyes were, the first field is seconds.

**Comment by piksel** [comment]
Well, it is quite uncommon, and a mistake that the author rectified in v3. The only problem is that changing to v3 will suddenly break peoples setups.

**Comment by DoTheEvo** [comment]
Break is a strong word... change a bit the schedule sounds betters
and IMO not many people must have run on schedule if only now its found out.

But theres always just changing the documentation...

**Comment by piksel** [comment]
Oh, now I see what you mean. The watchtower documentation contains a link to the documentation for "v3" instead of the previous version of robfig/cron. Weirdly enough "https://pkg.go.dev/github.com/robfig/cron?tab=doc" still contains the old documentation...?

**Comment by gargamelonly** [comment]
So I am confused.
I get the same error with this configuration:
- WATCHTOWER_SCHEDULE="0 0 23 * * SUN"

Is this not correct?
