### ISSUE TITLE
Failed to send notification email:  unencrypted connection

### ISSUE THREAD

**Issue by opelx** [containrrr/watchtower#492]
**Describe the bug**

Using the notification type email, on unencrypted (private) network sending mail fails, even with NOTLS. The error is:

Failed to send notification email:  unencrypted connection

**To Reproduce**

use docker-compose.yml
--------------------8<-----------------------
version: '3'
services:
  watchtower:
    image: 
      containrrr/watchtower
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      --cleanup
    environment:
      - TZ='Europe/Berlin'
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=admin@example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=watchtower@example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=watchtower
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=3
-------------------->8----------------------
$ sudo docker-compose up -d

**Expected behavior**
Sending an email :)

**Environment**
 - Platform
clear linux 

 - Architecture
i86/x64

 - Docker version 
$ docker --version
Docker version 19.03.6, build 369ce74a3ce86a392e39e45d3960ce970fdfac97
$ docker-compose --version
docker-compose version 1.24.1, build unknown

**Logs from running watchtower with the `--debug` option**

time="2020-04-03T15:25:28Z" level=info msg="Starting Watchtower and scheduling first run: 2020-04-03 15:30:28 +0000 UTC m=+300.461220288"
Failed to send notification email:  unencrypted connection

**Additional context**

The setup is part of a private "Home Lab" without SSL connections yet, which isn't required at this time. Testing mail transfer works, I'm using mailu.io for this.

**Comment by piksel** [comment]
This is unfortunatly not supported by the go smtp library:
https://godoc.org/net/smtp#PlainAuth

**Comment by opelx** [comment]
> This is unfortunatly not supported by the go smtp library:
> https://godoc.org/net/smtp#PlainAuth

Ok, so far I understand (or even not), What is the purpose of WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY in this context?

**Comment by piksel** [comment]
Skipping the certificate verification, meaning you can use a self-signed cert

**Comment by opelx** [comment]
Ok, thanks.
