### ISSUE TITLE
Ignoring list of containers to update when given as arguments

### ISSUE THREAD

**Issue by andyleadbetter** [containrrr/watchtower#495]
**Describe the bug**
Have a suite of containers, some are created locally using dockerfile's and build, some are pulled from the docker hub registry.  I want watchtower to update the hub images only, and so launched the watchtower container with a list if container names to update, however watchtower is failing with an error about not finding an image that is associated to one of the local containers.

**To Reproduce**

Create two running containers, one using a local docker file, one using a docker hub image.
Explicitly name the containers 'Hub' and 'Local'

Launch watchtower container, with the argument 'Hub' 

I expect watchtower to monitor the hub container and update only that one. 

**Screenshots**

**Environment**
Debian 
Docker 19.03

**Logs from running watchtower with the `--debug` option**
time="2020-04-06T17:10:12Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-04-06T17:10:13Z" level=debug msg="Retrieving running containers"
time="2020-04-06T17:10:13Z" level=fatal msg="Error: No such image: sha256:b598110d0fffc42862269a25d8767dd95764d0740f318fd6c0a097f8a22de5bf"

**Additional context**

**Comment by tammert** [comment]
So, I think Watchtower is actually correctly ignoring other images in this.

There is an ongoing bug which caused a crash when local images were missing (#215), which I believe caused what you're seeing too. After the proposed fix in #571 I'm confident this problem would be gone too!

**Comment by simonaronsson** [comment]
Fixed by #571
