### ISSUE TITLE
Self-Signed Certificates Error ->  x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by opelx** [containrrr/watchtower#497]
After closing [#492](https://github.com/containrrr/watchtower/issues/492) I'm starting with self signed certificates to get email notification started.

**Describe the bug**
The logs shows now:

    Failed to send notification email:  x509: certificate signed by unknown authority

The SSL connection can be established:

        $ openssl s_client -starttls smtp -connect mail.home.lan:587
        CONNECTED(00000003)
        depth=0 C = DE, ST = Germany, L = SmallCity, O = "HomeLAN Servers, Limited", CN = Test Server
        verify error:num=20:unable to get local issuer certificate
        verify return:1
        depth=0 C = DE, ST = Germany, L = SmallCity, O = "HomeLAN Servers, Limited", CN = Test Server
        verify error:num=21:unable to verify the first certificate
        verify return:1
        ---
        Certificate chain
         0 s:C = DE, ST = Germany, L = SmallCity, O = "HomeLAN Servers, Limited", CN = Test Server
           i:C = DE, ST = LSA, L = SmallCity, O = "HomeLAN Root CA, Limited", OU = HomeLAN Server Research Department, CN = BigUser CA, emailAddress = BigUser@home.lan
        ---
        Server certificate
        -----BEGIN CERTIFICATE-----
        ...
        ieMaS+Q9Jrl7
        -----END CERTIFICATE-----
        subject=C = DE, ST = Germany, L = SmallCity, O = "HomeLAN Servers, Limited", CN = Test Server

        issuer=C = DE, ST = LSA, L = SmallCity, O = "HomeLAN Root CA, Limited", OU = HomeLAN Server Research Department, CN = BigUser CA, emailAddress = BigUser@home.lan

        ---
        No client certificate CA names sent
        Peer signing digest: SHA256
        Peer signature type: RSA-PSS
        Server Temp Key: X25519, 253 bits
        ---
        SSL handshake has read 1916 bytes and written 441 bytes
        Verification error: unable to verify the first certificate
        ---
        New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
        Server public key is 2048 bit
        Secure Renegotiation IS supported
        Compression: NONE
        Expansion: NONE
        No ALPN negotiated
        SSL-Session:
            Protocol  : TLSv1.2
            Cipher    : ECDHE-RSA-AES256-GCM-SHA384
            Session-ID: E77E84A2B0A52194748677DC3E01E70EBACADE3F298D147185FB70EA92C0C170
            Session-ID-ctx: 
            Master-Key: E74C19D2E5C5C2C94F1D895CFDCC25D9EEE05B83314E938569F13503966B343C9DBA5C171A7B539D0752CC45AC3397F5
            PSK identity: None
            PSK identity hint: None
            SRP username: None
            Start Time: 1586418479
            Timeout   : 7200 (sec)
            Verify return code: 21 (unable to verify the first certificate)
            Extended master secret: yes
        ---
        250 STARTTLS

After accepting these certificate in thunderbird I'm also able to email.

**Expected behavior**
working email notification :)

**Environment**

    $ cat ../watchtower/docker-compose.yml
    # watchtower
    version: '3'
    services:
      watchtower:
        image: 
          containrrr/watchtower
        restart: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        command:
          --cleanup
        environment:
          - TZ='Europe/Berlin'
          - WATCHTOWER_NOTIFICATIONS=email
          - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@home.lan
          - WATCHTOWER_NOTIFICATION_EMAIL_TO=admin@home.lan
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.home.lan
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=watchtower@home.lan
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=watchtower
          - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=3

    Platform
    clear linux

    Architecture
    i86/x64

    Docker version
    $ docker --version
    Docker version 19.03.6, build 369ce74a3ce86a392e39e45d3960ce970fdfac97
    $ docker-compose --version
    docker-compose version 1.24.1, build unknown

**Logs from running watchtower with the `--debug` option**

     Failed to send notification email:  x509: certificate signed by unknown authority

** Additional context **

I'm not sure if [#474](https://github.com/containrrr/watchtower/issues/474) is relevant here.

**Comment by simonaronsson** [comment]
Could you please try adding =true to the tls skip verify env var? I don’t think they get enabled implicitly as with flags.

**Comment by kevdogg** [comment]
@opelx -- As an alternative I have Let's Encrypt certs running on my postfix server.  I can verify these work without having to add any flags.

Any idea when the go smtp library will be updated to use TLSv1.3?

**Comment by opelx** [comment]
thanks for your suggestions. Finally I added ```--notification-email-server-tls-skip-verify ``` on command.

**Comment by simonaronsson** [comment]
I interpret this as the issue being solved. If the problem remains, feel free to create a new issue. Thanks. 🙏
