### ISSUE TITLE
Conditional upgrade

### ISSUE THREAD

**Issue by agilob** [containrrr/watchtower#499]
I would like to setup a conditional deploy on some containers.
Eg. a container is provided with a label pointing to a script:
`com.centurylinklabs.watchtower.condition=allow_docker_update.sh`

If the script has exist status 0 watchtower will not upgrade it and retry upgrade on the next schedule, if status 1, container will be stopped and upgraded.

**Comment by zoispag** [comment]
It should be possible to do this using the pre-update lifecycle hook, given that watchtower can read the exit status of the script.

**Comment by agilob** [comment]
>The failure of a command to execute, identified by an exit code different than 0, will not prevent watchtower from updating the container. Only an error log statement containing the exit code will be reported.

I would like to cancel update process if script fails.

**Comment by Minipada** [comment]
> > The failure of a command to execute, identified by an exit code different than 0, will not prevent watchtower from updating the container. Only an error log statement containing the exit code will be reported.
> 
> I would like to cancel update process if script fails.

Also interested in this 👆

**Comment by simonaronsson** [comment]
@agilob

> I would like to cancel update process if script fails.

If a pre-update lifecycle hook exits with a code other than 0, that container will be skipped. Give it a try and let us know if it satisfies your use case 👍

**Comment by simonaronsson** [comment]
Apparently this is not in the docs though... I'll check to make sure it's included in the currently released version of watchtower.

**Comment by simonaronsson** [comment]
Unfortunately, this has not been released yet. It will be included in the next release of watchtower.

**Comment by simonaronsson** [comment]
Closing this as the `pre-update` timeout changes are now live:

https://github.com/containrrr/watchtower/blob/9e7dfe7be442d1259b6ed5223558f2201f1fd43b/internal/actions/update.go#L76-L80
