### ISSUE TITLE
Suggestion: Add an option to not start the container again

### ISSUE THREAD

**Issue by mjohnson9** [containrrr/watchtower#5]
My containers are managed by systemd on CoreOS and, thus, if watchtower were to stop one, it would be started again by systemd. This means that the container is stopped by watchtower, a new one is started once by watchtower, killed by systemd, and started again by systemd. I feel that a more reasonable approach to this would for watchtower to kill the container(s) and allow systemd to bring them back up.

**Comment by davidgardner11** [comment]
Good suggestion. Will you please submit a PR with your enhancement and I'll review and merge.
