### ISSUE TITLE
New docker images on docker hub

### ISSUE THREAD

**Issue by stffabi** [containrrr/watchtower#50]
Introduce the new v2tec/watchtower image on docker hub.

**Comment by nielsole** [comment]
Hi, is there a way to use watchtower right now? I did not find a reference to prebuilt images nor any tips on how to build from source (there is no Dockerfile?!)
I am ooking forward to trying it out and thanks for your work.

**Comment by stffabi** [comment]
I'm not yet finished with the overall build process automatisation. In the meantime you may use the ci binary from the circleci artifacts, e.g. https://circleci.com/gh/v2tec/watchtower/102#artifacts/containers/0 in combination with the following [Dockerfile](https://github.com/v2tec/watchtower/blob/CenturyLink/Dockerfile). 

Hope this helps out for the time being.

**Comment by nielsole** [comment]
Hi thanks. Pushed it to dockerhub incase someone else needs it: `nielsole/watchtower`

**Comment by stffabi** [comment]
New official builds are now available on [docker hub](https://hub.docker.com/r/v2tec/watchtower/tags/).
