### ISSUE TITLE
Don't add timestamps to shoutrrr notifications

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#502]
One feature I’m missing while testing the new notifications on latest-dev is to disable the timestamps. Since I think most of the services show timestamps anyway, I think there should be an option to disable and/or format them in watchtower.

_Originally posted by @mbrandau in https://github.com/containrrr/watchtower/issues/264#issuecomment-612574815_

**Comment by mbrandau** [comment]
Also I think there should be an option to disable the log level too.

What would be your preferred way to fix this?
1. Add flags like `--notificationsShowTimestamps=false` `--notificationsShowLevel=false` (IMHO not showing these should be the default)
2. Generally remove them
3. ?

Where to fix this: https://github.com/containrrr/watchtower/blob/1fad78799f96736da00c95d271ff8fe8f2199cfe/pkg/notifications/shoutrrr.go#L44

**Comment by simonaronsson** [comment]
I'd say it's ok to just remove it, as none of the legacy notification services have it.

**Comment by simonaronsson** [comment]
`--notifications-show-level` would be more in line with the other flags, but other than that - all for. defaulting to off seems reasonable as well.

**Comment by mbrandau** [comment]
> I'd say it's ok to just remove it, as none of the legacy notification services have it.

The SMTP legacy service also shows timestamps and log levels. (I copied that function from there)

I'm gonna put up a PR that removes the timestamps from Shoutrrr notifications but adds a flag to optionally enable showing log levels.
