### ISSUE TITLE
Dependencies are not shut down before updating a container.

### ISSUE THREAD

**Issue by BakasuraRCE** [containrrr/watchtower#504]
Hi,

Please re-open this issue: https://github.com/containrrr/watchtower/issues/188

Still having the problem.

**Comment by simonaronsson** [comment]
Hi,

We'll continue from this issue then. 👍  Any difference in error message, or anything like that, or is everything just as before?

**Comment by BakasuraRCE** [comment]
The logs not show any visible, my config is:

```
>>> watchtower:

docker run -d \
    --name watchtower \
    --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e WATCHTOWER_POLL_INTERVAL=30 \
    -e WATCHTOWER_INCLUDE_STOPPED=true \
    -e WATCHTOWER_CLEANUP=true \
    -e WATCHTOWER_DEBUG=true \
    containrrr/watchtower

>>> Parent container:

docker run -d -it \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun \
  --name vpn \
  --restart always \
  --dns 1.1.1.1 \
  -p 1080:1080 \
  -v /myvolume dperson/openvpn-client -f ""

>>> Child container:

docker run -d --net=container:vpn --name dante -e workers=20 --restart=always -v /myvolume2/sockd.conf:/etc/sockd.conf bakasura/dante2
```

When the VPN is updated the log only show this:

```
time="2020-05-09T17:23:26Z" level=info msg="Stopping /vpn (1a4e22cf2c2...2cc0874) with SIGTERM",
time="2020-05-09T17:23:28Z" level=debug msg="Removing container 1a4e22cf2c2...2cc0874",
time="2020-05-09T17:23:28Z" level=info msg="Creating /vpn",
time="2020-05-09T17:23:28Z" level=debug msg="Starting container /vpn (f90bb296...fb8b4271044)",
time="2020-05-09T17:23:28Z" level=info msg="Removing image sha256:7e04e09e93add...1515cd4e476c",
time="2020-05-09T17:23:28Z" level=error msg="Error response from daemon: conflict: unable to delete 7e04e09e93ad (cannot be forced) - image is being used by running container 978aec00b063",
time="2020-05-09T17:23:28Z" level=debug msg="Scheduled next run: 2020-05-09 17:23:38 +0000 UTC",
time="2020-05-09T17:23:38Z" level=debug msg="Checking containers for updated images",
```

What happened?

1. The VPN container is recreated successfully and running
2. The Dante container is not modified and keep running with the reference to the old VPN container (not working the network)
3. When I try to restart Dante container fail and I must remove and create again with the new reference to VPN container

**Comment by simonaronsson** [comment]
Would you mind trying with adding a link from dante to vpn, using the `--link` option? In the next version we've added `com.centurylinklabs.watchtower.depends-on` which will let you emulate docker-compose's `depends_on` key in watchtower as well.

**Comment by BakasuraRCE** [comment]
Can you explain to me the use of link option?  I checked in docs and seems to be in disuse:

https://docs.docker.com/network/links/
https://docs.docker.com/engine/reference/commandline/network_connect/

**Comment by simonaronsson** [comment]
> Can you explain to me the use of link option? I checked in docs and seems to be in disuse:
> 
> https://docs.docker.com/network/links/
> https://docs.docker.com/engine/reference/commandline/network_connect/

It is deprecated, just as you've noticed. However, it is still usable and probably the most "native" way of adding dependencies between containers. However, the depends-on label should now be live, so please give that a try.

**Comment by kje1** [comment]
Hi. 

I run watchtower through the vtec2/watchtower image using docker-compose. The docker hub page for this image points here for raising issues although the image hasn't been updated for 2 years.

I'm getting the same error (conflicting options: hostname and the network mode") when trying to update containers that have network_mode: service:vpn. I've set up depends_on for my containers that are running through a VPN service but this doesn't seem to help.

Will switching images to containrrr/watchtower/ fix the problem?

Thanks!

**Comment by kje1** [comment]
Are there any updates on this? I've switched watchtower from vtec2/watchtower to containrrr/watchtower but still getting problems. My VPN container updated today but unfortunately none of my other containers which depend on VPN and have the depends on label attached to them were stopped and restarted correctly according to the linked container documentation (https://containrrr.dev/watchtower/linked-containers/).

I'm using depends_on but do I need to use link? Or maybe com.centurylinklabs.watchtower.depends-on?

**Comment by simonaronsson** [comment]
Hi there!

You need to use `com.centurylinklabs.watchtower.depends-on`.

Best, Simme.

**Comment by simonaronsson** [comment]
Closing this issue as the original question was solved with `com.centurylinklabs.watchtower.depends-on`. For how-to-style questions, where you're unsure whether it's an actual bug in watchtower, please start by posting in `Discussions` until it's been confirmed as a bug.
