### ISSUE TITLE
-- Feature Request -- Integrate Apprise-Api

### ISSUE THREAD

**Issue by bf8392** [containrrr/watchtower#507]
**Is your feature request related to a problem? Please describe.**
E-Mail notifications are not very handy for me...I like Telegram =) 

**Describe the solution you'd like**
To support multiple ways of notification, the fastest and easiest way is to integrate apprise-api https://github.com/caronc/apprise-api
You can have it as sidecar =). It would make your Image slimmer, and you have more than 50+! Notification-Cahnnels at once just by a curl-command =)

**Describe alternatives you've considered**
Build in apprise, but this would require more code. The above solution is the fastest and easiest, to add a whole lot of features to your container =)

**Additional context**

**Comment by simonaronsson** [comment]
Hey there!

We're already well on the way with integrating [shoutrrr](https://github.com/containrrr/shoutrrr), which is an apprise alternative written in go. It's currently in the latest-dev image on dockerhub and will be added with the next release.

Thanks 🙏🏼

**Comment by bf8392** [comment]
Okay thank you :-)

**Comment by simonmcnair** [comment]
....but I use apprise, and not shoutrrr ?  Please can you tell me if shoutrrr is compatible with apprise and if not why would you close a request for apprise by saying that you added something else ?
