### ISSUE TITLE
Automatic pruning after image update.

### ISSUE THREAD

**Issue by reitermarkus** [containrrr/watchtower#510]
**Is your feature request related to a problem? Please describe.**

I recently ran into the issue that I ran out of disk space because of all the old images, since they are not automatically removed.

**Describe the solution you'd like**

I would like to have an option to automatically prune the old image(s) when `watchtower` updates an image.

**Describe alternatives you've considered**

Running a cron job or similar to automatically prune everything.

**Additional context**

None.

**Comment by simonaronsson** [comment]
This is already possible using the [`--cleanup`](https://containrrr.github.io/watchtower/arguments/#cleanup) option. :)

Hope that helps.

**Comment by reitermarkus** [comment]
Thanks, @simskij! I was only looking for “prune”, so I completely missed “cleanup”.
