### ISSUE TITLE
Where is watchtower's github.io source code located?

### ISSUE THREAD

**Issue by victorcmoura** [containrrr/watchtower#514]
I would like to update the page with the latest /docs markdowns.

**Comment by simonaronsson** [comment]
Hey!

It's on the `gh-pages` branch. I've set it up to only release automatically through CI when we tag a new version, to prevent inconsistencies between what's yet to be released and what is live.

If you have any suggestion on how to improve this (which I think is long overdue), I'd be happy to assist in any way possible.

Thanks,
Simme

**Comment by simonaronsson** [comment]
Something like this, courtesy of the babel project, would likely make sense. We'd need to look into how to implement it properly using mkdocs though:

![image](https://user-images.githubusercontent.com/1596025/80278283-3efb7d80-86f5-11ea-9524-98e8c2ed37d9.png)

**Comment by victorcmoura** [comment]
The current solution is good, I just thought the docs had to be manually updated. If at some point I come through a better way to do this, I'll let the community know =)
