### ISSUE TITLE
Watchtower logs the password from auth credentials to stdout in debug

### ISSUE THREAD

**Issue by darthdeus** [containrrr/watchtower#517]
**Describe the bug**
When watchtower is started in debug mode, it will log `Loaded auth credentials {username password host} from config.json`. I understand that debug mode is for debugging, but at the same time I don't think anyone ever wants their passwords logged to stdout if there's even a slightest chance of preventing it, and even in debug I probably wouldn't expect to see a password logged.

**To Reproduce**
1. Run watchtower in debug mode
2. Setup a private registry connection
3. Look in the stdout log
4. See login/password being logged

**Expected behavior**
I'd expect at least the password to be redacted from the output, and if logging it is critical for some reason, then make it explicit with an environment variable or a flag. Secure defaults are secure.

**Comment by tammert** [comment]
Gave this a go, let me know what you think @simskij

**Comment by simonaronsson** [comment]
Looks great! Thanks for the contribution!
