### ISSUE TITLE
Confusion about container selection

### ISSUE THREAD

**Issue by sfkpmr** [containrrr/watchtower#519]
The Arguments page in the docs says ```you can restrict watchtower to monitoring a subset of the running containers by specifying the container names as arguments when launching watchtower```.

But on the Container selection page it says ```If you need to exclude some containers, set the com.centurylinklabs.watchtower.enable label to false```.

Is setting this to false necessary if you specify the containers you want to update when launching?

**Comment by opelx** [comment]
Hi, I like t make a crosslink to closed issue [label com.centurylinklabs.watchtower.enable=false is ignored #225](https://github.com/containrrr/watchtower/issues/225) which comes in this context relevant to em and maybe you.

**Comment by victorcmoura** [comment]
Container selection occurs by filtering running containers. On startup, this filter is built based on the passed arguments:
https://github.com/containrrr/watchtower/blob/3e069a707e56e97c951649c730e6e6189494a94f/pkg/filters/filters.go#L55

Currently, to build a container filter, the following local filters are set as a kind of pipeline:
1. Filter by name (returns true for all containers that are on the names list if it is set)
2. Filter by enabled label (returns true for all containers with the label `com.centurylinklabs.watchtower.enable=true` if --label-enable is used)
3. Filter by disabled label (returns false for all containers with the label `com.centurylinklabs.watchtower.enable=false`, regardless of any argument)

At runtime, every container that returns false for any one of these filters will not be monitored. So, if you don't include a container's name on the list (considering that there is a list), it should be ignored as it won't return true for this criteria.

> Is setting this to false necessary if you specify the containers you want to update when launching?

No, it doesn't seem necessary.
