### ISSUE TITLE
Customize either subject or text of notification email to differentiate source of email

### ISSUE THREAD

**Issue by kevdogg** [containrrr/watchtower#524]
I have containers running within multiple VMs which I utilize watchtower to keep at latest version.
The notifications that watchtower sends is basically the same on each host.

2020-04-30 00:18:18 (info): Starting Watchtower and scheduling first run: 2020-04-30 04:00:00 -0500 CDT

I was wondering if it would be possible to either customize the Subject or Body of the notification email that was sent so it would be easy for me to differentiate the source of the email.  Perhaps adding the name of the docker host or other identifying information would be helpful.

Thanks for the consideration.

**Comment by ilike2burnthing** [comment]
Perhaps introducing an optional environment variable like `-e name=Watchtower_vm3_wt2` (or Diego, Livingroom, Panther47, whatever) and then pass this to the log template, e.g. `Starting Watchtower_vm3_wt2 and scheduling first run` or `Starting Watchtower (Livingroom) and scheduling first run`.

Or, if possible, use `--name` for that.

**Comment by dearekaelle** [comment]
you can use WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG for that purpose.

**Comment by simonaronsson** [comment]
Thank you, @dearekaelle, for providing the solution. Closing this issue.
