### ISSUE TITLE
Fatal error - /var/lib/docker/overlay2

### ISSUE THREAD

**Issue by PaPaTheGMan** [containrrr/watchtower#531]
**Describe the bug**
Watchtower container keeps re-starting with the following error:
```
time="2020-05-03T17:02:53-04:00" level=fatal msg="Error response from daemon: readlink /var/lib/docker/overlay2/q����x�~\x0f��\x06��1=�\x10reC�6��7*��q8\t���5ܮ�p\U00015305�����p�[�\x184��W�\x1d�;S'���\x0e\x02g��d�m���r�1#Xn�J��e!�jz: no such file or directory",
```

**To Reproduce**
Start the container, watch the log

**Expected behavior**
I would expect the container to run normally.

**Screenshots**

**Environment**
 - Platform = Raspberry Pi 3B+ Raspberry Pi 3B+ running Debian Buster.  (All apt update's and upgrade's have been run.). Details = Linux RaspberryPi3B 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux

 - Architecture = aarch64

 - Docker version = docker.io, 18.09.1+dfsg1-7.1+rpi1+rpt1

**Logs from running watchtower with the `--debug` option**

[watchtower.log](https://github.com/containrrr/watchtower/files/4571831/watchtower.log)

**Additional context**
- Container had been running fine until Wednesday, 29-Apr.  Can't say what happened, specifically just noticed that the regularly scheduled purge didn't run and started to investigate.  Have removed. purged and re-pulled many times.  Container refuses to start.

- Contents of script to create and run the container are:
```
$ docker run -d \
    --name watchtower \
    -e TZ="America/New_York" \
    -e WATCHTOWER+CLEANUP=false \
    -e WATCHTOWER_INCLUDE_STOPPED=true \
    -e WATCHTOWER_POLL_INTERVAL=3600 \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    --restart unless-stopped \
    containrrr/watchtower:latest
```

- Other containers running on this machine are: pihole, duckdns, wetty,  portainer & netdata.

**Comment by sixcorners** [comment]
Looks related to moby/moby#35747.
Do normal docker commands work? It looks like the error is coming from dockerd.

**Comment by PaPaTheGMan** [comment]
Not sure what type of normal commands you mean, but the container seems caught in a restart loop.  This being a rather passive type of application, there really isn't any interaction.  The log does populate, as you see, but it doesn't execute the regular search/update mission.  It worked fine up until a few days ago.  There were no system changes other than regular 'apt update/upgrades' and Watchtower image updates.

Sorry I didn't catch the issue right away.  I run regular Docker Prunes every night with email notifications.  A couple of days went by with out any image clean-ups, which isn't all that unusual but then an image on multiple machines updated elsewhere but not here which triggered me to look further.

**Comment by PaPaTheGMan** [comment]
P.S., I'm happy to try some tests or send other background, if it will help.

**Comment by simonaronsson** [comment]
```
  -e WATCHTOWER+CLEANUP=false
```

This plus in the env var name seems like it could cause some issues.
Could you try fixing that and report back?

**Comment by PaPaTheGMan** [comment]
Good catch, I missed that typo.  I changed + to _.  Unfortunatelyit didn't help.  Same issue persists.  New log attached.

[post env change watchtower.log](https://github.com/containrrr/watchtower/files/4593152/post.env.change.watchtower.log)

**Comment by simonaronsson** [comment]
My initial reaction from looking at your log is that there are a lot of non-ascii letters in your overlay name. Just as @sixcorners, I suspect `dockerd` in this case.

> I saw this error today on a dind 17.11.0-ce on Linuxkit, on XFS. I wiped /var/lib/docker and the issue went away. Not sure the cause offhand.

**Comment by PaPaTheGMan** [comment]
Thanks, I'll take a look.

**Comment by simonaronsson** [comment]
Assuming this solved the issue as we've not heard back from the user in six months.
