### ISSUE TITLE
Should watchtower be able to pull from the local docker host?

### ISSUE THREAD

**Issue by wsw70** [containrrr/watchtower#533]
I have the following setup:

- a server called `srv` which hosts docker
- several containers whihc are pulled from Docker Hub
- a few containers which I built myself, hosted on `srv` 
- `watchtower` runs itself in a container on `srv`

I do not have a problem updating the Docker Hub  based images, but I get errors when trying to update a local one:

```
watchtower    | time="2020-05-04T23:44:22+02:00" level=debug msg="Pulling caddy:latest for /caddy"
watchtower    | time="2020-05-04T23:44:22+02:00" level=debug msg="No credentials for caddy:latest in /config.json"
watchtower    | time="2020-05-04T23:44:22+02:00" level=debug msg="Got image name: caddy:latest"
watchtower    | time="2020-05-04T23:44:22+02:00" level=debug msg="Got auth value: "
watchtower    | time="2020-05-04T23:44:23+02:00" level=debug msg="No new images found for /caddy"

watchtower    | time="2020-05-04T23:44:23+02:00" level=debug msg="Pulling dash:latest for /dash"
watchtower    | time="2020-05-04T23:44:23+02:00" level=debug msg="No credentials for dash:latest in /config.json"
watchtower    | time="2020-05-04T23:44:23+02:00" level=debug msg="Got image name: dash:latest"
watchtower    | time="2020-05-04T23:44:23+02:00" level=debug msg="Got auth value: "
watchtower    | time="2020-05-04T23:44:24+02:00" level=debug msg="Error pulling image dash:latest, Error response from daemon: pull access denied for dash, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
watchtower    | time="2020-05-04T23:44:24+02:00" level=info msg="Unable to update container /dash. Proceeding to next."
watchtower    | time="2020-05-04T23:44:24+02:00" level=debug msg="Error response from daemon: pull access denied for dash, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
```

Should `watchtower` be able to check for (and possibly update) the image stored on `srv`? (in the case of the log above, the image called `dash`). It has access to the docker socket so I do not see why not.

**Comment by simonaronsson** [comment]
Hi!

If you've tagged the image as dash:latest in your local registry, that should work. However, if you've got pulling enabled, it will try to pull the image from an image registry, which will lead to it failing if that image is unavailable. You could use the [`--no-pull` option](https://containrrr.github.io/watchtower/arguments/#without_pulling_new_images), but unfortunately, that would lead to your other remote images not being pulled either.

I could see this being solved by adding a no-pull option on the container label level. If you would like to have a stab at implementing this, I'd be happy to assist you with code reviews and whatever else might be needed to get it merged.

Thanks,
Simme.
