### ISSUE TITLE
Blacklist in addition to Whitelist

### ISSUE THREAD

**Issue by Miosame** [containrrr/watchtower#535]
Currently there is a whitelist behavior you can enable via [filter_by_enable_label ](https://containrrr.github.io/watchtower/arguments/#filter_by_enable_label) but a lot of setups would benefit instead from setting a blacklist of containers by label, simply because there is so many containers that would need to get a label added, versus just a few that shouldn't be checked each time - e.g. custom locally built containers.

**Comment by simonaronsson** [comment]
Hey,

Thank you for your issue!

That is already possible, by setting `com.centurylinklabs.watchtower.enable` to `false` without passing `--label-enable`.

Hope that helps :)

**Comment by Miosame** [comment]
@simskij ~~so how would watchtower then decide what containers it _should_ update? the proposed issue I have is to just add a label to containers it should straight up ignore, basically the same behavior as enable - but disable.~~

So the containers that have `com.centurylinklabs.watchtower.enable` set to false will be ignored? if that's the case, that would be extremely helpful to mention in the docs.

**Comment by victorcmoura** [comment]
@Miosame we are planning to mention it soon: https://github.com/containrrr/watchtower/pull/511#issuecomment-622283650

**Comment by simonaronsson** [comment]
It is in the docs, although not that clearly described:

> By default, watchtower will watch all containers. However, sometimes only some containers should be updated.
>
> If you need to exclude some containers, set the com.centurylinklabs.watchtower.enable label to false.

https://containrrr.github.io/watchtower/container-selection/

**Comment by Miosame** [comment]
I see, it was a separate page entirely, seeing that everything else was listed in Arguments too incl. examples and that was always the page I hit by googling things, I never went outside that page. Maybe a small note in the enable argument section linking back would help others alike to find it? :smile:

**Comment by simonaronsson** [comment]
That would be great! Would you mind creating a PR? :) I'd be happy to help you getting it merged.

**Comment by Miosame** [comment]
@simskij absolutely, I can see multiple ways of how this could be handled, one of these in #540

**Comment by simonaronsson** [comment]
Closing this now that the PR is merged. Thank you for your contribution! 🙏
