### ISSUE TITLE
Attempting to update container causes it to go away after an error

### ISSUE THREAD

**Issue by sixcorners** [containrrr/watchtower#542]
**Describe the bug**
Container doesn't exist after attempt to update

**To Reproduce**
```
docker pull containous/whoami:v1.4.0
docker tag containous/whoami:v1.4.0 containous/whoami
docker run -d --stop-timeout=300 containous/whoami
docker run --rm -it -v/var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -R
```
**Expected behavior**
Error occurs but everything is put back to how it was
roblem.

**Environment**
 - linux
 - x86_64
 - 19.03.8 and 18.09.9 

**Logs from running watchtower with the `--debug` option**
```
INFO[0000] Running a one time update.
DEBU[0000] Checking containers for updated images
DEBU[0000] Retrieving running containers
DEBU[0000] No pre-check command supplied. Skipping
DEBU[0000] No pre-check command supplied. Skipping
DEBU[0000] No pre-check command supplied. Skipping
DEBU[0000] No pre-check command supplied. Skipping
DEBU[0000] Retrieving running containers
DEBU[0000] Pulling containous/whoami:latest for /mystifying_brattain
DEBU[0000] No credentials for containous in /config.json
DEBU[0000] Got auth value:
DEBU[0000] Got image name: containous/whoami:latest
DEBU[0000] No authentication credentials found for containous/whoami:latest
INFO[0001] Found new containous/whoami:latest image (sha256:0f6fbbedd3777530ea3bedadf0a75b9aba805a55f6c5481ef0ebd762c5eeb818)
DEBU[0001] Pulling ubuntu:latest for /quirky_solomon
DEBU[0001] No credentials for ubuntu:latest in /config.json
DEBU[0001] Got auth value:
DEBU[0001] Got image name: ubuntu:latest
DEBU[0001] No authentication credentials found for ubuntu:latest
DEBU[0002] No new images found for /quirky_solomon
DEBU[0002] Pulling ubuntu:latest for /condescending_roentgen
DEBU[0002] No credentials for ubuntu:latest in /config.json
DEBU[0002] Got auth value:
DEBU[0002] Got image name: ubuntu:latest
DEBU[0002] No authentication credentials found for ubuntu:latest
DEBU[0003] No new images found for /condescending_roentgen
DEBU[0003] Pulling ubuntu:latest for /beautiful_perlman
DEBU[0003] No credentials for ubuntu:latest in /config.json
DEBU[0003] Got auth value:
DEBU[0003] Got image name: ubuntu:latest
DEBU[0003] No authentication credentials found for ubuntu:latest
DEBU[0004] No new images found for /beautiful_perlman
DEBU[0004] No pre-update command supplied. Skipping
INFO[0004] Stopping /mystifying_brattain (ef38c946a87f24b20f9de504079c12bd430be53a485a6455acc85a89157dbba5) with SIGTERM
DEBU[0005] Removing container ef38c946a87f24b20f9de504079c12bd430be53a485a6455acc85a89157dbba5
INFO[0005] Creating /mystifying_brattain
ERRO[0005] "stop timeout" requires API version 1.25, but the Docker daemon API version is 1.24
DEBU[0005] Retrieving running containers
DEBU[0005] No post-check command supplied. Skipping
DEBU[0005] No post-check command supplied. Skipping
DEBU[0005] No post-check command supplied. Skipping
DEBU[0005] No post-check command supplied. Skipping
```

**Comment by tammert** [comment]
Would seem the problem is caused by this:
`ERRO[0005] "stop timeout" requires API version 1.25, but the Docker daemon API version is 1.24`

Fix would be upgrading the used version of `github.com/docker/docker/client`. Until that time, you can't use the `--stop-timeout` flag, unfortunately.

**Comment by sixcorners** [comment]
I think the bigger issue is that the container can be dropped and forgotten about. Is there a way the error handling can be fixed so that when errors like this happen it falls back to just putting everything back to how it was?

**Comment by simonaronsson** [comment]
Not really, I'm afraid. We could, of course, implement such a fallback. That will require us to keep track of the hash of the previous image while updating, and upon failure, roll back to that version.

The problem with doing that is that it would keep repeating this procedure at every check interval, which is why I've been hesitant to add that feature.

In any case, I went ahead and bumped the min version required to `1.25` (https://github.com/containrrr/watchtower/commit/3b60add69d976ddbf235a1e387caa2ed1717d75b)

**Comment by sixcorners** [comment]
Would it make sense to implement an exponential back off in trying to update the container?

**Comment by simonaronsson** [comment]
> Would it make sense to implement an exponential back off in trying to update the container?

Maybe. Unsure. I'm generally a bit skeptic of introducing this kind of logic as it adds quite a bit of complexity to an otherwise pretty simple service. @containrrr/watchtower-contributors, care to pitch in?

**Comment by piksel** [comment]
@simskij If we added a fallback, then the back off for failed attempts should not be too hard/complex (as long as we can keep it in-process, as in no persistence). The easiest way, I guess, would be to have a record of "blacklisted" hashes that have failed on earlier attempts  and skip updating the container until a newer image is found (until the process exits).

**Comment by tammert** [comment]
In this case though, it was a problem where the API version was too low. In which case Watchtower can delete the container, but never recreate it... an exponential back off wouldn't fix this in the slightest. Are there any valid/realistic use cases for which a create would fail maybe once, but succeed 'magically' later?

**Comment by zoispag** [comment]
> Are there any valid/realistic use cases for which a create would fail maybe once, but succeed 'magically' later?

Only case I can think of, is the container relying on mounted data on start. Otherwise, being stateless as an image, situation should be identical on every container run.

**Comment by sixcorners** [comment]
@tammert The container could have been updated to not have the problematic configuration. watchtower itself could have been updated so it could handle it.
I think the bigger issue is that the container can be dropped and forgotten about. If this could roll back what it did when it failed then I sort-of wouldn't mind if the logic was that the container is ignored forever afterwards.

**Comment by piksel** [comment]
Both of those would be handled if it's based on the image hash (and not persisted when Watchtower is restarted/updated)

**Comment by simonaronsson** [comment]
I get that this is quite an unpopular opinion, and I'm happy to be overruled if anyone wants to contribute a reasonably complex pull request, but here are my two cents after giving this some thorough thought:

> The container could have been updated to not have the problematic configuration. watchtower itself could have been updated so it could handle it.

Still not convinced that this is enough to motivate the additional complexity. 

> I think the bigger issue is that the container can be dropped and forgotten about

In my opinion, the solution to that particular problem is to set up notification and/or monitoring.

> The easiest way, I guess, would be to have a record of "blacklisted" hashes that have failed on earlier attempts and skip updating the container until a newer image is found (until the process exits).

Out of the suggested implementations, this is the one I'm having the least problems with. In my opinion, it's **a lot** better and simpler than exponential backoffs.

In this suggestion, and in general, I guess:

- What would happen if it tries to update, fails, tries to roll back, and fails the rollback as well?
- What would happen if `cleanup` is enabled? I assume these two options would be mutually exclusive?

**Comment by simonaronsson** [comment]
Same as in the other cases of backoffs and rollbacks, it's not something we'll pursue. If anyone wants to contribute a PR that implements this behavior, you are more than welcome, but I'll go ahead and close this issue.
