### ISSUE TITLE
Slack messages are being sent as block quotes, how can I turn them into normal messages?

### ISSUE THREAD

**Issue by You-Honey** [containrrr/watchtower#546]
Is this watchtower's or logrus' feature? I'd want to remove block quote sign ">" from the slack messages.

How can I do it?

**Comment by simonaronsson** [comment]
I think this is a slackrus ”feature”. A new version will be released any day now that integrates shoutrrr, which will add a lot more flexibility.

**Comment by simonaronsson** [comment]
Now that 1.0.0 is released, switching from the notification option `slack` to `shoutrrr` solves this issue. 🥳

See https://containrrr.github.io/watchtower/notifications/#containrrrshoutrrr and https://containrrr.github.io/shoutrrr/services/overview/
