### ISSUE TITLE
using "schedule" throws error "Failed to parse int"

### ISSUE THREAD

**Issue by ThetaGamma** [containrrr/watchtower#548]
**Describe the bug**
I tried to switch from intervalls to use a schedule as described [here](https://containrrr.github.io/watchtower/arguments/#scheduling) in the docs. Here's the relevant code from my compose file:

```yaml
environment:
      - TZ=$TZ
      # Watchtower specific
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/redactedstring
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=":whale:"
      - WATCHTOWER_SCHEDULE="0 0 4 * * *"
      #- WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_MONITOR_ONLY=false
```
after starting up, I get the following error:

> time="2020-05-20T20:44:04+02:00" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"

I use the _latest_ tag for watchtower from docker hub, Digest: sha256:76fb863ea0c513d870f8634a13e061f81c387a62ecc27ad64f9b06179181c394

this kind of error message was also mentioned in #488 with no further link to an error, which causes this. I even experimented with the "newer" 5 field version with no luck

**To Reproduce**
`docker-compose -f "watchtower/docker-compose.yml" up -d --build`

**Expected behavior**
no error message and schedule a run once a day on 4am
**Environment**
 - Linux  5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Docker version 19.03.8, build afacb8b7f0

**Logs from running watchtower with the `--debug` option**

> time="2020-05-20T21:11:25+02:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2020-05-20T21:11:26+02:00" level=debug msg="Retrieving running containers"
time="2020-05-20T21:11:26+02:00" level=debug msg="There are no additional watchtower containers"
time="2020-05-20T21:11:26+02:00" level=error msg="Failed to parse int from \"0: strconv.Atoi: parsing \"\\\"0\": invalid syntax"

**Comment by luxcel** [comment]
I had the same error, remove the quotation marks around `WATCHTOWER_SCHEDULE="0 0 4 * * *"` and try with `WATCHTOWER_SCHEDULE=0 0 4 * * *`

**Comment by ThetaGamma** [comment]
can't believe it's that easy! I'm so used that strings need to be quoted somehow... thanks @xSMiNTx !
