### ISSUE TITLE
Configure update schedule containerwise

### ISSUE THREAD

**Issue by eloo** [containrrr/watchtower#549]
Hi,
i would like to ask if it is possible to configure the update schedule for specific containers.. 
For example i want to have all containers checked/updated once a week. But one specific container should be updated daily. My idea was if it is possible to use docker labels for such a configuration? 
So i can have a default configured in watchtower and overwrite it using container labels.

I'm not sure if this is a feature request or it is already possible and thatfore a question?

Thanks

**Comment by simonaronsson** [comment]
Hi,

This is, unfortunately, currently not possible. If you would like to have a stab at implementing this, feel free to submit a PR and I'd be happy to assist you with reviews and suggestions.

Thanks,
Simme

**Comment by simonaronsson** [comment]
I really think we should add this at some point, but rather than a schedule, I think specifying a maintenance window through labels would make more sense.
