### ISSUE TITLE
Running multiple instances for different hosts?

### ISSUE THREAD

**Issue by hepto** [containrrr/watchtower#550]
I appreciate you can't run multiple instances of watchtower pointing at the same Docker host, but should it be possible to run multiple on one host if they all point to different hosts?

I'm having my second instance be terminated (eventually) with the error:

```time="2020-05-19T05:19:34Z" level=info msg="Found multiple running watchtower instances. Cleaning up."```

But in the `run` I have that pointed at a different `host` than the others.  Therefore, when it is checking for other watchtower instances, how is it finding the ones pointing to other hosts?

That is, even though it is running on `hostA`, as it is configured to look at `hostB` that is where I thought it would check for other instances, but it looks like it makes the check on `hostA` still.

I can understand why you would not want multiple instances checking the _same_ host, but it seems reasonable to me that having them pointed at other hosts would be OK.  Do you think it should or what am I missing?

Hope that makes sense - ultimate goal is to have multiple watchtowers running on one host, but all monitoring containers on other hosts, using the `--host` switch.

**Comment by simonaronsson** [comment]
Hi,

Thanks for the issue! This is on its way in issue #511, which is approaching merging rapidly. 👍 

Best regards,
Simme

**Comment by hepto** [comment]
> Hi,
> 
> Thanks for the issue! This is on its way in issue #511, which is approaching merging rapidly. 👍
> 
> Best regards,
> Simme

Hey Simme - thanks for the reply.

I did read #511, but I wasn't sure it was exactly the same. In particular I don't really want to have to configure a scope in each container - I just want to point an instance at a host and have it check all the containers on that host.  The number of containers on the target host will be variable, so having to remember to configure each one won't really work ideally.

In this case, I'm not sure it's not a bug, as if I am pointing it at another host using `--host`, why is it then checking it's own host for other instances?

**Comment by simonaronsson** [comment]
The reason for this is because if it didn't, watchtower updating itself would lead to the container multiplying by 2 each time.

**Comment by hepto** [comment]
Ah yes!  I hadn't considered it updating itself!  OK, I can see the logic here now, thanks for clarifying.  Will keep an eye on #511 and see if I can make that work for me.
