### ISSUE TITLE
How to handle dockerfiles?

### ISSUE THREAD

**Issue by totti4ever** [containrrr/watchtower#551]
Hi, I have to extend the nextcloud docker image to be able to use Samba and therefore use an dockerfile based on the default nextcloud image.

Watchtower pulled the default docker file and ran the container using it, instead of rebuilding the dockerfile. Couldn't find anything in the docs, but what I need is that watchtower rebuilds the dockerfile.

thanks for this great project!

**Comment by simonaronsson** [comment]
Hi and welcome to the community,

Currently, watchtower only allows for monitoring changes of images stored in repositories.
My suggestion would be to push your modified image to a registry and use the image from there.

Best regards,
Simme.
