### ISSUE TITLE
Add REPO_HOST variable

### ISSUE THREAD

**Issue by kosssi** [containrrr/watchtower#552]
**Is your feature request related to a problem? Please describe.**
We can configure user and password directly on environment variable with REPO_USER and REPO_PASS, I imagine it's for hub.docker.com. If I would like used an private registry I should create `config.json` file, generate image, push it on my private registry and after launch docker-compose on multi server. If I can just configure this image with varialbes it's more easy.

**Describe the solution you'd like**
Add REPO_HOST

**Describe alternatives you've considered**
Use config.json file :D

**Additional context**
Thanks for this service

**Comment by simonaronsson** [comment]
Hi, and welcome to the community!

I might have misunderstood you. If so, I'm sorry for that.

You should never build a docker image containing tokens or secrets, as that opens up to all sorts of unintentional security vulnerabilities. Intead, you  could mount the `config.json` file into your docker container using volume mounts, as [described in the docs](https://containrrr.github.io/watchtower/private-registries/), removing the need to build a custom image and push that to your registry.

> When the Docker container is started, pass the configuration file to watchtower:
>
> ```
> docker run [...] \
>   -v <PATH_TO_HOME_DIR>/.docker/config.json:/config.json \
>  containrrr/watchtower
> ```


Regarding REPO_USER and REPO_PASS, they're used for all images for all containers that watchtower instance is monitoring, regardless of their origin. If you want to mix restricted registries and public ones, using `config.json` will be your way forward, as that allows for different credentials for each registry.

Hope that helps!

**Comment by kosssi** [comment]
I thought the local files were not imported into the remote container, I just checked and it works ...

thank you for the answer
