### ISSUE TITLE
Modify Shoutrrr Notification message

### ISSUE THREAD

**Issue by budimanjojo** [containrrr/watchtower#556]
Hello, I decided to migrate from Ouroboros to Watchtower. But there's something I want to have in the notification sent by Watchtower. I'm using `shoutrrr` and `telegram` for my notifications. Here's what it looks like when there's an updated container:
```
Found new linuxserver/jackett:latest image (sha256:<hash>)
Stopping /jackett (<hash>) with SIGTERM
Creating /jackett
Removing image sha256:<hash>
```
And for comparison purpose, here's how it looks like with Ouroboros:
```
Ouroboros has updated containers!
Host/Socket: <hostname> / var/run/docker.sock
Containers Monitored: 21
Total Containers Updated: 10
Containers updated this pass: 1
jackett updated from c844870baa to 028a37b167
```

What I want to have in Watchtower notification is the ability to have the `hostname`, `monitored containers`, `total updated containers`. Here's my mock up on more or less I want it to look like:
```
Found new linuxserver/jackett:latest image (sha256:<hash>)
Stopping /jackett (<hash>) with SIGTERM
Creating /jackett
Removing image sha256:<hash>

Host/Socket: <hostname> / var/run/docker.sock
Containers Monitored: 21
Total Containers Updated: 10
```
Hostname is very important at least for me, because I have multiple machines and some of them are running the same containers and when they got updated, I'll know which machine it is.

Question:
Is there an options for this? I can't find it anywhere. The `WATCHTOWER_NOTIFICATION_TEMPLATE` env variable can only modify the layout but not the entire message (or can I?)

**Comment by simonaronsson** [comment]
Hi, and welcome to the community! 🎉 

Correct, the template wont allow you to override the entire message. However, allowing for a summarized view has been requested earlier in #214 and #255, and now that we have shoutrrr in place, adding it shouldn't be that big of a task.

I can't make any promises on when I'll be able to get to it, given that I have very limited time for open source work at the moment, but I'll definitely give it a go! 👍

**Comment by budimanjojo** [comment]
Okay thanks, I'll follow the other issue and will close this one 👍
