### ISSUE TITLE
Notification grouping/summary instead of log notification spam 

### ISSUE THREAD

**Issue by frebib** [containrrr/watchtower#560]
**Is your feature request related to a problem? Please describe.**
We use the Slack notifications, and pipe them through a service which forwards them to a Telegram chat, and this has worked fine for years with several Watchtower builds/variations.
The issue is that Watchtower sends 4-6 notifications *per* container that it updates, which seems excessive

**Describe the solution you'd like**
Have a configurable to send *one* summary notification after the job has been done, with detail of which failed, succeeded and updated. Notifications are not logging, so having them decoupled would be good. Also an option to send error logging as notifications additionally would be good.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/775104/83243533-f02e8100-a195-11ea-95b3-20c7072265a5.png)

**Comment by simonaronsson** [comment]
Hi, and welcome to the community! 🎉 

I'm going to close this issue as your feature suggestion is tracked in #255 already.
