### ISSUE TITLE
Warn if using both `WATCHTOWER_NO_PULL` and `WATCHTOWER_MONITOR_ONLY` at the same time

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#570]
> Maybe we should warn/fatal on doing this combination of options, since Watchtower will essentially be useless with both those specified?

_Originally posted by @piksel in https://github.com/containrrr/watchtower/discussions/557#discussioncomment-23224_

As there is a very very corner use case for this, where one builds images locally using some kind of automation, but dont want the update to be automatic, it should likely not error out but rather warn that this combination might be unintentional, preferably once at startup.

**Comment by m-sedl** [comment]
Hello. Did I understand correctly that to solve the problem it is enough to check the presence of both flags in the `PreRun()` method in `root.go` and display a message to the user using `log.Warn()`?

Should I create a new branch for this task or can I make a pull request to the master?
