### ISSUE TITLE
Smarter Notifications for --monitor-only Mode

### ISSUE THREAD

**Issue by Turakar** [containrrr/watchtower#576]
**Is your feature request related to a problem? Please describe.**
I use the `--monitor-only` flag together with Gotify notifications. This makes it very easy for me to monitor container updates on my personal home server. If a container has an update, Watchtower sends a Gotify notification every 10 minutes (my configured interval). This spamming is annoying and not very useful.

**Describe the solution you'd like**
Watchtower should not resend the same information. Instead, it should only notify of each update once.

**Describe alternatives you've considered**
- Implementing a filter in between, acting like a proxy.
- Lowering the check interval. This increases latency of notifications and does not really solve the problem.
- Enabling automatic updates. Seems too risky too me.

**Additional remarks**
If each update is only notified of once, the number of unread notifications in Gotify would be a helpful indicator for the amount of admin work necessary. Currently its more like a boolean flag.

**Comment by simskij** [comment]
Hi, and welcome to the community! 🎉 

I kind of get what you're after, but at the same time, that would break behavior that people might already rely on either in their monitoring or for being reminded there's still work left to do. If this suggestion was to enter watchtower, it would have to be as a non-default toggle, and as we don't persist any information between container instances, it would have to be repeated in case the watchtower container was recreated or restarted.

Does this sound reasonable? I kind of want other people to weigh in as well before we decide in any direction.

Best,
Simme

**Comment by simskij** [comment]
Converting this to a discussion until we decide on something.
