### ISSUE TITLE
add new container into the monitor list

### ISSUE THREAD

**Issue by zhenyulin** [containrrr/watchtower#58]
As in the mode of monitoring particular containers for automatic updates and to avoid the unexpected updates of containers such as database, currently I need to stop and remove watchtower and re-run the setup script to add a new container to the monitor list.

Is there some command like "docker exec -it watchtower add <container_name>" for doing this?

**Comment by stffabi** [comment]
Currently this is not possible. But there are plans to bring some kind of label select functionality into watchtower, like mentioned in #4. With such a functionality, watchtower would automatically update all containers with a specific defined label. So you could just start containers with that label and watchtower would automatically pick them up for updating.

**Comment by stffabi** [comment]
The possiblity to watch containers with an assigned label has been introduced with #104
