### ISSUE TITLE
Watchtower is not detecting new images in docker hub private repository

### ISSUE THREAD

**Issue by aw94** [containrrr/watchtower#580]
**Describe the bug**
Watchtower doesn't seem to find new images in my docker hub repository.

```
time="2020-06-14T19:38:24Z" level=debug msg="Pulling awif1570/test:1.5 for /elegant_ramanujan"
time="2020-06-14T19:38:24Z" level=debug msg="Loaded auth credentials for user awif1570, on registry awif1570/test:1.5, from file /config.json"
time="2020-06-14T19:38:24Z" level=debug msg="Got image name: awif1570/test:1.5"
time="2020-06-14T19:38:25Z" level=debug msg="No new images found for /elegant_ramanujan"
```

I started Watchtower like this from the terminal
```
docker container run -d -v /var/run/docker.sock:/var/run/docker.sock -v /root/.docker/config.json:/config.json containrrr/watchtower --debug --interval 30
```

My config.json
```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "auth-key"
                },
                "awif1570/test": {
                        "auth": "auth-key"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.8 (linux)"
        }
}
~      
```

My latest image in my docker hub repository is called awif1570/test:1.6
Watchtower seems to be pulling 1.5 over and over because the download counter of that image keeps ticking up.
I've tried REPO_USER and REPO_PASS environment variables however I have the exact same issue.

**To Reproduce**

1. Run in terminal: 
```
docker container run -d -v /var/run/docker.sock:/var/run/docker.sock -v /root/.docker/config.json:/config.json containrrr/watchtower --debug --interval 30
```
2. Push new image to docker hub registry with docker push

**Expected behavior**
Watchtower should detect and pull latest image

**Environment**
 - Platform
Ubuntu 18.04.3 LTS

 - Architecture
amd64

 - Docker version 
Docker version 19.03.8, build afacb8b7f0

**Logs from running watchtower with the `--debug` option**
```
time="2020-06-14T19:38:24Z" level=debug msg="Pulling awif1570/test:1.5 for /elegant_ramanujan"
time="2020-06-14T19:38:24Z" level=debug msg="Loaded auth credentials for user awif1570, on registry awif1570/test:1.5, from file /config.json"
time="2020-06-14T19:38:24Z" level=debug msg="Got image name: awif1570/test:1.5"
time="2020-06-14T19:38:25Z" level=debug msg="No new images found for /elegant_ramanujan"
```

**Comment by simskij** [comment]
Hi, and welcome to the community! 🎉 

Watchtower only updates on image changes for the same tag. The usual way to solve this is to have a `:latest` tag that you update with each release in addition to adding your versioned tag.
