### ISSUE TITLE
Shoutrrr send params

### ISSUE THREAD

**Issue by PssbleTrngle** [containrrr/watchtower#590]
**Is your feature request related to a problem? Please describe.**
shoutrrr accepts a params map for some services.
These params are always an empty map and cannot be specified

**Describe the solution you'd like**
It would be great if there was any way to set them.
I do realise that parsing a map from one enviromental variable is not optimal, but maybe there is a way to provide the possibility

**Comment by simonaronsson** [comment]
I think we should keep this open. It is still an issue and something we'd like to implement.

**Comment by simonaronsson** [comment]
This is automatically mapped using queryParams in the URL in the later version of shoutrrr. This change will be part of the next release of watchtower.
