### ISSUE TITLE
Option/Argument to specify how many image should be kept

### ISSUE THREAD

**Issue by TECHNOFAB11** [containrrr/watchtower#591]
**Is your feature request related to a problem? Please describe.**
I would like Watchtower to clean up the old image, but still keep at least one around to be able to rollback fast

**Describe the solution you'd like**
An argument or maybe even a docker label to be able to specify how many of the last images should be kept (eg. 2)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by zoispag** [comment]
Hi there,

I find difficult to see how this would work. Watchtower pulls the same image. Technically it is possible, but they will either be dangling images left in the host (you will see SHAs with tag <none> of you run `docker images`) or watchtower should tag them with another names instead of deleting them.

In both cases I don't see how watchtower could know the old images' SHAs and delete them later, since there is no local state.

**Comment by TECHNOFAB11** [comment]
Wouldnt it be possible to pull the latest image, then check which SHA the old image has/tag it and save it. Then, when the next image should be pulled it could delete the oldest one for example. Or it could go by the date when it was pulled (https://stackoverflow.com/questions/39890137/how-can-i-check-when-was-a-docker-image-pulled), but i dont know if Watchtower has access to that without any volume mounting etc.

**Comment by zoispag** [comment]
I don't think watchtower should store SHAs. Local state would mean that the list is gone after a restart of the watchtower container. And an actual storage, would mean that users would need to give some persistance to watchtower storage, even if it is a real db, or a named volume.

@simskij any ideas?

**Comment by simonaronsson** [comment]
I totally agree. After discussing this with @piksel as well, we've come to the conclusion that this isn't something we'll pursue any time soon. Closing this issue and hoping you find another suitable way to do this. 👍  Labeling it `Status: Idea Bank` for easy discovery later.

**Comment by piksel** [comment]
This relies on either watchtower having persistent storage (doubtful that it's going down that route, but who knows?) or that the way it identifies/discovers images changes enough to be able to see multiple versions of the same image (and sort them chronologically).
