### ISSUE TITLE
Support for Docker via WSL2?

### ISSUE THREAD

**Issue by PhantomGamers** [containrrr/watchtower#604]
I'm unsure if watchtower just doesn't work under WSL2 or if I'm doing something wrong.

Using the quick start docker create command to create the watchtower instance launches and says
 `
time="2020-07-16T14:39:06Z" level=info msg="Starting Watchtower and scheduling first run: 2020-07-16 14:44:06 +0000 UTC m=+300.283507001"`  
However it never actually runs and the docker container doesn't restart properly after restarting windows (Docker reports that the container exited with code 255 but there are no errors in the log).

The only information in the log is the scheduling first run line above as well as `time="2020-07-16T14:39:10Z" level=info msg="Waiting for running update to be finished..."`

Seems that it never actually does anything.

I'm running Windows 10 Pro x64 build 2004 with Docker Desktop version 2.3.0.3 using the WSL 2 based engine. My other docker containers are working fine, watchtower is the only one I'm having problems with.

**Comment by piksel** [comment]
You can add `--debug` to get a bit more logging output. If there are no updated images, there is no additional output on `info` logging level.
