### ISSUE TITLE
Home Assistant Notifications

### ISSUE THREAD

**Issue by Morphy99** [containrrr/watchtower#618]
**Is your feature request related to a problem? Please describe.**
None of the current notification methods are suitable

**Describe the solution you'd like**
Would like to be able to see progress of updates and any updates available when in monitor mode in the Home Assistant GUI.

**Describe alternatives you've considered**
All the current options involve setting up a third party service which I don't need.

**Additional context**
Using Watchtower to update and monitor container updates on a Home Assistant focused machine.

**Comment by piksel** [comment]
To get the notifications into Home Assistant, it looks like the `POST /api/events/<event_type>` could be used, and then by creating a custom card that receives and interprets those events you could get them displayed in Lovelace.

If that is something that you think would work we can add it to [containrrr/shoutrrr](https://github.com/containrrr/shoutrrr/) as a notification service.

**Comment by Morphy99** [comment]
That sounds like something which would work!

**Comment by dougle03** [comment]
> That sounds like something which would work!

Did you get this working? Any chance of sharing your approach?
Thanks,

**Comment by Morphy99** [comment]
> > That sounds like something which would work!
> 
> Did you get this working? Any chance of sharing your approach?
> Thanks,

Sorry missed this. No. Tbh I was struggling to get my head around shoutrrr. I can't install it as advised as I'm running a read only OS. Would have to use as a container which is a bit weird for calling a service and I can't find any guides or info. I don't think HA has been added to shoutrrr yet in any case.

**Comment by piksel** [comment]
@Morphy99 Yeah, sorry, that wasn't very clear of me. If you are able to figure out how to display the information in Home Assistant, then we could add a service to Shoutrrr that talks to it using whatever method works. I don't use HA myself, and since some experimenting is needed to get it working I don't really have anything to add to Shoutrrr until then.

**Comment by simonaronsson** [comment]
Closing this in favor of https://github.com/containrrr/shoutrrr/issues/86
