### ISSUE TITLE
Can't pull from registry.gitlab.com

### ISSUE THREAD

**Issue by weslleycamilo** [containrrr/watchtower#62]
Hello Guys,

I have searched in the issues to see if there is a solution to it but i am not able to pull from any of my private repositories.

Am I missing something?

  docker run -d \
  --name watchtower  \
  -v /home/weslley/.docker/config.json:/config.json \
  -v /var/run/docker.sock:/var/run/docker.sock \
  drud/watchtower  \
   --cleanup \
    -i 10 \
    --debug

I have looked to the logs and it just say  "... denied: access forbidden"

I also tried 

  docker run -d \
      --name watchtower  \
      -e REPO_USER="user" \
      -e REPO_PASS="pass" \
      -v /var/run/docker.sock:/var/run/docker.sock \
      drud/watchtower  \
       --cleanup \
        -i 10 \
        --debug

Can anyone help me ?

THank you.

**Comment by stffabi** [comment]
Did you try the latest master builds? Should be fixed on master. Currently latest docker hub images are still pending, but please see #50. Someone put up a recent version on docker hub.

**Comment by weslleycamilo** [comment]
I didnt try that.. I thought it was available  on docker hub already and i was doing something wrong lol.

I will try it out. 

Thank you.

**Comment by stffabi** [comment]
New official builds are now available on [docker hub](https://hub.docker.com/r/v2tec/watchtower/tags/).
