### ISSUE TITLE
update container with new image tag

### ISSUE THREAD

**Issue by willzhang** [containrrr/watchtower#621]
## question
i run docker build in jenkins cicd, then push the image to harbor , every image have a new image tag with BUILD_ID env, then i will update the image in remote docker hosts by docker pull and docker run。

## what i want
when i push a new image with new tag to harbor registry , watchtower update a container with the new tag，but watchtower only suppport update a fixed tag？

and if you always use the same tag ,  It's impossible when you want to perform a rollback some day。

**Comment by simskij** [comment]
Hi and welcome to the community!

Yes, watchtower only allows for tracking a fixed tag. At the moment, we have no plans to introduce features that allow for following changing tag names. The usual approach is to use `latest` as a static tag and point it at the same images as your versioned tags.
