### ISSUE TITLE
Environment variable persistance

### ISSUE THREAD

**Issue by nickwaring** [containrrr/watchtower#63]
Hi,

Having setup watchtower, it worked perfectly - stopping containers, updating images & restarting images.

However, on restart all my containers were missing the environment variables which were specified when I setup the container. Examples include:
  -e PUID=1033 \
  -e PGID=65536 \
  -e TZ=Europe/London \

Is this a known issue or something strange with my setup?

Thanks

Nick

**Comment by stffabi** [comment]
What version of watchtower are you using? Could you please try the latest official images from [docker hub](https://hub.docker.com/r/v2tec/watchtower/tags/).

These should be working fine.

**Comment by nickwaring** [comment]
hi, thanks for the reply. I'm using the latest image from docker hub.

It continues to delete the environment variables from my container (all other port and drive mappings are carried forward)

Interestingly, when I try to connect to the container to view the logs etc (docker exec -t watchtower /bin/bash) I get an error:
`rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/bash\": stat /bin/bash: no such file or directory"`

Is this normal?

**Comment by stffabi** [comment]
Could you please send the docker inspect output of your watchtower container?

You can't connect to the container, the container doesn't contain any binaries except watchtower. This makes the image small and there are no dependencies that are needed. Logs are written to the docker log.

**Comment by stffabi** [comment]
Could you also provide an example docker run command for a container where the environment variables get lost on update?

**Comment by nickwaring** [comment]
Hi,

Docker run command:
`docker run \
  --name=plexpy \
  --restart always \
  -itd \
  -v /volume1/docker/plexpy:/config \
  -v /volume1/public/security/fromnas:/security \
  -v "/volume1/Plex/Library/Application Support/Plex Media Server/Logs":/plex_logs \
  -e PUID=1033 \
  -e PGID=65536 \
  -e TZ=Europe/London \
  -p 8089:8181 \
  linuxserver/plexpy`

**Comment by nickwaring** [comment]
and inspect output of the watchtower container:


[temp.txt](https://github.com/v2tec/watchtower/files/784981/temp.txt)

**Comment by stffabi** [comment]
Thanks for the output. From the inspect of the watchtower container, it seems like you are still using the centurylink/watchtower image.

```
"Image": "centurylink/watchtower",
```

These are the old images maintained by centurylink. V2tec has taken over the maintenance of watchtower and new images will be published as `v2tec/watchtower`.
Could you switch to that version and try it again?

**Comment by nickwaring** [comment]
Hi,

I've updated but now have api version problem! (which is referred to in another issue).

Nick
