### ISSUE TITLE
Found a possible typo on the wiki

### ISSUE THREAD

**Issue by jpoggi** [containrrr/watchtower#634]
**Describe the bug**
I think I may have found a typo on your wiki.

**To Reproduce**
1. Go to 'https://containrrr.dev/watchtower/container-selection/'

**Expected behavior**
Environment variable '**WATCTOWER_LABEL_ENABLE**' should be written **'**WATCHTOWER_LABEL_ENABLE**'**

**Comment by piksel** [comment]
Hello! First of all, I just wont to point out that you can actually make PRs with changes like this one directly from the documentation by clicking the ✏.
If you do that now however you might notice that it's already fixed. Unfortunately, documentation is updated on release (as the current documentation should always reflect the current release), but that also means that typos like this doesn't get updated until the version is released.

@simskij any thoughts on how to handle documentation updates that are equally relevant for the *current* release?

**Comment by jpoggi** [comment]
I, already fixed seems a good reason to close this issue.

Even if we have to wait for the next release.

Thx.
