### ISSUE TITLE
Watchtower unable to update containers, skipping to next

### ISSUE THREAD

**Issue by carlsimmons81** [containrrr/watchtower#636]
I'm not sure what I'm doing wrong but watchtower fails to update anything.  I'm running watching on QNAP in container station by way of Portainer. 

I'm using this for the install.
docker run -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower --cleanup

I really hope I can resolve this issue.  Thanks!

**Comment by dougle03** [comment]
None of my containers are updating either, with the same notice.
All mine are hub images. Getting this on a RPi4 running RASP OS

**Comment by simonaronsson** [comment]
Hey,

Thanks for your reports! Would you mind posting your logs with `--debug` enabled?

Best,
Simme

**Comment by carlsimmons81** [comment]
> Hey,
> 
> 
> 
> Thanks for your reports! Would you mind posting your logs with `--debug` enabled?
> 
> 
> 
> Best,
> 
> Simme

Simme,
Thanks for responding.  I actually removed watch tower for the moment so I can't assist with the logs this time around.  I do thank you for reaching out though!

**Comment by glc650** [comment]
I've been having the same issue for at least a week now.

2020-09-15 20:00:04 (info): Unable to update container /watchtower-monitor, err='Error response from daemon: Get https://registry-1.docker.io/v2/containrrr/watchtower/manifests/latest: received unexpected HTTP status: 500 Internal Server Error'. Proceeding to next.

**Comment by Zixim** [comment]
Same here : 
```time="2020-09-18T10:27:33+02:00" level=info msg="Unable to update container /watchtower, err='Error response from daemon: Get https://registry-1.docker.io/v2/v2tec/watchtower/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Av2tec%2Fwatchtower%3Apull&service=registry.docker.io: net/http: TLS handshake timeout'. Proceeding to next." 
time="2020-09-18T10:30:32+02:00" level=info msg="Unable to update container /watchtower, err='Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout'. Proceeding to next." 
time="2020-09-18T10:30:59+02:00" level=info msg="Unable to update container /syncthing, err='Error response from daemon: Get https://registry-1.docker.io/v2/syncthing/syncthing/manifests/latest: net/http: TLS handshake timeout'. Proceeding to next." 
time="2020-09-18T10:31:49+02:00" level=info msg="Unable to update container /syncthing, err='Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)'. Proceeding to next." 
time="2020-09-18T10:38:35+02:00" level=info msg="Unable to update container /portainer, err='Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout'. Proceeding to next." 

```

**Comment by simonaronsson** [comment]
Well, we can't really do that much about this, as it's a TLS timeout. @Zixim, If the problem remains, but it works when running `docker pull`, feel free to open another issue. Otherwise, it's on the docker hub (or your network) side of things, unfortunately.
