### ISSUE TITLE
Watchtower stops working

### ISSUE THREAD

**Issue by andig** [containrrr/watchtower#639]
**Describe the bug**
A couple of days ago, watchtower stopped producing log entries while the container is still running:

```
...
time="2020-09-03T18:07:05Z" level=info msg="Unable to update container /gravo. Proceeding to next."
time="2020-09-03T18:13:04Z" level=info msg="Unable to update container /gravo. Proceeding to next."
time="2020-09-03T18:56:04Z" level=info msg="Unable to update container /gravo. Proceeding to next."
time="2020-09-03T19:04:05Z" level=info msg="Unable to update container /gravo. Proceeding to next."
time="2020-09-03T19:08:05Z" level=info msg="Unable to update container /gravo. Proceeding to next."
time="2020-09-03T19:08:05Z" level=info msg="Unable to update container /gravo. Proceeding to next."
time="2020-09-04T07:05:31Z" level=info msg="Found new tvial/docker-mailserver:latest image (sha256:81318bae5710d904713e8bb7c34c407efa5d265bc8457ae376815fb80d51db56)"
time="2020-09-04T07:05:39Z" level=info msg="Stopping /mail (8c9b6af195937b437a73a600f400cdad9929949a6a77936579cf1271e90662f5) with SIGTERM"
```

No more entries after that line, other containers are no longer updated.

**To Reproduce**
Not able to 

**Expected behavior**
I'd expect a deadlock inside watchtower.

**Screenshots**

**Environment**
 - Platform docker 
 - Architecture x86
 - Docker version sha256:b26dfbdda14acac2b5cc862691a0e8248f510a1671532b55dabb2a5231126800

**Logs from running watchtower with the `--debug` option**
Restarting now with debug option and will monitor

**Comment by andig** [comment]
Closing until I can repro in debug mode.

**Comment by simonaronsson** [comment]
> Closing until I can repro in debug mode.

Thanks! That will definitely make it easier to help you 👍
