### ISSUE TITLE
Question: self updating application

### ISSUE THREAD

**Issue by pauldotknopf** [containrrr/watchtower#64]
I have a web application that needs to support updating itself.

My user interface will query a docker registry, and determine if updates are available. If there is a new image, I will download it and add it to my docker host. I will be doing this inside of my application (using /var/run/docker.dock).

Watch tower will eventually see that an image is updated, and it will restart the container that installed the image.

My problem is that I need my web application to perform this at a very exact moment. When my users press "update", the update can't begin later, it must happen at that exact moment.

This brings me to my main question.

What about adding support for an HTTP/REST api for manually triggering the update of a container?

**Comment by SStorm** [comment]
Got a similar situation, but I figure I can work around that by only downloading the image when the user presses "update". 

The bigger issue here is the lack of a rollback capability if things go wrong.

**Comment by simonaronsson** [comment]
This will be addressed in issue #262. Feel free to participate in that issue instead. 👍
