### ISSUE TITLE
Update images that have never been launched as a container

### ISSUE THREAD

**Issue by mneil** [containrrr/watchtower#640]
I have a use case where I want images updated on a machine but I haven't necessarily ran the image yet as a container. In this case, `--include-stopped` takes no effect (a container never ran), and there are no options to look at images only.

Expanded problem:
I have a CI system. The worker instances, when created, pull images that we've approved to run. When a new worker starts up it uses the local version of the image (never reaches out to a repository for images). Our system will periodically recycle the worker instances and may load up older versions of images on them. 

We'd like something in place that looks at the images, determines they are older, then updates them. This way when the first job comes into a machine it'll have the latest version of that image instead of the one we had specified when the image was built. Only certain images should be able to pull the "latest" while others are ignored and pinned to the version we specified.

**Describe the solution you'd like**
I would like a flag that allows watchtower to look at images, not containers, on a machine and determine if a new version needs to be pulled.

**Describe alternatives you've considered**
Given our scenario we could run all the images on startup then shut them down. The `--include-stopped` flag would likely work for us then.

**Additional context**
I'm willing to do the work. I was already looking at where the `--include-stopped` flag is implemented and am proficient with go. The biggest hurdle is that this relies on images and not containers. I want to know if this is something the community would want before I go putting in the effort to open a PR with this functionality. If it's not valuable, or is too specific to my use case, I will consider other workarounds or roll my own image update process. I'd like to build something more useful though :).

**Comment by zoispag** [comment]
Hi there,

I don't see this as something you need watchtower to do. If the image is not running in a container, the procedure is a lot simple imho.

You can try to add a cronjob or a task in your CI pipeline, to run something like this:
```bash
docker images --format "{{.Repository}}:{{.Tag}}" -f "dangling=false" -q | xargs -L1 docker pull;
```

The `docker images` command will return a list like this:

```
nginx:latest
minio/minio:latest
golang:alpine
python:3.7.7-buster
node:lts
alpine:latest
timescale/timescaledb-postgis:latest
debian:stretch-slim
```

and `xargs` will feed each line to a `docker pull` command.

Is this something that would do the trick for you?

**Comment by mneil** [comment]
Yes, that's an alternative that would work. Running it on a cron and updating the image(s).  I'm not opposed to that (I've considered it previously) but it has some negatives:

 - I'm using watchtower already, but now I need to write something else to manage these images
 - I could do this in bash, but it's not very testable / provable like it could be in go
 - Not as extensible / shareable with the community

Doing this in CI would not make sense, however, as asking users to run this in their pipelines and having unknown number of build targets all competing to do the same thing on different agents is not ideal. They also don't have permissions to pull images as they come from a mix of private / public registries.

If this isn't something that belongs in watchtower that's fine. I appreciate the suggestion on alternative ways to solve.
