### ISSUE TITLE
Make watchtower skip update if pre-update lifecycle hook exits with a non-zero exit code

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#649]
> Yeah, to be totally honest, I already thought we did this! 😅  This is the intended behavior, so we'll need to fix that. Thanks for reporting!

_Originally posted by @simskij in https://github.com/containrrr/watchtower/discussions/647#discussioncomment-81488_

**Comment by simonaronsson** [comment]
This should be a small self-contained fix in `pkg/container/client.go` around line 380-383, where we need to add an error return:

```go
if execInspect.ExitCode > 0 {
    log.Errorf("Command exited with code %v.", execInspect.ExitCode)
    log.Error(execOutput)
}
```

**Comment by ShaileshSurya** [comment]
Hi, @simskij Looks like a small change here. What should be the error to return here for exitcode other than 0? 

It will be great if you could provide the error string. 

Also, What is the timeline around this. This looks like targeted for hactoberfest and the event is still days away.

**Comment by simonaronsson** [comment]
If you want to do it, feel free. I just thought it would be a good hacktoberfest issue, given the very limited scope. 😅 

The current error text, but lowercased and without a trailing dot will do for now. Switching that call to `fmt.Errorf` and then printing that one using the logger should be be sufficient. 👍

**Comment by yrien30** [comment]
Is it possible to read message printed from the preupdate script and log that as error when exit code is higher than 0 ? I thought it would be saved to execOutput variable but that is not the case.

When WATCHTOWER_INCLUDE_STOPPED=true is set : then failing to run the script because the docker container is not running should not prevent a update.

**Comment by simonaronsson** [comment]
> Is it possible to read message printed from the preupdate script and log that as error when exit code is higher than 0 ? I thought it would be saved to execOutput variable but that is not the case.
> 
> When WATCHTOWER_INCLUDE_STOPPED=true is set : then failing to run the script because the docker container is not running should not prevent a update.

Agreed, as long as it fails because it's stopped, and not because of some other arbitrary reason. We need to check this and make sure we don't ignore other reasons as well.

**Comment by ryester19** [comment]
Can we do something like this for the exit codes?

0: Proceed with update
1: Skip update, don't log
2 and greater: Skip update, log as error

My reasoning for requesting this is because I want to use a script to prevent a pyload container from being updated and restarted while a download is still running. Having an error logged every 5 minutes would be an annoyance in my use case because these downloads can sometimes last 8 hours or more.

**Comment by kevinlul** [comment]
I'm interested in this feature for pre-check and pre-update but how difficult would it be to implement having not worked with Golang before?

**Comment by piksel** [comment]
@kevinlul I think it's more a matter of understanding how `watchtower` works. Go itself is (mostly) really easy to get into. A large portions of PRs are the authors first attempt at Go.

@ryester27 Perhaps we could use the [BSD standard exit code](https://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3) 75 (`EX_TEMPFAIL`), which is roughly used for this kind of scenario. Exit code 1 is generally the catch-all generic error that tools who doesn't emit any more granular exit codes use for errors.

**Comment by zoispag** [comment]
> Perhaps we could use the [BSD standard exit code](https://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3) 75 (`EX_TEMPFAIL`).

TIL!

**Comment by yrien30** [comment]
I think there is a issue when you return exitcode other than 0 that it will not stop the container but it will try to start new one and complaine that there is allready another container whit same name. Can anyone confirm this?
