### ISSUE TITLE
Updating containers that is rebooting

### ISSUE THREAD

**Issue by yrien30** [containrrr/watchtower#650]
Hi,
if we at some point we introduce a problem in a docker container that cause crashing of the container then it will be standing in a reboot loop if --restart always is set on that container. Even if you include WATCHTOWER_INCLUDE_STOPPED=true then it will not update the container when it standing in a reboot loop. I though it would be a good idea to introduce a new setting WATCHTOWER_INCLUDE_REBOOTING so that when the docker container get fixed then it will pull down the new one. Restoring the operation of the docker container. 

rebooting status is not included in filter:
https://github.com/containrrr/watchtower/blob/98b518612b6ae2c005667de997bec67325cd98cf/pkg/container/client.go#L102-L112

**Comment by simonaronsson** [comment]
Sure! This sounds like a reasonable addition. Feel free to provide a PR and I'll make sure to review it. 👍  🙏

**Comment by Pierre-Gilles** [comment]
Wow, we are using watchtower on embedded Raspberry Pi (on [GladysAssistant/Gladys](https://github.com/GladysAssistant/Gladys)) running on +100 instances and had exactly this need. If we deploy a bad container, all instances are stuck and we have to do a manual step to update each of them. 

Many thanks for your implementation @yrien30, we are looking forward to see this in Watchtower 👏

**Comment by aehlke** [comment]
This should be on by default! Or with a huge disclaimer. It's essentially a bug in expected behavior
