### ISSUE TITLE
Rolling restart delay

### ISSUE THREAD

**Issue by pcamelo** [containrrr/watchtower#675]
**Is your feature request related to a problem? Please describe.**
I would like to be able to introduce a delay between restarts when using `--rolling-restart` or allow me to have a custom timeout on the post update-command so I could flag watchtower that it can update the next container.

Context: I'm using watchtower on containers that shouldn't be restarted at the same time and should have some delay between each restart due to file related operations. This operation takes about 10 to 15 minutes.

**Describe the solution you'd like**
Additional argument that would delay the update of a container when using `--rolling-restart`. For example `--rolling-restart-delay <TIME_IN_SECONDS>` or additional option to allow a custom timeout on post update command.

**Describe alternatives you've considered**
Lifecycle hooks could be an alternative but given that watchtower timeouts after 60s of the post-update task this is not an option.

**Comment by wsw70** [comment]
This is tangentially related to a feature request I had in the past (https://github.com/containrrr/watchtower/issues/426), but I do not have the Go expertize to do a PR (but thanks a lot @simskij for the feedback)

**Comment by piksel** [comment]
Perhaps allowing the timeout to be altered would be the most generic solution here?
It's currently hard coded to `1` (minute):
https://github.com/containrrr/watchtower/blob/99eaf42de0cfe9ee1dcb0158fb2cb7930fc53bfa/pkg/lifecycle/lifecycle.go#L54
