### ISSUE TITLE
Per container update intervals

### ISSUE THREAD

**Issue by Keridos** [containrrr/watchtower#686]
**Is your feature request related to a problem? Please describe.**
The docker pull rate limit severly limits this project. For getting around that problem I have set the checking interval for watchtower globally to 2h. But I have several self built containers hosted on a private registry i'd like to get checked for much faster.

**Describe the solution you'd like**
Create a label that enables you to specify an update interval per container.

**Describe alternatives you've considered**
Cronjob on each hosts system that periodically checks those containers/images manually (pretty ugly)

**Additional Context**
#669

**Comment by unixfox** [comment]
I think you can achieve the same result by launching multiple instances of watchtower and specifying the name of the containers using the `command` parameter or you can use labels for that.

**Comment by Rush** [comment]
> I think you can achieve the same result by launching multiple instances of watchtower and specifying the name of the containers using the `command` parameter or you can use labels for that.

that's hardly convenient ;)

**Comment by simonaronsson** [comment]
> The docker pull rate limit severly limits this project. For getting around that problem I have set the checking interval for watchtower globally to 2h. But I have several self built containers hosted on a private registry i'd like to get checked for much faster.

This shouldn't be an issue now that the HEAD requests have been implemented. WIth that said, I still think the feature makes sense.

**Comment by Rush** [comment]
My auto update containers are running off a private gitlab registry. The concern is thus not universal

**Comment by simonaronsson** [comment]
If anyone wants to have a stab at this, feel free to go ahead. Just to set reasonable expectations, I won't have time in the near future, but I definitely think this makes sense.
