### ISSUE TITLE
Suggestion: Allow timeout value to be changed

### ISSUE THREAD

**Issue by Robotex** [containrrr/watchtower#69]
**[Premise]**
Some of my containers require to shutdown gracefully because they have long tasks that might run for minutes before they can exit.
I haven't learned Go yet but reading your code especially the line at [update.go#L13](https://github.com/v2tec/watchtower/blob/master/actions/update.go#L13) I assume that it waits 10 seconds before forcefully killing the container in [client.go#L106](https://github.com/v2tec/watchtower/blob/master/container/client.go#L106)
**[Actual request]**
Would be it possible to add a parameter for allowing to change the timeout?
As an alternative I think just signalling the container without terminating it still through a parameter like `--no-kill` would work for me.
Thanks in advance.

**Comment by stffabi** [comment]
Adding a timeout parameter would be a good suggestion. Adding a no-kill option would be a little bit harder, because if the old container doesn't get removed or renamed one can't start the new one with the same old name.

**Comment by stffabi** [comment]
Will be available with the next version.
