### ISSUE TITLE
Utilize Compose API to maintain versioning

### ISSUE THREAD

**Issue by rg9400** [containrrr/watchtower#696]
**Is your feature request related to a problem? Please describe.**
I am using Watchtower/Ouroboros right now in a large Compose stack. Both options work really well in updating containers and removing the older ones during cleanup. However, if I restart the host, containers that had been updated do not automatically spin back up properly even though they are set to restart `unless-stopped`. From what I gathered, the issue is related to how these images are updated using the Container API, but since Compose maintains its own versioning, it is not aware that the images have been recreated, so it requires an additional `docker-compose up -d` to bring its version up to date and recreate the containers that were updated.

**Describe the solution you'd like**
I may be off base here, but it seems like the latest version of Compose-CLI (`1.0.3`) does seem to allow API commands to Compose (https://github.com/docker/compose-cli/releases/tag/v1.0.3). If that is indeed true, it would be good to be able to have Watchtower utilize Compose commands vs Container commands, either via an environment variable or by recognizing how it is being run. That way, maybe the above problem could be solved since Watchtower would be leveraging Compose, thereby making sure the versioning remains consistent.

**Describe alternatives you've considered**
An alternate is to just run a separate `docker-compose up -d` command on the host on a scheduled basis or on start up. It solves the problem, though not super elegantly as it requires the containers to go down an additional time for each update, or mess up the start order of the containers depending on which ones had to be recreated.

**Comment by simonaronsson** [comment]
> However, **if I restart the host, containers that had been updated do not automatically spin back up properly even though they are set to restart `unless-stopped`**. From what I gathered, the issue is related to how these images are updated using the Container API, but since Compose maintains its own versioning, it is not aware that the images have been recreated, so it requires an additional docker-compose up -d to bring its version up to date and recreate the containers that were updated.

To my knowledge, this should not be the case. I've successfully run it exactly this way myself for years. Can you give us some additional info that might help to reproduce it?

**Comment by rg9400** [comment]
Just to confirm, if watchtower updates a container, and you run `docker-compose up -d container` where container is the one that was updated, do you see it say that it is recreating the container?

Because that is the issue. When Watchtower updates a container, `docker-compose up -d` still has to recreate it. The container itself starts up fine, but prior to running that command, if you restart the host, the container will say it is running, but it will not be functional. As mentioned, this behavior is because Compose seems to be tracking versions internally, separate from the way Watchtower does the updates. When you restart Compose, if the container is set to `restart`, it seems to be using an older image that is no longer available. It says the container is running, but it won't actually be functional. Running `up -d` seems to bring compose up to date with the latest image that has been pulled, hence the recreate.

Steps to reproduce:

1. Pull a container that has a web UI.
2. Try to access the web UI, make sure it works
3. Update that container using Watchtower
4. Without running any commands, restart the host. On start, make sure `docker-compose up -d` is not running as a task or service or job
5. Try to access the web UI now
6.  Run `docker-compose up -d container`, see how the container is recreated
7.  Try to access the web UI now

**Comment by simonaronsson** [comment]
1. _used nginx tagged as tutum/hello-world_
2. _works, see image below_
![image](https://user-images.githubusercontent.com/1596025/115700726-46388400-a367-11eb-9e38-a0660189e28c.png)

3.  _check_
4.  _check_
5.  _works, see image below_
![image](https://user-images.githubusercontent.com/1596025/115700807-5ea89e80-a367-11eb-8881-bbf457757cb6.png)
6.  _indeed recreates, but this is a known issue due to docker-compose having its own tracking hashes_
7. _yup, still works_

**Comment by rg9400** [comment]
@simskij can you share the compose you used for this reproduction? I am mainly curious about the restart policy. I use `unless-stopped` and have tried using multiple different environments, and it never works. Also, it seems like anyone I ask about this issue has the same behavior. That's why I am so curious how you are getting it to work.

Also, point 6 (compose having its own tracking hashes) is essentially the crux of the issue from what I understand. Would the new API for compose help resolve that? I guess unless it is not specifically causing the issues outlined in this thread, then it may not be as important.

**Comment by owine** [comment]
Yes point 6 is exactly what this request wants to fix. I’ll admit, it’s a nuisance more than anything else, but avoiding superfluous container recreation would certainly be nice. For a compose container, pull the new image but leave recreating the container to compose rather than watchtower handling on its own.

**Comment by simonaronsson** [comment]
Unfortunately, from what I can tell that’s not what that API is for.

If 5 is an issue, we’ll of course try to find a way to solve it, but for 6 we’ve decided to not pursue fixing that nuisance.

I’ll try to remember to post the compose file next time I’m at the computer, but it was nothing fancy, just a tutum/hello-world with a port mapping.
