### ISSUE TITLE
An option for staggered startup of new containers

### ISSUE THREAD

**Issue by fbuchmeier** [containrrr/watchtower#72]
We are running many JIRA and Confluence containers on a single host. When an update is found, watchtower pulls all updates, removes all containers and then creates new containers in short sequence.

Since all containers now start up at almost the same time, some of them fail to start correctly (plugin timeouts) because the underlying hardware cannot keep up with all the new processes.

It would be great to have an option for staggered startup, e.g. wait 30s before triggering the start of the next container.

What do you guys think?

Cheers,

Florian.

**Comment by ckeeney** [comment]
Additionally, it would be nice if I could just have 2 instances of the same container running as a failover, and just upgrade one at a time, with a 30s delay between the 2, basically a lazy man's rolling update.

**Comment by jazoom** [comment]
So watchtower doesn't do rolling updates like Docker itself does? I couldn't find anything about it in the docs but I suppose this answers my question. Maybe I can't use this image then.

**Comment by simonaronsson** [comment]
yeah, that would likely be a fitting enhancement applicable to a couple of different scenarios. it would also be pretty simple to add. with that said, i'm not sure i'll have enough free time on my hands to do it any time soon.

if anyone would like to have a stab at it i'd be happy to review the pull request. my thought is that this should be implemented using a label on the target container, maybe something like `org.containrrr.watchtower.delay-recreation=<seconds to wait>`.

Another thing to consider is that the actual recreation would have to be performed in a separate goroutine to avoid delaying recreation of other containers as well.
