### ISSUE TITLE
Provide image on ghcr.io as part of build/publish CI

### ISSUE THREAD

**Issue by ksurl** [containrrr/watchtower#722]
**Is your feature request related to a problem? Please describe.**

with docker hub pull limits (which should be mitigated by the latest release based on digest compare i know), it would be nice to have ghcr.io as an alternative for the watchtower container.

**Comment by simonaronsson** [comment]
Great idea! I think ghcr also has, or will have, some kind of limit, but it would definitely make sense as an alternative. Likewise for quay.io

**Comment by ksurl** [comment]
I want to do a PR for this, I guess circle ci config.yml for the prod release and the github actions workflow for the dev release. Should this be PR in main or ci-test branch?

**Comment by simonaronsson** [comment]
Awesome! Thanks!
