### ISSUE TITLE
Support for semantically versioned tags

### ISSUE THREAD

**Issue by lukasmrtvy** [containrrr/watchtower#749]
**Is your feature request related to a problem? Please describe.**
Semver container update should be supported, a lot of software already does not support latest tag ( anti pattern )... ( these will be ignored by watchtower ) and more will come for sure.

**Describe the solution you'd like**
1. own solution 
2. https://github.com/flavio/fresh-container as integrated solution
2. fresh-container ( server mode - REST API ) and watchtower ( GET `/api/v1/check?image=$image&constrains=$labels.watchtower.image-constrains` ) working togheter as two components..

**Describe alternatives you've considered**
X

**Additional context**
Related: https://github.com/containrrr/watchtower/issues/216
Related: https://github.com/containrrr/watchtower/issues/397

Thanks

**Comment by simonaronsson** [comment]
Thank you for your request.

https://github.com/containrrr/watchtower/issues/216#issuecomment-748461559 sums up the current state:

> It's closed due to no one picking it up to work on it. It's not that it's deemed a bad idea or anything, it's just that the currently open issues are the ones that have activity. If anyone wants to do a PR with this change we'd be happy to take a look at it!

ie. we're not likely to pick this up any time soon, but if anyone would like to contribute a solution, we'd be happy to assist with reviews, suggestions, and so on.

**Comment by Kernald** [comment]
This is still relevant.

**Comment by vibhorgupta-gh** [comment]
Hi community,

I've built my own solution for container base image updates over at [Argus](https://github.com/VibhorCodecianGupta/Argus) in an attempt to address what lacks here, many more features to come.
 _v1.0.0 is on NPM and available as a Docker image too._

Capabilities:
- Automated base image updates
- Support for semantically versioned tags (more info in [this issue](https://github.com/VibhorCodecianGupta/Argus/issues/33))
- Email notifications
- Push/webhook notifs for Telegram, Slack, Discord, Pushover
- Data and metrics support, integrated with Prometheus and InfluxDB

It specifically addresses the issue of supporting semantically versioned tags, more info in [this issue](https://github.com/VibhorCodecianGupta/Argus/issues/33)

**Comment by moqmar** [comment]
As a relatively simple solution, we could use a syntax like `com.centurylinklabs.watchtower.match-latest-tag=1.#.#`, with `#` as a numerical placeholder. Then, it'd be easy to just filter the tags, sort them in ascending order, and select the latest matching tag, without using an external library. It would also be possible to do non-semver stuff like `v1.#.#` or `version-2-beta#`.

Theoretically this could be extended ad absurdum (stuff like `1.#|1.#-beta#` to use version 1.2 as long as no 1.3-beta1 package is available, and so on), but I think for most application that simple matching would work quite well, and adding more complex functionality only adds confusion.

Would that be fine as a PR to solve this issue?

**Comment by piksel** [comment]
You would still need to implement fetching all tags from the repo:
https://docs.docker.com/registry/spec/api/#listing-image-tags
(including pagination). There is no such support in watchtower right now.

I should probably also inform you that if you are in control of the image repo, you could just put multiple tags on your images, like:
`myapp:1 myapp:1.3 myapp:1.3.4` or `myapp:v1.3.4 myapp:stable`
This is the de facto standard of doing semver releases on dockhub afaik. 

```
❯ docker image inspect nginx:latest | jq '.[].RepoTags'
[
  "nginx:1",
  "nginx:1.21",
  "nginx:1.21.4",
  "nginx:latest"
]

❯ docker image inspect nginx:stable | jq '.[].RepoTags'
[
  "nginx:1.20",
  "nginx:1.20.2",
  "nginx:stable"
]
```

**Comment by simonaronsson** [comment]
We're not implementing this. If you want to follow semantically versioned tags, you'll need to take care of this yourself. Watchtower tracks **one** tag, most commonly `latest`.

**Comment by onedr0p** [comment]
For those disappointed by that you could put your manifests in a public/private github repo and use [renovate](https://github.com/renovatebot/renovate) to scan your repo for updates. Renovate can auto merge changes or open PRs for review when new docker images are found. It's an awesome tool. Latest tags are pretty annoying and once you're bitten by a bad update you'll want take the time to review changes in applications, or be at the wheel to accept changes.
