### ISSUE TITLE
Getting 404 not found for most images

### ISSUE THREAD

**Issue by fgierlinger** [containrrr/watchtower#752]
**Describe the bug**
When running watchtower I receive a lot of 404 not found errors during the HEAD requests. 

```
DEBU[0018] Doing a HEAD request to fetch a digest        url="https://index.docker.io/v2/grafana/grafana/manifests/master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
WARN[0018] Could not do a head request, falling back to regular pull.  container=/grafana_grafana.1.hsya0ojrtar0brlm3ctvfpfc2 image="grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
DEBU[0018] Reason: registry responded to head request with &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[19] Content-Type:[text/plain; charset=utf-8] Date:[Sun, 10 Jan 2021 14:48:44 GMT] Docker-Distribution-Api-Version:[registry/2.0] Strict-Transport-Security:[max-age=31536000] X-Content-Type-Options:[nosniff]] {} 19 [] false false map[] 0x146a000 0x1070540} 
```
When running without credentials, the 404 Not Found results are mixed with some 401 Unauthorized responses. 

**To Reproduce**
1. Run watchtower `docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e REPO_USER=fgierlinger -e REPO_PASS=DOCKER_HUB_TOKEN containrrr/watchtower:1.1.6 --run-once --debug`
2. See error

**Expected behavior**
When providing credentials for Docker Hub, the login succeeds and images get pulled.

**Environment**
 - linux/arm/v7
 - Raspbian GNU/Linux 10 (buster)
 - Docker version 20.10.1, build 831ebea
 - Docker swarm activated (4 nodes, 4 master)

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
DEBU[0017] Trying to load authentication credentials.    container=/grafana_grafana.1.hsya0ojrtar0brlm3ctvfpfc2 image="grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
DEBU[0017] Loaded auth credentials for user fgierlinger on registry grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76 
DEBU[0017] Got image name: grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76 
DEBU[0017] Credentials loaded                           
DEBU[0017] Checking if pull is needed                    container=/grafana_grafana.1.hsya0ojrtar0brlm3ctvfpfc2 image="grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
DEBU[0017] Building challenge URL                        URL="https://index.docker.io/v2/"
DEBU[0017] Got response to challenge request             header="Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\"" status="401 Unauthorized"
DEBU[0017] Checking challenge header content             realm="https://auth.docker.io/token" service=registry.docker.io
DEBU[0017] Setting scope for auth token                  image=grafana/grafana scope="repository:grafana/grafana:pull"
DEBU[0017] Credentials found.                           
DEBU[0018] Parsing image ref                             host=index.docker.io image=grafana/grafana normalized="docker.io/grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76" tag="master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
DEBU[0018] Doing a HEAD request to fetch a digest        url="https://index.docker.io/v2/grafana/grafana/manifests/master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
WARN[0018] Could not do a head request, falling back to regular pull.  container=/grafana_grafana.1.hsya0ojrtar0brlm3ctvfpfc2 image="grafana/grafana:master@sha256:89576bfdac5d7e71fecadd75ab35995facca646f1449355273fed58499229e76"
DEBU[0018] Reason: registry responded to head request with &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[19] Content-Type:[text/plain; charset=utf-8] Date:[Sun, 10 Jan 2021 14:48:44 GMT] Docker-Distribution-Api-Version:[registry/2.0] Strict-Transport-Security:[max-age=31536000] X-Content-Type-Options:[nosniff]] {} 19 [] false false map[] 0x146a000 0x1070540} 
```

</details>

**Comment by simonaronsson** [comment]
Thanks for reporting this! We'll need to have a look. Seems the URL for pinned images is still wrong and will need to be changed.

However, in this particular case; what would you expect to happen? I'm asking because I'm not a swarm user myself.

If we were to implement this from what (at least I think) would be the most obvious approach, these pinned images would be skipped as the digest itself is immutable. Likely, that is not the behavior you're expecting though, as I assume that would make watchtower completely useless with docker swarm.

**Comment by fgierlinger** [comment]
Ok, that is interesting, because in my playbooks I did not pin a specific version. I mostly used the _:latest_ tag. I must add, that I am using portainer to manage the swarm environment on top of docker swarm. I deploy the watchtower in global mode, which means that there is one instance of watchtower per node.

My expectation is, that watchtower will iterate through all the images on the node, pull a new image and restart the container with the new image. Could it be, that watchtower is not compatible with portainer on top of swarm?

**Comment by simonaronsson** [comment]
I think the issue is that watchtower cant do much with pinned images (on top of the actual bug i mentioned earlier). 

The most suitable solution seems to be to make watchtower default to skipping pinned containers and add an override that ignores pinning. 

Does that seem like a feasible approach to you?

**Comment by piksel** [comment]
Asking the question "Is this the latest version of this pinned version?" doesn't make any sense, so yeah. But that would also mean that the container would switch tags on update (either to a non-pinned version or to a new pin), it seems like that might cause issues with docker swarm?

**Comment by fgierlinger** [comment]
You are totally right, this is not a watchtower issue. I couldn’t fully figure out from the logs what is going on. But if containers are deployed with a pinned version, that watchtower will only try to grab that exact version. I will look into the docs of portainer if there is another way to deploy the container.

**Comment by simonaronsson** [comment]
Did you ever manage to solve this, @fgierlinger? If so, would you mind having a look at https://github.com/containrrr/watchtower/discussions/860? @malenurse is experiencing a similar issue from what it seems.
