### ISSUE TITLE
Setting notification-level to trace disables notifications

### ISSUE THREAD

**Issue by piksel** [containrrr/watchtower#759]
This is caused by the first check permitting "trace" as it's a valid logrus level:
https://github.com/containrrr/watchtower/blob/3369d2427c3a7862444f8f34f09aeed3526f1424/pkg/notifications/notifier.go#L21-L26

...but then when grabbing all levels above it at:
https://github.com/containrrr/watchtower/blob/3369d2427c3a7862444f8f34f09aeed3526f1424/pkg/notifications/notifier.go#L27
it uses the `AllLevels` slice from `slackrus`, which doesn't contain `Trace`:
https://github.com/johntdyer/slackrus/blob/f7aae3243a0786c5a974bce71ed951c459876e64/levels.go#L8-L15

...which means that it will return an empty array of accepted levels:
https://github.com/johntdyer/slackrus/blob/f7aae3243a0786c5a974bce71ed951c459876e64/levels.go#L17-L25

**Comment by zoispag** [comment]
`slackrus` looks like it does not allow trace level. 
We can make our own `LevelThreshold` method easily, thus making Trade level to not disable notifications, but are there any consequences to the legacy notifiers or shoutrrr?

How are the log levels used? I know that Info and Error give different attachment colors in the legacy slack for example. Would `log.Trace` work or would completely go nuts? :D

**Comment by piksel** [comment]
I doubt anyone REALLY wants anything below `Info` for normal use. But leaving it to the end user to decide if they want `Debug` is probably a good idea. `Trace` on the other hand is mainly used for credentials, which might not be apparent and not something you may want 3rd parties (notification services) to receive and/or keep a log of. I suggest we don't support setting the level that low.
