### ISSUE TITLE
"Shoutrrr notification" Title when notifying with Gotify

### ISSUE THREAD

**Issue by StewartThomson** [containrrr/watchtower#761]
**Describe the bug**
As of 1.1.6, Watchtower notifications are being sent to gotify with a title of "Shoutrrr notification" rather than "Watchtower" intermittently.

**To Reproduce**
1. Send notifications to a gotify server

**Expected behavior**
Notifications should have a title of "Watchtower"

**Screenshots**
![image](https://user-images.githubusercontent.com/17557453/104268631-58e71700-5462-11eb-81e1-835bf4b94fab.png)

**Comment by piksel** [comment]
For some reason, the title was not settable in config/URL for gotify.

When https://github.com/containrrr/shoutrrr/pull/116 is merged, this will need an additional (small) fix in watchtower.
