### ISSUE TITLE
In v1.1.6, Notifications Fail with Insecure (HTTP) Gotify URL

### ISSUE THREAD

**Issue by revelous** [containrrr/watchtower#767]
**Describe the bug**
On v1.1.6, Gotify notifications fail when configured with HTTP URL.

**To Reproduce**
1. Configure Watchtower to send notifications to insecure (HTTP) Gotify URL.
2. Trigger notification
3. Watchtower attempts to send via HTTPS & it fails.

**Expected behavior**
Expectation would be that notifications would be sent to HTTP URL and not HTTPS URL.

**Screenshots**
v1.1.5:
time="2021-01-12T08:41:03-06:00" level=warning msg="Using an HTTP url for Gotify is insecure"
time="2021-01-12T08:41:04-06:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-13 06:15:00 -0600 CST"

v1.1.6:
time="2021-01-12T08:48:40-06:00" level=warning msg="Using an HTTP url for Gotify is insecure"
time="2021-01-12T08:48:41-06:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-13 06:15:00 -0600 CST"
Failed to send notification via shoutrrr (url=gotify://gotify/REMOVED):  failed to send notification to Gotify: Post "https://gotify/message?token=REMOVED": dial tcp 172.21.0.17:443: connect: connection refused

**Environment**
Debian 10
docker-compose version 1.21.0-3
docker.io version 18.09.1+dfsg1-7.1+deb10u2

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2021-01-12T08:56:41-06:00" level=debug
time="2021-01-12T08:56:41-06:00" level=warning msg="Using an HTTP url for Gotify is insecure"
time="2021-01-12T08:56:41-06:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2021-01-12T08:56:42-06:00" level=debug msg="Retrieving running containers"
time="2021-01-12T08:56:42-06:00" level=debug msg="There are no additional watchtower containers"
time="2021-01-12T08:56:42-06:00" level=debug msg="Watchtower HTTP API skipped."
time="2021-01-12T08:56:42-06:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-13 06:15:00 -0600 CST"
Failed to send notification via shoutrrr (url=gotify://gotify/REMOVED):  failed to send notification to Gotify: Post "https://gotify/message?token=REMOVED": dial tcp 172.21.0.17:443: connect: connection refused
```

</details>

**Additional context**
Downgrading back to v1.1.5 resolves this for now.

**Comment by piksel** [comment]
Fixed in https://github.com/containrrr/shoutrrr/pull/116. This will require some (small) modifications to watchtower as well to use.
