### ISSUE TITLE
Watchtower 1.1.6 Discord via slack url no long has correct formatting

### ISSUE THREAD

**Issue by ksurl** [containrrr/watchtower#768]
**Describe the bug**

updated to 1.1.6 and discord notifications no longer display with correct formatting, just plain text. also does not respect custom username and defaults to watchtower

**Expected behavior**

environment variables set and settings working as before

**Screenshots**

working version
![image](https://user-images.githubusercontent.com/1371562/104339339-55787d80-54ac-11eb-8c88-3d540bed28c7.png)

broken version
![image](https://user-images.githubusercontent.com/1371562/104339394-62956c80-54ac-11eb-87b1-e35744b79458.png)

**Environment**
 - Platform docker
 - Architecture x86
 - Docker version 20.10.2

**Comment by ksurl** [comment]
since shoutrrr supports discord natively, should that be added as an option in watchtower?

**Comment by simonaronsson** [comment]
Thank you for your report!

This is tracked in shoutrrr in issue https://github.com/containrrr/shoutrrr/issues/110 and will be released as soon as it' ready.
