### ISSUE TITLE
Not restarting container after updating images

### ISSUE THREAD

**Issue by pavithrachandrakasu** [containrrr/watchtower#77]
My log details

rancher@susiaalimbssro2:~$ sudo docker logs -f c1d1e6d75953
INFO[0000] First run: 2017-04-11 19:01:59 +0000 UTC

INFO[0299] Checking containers for updated images
INFO[0301] Found new streamsets/datacollector:latest image (sha256:0014c798cc0f99168ba0f2a9b1f66f241d1c0df71b487c604599c610fedd8943)
INFO[0305] Found new bekt/logspout-logstash:latest image (sha256:b95771a453e78e785c403a2d1f301fa1b0b962c309babd06317b6d122ffa777a)
INFO[0317] Found new rancher/net:holder image (sha256:665d9f6e8cc1ec3fa1181398d0661715cf71134db65666072998c54dbeeb7072)
INFO[0319] Stopping /r-ipsec-ipsec-3-c389ba67 (69bcaa601bfa713120af783a12366d2f4c7b9386c045913e4f969a1ece47a132) with SIGTERM
INFO[0329] Stopping /r-elasticsearch-5-logspout-3-d2508349 (117dbcf8ad81253db0e4ada6dcd66b3dfd3a42f2b99e807dfc66a7fb2dd3f117) with SIGTERM
INFO[0330] Stopping /r-streamsets_test-13868513 (472e42d311579a691a6df4c10d58703aec203d8a1d0be844bae0a0d435fe552b) with SIGTERM
INFO[0331] Creating /r-streamsets_test-13868513
INFO[0332] Creating /r-elasticsearch-5-logspout-3-d2508349
INFO[0332] Creating /r-ipsec-ipsec-3-c389ba67
INFO[0599] Checking containers for updated images
INFO[0899] Checking containers for updated images
INFO[1199] Checking containers for updated images
INFO[1499] Checking containers for updated images
INFO[1799] Checking containers for updated images
INFO[2099] Checking containers for updated images
INFO[2399] Checking containers for updated images

--------------

docker ps -a  shows that the container is exited

036154f6805f        streamsets/datacollector:2.4.1.0   "/docker-entrypoin..."   54 minutes ago      Exited (143) 51 minutes ago                       stupefied_haibt

Please check this one.

**Comment by stffabi** [comment]
Do you see a new container `r-streamsets_test-13868513`? Could you run watchtower with the `--debug` flag and post the output?

Are you using the host network for these containers?

**Comment by pavithrachandrakasu** [comment]
No I am not seeing a new container with that name. I am using Rancher Orchestration to run my containers. 

Do you want me run it again with --debug flag?

**Comment by stffabi** [comment]
Yes running watchtower with --debug might give us some hints.

**Comment by raiscan** [comment]
Hi!

I have the same problem; specifically with "linuxserver/plex". The container is recreated, but is not started. All other containers restart after update correctly.

debug messages:

{"log":"time=\"2017-06-09T22:56:33Z\" level=debug msg=\"Pulling linuxserver/plex:latest for /plex\" \n","stream":"stderr","time":"2017-06-09T22:56:33.829740222Z"}
{"log":"time=\"2017-06-09T22:56:33Z\" level=debug msg=\"No credentials for linuxserver in /config.json\" \n","stream":"stderr","time":"2017-06-09T22:56:33.829748772Z"}
{"log":"time=\"2017-06-09T22:56:33Z\" level=debug msg=\"No authentication credentials found for linuxserver/plex:latest\" \n","stream":"stderr","time":"2017-06-09T22:56:33.82975325Z"}
{"log":"time=\"2017-06-09T22:56:50Z\" level=info msg=\"Found new linuxserver/plex:latest image (sha256:870eae901561066433b8769742a1b844568f626cd69c7bfe56e620aeb31568c2)\" \n","stream":"stderr","time":"2017-06-09T22:56:50.123367564Z"}
{"log":"time=\"2017-06-09T22:56:54Z\" level=info msg=\"Stopping /plex (e69d25f7e5ebd73328955d18c1713278fd31c5d251b0472144058390f032c548) with SIGTERM\" \n","stream":"stderr","time":"2017-06-09T22:56:54.918703082Z"}
{"log":"time=\"2017-06-09T22:57:04Z\" level=debug msg=\"Removing container e69d25f7e5ebd73328955d18c1713278fd31c5d251b0472144058390f032c548\" \n","stream":"stderr","time":"2017-06-09T22:57:04.937850051Z"}
{"log":"time=\"2017-06-09T22:57:30Z\" level=info msg=\"Creating /plex\" \n","stream":"stderr","time":"2017-06-09T22:57:30.737758345Z"}
{"log":"time=\"2017-06-09T22:57:30Z\" level=error msg=\"Error response from daemon: Container cannot be disconnected from host network or connected to host network\" \n","stream":"stderr","time":"2017-06-09T22:57:30.818465601Z"}

**Comment by Ezwen** [comment]
I also encountered a case where a container was not restarted:
```
╰─➤  sudo docker-compose logs
Attaching to watchtower_watchtower_1
watchtower_1  | time="2018-02-24T08:55:57Z" level=info msg="First run: 2018-02-24 09:00:57 +0000 UTC" 
watchtower_1  | time="2018-02-24T09:01:04Z" level=info msg="Found new nginx:1.13 image (sha256:e548f1a579cf529320a3c1d8789399e5fea0bfaa04cbb70d03890afafb748a2f)" 
watchtower_1  | time="2018-02-24T09:01:06Z" level=info msg="Found new nginx:1.13 image (sha256:e548f1a579cf529320a3c1d8789399e5fea0bfaa04cbb70d03890afafb748a2f)" 
watchtower_1  | time="2018-02-24T09:01:09Z" level=info msg="Stopping /admindocs_webserver_1 (bf4e477194a8d465127f7aec9fbf911296cdd6aac216373fc213a095644a1ba0) with SIGTERM" 
watchtower_1  | time="2018-02-24T09:01:10Z" level=info msg="Stopping /frontpage_webserver_1 (0813c54da7278c394874a64795f8ff8045f445f0e39934e0cb49c34daab15bc9) with SIGTERM" 
watchtower_1  | time="2018-02-24T09:01:11Z" level=info msg="Creating /frontpage_webserver_1" 
watchtower_1  | time="2018-02-24T09:01:12Z" level=info msg="Removing image sha256:9e988ed19567262bd07d62a8e51b3c0db8bda5d7afd63268860aabfe04d46168" 
```

As you can see, `frontpage_webserver_1` was restarted, but not `admindocs_webserver_1`.

**Comment by stffabi** [comment]
@Gwend4l would it be possible for you to reproduce it again with `--debug` flag?

**Comment by simonaronsson** [comment]
No response in over a year. Closing.
