### ISSUE TITLE
Add custom text at start of notification message

### ISSUE THREAD

**Issue by airlie** [containrrr/watchtower#773]
I have several servers running Watchtower and the notifications themselves don't give me any way to identify which server is sending the message.

I am currently using Gotify and MS Teams and the messages all look the same, without any identifying information: 

```
Starting Watchtower and scheduling first run: 2021-01-13 14:17:39 +0000 UTC m=+3600.560229540
Starting Watchtower and scheduling first run: 2021-01-13 14:17:38 +0000 UTC m=+3601.126906021
Starting Watchtower and scheduling first run: 2021-01-13 14:17:36 +0000 UTC m=+3600.265141452
```

It would be nice to have an additional config option that would add a string to the beginning of each message. I then pass the Watchtower container the name of the server it is running on.

Example: `WATCHTOWER_NOTIFICATION_PRETEXT="MyServerName - "`

My messages would then look like:
```
MyServerName - Starting Watchtower and scheduling first run: 2021-01-13 14:17:39 +0000 UTC m=+3600.560229540
OtherServer - Starting Watchtower and scheduling first run: 2021-01-13 14:17:38 +0000 UTC m=+3601.126906021
AnotherServer - Starting Watchtower and scheduling first run: 2021-01-13 14:17:36 +0000 UTC m=+3600.265141452
```

The default should be empty and have no effect on anyone not explicitly setting a value.

Some users might like a POSTTEXT option as well, although I don't personally have a need for it.

**Comment by piksel** [comment]
"Pretext" is probably a confusing choice of words 😁, but yeah, there should probably be a way to customize the message template somehow...
Gotify will get `title` support in next version, which can be customized to show a prefix or totally replaced for each instance.
Teams doesn't have title support right now, but will probably get it in the Rich Messages update to Shoutrrr.

**Comment by airlie** [comment]
> "Pretext" is probably a confusing choice of words

You're right, how about "BeforeText/AfterText",  or "StartText/EndText" ?

Title support would be nice, but if notification channels don't all support them it quickly becomes a pain.

I know when we start talking about customization it can get complicated real fast. I'm trying to keep it simple and easy to do.

**Comment by simonaronsson** [comment]
Maybe `Prefix` would be a natural choice? 😅 In any case, mail notifications support subject tags, so I guess we should do something similar for the other services as well.

**Comment by airlie** [comment]
The beauty is, giving users the ability to add a little text to the beginning of the message, should be relatively easy to do and would work no matter what services were being used.

**Comment by piksel** [comment]
Ehm, I kind of forgot about this:
```
WATCHTOWER_NOTIFICATION_TEMPLATE="{{range .}}MyServerName {{.Message}}{{println}}{{end}}"
 ```

You can set the template for the messages by using `--notification-template` or `WATCHTOWER_NOTIFICATION_TEMPLATE`

**Comment by airlie** [comment]
Awesome! Sorry for missing it in the documentation. I see it now that you've pointed it out.

I just used it to solve my problem.
