### ISSUE TITLE
Invalid mail header with new version

### ISSUE THREAD

**Issue by cybermcm** [containrrr/watchtower#775]
**Describe the bug**
It seems that in the latest version (1.1.6) mail sending is somehow broken. Currently, watchtower mails get tagged by my mail server because of a bad mail header.
Error msg:
```
INVALID HEADER
Missing required header field: "Date"
```

I checked the original mail and the Date field is missing

**To Reproduce**
Send mail via watchtower

**Expected behavior**
Well-formed email header

**Environment**
 - x86 and ARM
 - docker current version

**Comment by piksel** [comment]
Fixed in https://github.com/containrrr/shoutrrr/pull/118

**Comment by molnarti** [comment]
any ETA for the fix in watchtower itself? my selfhosted mailserver keeps refusing the messeges from watchtower (and watchtower only)

**Comment by cybermcm** [comment]
@piksel: any idea when this pull request will get through?

**Comment by piksel** [comment]
@cybermcm @molnarti Since this project is community maintained, it depends on when volunteers have enough spare time to sink into doing a release (mostly reviewing, testing, etc.), which may, unfortunately, take longer than expected. If I had a good ETA to give you, I would, but unfortunately the only I think I can provide is "as soon as possible".

**Comment by cybermcm** [comment]
@piksel: Thanks for your answer, just thought that there is not much left to do, but I'm no programmer, so I do not understand all these commits and requests ;-)
take your time...

**Comment by cybermcm** [comment]
My mails are working again even the pull request isn't closed by now?
Can anybody confirm? Maybe we could close this one...

**Comment by molnarti** [comment]
@cybermcm nope, still does not work for me. according to watchtower logs last updates took place cca. an hour ago. mail server log still complains about bad header:

`Feb 25 07:26:50 mail amavis[532]: (00532-11) Blocked BAD-HEADER-0 {BouncedOpenRelay,Quarantined}, [192.168.50.1]:8854 <sender@mydomain.com> -> <sent_to@mail.com>, quarantine: 4/badh-4Z-3X1Q_SDJg, Queue-ID: C886416009B, mail_id: 4Z-3X1Q_SDJg, Hits: -, size: 1029, 116 ms`

**Comment by cybermcm** [comment]
@molnarti: Just double-checked, at least the date field is there (my initial problem). Mails do not get tagged as spam any longer in my case.

**Comment by molnarti** [comment]
@cybermcm i never had problem with mails tagged spam. mail sending fails on mail server level, so nothing gets sent since the 1.16 update. i have just downgraded to 1.1.5 and email notifications work as before.

**Comment by cybermcm** [comment]
@molnarti: You are right, I didn't remember correctly, mails didn't get tagged as spam, they weren't delivered at all due to the missing date field.
