### ISSUE TITLE
Code of Conduct link broken

### ISSUE THREAD

**Issue by alexharrington** [containrrr/watchtower#777]
When posting a new issue here, there's a bot which suggests reading the Code of Conduct and guide for contributing:
![image](https://user-images.githubusercontent.com/10450518/104589470-d3ca5080-5661-11eb-9fe4-926bb32c36ba.png)

The link there to the Code of Conduct is broken. The link points to:
https://github.com/containrrr/watchtower/blob/master/CODE_OF_CONDUCT.md

which is a 404. I believe the correct URL should be:
https://github.com/containrrr/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by zoispag** [comment]
Thanks for the heads up @alexharrington! Very much appreciated!
