### ISSUE TITLE
MS Teams with different webhook domain

### ISSUE THREAD

**Issue by BitDesert** [containrrr/watchtower#792]
Currently it forces the URL of a webhook to start with `https://outlook.office.com/webhook/`:
https://github.com/containrrr/watchtower/blob/aa3ed8833f484b3c016f8c76260442b1487a91c4/pkg/notifications/msteams.go#L48

A new webhook I created starts with (company name replaced, token removed) 
``` 
https://mycompany.webhook.office.com/webhookb2/...
```

It does not send any notification with the following error in the log:

```
Failed to send notification via shoutrrr (url=teams://%22https%3A:@mycompany.webhook.office.com):  failed to send notification to teams, response status code 404 Not Found
```

**Comment by piksel** [comment]
Interesting, I didn't know you could do that.
The teams URLs were fixed to make them easier to use in https://github.com/containrrr/shoutrrr/pull/117, but custom domains are still not supported. I were thinking about adding a second type of URL using the following syntax:
```
teams+https://<FULL-WEBHOOK-URL>/?<PROPS>
``` 
Given that the domain can be custom, this gives us yet another reason to do so...

**Comment by lowey71** [comment]
Affected by the same issue
