### ISSUE TITLE
Gotify notifications fail when gotify url contains path

### ISSUE THREAD

**Issue by borislavg** [containrrr/watchtower#795]
My setup is as follows:

```
WATCHTOWER_NOTIFICATIONS=gotify
WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://example.org/gotify
WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=aToken
```
Since upgrade to 1.1.6, container fails to start with:
```
time="2021-01-24T22:09:39+02:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"gotify://example.org%2Fgotify/aToken\": invalid URL escape \"%2F\"\n"
```

I suspect this is related to https://github.com/containrrr/watchtower/commit/35490c853d95f9ead6799bd2a16c991a0e1a0ddf

**Comment by piksel** [comment]
Yeah, it's because it's now using Shoutrrr.

How are you using gotify with a path? Are you using a reverse proxy?
I can add support for it, just didn't know you could do that.
