### ISSUE TITLE
Unable to update container when using credentials with default registry

### ISSUE THREAD

**Issue by belak** [containrrr/watchtower#81]
`docker run -v /var/run/docker.sock:/var/run/docker.sock -v /root/.docker/config.json:/config.json -it v2tec/watchtower --debug`

I keep seeing `INFO[0017] Unable to update container /root_blog-coded_1. Proceeding to next.`

But when I just run `docker pull [image name]` as root outside the container, it works fine.

**Comment by stffabi** [comment]
Duplicate with #68
