### ISSUE TITLE
failed to send notification to Gotify: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by virtualex-itv** [containrrr/watchtower#822]
Using a self-signed certificate, I am trying to send notifications to Gotify.  When deploying watchtower with the `-e WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true` variable, it fails to send the notification with the following error: `failed to send notification to Gotify: x509: certificate signed by unknown authority`.  For some reason it seems like the flag is not working properly, i guess?

**Comment by piksel** [comment]
Yeah, this will be fixed in #810
