### ISSUE TITLE
Watchtower TZ environment variable has no effect

### ISSUE THREAD

**Issue by chippey5** [containrrr/watchtower#840]
**Describe the bug**
The TZ environment variable is either not read or doesn't seem to be working.

**To Reproduce**
1. Set the `TZ` environment variable to any acceptable `TZ` value (for instance _**Australia/Melbourne**_).
2. Start your container.
3. Run `docker logs` for the container.
4. The log timestamps are presented in UTC anyway.

**Expected behavior**
The container should handle the passed environment variable. 

**Environment**
 - Platform: Debian 10 (buster)
 - Architecture: arm64v8
 - Docker version: 20.10.4

**Additional context**
I made a search for _TZ_ in the repo, but couldn't find anything pointing towards this environment variable whilst others can be found being declared in [/internal/flags/flags.go](https://github.com/containrrr/watchtower/blob/main/internal/flags/flags.go).

**Comment by chippey5** [comment]
According to [https://containrrr.dev/watchtower/arguments/#time_zone](https://containrrr.dev/watchtower/arguments/#time_zone) the environment variable doesn't have an argument. To give more verbose context to the matter at hand:


```
$ cat /etc/timezone
Europe/Stockholm

$ cat docker-compose.yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_DEBUG=false
    restart: unless-stopped

$ docker-compose up -d
watchtower is up-to-date

$ docker logs watchtower
time="2021-03-01T19:16:40Z" level=info msg="Starting Watchtower and scheduling first run: 2021-03-01 20:16:40 +0000 UTC m=+3600.420816404"

$ date
Mon Mar  1 20:19:05 CET 2021
```

**Comment by piksel** [comment]
>  made a search for TZ in the repo, but couldn't find anything [...]  

Yeah, it's because we don't explicitly handle the timezone inside watchtower, it's part of [the go time package](https://golang.org/pkg/time/#Location).


> [...] the environment variable doesn't have an argument [...]  

What `Argument: n/a` means here is that you cannot specify the timezone as a command argument to the watchtower binary. As in, something like `watchtower --timezone Europe/Stockholm`, does not work.


Did you try 
```yaml
    environment:
      - TZ=Europe/Stockholm
```
as well?

**Comment by chippey5** [comment]
> Did you try
> 
> ```yaml
>     environment:
>       - TZ=Europe/Stockholm
> ```
> 
> as well?

I did at the time, but when doing this now I'm not able to replicate the issue anymore, the TZ env. variable seems to be read now:

```
$ cat docker-compose.yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_DEBUG=false
      - TZ=Europe/Stockholm
    restart: unless-stopped

$ docker-compose up -d
Recreating watchtower ... done

$ date
Wed  3 Mar 11:51:11 CET 2021

$ docker logs watchtower
time="2021-03-03T11:51:05+01:00" level=info msg="Starting Watchtower and scheduling first run: 2021-03-03 12:51:05 +0100 CET m=+3601.030885218"
```

I did update from `docker-ce 20.10.5` from `20.10.4`. Trying on a secondary arm64v8 device with version `20.10.4` I still couldn't replicate the issue. I know i changed the TZ and regenerated the locale when I encountered the issue and the board has been rebooted since then. 

Safe to say this was perhaps a one time issue given the conditions. Thanks for the help!
