### ISSUE TITLE
Poll Time via Label

### ISSUE THREAD

**Issue by hactar** [containrrr/watchtower#842]
**Is your feature request related to a problem? Please describe.**
We're running a docker host with about 60 containers. Watchtower runs on the host and polls once a day. We have one container that would need a polling of 5 minutes, because updates to the image can occur frequently and need to be reflected quickly too. There appears to be no way to get one instance of watchtower to have a different poll time for individual containers.

**Describe the solution you'd like**
It would be great if i could use docker's label system to override default poll times of watchdog for individual containers. For example a label like `com.centurylinklabs.watchtower.poll_time=300` could be added to set the poll time to 5 minutes.

**Describe alternatives you've considered**
- Two watchtowers with scope could be setup instead, however that means setting up one new watchtower instance for the 5 minute container, and then creating a second instance with a different scope, and then adding the scope label to the other 59 containers, which is super cumbersome.
- Watchtower could be changed to have a default scope when none is defined, and all containers without a scope label could be considered as being part of this default scope. If a new watchtower is created with a defined scope, this would then not clash with the "scopeless" watchtower instance, as it currently does according to the documentation, which says you can only run two watchtower instances if both define a scope.

**Comment by piksel** [comment]
This has been suggested earlier, but I think your second option might actually be not that complicated to fix (and seems like a better "default" behaviour to boot).

For a quick solution though, you could just employ the system cron service and add several entries that run watchtower with `--run-once` and supplying a list of the containers to target.

**Comment by simonaronsson** [comment]
I like the second suggestion as well!
