### ISSUE TITLE
Unable to authenticate using a private registry

### ISSUE THREAD

**Issue by stephentan-luddart** [containrrr/watchtower#849]
**Describe the bug**
I am unable to authenticate using Watchtower when it is set to use a private registry. I have tried 2 private registries so far and it fails with the same error for both. 

**To Reproduce**
I have used the registries canister.io and treescale.com. I create a user and a repository. I then push to the repos. An example container tag is: cloud.canister.io:5000/luddart/production-backend-auction-site also another tried is: repo.treescale.com/luddart/production-backend-auction-site

Whenever I run Watchtower, I get a failed auth. I have a gist of the debug log here: https://gist.github.com/stephentan-luddart/e4d8abba99b6a3dd30c3bf190060745e

Note that I am using the exact config.json that works for a normal docker operation so I know that the credentials are correct! This fails for both registries!

**Expected behavior**
I would expect Watchtower to not throw a 401 error.

**Screenshots**

**Environment**
 - Platform - linux, Ubuntu 18.04
 - Architecture - amd64
 - Docker version - 20.10.2 Community
 - Watchtower version: latest    9f33b7c5cb35

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```

```

</details>

**Additional context**

**Comment by piksel** [comment]
Your repos are responding with `401` for HEAD requests. Watchtower is falling back to doing a regular pull and that works correctly.
The `401` is not an error message, it's a debug level message that is only relevant if you actually expect HEAD requests to work and try to... well, debug it...

**Comment by stephentan-luddart** [comment]
oh! Sorry. I will test by pushing a small change then. Thank you for such a quick response.
