### ISSUE TITLE
platform linux/arm64/v8 is seen as linux/amd64 

### ISSUE THREAD

**Issue by Rar9** [containrrr/watchtower#851]
Ubuntu 20.04 + latest docker

docker run -d     --name watchtower     -v /var/run/docker.sock:/var/run/docker.sock     containrrr/watchtower:latest              

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

I found this old issue
https://github.com/containrrr/watchtower/issues/779

Is this container now running as expected ?

**Comment by piksel** [comment]
Issue #779 has not been released yet. It will be in the upcoming release.
Usually you can you use `:latest-dev` to try it, but I don't think that one has multi-arch support...

**Comment by simonaronsson** [comment]
> Issue #779 has not been released yet. It will be in the upcoming release.
> Usually you can you use `:latest-dev` to try it, but I don't think that one has multi-arch support...

Correct! However, this should be solved in `v1.2.1`
