### ISSUE TITLE
docker image linux/arm/v7 platform request

### ISSUE THREAD

**Issue by tataue** [containrrr/watchtower#853]
**Is your feature request related to a problem? Please describe.**

I choose the `armhf-latest` tag to run on my raspberry and got the warning
```shell
docker run -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower:armhf-latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
```
however watchtower is running okay.

Since i saw the tags from the docker official document [here](https://github.com/docker-library/official-images#architectures-other-than-amd64)

and there are `arm32v6` and `arm32v7` tags

So, should we mv `armhf` to `arm32v6` and `arm32v7` ?

**Describe the solution you'd like**

or add a tag like `arm32v7`?

**Describe alternatives you've considered**

**Additional context**

**Comment by piksel** [comment]
`linux/arm/v7` is an alias for `linux/arm` which we do support. Please fill out the issue template.

**Comment by tataue** [comment]
> Hi there! 👋🏼 As you're new to this repo, we'd like to suggest that you read our [code of conduct](https://github.com/containrrr/.github/blob/master/CODE_OF_CONDUCT.md) as well as our [contribution guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md). Thanks a bunch for opening your first issue! 🙏

Okay I will~

**Comment by tataue** [comment]
> `linux/arm/v7` is an alias for `linux/arm` which we do support. Please fill out the issue template.

Thank you, it the `armhf-latest` did work.
