### ISSUE TITLE
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY not working

### ISSUE THREAD

**Issue by adispi** [containrrr/watchtower#854]
i have set up the postfix with self signed certificate and verified it.
this is a test environment.
i set env WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY TRUE (i use portainer for this)
however i still get this reject on the server side from the client:
SSL_accept error from unknown
 warning: TLS library problem: 28233:error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:s3_pkt.c:1275:SSL alert number 42:
lost connection after STARTTLS from unknown

**Comment by simonaronsson** [comment]
Yeah, I think this is a limitation in the compatibility layer between the old notifications and shoutrrr. If you switch to using a shoutrrr URL, you'd be able to set this as a queryParam in the URL. @piksel, should we add this for compatibility or just consider the old types deprecated and pending deletion?

**Comment by piksel** [comment]
Ehm, on the server side? What about the watchtower logs?

`WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY` should disable STARTTLS, so I'm not sure why the server thinks that a StartTLS session has been started...
