### ISSUE TITLE
Watchtower not starting container after updating it

### ISSUE THREAD

**Issue by raiscan** [containrrr/watchtower#86]
Hi!

I'm having a problem specifically with watchtower updating "linuxserver/plex". The container is recreated, but is not started. All other containers restart after update correctly. I am using watchtower in tcp mode (not socket) and the plex container uses the hosts' network.

I can manually start the container without issue.

debug messages:

{"log":"time="2017-06-09T22:56:33Z" level=debug msg="Pulling linuxserver/plex:latest for /plex" \n","stream":"stderr","time":"2017-06-09T22:56:33.829740222Z"}
{"log":"time="2017-06-09T22:56:33Z" level=debug msg="No credentials for linuxserver in /config.json" \n","stream":"stderr","time":"2017-06-09T22:56:33.829748772Z"}
{"log":"time="2017-06-09T22:56:33Z" level=debug msg="No authentication credentials found for linuxserver/plex:latest" \n","stream":"stderr","time":"2017-06-09T22:56:33.82975325Z"}
{"log":"time="2017-06-09T22:56:50Z" level=info msg="Found new linuxserver/plex:latest image (sha256:870eae901561066433b8769742a1b844568f626cd69c7bfe56e620aeb31568c2)" \n","stream":"stderr","time":"2017-06-09T22:56:50.123367564Z"}
{"log":"time="2017-06-09T22:56:54Z" level=info msg="Stopping /plex (e69d25f7e5ebd73328955d18c1713278fd31c5d251b0472144058390f032c548) with SIGTERM" \n","stream":"stderr","time":"2017-06-09T22:56:54.918703082Z"}
{"log":"time="2017-06-09T22:57:04Z" level=debug msg="Removing container e69d25f7e5ebd73328955d18c1713278fd31c5d251b0472144058390f032c548" \n","stream":"stderr","time":"2017-06-09T22:57:04.937850051Z"}
{"log":"time="2017-06-09T22:57:30Z" level=info msg="Creating /plex" \n","stream":"stderr","time":"2017-06-09T22:57:30.737758345Z"}
{"log":"time="2017-06-09T22:57:30Z" level=error msg="Error response from daemon: Container cannot be disconnected from host network or connected to host network" \n","stream":"stderr","time":"2017-06-09T22:57:30.818465601Z"}

**Comment by FrozenDragoon** [comment]
What's your OS and how did you install Docker? I went through this just recently on my Ubuntu 16.04 box.  It turns out that if all you did was "sudo apt-get install Docker" (the Ubuntu managed repo), you have a very out of date version of Docker.  To get the most up to date version you have to install it directly from Docker's own repo.

I followed the [official installation instructions](https://www.docker.com/community-edition#/download) and now have no issues using Watchtower.

**Comment by raiscan** [comment]
Hi!

I am running VMWare Photon OS as a virtual machine. Docker comes installed as standard so is likely not bleeding edge.

**Comment by stffabi** [comment]
You are facing the same problem as described in #73. It has already been fixed on master. Unfortunatelay I was super busy the last few months, but I'm going to release a new version by the end of next week.

**Comment by raiscan** [comment]
Great to hear it's coming in the future. Thanks for all the hard work!
