### ISSUE TITLE
Update documentation regarding monitoring

### ISSUE THREAD

**Issue by zilexa** [containrrr/watchtower#862]
https://containrrr.dev/watchtower/arguments/#without_updating_containers

Still says: 
>Without updating containers
>Will only monitor for new images, send notifications and invoke the pre-check/post-check hooks, but will not update the containers.

    >⚠️ Please note

    >Due to Docker API limitations the latest image will still be pulled from the registry.

I thought that is no longer true since #674

**Comment by simonaronsson** [comment]
Hmm, will have to verify that. Not sure whether we changed `--monitor-only` to only do the head request. If my memory serves me, we didn't, due to the fact that the HEAD request might fail as it's still not even supported by all registries.

**Comment by zilexa** [comment]
OK, sorry now I am a bit confused. For updating you need to use pull, when is the head request used if not for `--monitor-only`?

**Comment by piksel** [comment]
@zilexa It's used to check if a pull is necessary. If there is no change, no pull will be performed. 

AFAIK, the only difference when using `--monitor-only`, is that it disables the recreation of containers that have a newer image. This happens in a step after the HEAD [+ pull] has been performed, so it should use exactly the same method for both scenarios.

The reason for thinking it would not use the HEAD request is that no separate effort for it was done (I think), hence why it might not support it.

**Comment by zilexa** [comment]
> it should use exactly the same method for both scenarios.

Thanks! Will close this and I'll def start using Watchtower now :)

**Comment by ghost** [comment]
To avoid important communication to get lost in a closed issues no one monitors, I'll go ahead and lock this issue. If you want to continue the discussion, please open a new issue. Thank you! 🙏🏼
