### ISSUE TITLE
Failed to execute 1.2.0 docker image

### ISSUE THREAD

**Issue by Teeed** [containrrr/watchtower#863]
**Describe the bug**
New docker image (1.2.0) failed to run.

**To Reproduce**
1. Go to your command line
2. Run command
```
~$ docker run --rm   --name watchtower     -v /var/run/docker.sock:/var/run/docker.sock    containrrr/watchtower:1.2.0 --run-once grafana
Unable to find image 'containrrr/watchtower:1.2.0' locally
1.2.0: Pulling from containrrr/watchtower
Digest: sha256:67e8841b1abbbaf211bb487b82a0074da50f16a617d8a4b39c1a7a2c38d4d970
Status: Downloaded newer image for containrrr/watchtower:1.2.0
standard_init_linux.go:211: exec user process caused "no such file or directory"
```
3. Enjoy failure.

**Expected behavior**
It should execute (1.1.6 works fine).

**Environment**
 - ubuntu 20.04
 - amd64
 - 19.03.8

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

</details>

**Additional context**
Maybe it is connected with https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory.

**Comment by bmorris591** [comment]
Just seen the same issue. With watchtower self-updating it spawns a failing container on every run.

**Comment by simonaronsson** [comment]
Thank you for the swift report! I've just released `v1.2.1` which should fix this issue. Please let me know whether it resolves it for you.

**Comment by bmorris591** [comment]
Successfully started with latest version, thanks @simskij

**Comment by Teeed** [comment]
Latest version (1.2.1 sha256:84e2aea373a196be2b11956ad5210e5927384036d3b0e74ed5b5521878fe14db) seems to work fine. Thank you for quick fix! :)
