### ISSUE TITLE
watchtower interferes with itself when upgrading itself (regression)

### ISSUE THREAD

**Issue by kevinlul** [containrrr/watchtower#864]
**Describe the bug**
I have a Compose deployment with each container labelled with a watchtower scope, so the watchtower instance started is only responsible for the containers in this stack. Today at 16:35 Eastern (2021-03-28 20:35 UTC), a new latest was pushed to Docker Hub, and the error in #747 reoccurred. This is a regression as previous watchtower self-updates since have succeeded.

**To Reproduce**
Simplified version of the actual compose file used is in the previous issue.

**Expected behavior**
I expected watchtower to update itself as it does with other containers, without sending a bunch of errors, fighting itself, and segfaulting. I also expected the updated container to have the same name as initialized by Compose (`emcee-tournament-bot_watchtower_1`).

**Screenshots**
![image](https://user-images.githubusercontent.com/6320810/112769092-3c806280-8fed-11eb-8034-7a27b63103a3.png)

Several containers were created and stuck in the `restarting` state before I ran `docker-compose stop watchtower` to stop them all.

```console
$ docker-compose ps
              Name                            Command                  State                Ports
-----------------------------------------------------------------------------------------------------------
MPSyhOBpiqbaarPyXwdTttkdnUkaxzFO   /watchtower                      Exit 1
VtjBBvihCpkMdSpsiasICfdKgBmVaxFj   /watchtower                      Exit 1
dOdfFsesaEctJLoIjbxEHiTdJTBemCUu   /watchtower                      Exit 1
dQSbCsgHvNfKmYmDLzsOkRfLdgaxEqzh   /watchtower                      Exit 1
emcee_adminer_1                    entrypoint.sh docker-php-e ...   Up (healthy)   127.0.0.1:8080->8080/tcp
emcee_backup_1                     /bin/sh -c exec /usr/local ...   Up (healthy)   5432/tcp
emcee_bot_1                        docker-entrypoint.sh node  ...   Up
emcee_postgres_1                   docker-entrypoint.sh postgres    Up (healthy)   127.0.0.1:5432->5432/tcp
emcee_watchtower_1                 /watchtower                      Exit 1
giYjGXQGWNjUeJSsvHkkEltvZsnGnhmX   /watchtower                      Exit 1
mElssuEBGeJMvClfAaiEUTiOuzgRMcjN   /watchtower                      Exit 1
pWEZJHRXUzuEeIJkvXeMbgqYJQhebdun   /watchtower                      Exit 1
qEvzDrawKPMoLHgYTzmYqJRZfoeiOWKH   /watchtower                      Exit 1
ukiTgKPOhnNdQFkvdkoIHizvrkkAneVp   /watchtower                      Exit 1
```

**Environment**
Ubuntu 18.04.5 LTS, x86_64
Docker version 20.10.2, build 2291f61
docker-compose version 1.27.4, build 40524192

This happened in production so I'm not running with `--debug`. The logs match the webhook output to Discord.

**Additional context**

**Comment by bmorris591** [comment]
Seems related to this https://github.com/containrrr/watchtower/issues/863

Do you have the logs from the containers?

**Comment by simonaronsson** [comment]
Thank you for the swift report! I've just released `v1.2.1` which should fix this issue. Please let me know whether it resolves it for you.

**Comment by Arcanemagus** [comment]
`v1.2.1` lets Watchtower start up at least, I'm not sure if it will fix the self-updating issue.

**Comment by kevinlul** [comment]
Hello, it seems to have updated successfully, albeit weirdly.

![image](https://user-images.githubusercontent.com/6320810/112774472-cd643780-9007-11eb-873e-9ac06aeefc3e.png)

After this, the new container removed the old watchtower container and the stale image. shoutrr is now failing to post to the webhook (it seems to be getting a 400 Bad Request now) but I don't believe that's related to this issue.

**Comment by ovizii** [comment]
also, with the 1.2.1 update I get some weird looking notifications from watchtower upon first start:

```
Watchtower v0.0.0-unknown
Using notifications: smtp
Only checking containers with name "bitwarden" or ...
```

**Comment by zek** [comment]
I'm also having the same problem all my servers are not responding due to high amount of docker containers.

![image](https://user-images.githubusercontent.com/3463291/112817231-df3aee80-908a-11eb-811b-7384d1a8adb9.png)

**Comment by simonaronsson** [comment]
Terribly sorry for the inconvenience this might have caused for you.

1.2.1 should resolve the self-replication issue. If not, please let me know.

**Comment by simonaronsson** [comment]
> also, with the 1.2.1 update I get some weird looking notifications from watchtower upon first start:
> 
> 
> 
> ```
> 
> Watchtower v0.0.0-unknown
> 
> Using notifications: smtp
> 
> Only checking containers with name "bitwarden" or ...
> 
> ```

Glad to hear!

Yeah, the message is intentional, although there still seem to be a couple of kinks to iron out.

**Comment by ovizii** [comment]
I was just wondering about the "Watchtower v0.0.0-unknown" part.

**Comment by simonaronsson** [comment]
> I was just wondering about the "Watchtower v0.0.0-unknown" part.

Yeah, I noticed that as well. Will have to look into that. 😅 Given how much errors this last release seems to have introduced, I wouldn't be surprised if there will be a couple of patch releases in the coming days.

**Comment by kevinlul** [comment]
I need to investigate what happened with Shoutrrr and Discord and open an issue there right? It seems like of all things the Teams side kind of started working 😅

**Comment by simonaronsson** [comment]
@kevinlul

> I need to investigate what happened with Shoutrrr and Discord and open an issue there right? It seems like of all things the Teams side kind of started working 😅

That definitely wouldn't hurt! We're mostly the same people on both teams, but it definitely helps to keep things separated when possible. 🙏🏼

**Comment by piksel** [comment]
For the version to be set in the executable, it needs to be built with ldflags. I didn't specify that in the PR.

**Comment by simonaronsson** [comment]
Yeah I've added the ldflag, but it won't be corrected until the next patch release.

**Comment by ksurl** [comment]
is version detection being read from the tag? I am seeing unknown when leaving blank which defaults to latest

**Comment by simonaronsson** [comment]
@ksurl 

> is version detection being read from the tag? I am seeing unknown when leaving blank which defaults to latest

No, it's supplied through an ldflag that sets the value at compile-time. However, this was not in place in the CI when 1.2.1 was released, so it won't show the correct version until we've done another release.

**Comment by kanishkatn** [comment]
When is the first patch release?

**Comment by simonaronsson** [comment]
The first patch, 1.2.1, is already out. The next, I don't really know yet. So far the only thing it includes is a fix for the version string at startup.
