### ISSUE TITLE
failed to send notification to Gotify: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by virtualex-itv** [containrrr/watchtower#866]
Issue [#822](https://github.com/containrrr/watchtower/issues/822) was marked as fixed and closed out but I just tested with the latest watchtower v1.2.1 and still got the same error in the logs:

2021-03-28 23:20:36 | stdout | Failed to send notification via shoutrrr (url=gotify://gotify.my.domain):  failed to send notification to Gotify: Post "https://gotify.my.domain/message?token=<token-removed>": x509: certificate signed by unknown authority
-- | -- | --

also seems like it broke discord notifications which was previously working.

`failed to send discord notification: response status code 400 Bad Request`  Issue referenced at [#856](https://github.com/containrrr/watchtower/issues/865)

and I noticed the same issue as [#864](https://github.com/containrrr/watchtower/issues/864)

**Comment by virtualex-itv** [comment]
@piksel @simskij - just wanted to make you both aware.  thx for all your hard work!

**Comment by piksel** [comment]
@virtualex-itv what is the URL you are using?
You either need to use http:// (if using the `WATCHTOWER_NOTIFICATION_GOTIFY_URL`) or pass the "?disabletls=yes" (if you are using  `WATCHTOWER_NOTIFICATION_URL`)

The helper should switch the URL Scheme to `http://` when `WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY` is set, but it was overlooked.

**Comment by virtualex-itv** [comment]
hey @piksel - here is what I am using for the deployment, and I've removed any personal data.

```
sudo docker run -d \
  --name=watchtower \
  --restart=unless-stopped \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e TZ=America/New_York \
  -e WATCHTOWER_DEBUG=true \
  -e WATCHTOWER_TRACE=true \
  -e WATCHTOWER_CLEANUP=true \
  -e WATCHTOWER_POLL_INTERVAL=3600 \
  -e WATCHTOWER_NOTIFICATIONS=shoutrrr \
  -e WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true \
  -e WATCHTOWER_NOTIFICATION_URL="gotify://gotify.lab.local/<token_removed>" \
  -e WATCHTOWER_NOTIFICATION_TEMPLATE="{{range .}} ({{.Level}}): {{.Message}}{{println}}{{end}}" \
  containrrr/watchtower
```

I'm also sending notifications to pushover, slack, and discord but the latest release seems to have broken discord notifications. Pushover and Slack work fine. I specify those URLs after gotify but removed them from the above.

**Comment by piksel** [comment]
```
  -e WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
```
Ah, yeah, that will have no effect. That will only effect the case when you use the old `WATCHTOWER_NOTIFICATION_GOTIFY_URL`.
Sorry for the confusion. 

Add `?disabletls=yes` to the end of `WATCHTOWER_NOTIFICATION_URL` and it should work.

And also, with Discord, add `?title=Watchtower` (or whatever title you want, it just can't be empty).

**Comment by virtualex-itv** [comment]
@piksel - ok that worked for discord...but nothing still for gotify. I removed `-e WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true` and added `?disabletls=yes` to the end of the `WATCHTOWER_NOTIFICATION_URL` but still got the following in the log:

```
Failed to send notification via shoutrrr (url=gotify://gotify.lab.local/<token_removed>?disabletls=yes):  failed to send notification to Gotify: Post "https://gotify.lab.local:5001/?token=<token_removed>": x509: certificate signed by unknown authority
```

**Comment by piksel** [comment]
haha, I were just able to reproduce this as well by bypassing my reverse proxy... it's because of this in the default gotify config:
```yaml
  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
 ```
So it's redirecting to https even though the API tries to use http.

**Comment by virtualex-itv** [comment]
ok good to know I am not going crazy over here.  so is there way a way to work around this or will I need to wait for another new release?  Or do I need to redeploy gotify a certain way with a specific parameter?

**Comment by piksel** [comment]
Just setting
```yaml
redirecttohttps: false
```
in your config.yaml should be enough. it should also be possible to mount in the self-signed certificate into the watchtower container, but I haven't tried it.

**Comment by virtualex-itv** [comment]
thanks @piksel - I could use a bit of guidance on how to do that.  both gotify and watchtower are running as docker containers on Synology.  I did not use a config.yaml so im unsure of how/where to make this edit.

**Comment by piksel** [comment]
Seems like you can just set the environment variable `GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=false` for the gotify container.
I don't have a synology device, so I don't know how to set it up there. Sorry.

**Comment by virtualex-itv** [comment]
ok redeployed a gotify container with that environment variable added but still get the same error in the logs. :(

**Update** - @piksel I tried specifying the gotify url as a local `http://IP:Port` and that seems to work just fine.  It's when I use the reverse proxy address of `https://gotify.lab.local` that doesn't work.  I believe it has something to do obviously with certificate validation.  I have some other containers that I needed to disable certificate validation for local addresses in order for them to work properly and communicate with other local containers via their fqdn.  Is there a way to do something similar for gotify and watchtower?

**Comment by piksel** [comment]
Oh, then it wasn't gotify that redirected the http to https, it was the reverse proxy (which has the non-trusted certificate).
I have added the *actual* TLS verification disabling to `DisableTLS` as well in https://github.com/containrrr/shoutrrr/pull/154, since the current solution obviously isn't solving the problem. The justification for not doing so initially was that it would be up to the server to allow unsecure connections (by either allowing connections via HTTP or not), instead of just ignoring the actual security features set up. The difference for real-world usage is actually minimal, and I don't think it makes sense to keep it.

Ideally, it should be possible to pass the local CA certificate to shoutrrr (or watchtower) in an env/arg/file instead.

**Comment by virtualex-itv** [comment]
@piksel - ok glad we're getting to the root of the problem, thank you.  so no workaround then in the interim, right?  I'd have to wait for an updated version of `shoutrrr` to be released with this change implemented then redeploy `watchtower`?

**Comment by piksel** [comment]
Well, the workaround needs to happen in your reverse proxy, which is kind of hard for me to help you with. You could debug it using `curl -v` and look at what is happening when posting to `http://gotify.lab.local`:
```
curl -v "http://gotify.lab.local/message?token=<apptoken>" -F "message=testmessage"
```

**Comment by virtualex-itv** [comment]
got it, thanks much for all of your help.  As I do have it working for now, it may be easier for me to just sit and wait for a new release and re-test at that point.  please keep me posted if you would, thanks again!

**Comment by simonaronsson** [comment]
This should be fixed with the latest shoutrrr release. If not, please create a new issue.
