### ISSUE TITLE
Cron Schedule not working

### ISSUE THREAD

**Issue by darkps10n** [containrrr/watchtower#87]
Hi,

The Cron Schedule seems to not work at all logs show the following date for first run:

"time="2017-06-21T08:53:50Z" level=info msg="First run: 2018-01-01 00:10:00 +0000 UTC" "

sudo docker run -d \
  --name watchtower \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower --cleanup --schedule "0 10 * * 1-5"

**Comment by stffabi** [comment]
Watchtower uses cron expressions like defined [here](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format).

```
Field name   | Mandatory? | Allowed values  | Allowed special characters
----------   | ---------- | --------------  | --------------------------
Seconds      | Yes        | 0-59            | * / , -
Minutes      | Yes        | 0-59            | * / , -
Hours        | Yes        | 0-23            | * / , -
Day of month | Yes        | 1-31            | * / , - ?
Month        | Yes        | 1-12 or JAN-DEC | * / , -
Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?
```

Therefore your cron expression defines to be run for the months `1-5`, which will result in first run on `2018-01-01 00:10:00 +0000 UTC`.

**Comment by darkps10n** [comment]
Is the second last "position" not Month/s and the Last Day/s?

**Comment by stffabi** [comment]
It is, but you only have 5 positions defined instead of 6. Therefore your last position `1-5` is months and not days.

**Comment by darkps10n** [comment]
Thanks for the help got it!
