### ISSUE TITLE
Watchtower v0.0.0-unknown

### ISSUE THREAD

**Issue by kevindd992002** [containrrr/watchtower#881]
After the latest update on Watchtower, I'm now getting these message in my notification emails:

```
Watchtower v0.0.0-unknown
Using notifications: smtp
Checking all containers (except explicitly disabled with label) Scheduling first run: 2021-04-09 06:00:00 +0800 PST Note that the first check will be performed in 167 hours, 53 minutes, 36 seconds
```

Is this a bug of some sort? I'm using this image "containrrr/watchtower:latest"

**Comment by DannyBoyKN** [comment]
That seems to be an unfinished feature. Look here [#861](https://github.com/containrrr/watchtower/issues/861#issuecomment-812481204)

**Comment by piksel** [comment]
Yeah, I'll quote my message here, since this issue is actually about his:
> A feature to display the version in the startup message was merged, but the release scripts were never updated to populate it. The only version that is released that displays v0.0.0-unknown is v1.2.1 though. Sorry for the confusion

**Comment by simonaronsson** [comment]
The CI has already been updated, so starting with `v1.2.2` it should work as intended.

**Comment by kevindd992002** [comment]
Great, thanks! As long as it's a cosmetic bug only, I'm fine. It does seem to update the containers properly anyway.
