### ISSUE TITLE
Watchtower crashing in a loop.

### ISSUE THREAD

**Issue by ddovidenko** [containrrr/watchtower#884]
**Describe the bug**
Watchtower is repeatedly crashing.

**To Reproduce**
Running with Dockstarter to maintain other containers. Noticed this container has been crashing repeatedly since April 2nd:

<code>goroutine 1 [running]:
github.com/containrrr/watchtower/pkg/notifications.(*Notifier).String(0xc000387b60, 0xcf9678, 0x16)
        /home/runner/work/watchtower/watchtower/pkg/notifications/notifier.go:61 +0x33a
github.com/containrrr/watchtower/cmd.writeStartupMessage(0xc000240dc0, 0x0, 0xed7fe3630, 0x12564c0, 0xd161d1, 0x3f)
        /home/runner/work/watchtower/watchtower/cmd/root.go:244 +0xee
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule(0xc000240dc0, 0xc00049eae0, 0xd161d1, 0x3f, 0x0, 0x0)
        /home/runner/work/watchtower/watchtower/cmd/root.go:282 +0x21a
github.com/containrrr/watchtower/cmd.Run(0xc000240dc0, 0x1287510, 0x0, 0x0)
        /home/runner/work/watchtower/watchtower/cmd/root.go:188 +0x385
github.com/spf13/cobra.(*Command).execute(0xc000240dc0, 0xc0000301b0, 0x0, 0x0, 0xc000240dc0, 0xc0000301b0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000240dc0, 0x406325, 0xc00008a058, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
        /home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x31
main.main()
        /home/runner/work/watchtower/watchtower/main.go:13 +0x25
panic: runtime error: slice bounds out of range [:-2]</code>

**Environment**
 - Ubuntu 20 LTS as KVM Guest
 - Dockstarter
 - Docker 20.10.5

**Comment by simonaronsson** [comment]
Looks like the title issue. @piksel, are you able to confirm?

**Comment by piksel** [comment]
No, this is the "notifications enabled, but no services configured" (fixed by #869)
Either remove "shoutrrr" from `WATCHTOWER_NOTIFICATIONS` or add notification URLs to `WATCHTOWER_NOTIFICATION_URL` to fix it locally @ddovidenko

**Comment by ddovidenko** [comment]
Thanks guys, @piksel this has resolved my issue. Really appreciate the help =).
