### ISSUE TITLE
Is there any way to see what watchtower is doing? E.g. a Logfile?

### ISSUE THREAD

**Issue by COLABORATI** [containrrr/watchtower#89]
Looks like a very good idea - however I have zero information about if watchtower is doing something on my docker host and if it was done successfully. How to get logs out of watchtower? Any docs about this?

**Comment by stffabi** [comment]
Just take a look onto the console output.

`docker logs your_watchtower_container`

You can also set `--debug` as mentioned in the README.md for more detailed information.

**Comment by stffabi** [comment]
The console output should give enough information. I'll close the issue, feel free to open a new one if you have any further questions or problems.
