### ISSUE TITLE
HEAD request log messages

### ISSUE THREAD

**Issue by simonaronsson** [containrrr/watchtower#892]
> Hi!
> 
> No, that is by design. Since DockerHub started to enforce rate limiting, we added support for doing HEAD requests to compare digests instead of pulling the whole manifest. We decided to put that as a warning as watchtower no longer doing head requests would mean their usage quota will be consumed.
>
_Originally posted by @simskij in https://github.com/containrrr/watchtower/discussions/890#discussioncomment-590012_

A lot of users have reported that this message is annoying or confusing, so I'd like to arrange some kind of vote about how to proceed. Personally, I'd much rather have watchtower warn about head request errors than not.

What do y'all feel? Let's do a vote using emojis. 

🎉  - Move warning to debug level
🚀  - Add an option to suppress the warning (ie. something like `--no-head-warnings`)
👀  - Keep as is.

**Comment by educatedCaveman** [comment]
I'd be fine with either moving it to debug or adding an option to suppress

**Comment by Dulanic** [comment]
I'd recommend exclusion being explicit not implicit. I just fixed mine because I saw so many of those messages and realized I had network mode none which was causing it. People should research it, but have the ability to easily turn it off. If it's implicit, I would not have known.

**Comment by piksel** [comment]
Thanks @Dulanic, it's much harder to justify being annoying 😅.

**Comment by simonaronsson** [comment]
> I'd recommend exclusion being explicit not implicit. I just fixed mine because I saw so many of those messages and realized I had network mode none which was causing it. People should research it, but have the ability to easily turn it off. If it's implicit, I would not have known.

That's great feedback! Thanks!

**Comment by simonaronsson** [comment]
We've decided to go for the explicit opt-out route, making the logs default for ghcr and dockerhub, but allowing users to turn them on for **all** repos if they wish, or off for **all** repos. Thank you for your input!
