### ISSUE TITLE
Panic  runtime error

### ISSUE THREAD

**Issue by vascozorrinho** [containrrr/watchtower#896]
**Describe the bug**
Container is crashing and not updating.

**Screenshots**

**Environment**
 - Platform raspbian os
 - Architecture ARM64
 - Docker version  20.10.5

<details>
 <summary><b> Logs from running watchtower</b></summary>

github.com/containrrr/watchtower/cmd.writeStartupMessage(0x1920840, 0x0, 0x0, 0xd8070030, 0xe, 0xbfd670, 0x7924d0, 0x3f)
/home/runner/work/watchtower/watchtower/cmd/root.go:244 +0xd8
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule(0x1920840, 0x1af6380, 0x7924d0, 0x3f, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:282 +0x1a0
github.com/containrrr/watchtower/cmd.Run(0x1920840, 0xc0f744, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:188 +0x2c8
github.com/spf13/cobra.(*Command).execute(0x1920840, 0x180e0f8, 0x0, 0x0, 0x1920840, 0x180e0f8)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8
github.com/spf13/cobra.(*Command).ExecuteC(0x1920840, 0x1858070, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20
main.main()
/home/runner/work/watchtower/watchtower/main.go:13 +0x14
panic: runtime error: slice bounds out of range [:-2]
goroutine 1 [running]:
github.com/containrrr/watchtower/pkg/notifications.(*Notifier).String(0x2356290, 0x775a08, 0x16)
/home/runner/work/watchtower/watchtower/pkg/notifications/notifier.go:61 +0x264
github.com/containrrr/watchtower/cmd.writeStartupMessage(0x21c2420, 0x0, 0x0, 0xd8070030, 0xe, 0xbfd670, 0x7924d0, 0x3f)
/home/runner/work/watchtower/watchtower/cmd/root.go:244 +0xd8
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule(0x21c2420, 0x2309790, 0x7924d0, 0x3f, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:282 +0x1a0
github.com/containrrr/watchtower/cmd.Run(0x21c2420, 0xc0f744, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:188 +0x2c8
github.com/spf13/cobra.(*Command).execute(0x21c2420, 0x20960e0, 0x0, 0x0, 0x21c2420, 0x20960e0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8
github.com/spf13/cobra.(*Command).ExecuteC(0x21c2420, 0x2094030, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20
main.main()
/home/runner/work/watchtower/watchtower/main.go:13 +0x14
panic: runtime error: slice bounds out of range [:-2]
goroutine 1 [running]:
github.com/containrrr/watchtower/pkg/notifications.(*Notifier).String(0x2989d60, 0x775a08, 0x16)
/home/runner/work/watchtower/watchtower/pkg/notifications/notifier.go:61 +0x264
github.com/containrrr/watchtower/cmd.writeStartupMessage(0x29ba420, 0x0, 0x0, 0xd8070030, 0xe, 0xbfd670, 0x7924d0, 0x3f)
/home/runner/work/watchtower/watchtower/cmd/root.go:244 +0xd8
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule(0x29ba420, 0x2b036a8, 0x7924d0, 0x3f, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:282 +0x1a0
github.com/containrrr/watchtower/cmd.Run(0x29ba420, 0xc0f744, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:188 +0x2c8
github.com/spf13/cobra.(*Command).execute(0x29ba420, 0x28960e0, 0x0, 0x0, 0x29ba420, 0x28960e0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8
github.com/spf13/cobra.(*Command).ExecuteC(0x29ba420, 0x2894030, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20
main.main()
/home/runne/work/watchtower/watchtower/main.go:13 +0x14
panic: runtime error: slice bounds out of range [:-2]
goroutine 1 [running]:
github.com/containrrr/watchtower/pkg/notifications.(*Notifier).String(0x1efc770, 0x775a08, 0x16)
/home/runner/work/watchtower/watchtower/pkg/notifications/notifier.go:61 +0x264
github.com/containrrr/watchtower/cmd.writeStartupMessage(0x1ce06e0, 0x0, 0x0, 0xd8070030, 0xe, 0xbfd670, 0x7924d0, 0x3f)
/home/runner/work/watchtower/watchtower/cmd/root.go:244 +0xd8
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule(0x1ce06e0, 0x1f3c360, 0x7924d0, 0x3f, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:282 +0x1a0
github.com/containrrr/watchtower/cmd.Run(0x1ce06e0, 0xc0f744, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:188 +0x2c8
github.com/spf13/cobra.(*Command).execute(0x1ce06e0, 0x1c960e0, 0x0, 0x0, 0x1ce06e0, 0x1c960e0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8
github.com/spf13/cobra.(*Command).ExecuteC(0x1ce06e0, 0x1c94030, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20
main.main()
/home/runner/work/watchtower/watchtower/main.go:13 +0x14
panic: runtime error: slice bounds out of range [:-2]
goroutine 1 [running]:
github.com/containrrr/watchtower/pkg/notifications.(*Notifier).String(0x1eac7a0, 0x775a08, 0x16)
/home/runner/work/watchtower/watchtower/pkg/notifications/notifier.go:61 +0x264
github.com/containrrr/watchtower/cmd.writeStartupMessage(0x1d20840, 0x0, 0x0, 0xd8070030, 0xe, 0xbfd670, 0x7924d0, 0x3f)
/home/runner/work/watchtower/watchtower/cmd/root.go:244 +0xd8
github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule(0x1d20840, 0x1ef6370, 0x7924d0, 0x3f, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:282 +0x1a0
github.com/containrrr/watchtower/cmd.Run(0x1d20840, 0xc0f744, 0x0, 0x0)
/home/runner/work/watchtower/watchtower/cmd/root.go:188 +0x2c8
github.com/spf13/cobra.(*Command).execute(0x1d20840, 0x1c0e0f8, 0x0, 0x0, 0x1d20840, 0x1c0e0f8)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x1e8
github.com/spf13/cobra.(*Command).ExecuteC(0x1d20840, 0x1c58070, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x250
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/containrrr/watchtower/cmd.Execute()
/home/runner/work/watchtower/watchtower/cmd/root.go:70 +0x20
main.main()
/home/runner/work/watchtower/watchtower/main.go:13 +0x14

</details>

I'm very noob :) can anyone help? Thanks!

**Comment by piksel** [comment]
This looks like the same issue as "notifications enabled, but no services configured" (fixed by #869) 

Either remove "shoutrrr" from `WATCHTOWER_NOTIFICATIONS` or add notification URLs to `WATCHTOWER_NOTIFICATION_URL` to fix it locally
