### ISSUE TITLE
Upgrades on schedule not working when API enabled

### ISSUE THREAD

**Issue by yrien30** [containrrr/watchtower#897]
**To Reproduce**
Enable http api: 
-e WATCHTOWER_HTTP_API_UPDATE=true -e WATCHTOWER_HTTP_API_TOKEN=Token

**Expected behavior**
I expect watchtower to check for updates every 10 minues since I have enabled this setting:  -e WATCHTOWER_POLL_INTERVAL=600

No updates since 2021-04-07T11:31:34Z time now is 2021-04-13T10:58:34Z
![image](https://user-images.githubusercontent.com/26816162/114526118-f828cf80-9c46-11eb-8531-9a4f6aa6b08d.png)

I suspect that api server is blocking for update scheduling from starting:
https://github.com/containrrr/watchtower/blob/aa3ed8833f484b3c016f8c76260442b1487a91c4/cmd/root.go#L182-L186

**Environment**
 - arm64

**Comment by simonaronsson** [comment]
The HTTP API is currently blocking. This will be changed by https://github.com/containrrr/watchtower/pull/916
