### ISSUE TITLE
How to rollback in case of catastrophic error?

### ISSUE THREAD

**Issue by COLABORATI** [containrrr/watchtower#90]
Well the title says it all - how to roll back in case an updated container breaks?

**Comment by franciscoed** [comment]
Sounds good. Any news about it?

**Comment by simonaronsson** [comment]
That is not something watchtower currently aims to solve. I do like the idea however. Do you have any suggestions on how this would work?

**Comment by simonaronsson** [comment]
Closing due to lack of response.

**Comment by iamareebjamal** [comment]
I think if the docker container fails to start/restart within a set period of time or its HEALTHCHECK fails, watchtower could rollback to previous version of the container?

**Comment by dankozlowski** [comment]
This seems like an essential idea.  Has there been any progress on this note?

**Comment by piksel** [comment]
No, there isn't anything like a "rollback" that watchtower can perform, even if it wanted to. In theory, it could hold on to the previous image and try to recreate the container with that image, but the most common reason for an update to fail is that the container uses something that watchtower doesn't understand. In such a case, recreating the container using the old image is unlikely to fare any better.

**Comment by maxime1992** [comment]
> but the most common reason for an update to fail is that the container uses something that watchtower doesn't understand. In such a case, recreating the container using the old image is unlikely to fare any better.

Personally that's not what I'm after. I'd like to be able to rollback to previous versions for example not only if something crashes but mainly if I notice that something has a regression (but the container is still working ok).

On Watchtower side, I'm guessing this would mean:
- Use docker inspect to be aware of a version of a given container
- Save this in a database
- Have a UI that shows the list of all the different versions that have been used in the past
- If someone wants to rollback, specify the older version to create the image

> This seems like an essential idea

Agreed. It's the primary reason I'm not using watchtower even though I was very interested in it initially (and still am). But with automatic upgrade, I need super easy rollback capabilities built in.

**Comment by gingerbeardman** [comment]
I'd also like this, I say this as watchtower upgraded to a latest that is broken/untested on my hardware setup.

**Comment by piksel** [comment]
> Use docker inspect to be aware of a version of a given container
> Save this in a database
> Have a UI that shows the list of all the different versions that have been used in the past
> If someone wants to rollback, specify the older version to create the image

None of this is compatible with how watchtower is structured today, it's stateless and UI-less (except for the CLI args/Env vars, but those are one-way). It **could** be done, but it would be a great effort (and perhaps alter the role of watchtower, which other users might not be be happy about), but the main problem is simply that no one is doing it. Watchtower is a community project and we are merely maintainers.

**Comment by meonkeys** [comment]
Another issue: what if an upgrade caused a database migration, and that container's database code doesn't support rollback / downgrade?

**Comment by gingerbeardman** [comment]
That issue would be on the container, not watchtower.

**Comment by meonkeys** [comment]
I agree, but it seems likely that watchtower would be blamed when a rollback fails. "Blame" isn't a great word here, I'm just not sure how common it is for containers to support rolling back to older images. Surely stateless/simple images would be fine.

Maybe it's just another case where a non-rollback-able container would need to be excluded from automated watchtower upgrades... but that means more hands-on sysadmin, communication, and research into which containers will be fine and which ones won't, and I use watchtower specifically to keep containers up to date with less manual work. :shrug:

**Comment by gingerbeardman** [comment]
You're over thinking this IMHO

**Comment by HerrMuellerluedenscheid** [comment]
I needed roll-backs as well and since watchtower doesn't have that I started building a very simple container update tool with a minimalistic subset of the features that watchtower offers but with automatic rollback (and a shitty web ui). Would be super happy if anybody would try it out. It's been doing its job over the last months for the two, three use cases of mine but would be curious to hear about the failures and edge cases that others encounter
https://github.com/HerrMuellerluedenscheid/hoister
