### ISSUE TITLE
Request: add an option to retain x number of older images

### ISSUE THREAD

**Issue by DeltaTangoLima** [containrrr/watchtower#910]
**Describe the solution you'd like**
I'd like an option that pairs with `--cleanup` (`--cleanup-keep`?) that lets me specify how many older images to retain for a given container, to be able to provide n-X rollback capability.

This would make rollback much quicker where a newer image has introduced a breaking change, rather than having to find and re-download the last known working image.

**Comment by simonaronsson** [comment]
Thank you for the suggestion! This would indeed be interesting to support. Do you have any suggestion as to how to decide which images to keep? We could of course use the `CREATED` timestamp, but as you can pull images in any order you want, this won't give any guarantees that it's the latest images that are kept.

**Comment by DeltaTangoLima** [comment]
To be honest, I hadn't thought that far ahead! Maybe we could just start with a simple `--keeplast` option, so we can keep the image currently in use as it's updated, guaranteeing n-1 rollback for that given container.

EDIT: y'know, reflecting on this a bit more, maybe this could be controlled with a label for each container, instead.  Something like `com.centurylinklabs.watchtower.keeplastimg: true` might do the trick.

The reason I made the feature request in the first place is becuase I had a pihole container update go pear-shaped, and I couldn't even get to the repo to redownload the last image without jumping through a couple of extra hoops.

**Comment by KevinGimbel** [comment]
I'd like to work on this since it's something we want as well! 

From a first look around it seems https://github.com/containrrr/watchtower/blob/dec6f84a7085e5d24716da10b4d4781a9c3d47d0/internal/actions/update.go#L100-L110 is a place to make any changes to the logic involving image deletion, right? In the `cleanUpImages` map we'd need to skip/remove the last used images to realise the `--keeplast` functionality as far as I understand the code.

**Comment by piksel** [comment]
The tricky part is finding out which are the non-recent images. You now only have the IDs of the new image, and the previous image. None of which should be cleaned up.

**Comment by JokerQyou** [comment]
Is this an revised version of #591?

**Comment by piksel** [comment]
@JokerQyou They are basically the same idea, sure, but I'm not entirely sure what you are asking 😅

**Comment by pbek** [comment]
This still would be awesome. 😉

**Comment by simonaronsson** [comment]
This is not something we will pursue. If someone wants to have a stab at this, feel free to create a PR with the necessary changes.
