### ISSUE TITLE
Please add ability to trigger updates via human intervention

### ISSUE THREAD

**Issue by COLABORATI** [containrrr/watchtower#92]
Basically, in combination with the other issues I would like to receive notifications that updates are ready and would like to see some way of manually triggering that update process - plus rollback. 

Looks lal very good, but fundamental things that an update process needs to be safe should be added to make this useful in real life.

**Comment by julianxhokaxhiu** [comment]
I totally agree with this. I would like to have the update process on-demand sometimes. Making it always up and running based on time doesn't bring any additional value, especially on PROD area.

Would be nice to have a command to run on PROD once everything is tested against on TESTING area.

**Comment by stffabi** [comment]
Issue #114 asks for the same thing, a possibility to just run watchtower once and update everything and then stop the execution. There's also a PR for this one #116
