### ISSUE TITLE
Sending Telegram message with parse mode fails

### ISSUE THREAD

**Issue by nadavgolden** [containrrr/watchtower#921]
Tried sending a message with `MarkdownV2` and `HTML` parse modes, both fail with HTTP 400:

URL: `telegram://****:****@telegram?channels=****&parseMode=html`
Logs:
```
failed to send notification to "****", response status code 400 Bad Request
```

**Comment by simonaronsson** [comment]
Transfering this to the watchtower repo as any change would have to be made there.
