### ISSUE TITLE
Difference between exposed and bound ports handled incorrectly

### ISSUE THREAD

**Issue by Frank071** [containrrr/watchtower#945]
Following https://github.com/containrrr/watchtower/issues/832#issuecomment-826085026_ I found that there is a difference between "publishing" ports and "exposing" ports. The latter is done with the EXPOSE keyword in the Dockerfile and results in config.ExposedPorts being filled. This "_does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published_". Publishing ports is done with either the "-p" option (on a per port basis) or the "-P" option (publishing all EXPOSED ports).

So it is possible that a container has port bindings without those ports being EXPOSED. Whether or not this is correct is a different discussion. However, based on this possibility I think these lines in container.go are incorrect:

```
229         for p := range c.containerInfo.HostConfig.PortBindings {
230                 config.ExposedPorts[p] = struct{}{}
231         }
```

Not only because these lines explicitly expose all bound ports, which need not be the correct configuration. But also (and I think this is the cause for the crash) because this code assumes the existence of config.ExposedPorts if there are PortBindings. Now I do not know enough about Go to suggest a patch, but probably it suffices to skip this if config.ExposedPorts == nil.... 

This, recently added, part would also fire on containers that publish not previously exposed ports, which is possible and thus these lines are, probably, incorrect:

```
284         if len(hostConfig.PortBindings) > 0 && containerConfig.ExposedPorts == nil {
285                 return errorNoExposedPorts
286         }
```

since it is allowed to have ports bound without them being exposed in the first place.

There are analogous tests in container_test.go that probably need to be removed or altered as well.

**Comment by piksel** [comment]
The above check was added to make sure that Watchtower does not crash if that happens. Skipping the update is better than stopping and removing the container and then crashing, leaving the container in a removed state.

> This, recently added, part would also fire on containers that publish not previously exposed ports, which is possible and thus these lines are, probably, incorrect

No, regardless of whether the image exposes the ports, this is populated in the response from an unmodified docker daemon.

I'm not sure that Config.ExposedPorts == EXPOSE in a Dockerfile, as it's not populated from the image, but rather from the running container config.
