### ISSUE TITLE
Documentation contains paragraph in unexpected location

### ISSUE THREAD

**Issue by tucknology** [containrrr/watchtower#946]
**Describe the bug**
There is a paragraph describing watchtower self-updates, but it appears under a heading for slack notifications.

**To Reproduce**
1. Go to <https://containrrr.dev/watchtower/notifications/#slack>
2. Read the first paragraph. Seems like this paragraph might belong elsewhere:

> If watchtower is monitoring the same Docker daemon under which the watchtower container itself is running (i.e. if you volume-mounted /var/run/docker.sock into the watchtower container) then it has the ability to update itself. If a new version of the containrrr/watchtower image is pushed to the Docker Hub, your watchtower will pull down the new image and restart itself automatically.

**Expected behavior**
This paragraph might be better organized in a different section of the documentation. Maybe under **Usage overview** , or perhaps under its own dedicated heading.

**Screenshots**
<img width="1288" alt="Screen Shot 2021-04-30 at 11 34 57" src="https://user-images.githubusercontent.com/19787615/116719091-abfcbf80-a9a8-11eb-8f00-7e0343e9c2e3.png">

**Comment by simonaronsson** [comment]
Yes, this definitely seems to have ended up in the wrong location. Thanks for the heads-up!

**Comment by piksel** [comment]
I spent the entire last weekend looking through the documentation, and somehow totally missed that. 😐
