### ISSUE TITLE
'Failed to send notification via shoutrrr' after recreating on another docker network bridge

### ISSUE THREAD

**Issue by BackedUpBooty** [containrrr/watchtower#948]
Hi, I had an issue back in Jan for a similar shoutrrr authentication error you helped me with (https://github.com/containrrr/watchtower/issues/754) and I've now got a similar but different error. 

I recently moved my watchtower from one docker network to another, along with a number of other containers in the stack.  Since doing so, I started getting the following error in the (portainer) log (I've replaced the sensitive data with the .env references):

`Failed to send notification via shoutrrr (url=smtp://root:[PASSWD]@[$SERVER]:587/?auth=Plain&encryption=None&fromaddress=[$FROM]&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on b694eb3e1072&toaddresses=[$TO]&usehtml=No):  error authenticating: 535 5.7.8 Authentication failed`

My docker-compose is as below:

``` watchtower: #automatic container version monitoring and updating
  container_name: watchtower
  image: containrrr/watchtower:latest
  environment: 
    - TZ=$TZ
    - DEBUG=true
    - WATCHTOWER_CLEANUP=true
    - WATCHTOWER_INCLUDE_RESTARTING=true
    - WATCHTOWER_INCLUDE_STOPPED=true
    - WATCHTOWER_NOTIFICATIONS=email
    - WATCHTOWER_NOTIFICATION_EMAIL_FROM=$FROM
    - WATCHTOWER_NOTIFICATION_EMAIL_TO=$TO
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=$SERVER
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=$SERVER_PORT
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=$USER
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=$PASSWD
    - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    - WATCHTOWER_LABEL_ENABLE=true
  command: --interval 360
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - Horus
```
Some things to note:

- I've not changed my compose file other than for networks (and it connects to the network no problem)
- I've not changed the smpt server details at all (email from/to, user, password,  server, auth etc.)
- I've quadruple checked the .env
- I've made the variables explicit (rather than .env references) and throw up the same error
- It's putting `root:$PASSWD` into the first part of the URL rather than the actual email address - this is confusing to me
- When I first moved the container across, I got the first notification email that WT had started, but then nothing (container remained up) so I checked the logs and found the error, and confirmed it had updated a few containers without sending notification

I've gone over the previous thread to make sure I'm not missing something, plus other support posts with an authentication error (that I could find) but no joy so far. 

Hoping you might have a suggestion. Thanks for any help!

**Comment by piksel** [comment]
I think this:
```yaml
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=$USER
```
resolves to:
```yaml
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=root
```
Since:
```
$ echo $USER
piksel
```
You should probably replace that environment variable with something that isn't populated by the OS, like $EMAIL_USER?

**Comment by BackedUpBooty** [comment]
That was the problem, thank you, should have realized it would conflict if  `$USER` was already in there. 

Closing as resolved.
