### ISSUE TITLE
Unable to set schedule multiple times per months

### ISSUE THREAD

**Issue by Whisper40** [containrrr/watchtower#953]
**Describe the bug**

**To Reproduce**
Hello, i would like to set this `WATCHTOWER_SCHEDULE: "0 4 5,18,28 * *"`  in order that update runs at 04h00 every 5 and 18 and 28 of each month.
But i'v got an error that is saying 28 is over 23 (max)..
```
time="2021-05-05T21:37:37+02:00" level=error msg="End of range (28) above maximum (23): 28"
```

**Expected behavior**

There is more than 23 days per months so.. :) 
I would like to be able to run update on the 28

**Comment by zoispag** [comment]
Add an extra `0` in the beginning for the seconds.
Watchtower is using the 6* notation, as mentioned [here](https://containrrr.dev/watchtower/arguments/#scheduling).
