### ISSUE TITLE
watchtower unable to detect image

### ISSUE THREAD

**Issue by Fredrik81** [containrrr/watchtower#96]
Hello,
Watchtower is unable to find image name of most of my containers.
It gives this output:
```
time="2017-07-18T22:46:42Z" level=debug msg="Pulling sha256:72323629575287eb57b46b1b1eec223af3f0fa0b660c43cc156a3cf5c99b9e0e for /muximux"
time="2017-07-18T22:46:42Z" level=debug msg="No credentials for sha256 in /config.json"
time="2017-07-18T22:46:42Z" level=debug msg="No authentication credentials found for sha256:72323629575287eb57b46b1b1eec223af3f0fa0b660c43cc156a3cf5c99b9e0e"
time="2017-07-18T22:46:44Z" level=debug msg="Error pulling image sha256:72323629575287eb57b46b1b1eec223af3f0fa0b660c43cc156a3cf5c99b9e0e, Error response from daemon: repository sha256 not found: does not exist or no pull access"
```

Some of them is working and give this output:
```
time="2017-07-18T22:46:37Z" level=debug msg="Pulling v2tec/watchtower:latest for /watchtower"
time="2017-07-18T22:46:37Z" level=debug msg="No credentials for v2tec in /config.json"
time="2017-07-18T22:46:37Z" level=debug msg="No authentication credentials found for v2tec/watchtower:latest"
time="2017-07-18T22:46:38Z" level=debug msg="No new images found for /watchtower"
time="2017-07-18T22:46:38Z" level=debug msg="Pulling linuxserver/openvpn-as:latest for /openvpn-as"
time="2017-07-18T22:46:38Z" level=debug msg="No credentials for linuxserver in /config.json"
time="2017-07-18T22:46:38Z" level=debug msg="No authentication credentials found for linuxserver/openvpn-as:latest"
time="2017-07-18T22:46:40Z" level=debug msg="No new images found for /openvpn-as"
```

**Comment by stffabi** [comment]
Seems like for the first one you have a container running a specific image `sha256:72323629575287eb57b46b1b1eec223af3f0fa0b660c43cc156a3cf5c99b9e0e` and not an image with a repository and name like `linuxserver/openvpn-as:latest`

How do you have created the container `muximux`? Could you please post your docker run command?

**Comment by simonaronsson** [comment]
Closing due to lack of response. If this is still an issue, feel free to let me know and I'll take a look.

**Comment by rafael-h-ferreira** [comment]
Hi! It's happening to me to, I think. 
I'm using a docker stack with this:
```
web_my_service:
    image: xpto.com/my_service:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"

```
and then I run watchtower with this:

```
sudo docker run -d \
  --name watchtower \
  -v /root/.docker/config.json:/config.json \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower  --debug --label-enable --interval 30
```

Here's the log:
```
time="2019-06-05T11:56:47Z" level=debug msg="Pulling xpto.com/my-service:latest@sha256:f24be6b60cdf4d99b8a57ffcd888eb4807c8cdbcbfbeb2b682733c6538fbab19 for /stack_name__web_my_service.1.lltio3h9tq3erj1osjblxo34w" 
time="2019-06-05T11:56:47Z" level=debug msg="Loaded auth credentials {xpto registry   xpto.com  } from /config.json" 
time="2019-06-05T11:56:47Z" level=debug msg="No new images found for /stack_name__web_my_service.1.lltio3h9tq3erj1osjblxo34w" 
```

And I know there's a new image because if I pull it manually, I get a new one. Watchtower seems to be pointing to a specific "sha" with the "@" symbol and not recognizing the new versions by image id.
Am I doing something wrong?
Thanks!

**Comment by stffabi** [comment]
Watchtower currently isn't compatible with docker swarm and stacks. Docker swarm pins the version of the image used to the version which is available during the creation of the service and the tasks (containers) of the service will be created with the pinned version. This is especially needed if you have several nodes and all these nodes should have the same version of the image running. Therefore watchtower tries to get the newest image of the pinned version, which is always the same version.

So as long as watchtower doesn't support docker swarm (docker services), it will not be possible to update services of stacks deployed on swarm.

**Comment by simonaronsson** [comment]
There is already an issue for that though so I don’t think this one needs to be reopened.
