### ISSUE TITLE
Notification support for pushover and/or a custom script

### ISSUE THREAD

**Issue by OliverHi** [containrrr/watchtower#960]
I am trying to send the watchtower notifications to my phone via the pushover service. Currently I have to use a workaround by sending an email to a generated pushover email address.
It would be great to have direct support for Pushover which has a simple [HTTPS API](https://pushover.net/api#messages).

As an alternative (but generally useful solution) it would be great to have a way to just call a custom script with the notification text. That way everyone can simply implement their own solution.

**Comment by piksel** [comment]
Shoutrrr landed Pushover support 2 years ago 😁
https://containrrr.dev/shoutrrr/services/pushover/

**Comment by OliverHi** [comment]
Thank you that worked very well. I was under the impression that shourtrrr is an external service you need to run, but it seems like it is just an included library.
