### ISSUE TITLE
Multiple containers using the same image makes cleanup throw an error

### ISSUE THREAD

**Issue by schklom** [containrrr/watchtower#963]
**Describe the bug**
Having multiple containers using the same image makes cleanup throw an error and the entire process stops.

**To Reproduce**
1. Start 2 containers with the same image
2. Run Watchtower with `cleanup` flag/variable

**Expected behavior**
Normal update and cleanup

**Environment**
 - Platform
Raspberry Pi 4
 - Architecture 
```
$ uname -srvmpio
Linux 5.10.0-0.bpo.5-arm64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64 unknown unknown GNU/Linux
```
 - Docker version
20.10.5

It was from yesterday, without debug option. I will make an update tomorrow and post logs with debug then.
<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
Found new schklom/ttrss-app:with-filelogging-latest image (ae5c5760d7ef)
Stopping /ttrss (5131bd9aa263) with SIGTERM
Creating /ttrss
Removing image 52bdf1c46dfe
Error response from daemon: conflict: unable to delete 52bdf1c46dfe (cannot be forced) - image is being used by running container c01d0e6fcad0
```

</details>

**Additional context**
A solution is to run Watchtower again. But it is really not ideal.

**Comment by piksel** [comment]
> ... and the entire process stops  

Are you sure about that?

Looking at the source, it should only report the error, and then continue as normal.
https://github.com/containrrr/watchtower/blob/61b715abec79dc931c6312b8334eb4fdd4a8f7e8/internal/actions/update.go#L175-L179

It's still weird that it doesn't do the cleanup after all the containers have been processed, which would prevent this error to be logged at all though...

**Comment by schklom** [comment]
> Are you sure about that?

Yes, removing and starting the container Watchtower again led to a successful update of every container (even the 2nd container using the same image) instead of just one.

> It's still weird that it doesn't do the cleanup after all the containers have been processed, which would prevent this error to be logged at all though...

This is what happened the 2nd time it ran. I have no idea why it didn't the 1st time.
I will wait a few days for images to be updated, then run the process with `debug` on and post the logs. Hopefully it will reveal what went wrong.

**Comment by simonaronsson** [comment]
Sounds like we need to wait for the next time those containers get updated. Might be that you ran on an older, cached, watchtower version?

**Comment by schklom** [comment]
Ok this was weird, no error happened today, and the opportunity was there. Watchtower didn't even update itself, so I guess I already had the latest version.
I have no idea what happened last time.
I will reopen this issue if it happens again. Thanks for trying to help, take care! :)
