### ISSUE TITLE
Per container maintenance window

### ISSUE THREAD

**Issue by bkmeneguello** [containrrr/watchtower#97]
In my environment there are services with special maintenance windows (midnight) and others with fast update needs (asap). I've tried to setup two watchtowers, one kills the other and only one can run at time.
I think a good solution is (like jwilder/nginx-proxy) set per container enviroment properties or labels setting schedule, interval, no-pull, cleanup or update flags.

**Comment by simonaronsson** [comment]
Sounds like a great addition! Feel free to create a pull request and I’ll be happy to review it.

**Comment by nogweii** [comment]
This isn't stale, it's still useful.

**Comment by blackandred** [comment]
I would also see this as useful.

**Comment by TheUltimateC0der** [comment]
You damn bot! Stop it. Still useful.

**Comment by piksel** [comment]
It is stale, since no one is working on this, and it's been 6 years.
