### ISSUE TITLE
Add healthcheck command.

### ISSUE THREAD

**Issue by Ryland0** [containrrr/watchtower#972]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
Add a healthcheck command to the image.

**Describe alternatives you've considered**
Not asking this question.

**Additional context**
Just curious if this has been discussed/considered.

**Comment by piksel** [comment]
Ref: https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by simonaronsson** [comment]
@piksel and I have been discussing this previously, and came to the conclusion that we don't really know what a healthcheck would even do in the watchtower case.

As watchtower runs on a scratch image, it means that watchtower crashing/not working will make the container exit and restart. Any suggestions?

**Comment by simonaronsson** [comment]
No takers, so closing this.

**Comment by aehlke** [comment]
record exit codes from last runs (tmp files?), report latest as health check to catch scenarios such as lifecycle hooks failing

**Comment by PiDroid-B** [comment]
maybe something like that :

`healthcheck.sh`
```bash
#!/bin/sh

PERIOD_12H=43200

MAX_DELAY=$(( PERIOD_12H + 60 ))

# delay since last loop (seconds)
DELAY=$(($(date +%s) - $(date +%s -r /tmp/last_loop)))

[ "${DELAY}" -gt "${MAX_DELAY}" ] && exit 1

exit 0
```
And for the dockerfile :
`HEALTHCHECK --interval=5m --timeout=2s --start-period=30s CMD sh healthcheck.sh`

it's just an example to improve and adjust with env var. The watchtower job has just to make a touch on the file to update it
