### ISSUE TITLE
Label: stop-timeout per container

### ISSUE THREAD

**Issue by jykae** [containrrr/watchtower#985]
## Problem
We have long-running containers that we would like to gracefully restart without "stop-timeout" to forcefully kill the container process. Global stop-timeout is not option for us.

## Possible solution
We would need label for disabling "stop-timeout" for individual containers. Stop timeout label could disable "stop-timeout" OR set "stop-timeout" for container.

**Comment by simonaronsson** [comment]
Sounds reasonable! I'd be happy to review such a PR if you're up for creating one! :)
