### ISSUE TITLE
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD

### ISSUE THREAD

**Issue by Yanik39** [containrrr/watchtower#991]
--notification-email-server-password (env. WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD): The password to authenticate with the SMTP server with. Can also reference a file, in which case the contents of the file are used.

Hello,

I passed the password file /home/user/secrets/passwd
but i get auth error to my smtp server.

How shall i refer to that password file?
i guess simply full path is not.

Cheers

**Comment by piksel** [comment]
The file must exist inside the container, so you'd have to mount it using a volume.
Command line example:
```
docker run -d \
--name watchtower \
-v /home/user/secrets/passwd:/home/user/secrets/passwd \
-v /var/run/docker.sock:/var/run/docker.sock \
--notification-email-server-password /home/user/secrets/passwd \
containrrr/watchtower
```
You would obviously need the rest of the email configuration variables as well.

**Comment by Yanik39** [comment]
Aha :D 
Worked like a charm.
Thanks
