### ISSUE TITLE
Integration for Healthchecks.io

### ISSUE THREAD

**Issue by hr87** [containrrr/watchtower#998]
**Is your feature request related to a problem? Please describe.**
Monitoring the execution of Watchtower with https://healthchecks.io/

**Describe the solution you'd like**
Offering monitoring via healthchecks, either the official website or self hosted. Preferably, in addition to normal notifications. Checks are don by connecting to a public, but unique URI. So no authentication is required, e.g
```
curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/your-uuid-here
```
Several examples are given in the documentation: https://healthchecks.io/docs/.

Best would it be, if you can support the start/finish/failure commands.

**Describe alternatives you've considered**
Give the user the possibility to run a custom command before and after the whole execution (not each container), maybe on failure, too

**Additional context**
Healthchecks.io send notifications when a scheduled check-in did not happen, alerting therefore to a hung container.

**Comment by modem7** [comment]
I'd argue that this isn't really within Watchtower's scope. I'd say it's more in Autoheal's or Monocker's scope.

Images may update at a whim, depending on when a dev or CI/CD updates, so not quite sure how useful a check-in would be.

**Comment by piksel** [comment]
Except for the "before" part, it could be done using Shoutrrr's [generic webhook](https://containrrr.dev/shoutrrr/dev/services/generic/) service (should be available in the next watchtower release).

The `before` part could be added in a more generic way by making it possible to set a template for a `before` notification. That should solve the issue, right?

**Comment by hr87** [comment]
> I'd argue that this isn't really within Watchtower's scope. I'd say it's more in Autoheal's or Monocker's scope.
> 
> Images may update at a whim, depending on when a dev or CI/CD updates, so not quite sure how useful a check-in would be.

This is not to monitor or restart other containers. Healthchecks.io (not related with docker healthcheck) allows to monitor scheduled tasks (aka cron jobs) and only notifies if the task does not check in on time. This allows to check on background tasks, if they hang or crash.

**Comment by hr87** [comment]
> Except for the "before" part, it could be done using Shoutrrr's [generic webhook](https://containrrr.dev/shoutrrr/dev/services/generic/) service (should be available in the next watchtower release).
> 
> The `before` part could be added in a more generic way by making it possible to set a template for a `before` notification. That should solve the issue, right?

This is more to monitor that watchtower executes as scheduled. It is not for notifications. Watchtower only send notifications if there are updates. Depending on which images one runs, notifications might be rare, and one does not notice if watchtower goes down for any reason. 

With healthchecks, watchtower would check in whenever it runs. If it misses a check in, healthchecks notifies the admin, so they can check what is going on. As long as watchtower checks in on time, no notifications are send.

**Comment by piksel** [comment]
@hr87 How would it know if there were any update *before* a check? Notifications are just the way watchtower communicates with 3rd party services, it could just as well be used to ping to ping a service like healthcheck. In the upcoming release, the "regular" notification messages can be much more customized (including under which conditions to skip sending it).

**Comment by hr87** [comment]
@piksel It does not. It just pings to let healthchecks know that it started a run. And once done it pings again, no matter if there was an update or not, to tell that is sucessfully finished. The start ping is optional.

**Comment by piksel** [comment]
Yeah, that was my point.
It was regarding this sentence:

> Watchtower only send notifications if there are updates

**Comment by modem7** [comment]
Bump

**Comment by milindpatel63** [comment]
Would love to have this too....
a simple curl executing at same time the watchtower cron job executes would work...
any way to do this?
looked into shoutrr, no option there...

**Comment by milindpatel63** [comment]
> Except for the "before" part, it could be done using Shoutrrr's [generic webhook](https://containrrr.dev/shoutrrr/dev/services/generic/) service (should be available in the next watchtower release).
> 
> The `before` part could be added in a more generic way by making it possible to set a template for a `before` notification. That should solve the issue, right?

is there a way implemented till now to send a generic webhook before updates are run...?

**Comment by piksel** [comment]
No, it was merely a suggestion.

**Comment by simonaronsson** [comment]
Add a [curl container](https://hub.docker.com/r/curlimages/curl) to your docker host and set up `com.centurylinklabs.watchtower.lifecycle.pre-check` and `com.centurylinklabs.watchtower.lifecycle.post-check` on that container to curl the healthchecks.io endpoint.

See https://containrrr.dev/watchtower/lifecycle-hooks/#specifying_update_commands for more details.
